### ISSUE TITLE
Replace deprecated notification creation

### ISSUE THREAD

**Issue by utopius** [ACRA/acra#102]
org.acra.ErrorReporter.notifySendReport(String reportFileName) uses a deprecated way to create notifications:
- Notification constructor
- Notification.setLatestEventInfo()

This could either be replaced by using NotificationCompat.Builder from the v4 support library which would introduce a dependency or by copying the builder and related code to ACRA.

**Comment by arcao** [comment]
Fixed in commit d1ada52.
