### ISSUE TITLE
application:acra service process does not stop on crash

### ISSUE THREAD

**Issue by dizzy-ghost** [ACRA/acra#1030]
I'm trying to use ACRA 5.8.4 for sending my application crash reports to server and just have got the following issue:

On emulated unhandled exception (division by zero) ACRA sends report, obtains response, finishes application, but service process application:acra stays in process table and never dies.

Target android version on device is 9.0

Here is the application code:

MyApplication.kt

`
    package org.acra.example
    
    import android.app.Application
    import android.app.job.JobInfo
    import android.content.Context
    import org.acra.ACRA

    import org.acra.BuildConfig
    import org.acra.config.*
    import org.acra.data.StringFormat
    import org.acra.ktx.initAcra
    import org.acra.sender.HttpSender

    class MyApplication : Application() {
    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)

        ACRA.DEV_LOGGING = true

        initAcra {

            buildConfigClass = BuildConfig::class.java
            reportFormat = StringFormat.JSON
            stopServicesOnCrash = true

            httpSender {
                uri = "http://myserver.com/report"
                httpMethod = HttpSender.Method.POST
                compress = false
              }
          }
      }
  }
`

MainActivirt.kt

`
    package org.acra.example
    
    import android.app.Activity
    import android.os.Bundle
    import org.acra.ACRA

    class MainActivity : Activity() {

        override fun onCreate(savedInstanceState: Bundle?) {

            var x: Int

            super.onCreate(savedInstanceState)

            ACRA.errorReporter.putCustomData("shelf_id", "23456789012")
            ACRA.errorReporter.putCustomData("ugugu", "agaga")
            println("-------------------------------------------------")
            println("Shelf_ID = ${ACRA.errorReporter.getCustomData("shelf_id")}")
            println("ugugu = ${ACRA.errorReporter.getCustomData("ugugu")}")
            println("-------------------------------------------------")

            x = zerodivide(15)

        }
    }

    fun zerodivide(x: Int): Int {
        val zero = 0
        return (x/zero)
    }
`

Logcat messages on crash:

`03/21 14:34:04: Launching 'app' on DZlogic x305.
Install successfully finished in 8 s 84 ms.
$ adb shell am start -n "org.acra.example/org.acra.example.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7793 on device 'amlogic-x301-WST1100318'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/rg.acra.exampl: Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)
W/rg.acra.exampl: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)
D/ACRA: ACRA processName='org.acra.example'
I/ACRA: ACRA is enabled for org.acra.example, initializing...
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.collector.Collector]
D/ACRA: Loaded Collector of type org.acra.collector.ConfigurationCollector
D/ACRA: Loaded Collector of type org.acra.collector.CustomDataCollector
D/ACRA: Loaded Collector of type org.acra.collector.DeviceFeaturesCollector
D/ACRA: Loaded Collector of type org.acra.collector.DeviceIdCollector
D/ACRA: Loaded Collector of type org.acra.collector.DisplayManagerCollector
D/ACRA: Loaded Collector of type org.acra.collector.DropBoxCollector
D/ACRA: Loaded Collector of type org.acra.collector.LogCatCollector
D/ACRA: Loaded Collector of type org.acra.collector.LogFileCollector
D/ACRA: Loaded Collector of type org.acra.collector.MediaCodecListCollector
D/ACRA: Loaded Collector of type org.acra.collector.MemoryInfoCollector
D/ACRA: Loaded Collector of type org.acra.collector.PackageManagerCollector
D/ACRA: Loaded Collector of type org.acra.collector.ReflectionCollector
D/ACRA: Loaded Collector of type org.acra.collector.SettingsCollector
D/ACRA: Loaded Collector of type org.acra.collector.SharedPreferencesCollector
D/ACRA: Loaded Collector of type org.acra.collector.SimpleValuesCollector
D/ACRA: Loaded Collector of type org.acra.collector.StacktraceCollector
D/ACRA: Loaded Collector of type org.acra.collector.ThreadCollector
D/ACRA: Loaded Collector of type org.acra.collector.TimeCollector
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.SchedulerConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.SchedulerConfiguration
D/ACRA: Ignoring disabled SenderSchedulerFactory of type Factory
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.SchedulerConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.SchedulerConfiguration
D/ACRA: Ignoring disabled ReportingAdministrator of type RestartingAdministrator
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.LimiterConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.LimiterConfiguration
D/ACRA: Ignoring disabled ReportingAdministrator of type LimitingReportAdministrator
D/ACRA: onActivityCreated class org.acra.example.MainActivity
I/System.out: -------------------------------------------------
I/System.out: Shelf_ID = 23456789012
I/System.out: ugugu = agaga
I/System.out: -------------------------------------------------
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.acra.example, PID: 7793
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.acra.example/org.acra.example.MainActivity}: java.lang.ArithmeticException: divide by zero
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ArithmeticException: divide by zero
        at org.acra.example.MainActivityKt.zerodivide(MainActivity.kt:30)
        at org.acra.example.MainActivity.onCreate(MainActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
E/ACRA: ACRA caught a RuntimeException for org.acra.example
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.acra.example/org.acra.example.MainActivity}: java.lang.ArithmeticException: divide by zero
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ArithmeticException: divide by zero
        at org.acra.example.MainActivityKt.zerodivide(MainActivity.kt:30)
        at org.acra.example.MainActivity.onCreate(MainActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
D/ACRA: Building report
D/ACRA: Starting collectors with priority FIRST
D/ACRA: Calling collector org.acra.collector.DropBoxCollector
D/ACRA: Collector org.acra.collector.DropBoxCollector completed
D/ACRA: Calling collector org.acra.collector.LogCatCollector
D/ACRA: Calling collector org.acra.collector.StacktraceCollector
D/ACRA: Collector org.acra.collector.StacktraceCollector completed
D/ACRA: Retrieving logcat output (buffer:default)...
D/ACRA: Collector org.acra.collector.LogCatCollector completed
D/ACRA: Finished collectors with priority FIRST
D/ACRA: Starting collectors with priority NORMAL
D/ACRA: Calling collector org.acra.collector.CustomDataCollector
D/ACRA: Calling collector org.acra.collector.DeviceFeaturesCollector
D/ACRA: Collector org.acra.collector.CustomDataCollector completed
D/ACRA: Calling collector org.acra.collector.MemoryInfoCollector
D/ACRA: Calling collector org.acra.collector.ConfigurationCollector
D/ACRA: Calling collector org.acra.collector.PackageManagerCollector
D/ACRA: Calling collector org.acra.collector.SettingsCollector
D/ACRA: Collector org.acra.collector.SettingsCollector completed
D/ACRA: Calling collector org.acra.collector.ReflectionCollector
D/ACRA: Collector org.acra.collector.DeviceFeaturesCollector completed
D/ACRA: Collector org.acra.collector.PackageManagerCollector completed
D/ACRA: Calling collector org.acra.collector.TimeCollector
D/ACRA: Calling collector org.acra.collector.DisplayManagerCollector
D/ACRA: Calling collector org.acra.collector.DeviceIdCollector
D/ACRA: Calling collector org.acra.collector.SimpleValuesCollector
D/ACRA: Collector org.acra.collector.DeviceIdCollector completed
D/ACRA: Calling collector org.acra.collector.SharedPreferencesCollector
D/ACRA: Collector org.acra.collector.SimpleValuesCollector completed
D/ACRA: Collector org.acra.collector.TimeCollector completed
D/ACRA: Collector org.acra.collector.ConfigurationCollector completed
D/ACRA: Collector org.acra.collector.SharedPreferencesCollector completed
D/ACRA: Collector org.acra.collector.MemoryInfoCollector completed
D/ACRA: Collector org.acra.collector.DisplayManagerCollector completed
D/ACRA: Collector org.acra.collector.ReflectionCollector completed
D/ACRA: Finished collectors with priority NORMAL
D/ACRA: Starting collectors with priority LATE
D/ACRA: Calling collector org.acra.collector.ThreadCollector
D/ACRA: Collector org.acra.collector.ThreadCollector completed
D/ACRA: Calling collector org.acra.collector.MediaCodecListCollector
D/ACRA: Collector org.acra.collector.MediaCodecListCollector completed
D/ACRA: Calling collector org.acra.collector.LogFileCollector
D/ACRA: Collector org.acra.collector.LogFileCollector completed
D/ACRA: Finished collectors with priority LATE
D/ACRA: Finishing activities prior to killing the Process
D/ACRA: Finished class org.acra.example.MainActivity
D/ACRA: Writing crash report file /data/user/0/org.acra.example/app_ACRA-unapproved/2022-03-21T14:44:23.971+03:00.stacktrace
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
D/ACRA: Mark 2022-03-21T14:44:23.971+03:00.stacktrace as approved.
D/ACRA: Schedule report sending
D/ACRA: Using PluginLoader to find ReportSender factories
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.MailSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.MailSenderConfiguration
D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
D/ACRA: reportSenderFactories : [org.acra.sender.HttpSenderFactory@3edf85d]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Adding reportSender : org.acra.sender.HttpSender@2ed45d2
D/ACRA: Using PluginLoader to find ReportSender factories
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.MailSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.MailSenderConfiguration
D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
D/ACRA: reportSenderFactories : [org.acra.sender.HttpSenderFactory@f96bd59]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@2c888ea] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2c888ea against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Adding reportSender : org.acra.sender.HttpSender@cb5ed1e
D/ACRA: Wait for Interactions + worker ended. Kill Application ? true
D/ACRA: Handing Exception on to default ExceptionHandler
Connected to process 7850 on device 'amlogic-x301-WST1100318'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ACRA: ACRA processName='org.acra.example:acra'
D/ACRA: Not initialising ACRA to listen for uncaught Exceptions as this is the SendWorker process and we only send reports, we don't capture them to avoid infinite loops
D/ACRA: About to start sending reports from SenderService
D/ACRA: Using PluginLoader to find ReportSender factories
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@4d8d589] for class : class org.acra.config.MailSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@4d8d589 against plugin class : class org.acra.config.MailSenderConfiguration
D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@4d8d589] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@4d8d589 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
D/ACRA: reportSenderFactories : [org.acra.sender.HttpSenderFactory@258d98e]
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@4d8d589] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@4d8d589 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Adding reportSender : org.acra.sender.HttpSender@3f215af
I/ACRA: Sending report /data/user/0/org.acra.example/app_ACRA-approved/2022-03-21T14:44:23.971+03:00.stacktrace
D/ACRA: Sending report using org.acra.sender.HttpSender
D/ACRA: Connect to http://myserver.com/report
D/ACRA: Checking plugin Configurations : [org.acra.config.HttpSenderConfiguration@4d8d589] for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@4d8d589 against plugin class : class org.acra.config.HttpSenderConfiguration
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/ACRA: Sending request to http://myserver.com/report
D/ACRA: Http POST content : 
D/ACRA: {"REPORT_ID":"3be1f253-4d5a-4527-a808-654010d15185","APP_VERSION_CODE":6,"APP_VERSION_NAME":"0.6.0","PACKAGE_NAME":"org.acra.example","FILE_PATH":"\/data\/user\/0\/org.acra.example\/files","ANDROID_VERSION":"9.0.0",
.....
D/ACRA: Request response : 200 : OK
I/ACRA: Request received by server
D/ACRA: Sent report using org.acra.sender.HttpSender
D/ACRA: Report was sent by all senders
D/ACRA: Finished sending reports from SenderService
`

Could you explain how to finish the application totally?

**Comment by F43nd1r** [comment]
Acra is using a `JobService` to send reports, which means android manages the process lifecycle. 
Your application process is already completely stopped at this point, and once ACRA report sending is done the :acra process is idle. Android should stop it if running out of resources, but we do not have control over this.
As far as I can tell this is not an issue.
