### ISSUE TITLE
Not possible to compile application with ACRA 5.9.0 (Java)

### ISSUE THREAD

**Issue by henrichg** [ACRA/acra#1048]
ACRA: 5.9.0. Language Java.

My ACRA configuration:

        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this)
                .withBuildConfigClass(BuildConfig.class)
                .withReportFormat(StringFormat.KEY_VALUE_LIST);
        builder.getPluginConfigurationBuilder(NotificationConfigurationBuilder.class)
                .withResChannelName(R.string.notification_channel_crash_report)
                .withResChannelImportance(NotificationManager.IMPORTANCE_HIGH)
                .withResIcon(R.drawable.ic_exclamation_notify)
                .withResTitle(R.string.acra_notification_title)
                .withResText(R.string.acra_notification_text)
                .withResSendButtonIcon(0)
                .withResDiscardButtonIcon(0)
                .withSendOnClick(true)
                .withEnabled(true);
        builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                .withMailTo("henrich.gron@gmail.com")
                .withSubject("PhoneProfilesPlus" + packageVersion + " - " + getString(R.string.acra_email_subject_text))
                .withBody(body)
                .withReportAsFile(true)
                .withReportFileName("crash_report.txt")
                .withEnabled(true);

And in Android Studio:

builder.getPluginConfigurationBuilder() - 'Cannot resolve method 'getPluginConfigurationBuilder' in 'CoreConfigurationBuilder''. 

In 5.8.4 is not this error.

Also:
import com.google.common.util.concurrent.ListenableFuture; Cannot resolve symbol 'ListenableFuture'.

**Comment by mikehardy** [comment]
I have this problem as well! Just went to integrate 5.9.0 in AnkiDroid after getting my PR here merged + released, and then this build error popped up when 5.8.x was working with my local changes. I apologize that I have not performed triage yet - it's likely an easy thing to find, so consider my comment mainly as posting to subscribe and to say that this indeed was an unexpected difference between 5.8.x-latest and 5.9.0

**Comment by henrichg** [comment]
Thank you F43nd1r, it working good. ;)

And how about 
import com.google.common.util.concurrent.ListenableFuture;

I'm added dependency from this: https://github.com/google/guava
It is ok?

**Comment by F43nd1r** [comment]
That's unrelated to ACRA, we don't use ListenableFuture.

**Comment by henrichg** [comment]
In gradle depencency with version 5.8.4 exists com.goolge.guava:listenablefuture:1.0
Maybe it is part of kotlin?

**Comment by F43nd1r** [comment]
That's possible, I'm unsure why that would show up there, but who knows.

In general, I recommend to not rely on transitive dependencies, but declare them yourself if you need them. It sounds like you did that now, so I'm going to close this issue.
