### ISSUE TITLE
Add ability to get stack trace object in CrashReportData

### ISSUE THREAD

**Issue by croemmich** [ACRA/acra#105]
I'm currently writing a custom sender for Errbit. The Airbrake api defines a backtrace as having an exception class, an exception message, and each numbered line of the trace. This would be easy to do if the actual exception object was available, but currently it is pretty much impossible.

**Comment by william-ferguson-au** [comment]
OK, while this would be nice, I'm closing it because I will never get to it and no one else has stepped in.
