### ISSUE TITLE
Crash with R8 full mode enabled

### ISSUE THREAD

**Issue by dnaka91** [ACRA/acra#1052]
**Describe the bug**
When enabling the _full mode_ of R8, I directly get a crash when starting the app. 

After some debugging, I found out that the problem is a reflection access through [`StubCreator`](https://github.com/ACRA/acra/blob/895a6cf5f4193831b8ed5080752db6c2ccd78ac1/acra-core/src/main/java/org/acra/util/StubCreator.kt#L23). With _full mode_ enabled, it modifies the `ErrorReporter` interface and turns it into something else (not important into what I guess, just not an interface anymore).

**Expected behavior**
The call should not fail.

**Version**
 - Android: 12 (32)
 - ACRA: 5.9.1

**Possible solution**
I got my app working again, by adding a rule to keep the `ErrorReporter` interface. Probably this should be added to the ProGuard rules, bundled with the acra releases.

```txt
-keep interface org.acra.ErrorReporter
```

**Comment by F43nd1r** [comment]
I don't see any crashes in a test app, even with full mode enabled. Do you have a reproducer?

**Comment by dnaka91** [comment]
Could reproduce it very easily in a sample app:

- Created a new project with Android Studio **Canary** with Jetpack Compose + Material3.
- Added ACRA and called `initAcra {}` (without any further configuration).
- Enable R8's full mode.

Uploaded it here for reference: https://github.com/dnaka91/acracrash
