### ISSUE TITLE
Is it possible to show the crash notification but also send the report immediately (without user having to click on the notification)

### ISSUE THREAD

**Issue by KAthul** [ACRA/acra#1070]
Hi,
I'm trying to implement ACRA in our android app and so far it is going well.

One of our requirements is to show a notification when the app crashes, but the crash report should be sent even if the user doesn't interact with the notification. Will this be possible with ACRA? I looked around in Notification class but couldn't find anything relating to this.

Thanks

**Comment by F43nd1r** [comment]
The notification module does not support that, but you can provide your own `ReportInteraction` and show a notification. If you return `true` from `performInteraction`, reports will be sent immediately.

**Comment by KAthul** [comment]
Thank you for the help. Creating my own ReportInteraction worked
