### ISSUE TITLE
Cannot resolve symbol 'ACRA'

### ISSUE THREAD

**Issue by r748** [ACRA/acra#1085]
I'm trying to upgrade ACRA from 5.7.0 to 5.9.3.. Gradle syncs fine, however in my Java class I can't call ACRA.init because Android Studio constantly shows the error "Cannot resolve symbol 'ACRA'".

My dependencies are like so:

```
dependencies {

    // Error Handling

    def acraVersion = '5.9.3'

    implementation "ch.acra:acra-http:$acraVersion"

    implementation "ch.acra:acra-notification:$acraVersion"

    ...
}
```

All all ACRA versions up to and including 5.8.4 resolve fine, I'm just having this problem with 5.9.0+. Any ideas?

**Comment by F43nd1r** [comment]
> Gradle syncs fine
Android studio often hides dependency errors.
Run a `gradle build` from the command line and post the output

**Comment by r748** [comment]
Thanks for the quick reply. That put me on the right track to solve the issue!!
