### ISSUE TITLE
A lot of documentation on https://www.acra.ch/docs/...  is out of date

### ISSUE THREAD

**Issue by Zardozz** [ACRA/acra#1089]
**Describe the bug**
It looks like all the documentation still references how to config things with the previous deprecated and now removed previously deprecated annotation config 

e.g. on https://www.acra.ch/docs/Interactions
it says "toast Interaction" is config'd with

`new ToastConfigurationBuilder()
    //required
    .withResText(R.string.toast_text) 
    //defaults to Toast.LENGTH_LONG
    .withLength(Toast.LENGTH_LONG)
    .build()`

but `withResText` was removed in [#856](https://github.com/ACRA/acra/pull/856)

and replaced with `withText`

**Expected behavior**
The documentation to be versioned to show both how to do it before and after this major change or just to show the latest correct config methods (as older stuff is still on the github wiki (which is versioned)

**Version**
 - Android: [All]
 - ACRA [e.g. 5.9.5] but probably from 5.9.0

**Comment by F43nd1r** [comment]
docs sources are here https://github.com/ACRA/acra/blob/master/web/docs/Interactions.mdx
You're very welcome to create a PR for this. Unfortunately I'm short on time to go over everything myself.

**Comment by Zardozz** [comment]
Pull request created.
