### ISSUE TITLE
could i catch and report exception within try catch?

### ISSUE THREAD

**Issue by ZhouBey** [ACRA/acra#1105]
if i put code within try catch,if this crash,that when crashed,the function of initAcra not called. so could i catch and report exception within try catch?

**Comment by F43nd1r** [comment]
https://www.acra.ch/docs/AdvancedUsage#sending-reports-for-caught-exceptions-or-for-unexpected-application-state-without-any-exception

**Comment by ZhouBey** [comment]
well,that means i need only manual call report funcation,can it be called automatically when catch within try catch?

**Comment by F43nd1r** [comment]
No, there is no language construct to listen to caught exceptions. You have to do it yourself.

**Comment by ZhouBey** [comment]
Thank you
