### ISSUE TITLE
[Community] Matrix chat room?

### ISSUE THREAD

**Issue by Doomsdayrs** [ACRA/acra#1108]
Using google groups is, in all case a dependency on google. And even then, it seems to not be active whatsoever.

A matrix room would be really nice, Like this https://matrix.to/#/#acra:matrix.org

**Comment by mikehardy** [comment]
Is there some discussion that needs to happen that is not currently handled adequately in this repository?
I'm just curious because there are issues and discussions available here and I have never (not now, not in past) seen any lack of responsiveness with regard to responses.

Feels like "solution in search of problem..."

**Comment by Doomsdayrs** [comment]
> Is there some discussion that needs to happen that is not currently handled adequately in this repository? I'm just curious because there are issues and discussions available here and I have never (not now, not in past) seen any lack of responsiveness with regard to responses.

The discussion group is quite stale. For example this [post](https://groups.google.com/g/acra-discuss/c/n2mdwlw6pO0) happened over a year ago with out any response. Any developer community would benefit from having some feeling that people are around.

> Feels like "solution in search of problem..."

I may have to agree, but having a proper room to chat in is superior to a google group that is stale.

**Comment by F43nd1r** [comment]
I do not support the google group or any other external communication medium. Given that I'm the only active maintainer those are not well suited to get your questions answered.
Github is the preferred way of asking questions, reporting issues or requesting features (although I do answer some stackoverflow questions occasionally).
If the google group is still linked somewhere point me there and I'll remove it.
