### ISSUE TITLE
RFE - Allow the server to throttle the client

### ISSUE THREAD

**Issue by bpappin** [ACRA/acra#111]
We ran a test of our ACRA support on www.pointrocket.com yesterday that turned out to bring up an important point that you might want to include in ACRA.
In this case there was actually an exception being throw in a service for the app, so the user wasn't seeing it, but ACRA was catching it.
We didn't turn on the server until over 100k users had it running and it flooded our servers with data, which essentially meant we caused a self-inflicted DDoS attack on ourselves :)

In the end we simply had no choice but to return a 410 to those clients.
This has led us to two conclusions that might be useful in ACRA as well:
- In our own drivers, we are going to add a response type that will let the server tell the driver to throttle itself or to stop reporting the same error over and over again.
- We are adding a version tag to the POST so that we can detect a driver that has known issues and handle them differently over time.

ACRA doesn't need the second one, because we can provide a special URL for it and protect the servers that way, but others might run onto that kind of issue in custom setups.
Handling it is important though, because device users simply can't be relied upon to update their apps.

**Comment by william-ferguson-au** [comment]
Just a follow up Brill. I'm hoping to release 4.6.0 soon.
So if you have some code to push,now is the time.

**Comment by bpappin** [comment]
Sorry, I didn't know you were waiting on me or expecting something from me.

I'm not sure I can get something done and tested well enough for you to
include in the next release.

- Brill

**Comment by william-ferguson-au** [comment]
Closing for now.
Open a pull request when you get that far.
