### ISSUE TITLE
Replace MediaCodecCollector

### ISSUE THREAD

**Issue by JeanPaulLucien** [ACRA/acra#1144]
**Required reading**
https://github.com/ACRA/acra/wiki/How-to-debug-ACRA

**Describe the bug**
```
INFORMATION,dalvikvm,Yggdrasil,Could not find method android.media.MediaCodecList.<init>, referenced from method org.acra.collector.MediaCodecListCollector.collectMediaCodecList	
WARNING,dalvikvm,Yggdrasil,VFY: unable to resolve direct method 498: Landroid/media/MediaCodecList.<init> (I)V
```

**Expected behavior**
No warning

**Version**
 - Android: 4.2.2
 - ACRA 5.9.6

**Comment by JeanPaulLucien** [comment]
MediaCodecList (Android 4.1+)
And only 2 methods for Android 4.1+

What about other way?

All info about codecs is placed in XML file: https://android.stackexchange.com/questions/62737/list-of-supported-a-v-and-image-codecs

**Comment by F43nd1r** [comment]
This is not a valid bug report. It lacks both information on what goes wrong and what is expected.
