### ISSUE TITLE
Other platforms

### ISSUE THREAD

**Issue by techker** [ACRA/acra#1181]
This is mostly a question and help:

I need to add this to all our platforms

Roku, Xamarin, IOS,WEB

Is there a way to use the backend without adding the sdk to the apps since it is only Android?

we can send the repport via http?

is there a way to make this compatible with other platforms?

**Comment by F43nd1r** [comment]
> is there a way to make this compatible with other platforms?

Technically it is possible to create other senders which conform to the ACRA format to allow you to share a server side backend.
However I am not aware of any projects doing so.

As for making this project compatible with Xamarin / IOS: That would require a full rewrite, I don't see that happening.
You're welcome to ask questions about the ACRA report format if you want to do it yourself.
