### ISSUE TITLE
Mitigate duplicates in the ReportContent 

### ISSUE THREAD

**Issue by Backfisch145** [ACRA/acra#1193]
Last week  I updated the ReportContent of my app and made the mistake, to add  "ANDROID_VERSION" twice to the ReportContent.
That leads to an error in the official backend (Acrarium).

To mitigate such error, it would be an improvement to throw an error on startup or to change the reportContent, from an Array, to a Set.

If there is a valid UseCase, where it is required to have a duplicate entry, please let me know

**Comment by F43nd1r** [comment]
This is a list not because of needing duplicate entries, but because the order matters. Especially in email reports, people prefer to see the most important fields at the top.
