### ISSUE TITLE
How can I find api for server?

### ISSUE THREAD

**Issue by amira133** [ACRA/acra#1204]
Hello
I want to create a server for `ACRA`. But I don't know what APIs are used by `ACRA`. Therefore, if there is a document in this field, please send it to me.
Thank you for your guidance.

**Comment by F43nd1r** [comment]
I don't think I have written down all the possibilities of what ACRA can send.
Options of the builtin http sender are (a custom sender can of course do everything):
 - POST or PUT
 - JSON or url-encoded key/value-Pairs.

The exact content depends on the configured `ReportField`s.
