### ISSUE TITLE
No leading boundary when using POST withAttachmentUris

### ISSUE THREAD

**Issue by theBlbDan** [ACRA/acra#1212]
When using withAttachmentUris(), I receive an error on the server side, ```java.io.IOException: Corrupt form data: no leading boundary:  != --%&ACRA_REPORT_DIVIDER&%```

I am using ColdFusion via reverse proxy, but I also tested by targeting the CF instance directly.  If I remove the withAttachmentUris() the report sends fine.  It appears that HttpSender.Method.PUT works as expected, but I cannot get POST to ... post.

```
ACRA.init(this, new CoreConfigurationBuilder()
	.withBuildConfigClass(BuildConfig.class)
	.withReportFormat(StringFormat.JSON)
	.withAttachmentUris("content://<my_package>.acra/files/databases/v4/bibleText.blb")
	.withPluginConfigurations(
		new HttpSenderConfigurationBuilder()
			.withUri("<my_report_link>")
			.withHttpMethod(HttpSender.Method.POST)
			.withConnectionTimeout(5000)
			.withSocketTimeout(20000)
			.withDropReportsOnTimeout(false)
			.withCompress(false)
			.build()
	)
	.withStopServicesOnCrash(true),
	false
);
```

**Version Information**
 - Android: targetSdkVersion = 32
 - ACRA acraVersion = '5.9.7'

**Comment by F43nd1r** [comment]
Apparently your server is picky in regards to the `multipart/form-data` format. ACRA was sending an additional newline at the beginning of the report, which was accepted by my server implementation.

**Comment by theBlbDan** [comment]
Are you willing to adjust this or are Java based backends just out of luck?

**Comment by F43nd1r** [comment]
@theBlbDan Should be fixed starting with 5.10.0

**Comment by theBlbDan** [comment]
Thank you.  I kinda figured I was misreading your reply.

**Comment by theBlbDan** [comment]
May I ask an additional favor related to multipart? The report data is being sent as though it were a file but with an empty filename value, thus causing ColdFusion to consume it out of its FORM structure and not pass it to my action page.

Can we either remove ```; filename=""```  from the Content-Disposition or give it a filename value, possibly one we can configure?

```
--%&ACRA_REPORT_DIVIDER&%
Content-Disposition: form-data; name="ACRA_REPORT"; filename=""
Content-Type: application/json

<REPORT_DATA>
--%&ACRA_REPORT_DIVIDER&%
Content-Disposition: form-data; name="ACRA_ATTACHMENT"; filename="INSTALLATION"
Content-Type: application/octet-stream

6e3c7f6f00e452004f6e009e6d00406f7ec77180
--%&ACRA_REPORT_DIVIDER&%--
```

**Comment by F43nd1r** [comment]
That probably makes sense. To not mix bug and enhancement, please open a new issue.
