### ISSUE TITLE
Mac Address in os 11

### ISSUE THREAD

**Issue by techker** [ACRA/acra#1220]
Can Acra still get the MAC from the device in OS 11 and later?

**Required reading**
http://www.acra.ch/docs/How-to-debug

**Describe the bug**

**Expected behavior**

**Version**
 - Android: [e.g. 8.1]
 - ACRA [e.g. 5.6.2]

**Comment by F43nd1r** [comment]
To my knowledge ACRA does not attempt to collect MAC adresses on any Android version.

**Comment by techker** [comment]
oh ok thx
