### ISSUE TITLE
Custom Extensions and KSP support

### ISSUE THREAD

**Issue by DenBond7** [ACRA/acra#1230]
Hello,

After switching to use [KSP (Kotlin Symbol Processing)](https://github.com/google/ksp)

`ksp("com.google.auto.service:auto-service:1.1.1")`

[Custom Extensions](https://www.acra.ch/docs/Custom-Extensions) don't work. I'm posting it just in case. Maybe this info will be useful for other devs.

After some research, I've found a workaround. It's a [KSP](https://github.com/google/ksp) implementation of [AutoService](https://github.com/google/auto/tree/master/service).

https://github.com/ZacSweers/auto-service-ksp

The following lines resolve a problem

```
ksp("dev.zacsweers.autoservice:auto-service-ksp:1.1.0")
ksp("com.google.auto.service:auto-service:1.1.1")
```

**Comment by DenBond7** [comment]
https://github.com/google/auto/issues/882

**Comment by F43nd1r** [comment]
Sounds like a good thing to add to the documentation. Would you be willing to make a PR for that?
