### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by paulWyszynski** [ACRA/acra#1272]
Hi,

will it be supported soon?

Thanks

**Comment by mikehardy** [comment]
For what it's worth, gradle 8.5 just came out which prompted an experimental attempt to use it in AnkiDroid (an ACRA user) and even 21 appeared to work locally. 17 definitely works.

**Comment by paulWyszynski** [comment]
Hey, thanks. I'm sorry, my build error was not Java17 related. I had an issue with the guava library, especially with the ListenableFuture which was used in CameraPreview lib as well.
