### ISSUE TITLE
Possible to send Acra reports with own custom error dialog?

### ISSUE THREAD

**Issue by paulWyszynski** [ACRA/acra#1278]
Is it possible like here https://www.acra.ch/docs/Interactions#dialog to send reports on positive button click in your own custom error dialog/ error activity or just to discard the custom error activity, without sending the report?

**Comment by mikehardy** [comment]
We do this you might like:

init whole system:
https://github.com/ankidroid/Anki-Android/blob/da2c69401a97d37d6d17e2a5b8e7c3e1a1219d74/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt#L110

specific acra init stuff where we set the dialog:
https://github.com/ankidroid/Anki-Android/blob/da2c69401a97d37d6d17e2a5b8e7c3e1a1219d74/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt#L119

click handler registration in dialog:
https://github.com/ankidroid/Anki-Android/blob/da2c69401a97d37d6d17e2a5b8e7c3e1a1219d74/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt#L51

just throwing everything away on a non-positive click:
https://github.com/ankidroid/Anki-Android/blob/da2c69401a97d37d6d17e2a5b8e7c3e1a1219d74/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt#L101

**Comment by F43nd1r** [comment]
The short answer is yes, you can have a custom dialog with send and discard buttons.
The example provided by @mikehardy should help.

**Comment by paulWyszynski** [comment]
Nice. Thanks for the shared links!
