### ISSUE TITLE
Empty report when selecting JSON Type

### ISSUE THREAD

**Issue by ghost** [ACRA/acra#135]
I'm getting empty reports (no data at all) when i select the JSON input type. FORM type is working fine.

My config:

@ReportsCrashes(formKey = "", formUri = "http://localhost/handle", mode = ReportingInteractionMode.TOAST, resToastText = R.string.crash, reportType = org.acra.sender.HttpSender.Type.JSON, httpMethod = org.acra.sender.HttpSender.Method.POST)

**Comment by rohnstock** [comment]
The problem with the JSON type still exists (ACRA V4.6.1). Report is empty. FORM type is working fine.

My annotation:
@ReportsCrashes(
        mode = ReportingInteractionMode.TOAST,
        httpMethod = HttpSender.Method.POST,
        formUri = "http://xxxx",
        forceCloseDialogAfterToast = false,
        resToastText = R.string.error_report,
        reportType = HttpSender.Type.JSON
)

Android 4.2, Huawei Ascend Mate
Android 4.4.2, Huawei Honor 6
Compiled with Android Studio 1.0.2

**Comment by william-ferguson-au** [comment]
You going to fix it?

**Comment by william-ferguson-au** [comment]
Empty reports can appear on the server if the server is too slow to respond to ACRA and ACRA timeout the socket connection. See socketTimeout in https://github.com/ACRA/acra/wiki/AdvancedUsage

**Comment by gdudek** [comment]
I believe this problem may reflect the fact that your script on the server is attempting to parse the request body as if it was for encoded, whereas for JSON you need to read the raw body.
