### ISSUE TITLE
Does ACRA catch ANR ?

### ISSUE THREAD

**Issue by GregCornis** [ACRA/acra#1352]
I'm wondering if ACRA can catch an "Application Not Responding" crash ? From my testing it doesn't seem so (I do receive the reports when the app crashes because of a code error), but maybe there is something to configure ?

**Comment by F43nd1r** [comment]
http://www.acra.ch/docs/AdvancedUsage#catching-application-not-responding-errors-anr

**Comment by GregCornis** [comment]
Nice ! Sorry I missed the info
