### ISSUE TITLE
Help creating a custom sender

### ISSUE THREAD

**Issue by GregCornis** [ACRA/acra#1356]
I'm trying to implement a custom sender as described in the [documentation](https://www.acra.ch/docs/Senders). I have:
1. added the dependencies (in module's `build.gradle`)
``` gradle
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'       // KSP
}

dependencies {
    def acraVersion = "5.11.3"
    implementation "ch.acra:acra-notification:$acraVersion"
    implementation("ch.acra:acra-http:$acraVersion")
    ksp("dev.zacsweers.autoservice:auto-service-ksp:1.1.0")
    ksp("com.google.auto.service:auto-service:1.1.1")
    implementation "com.google.auto.service:auto-service-annotations:1.1.1"
}
```
2. added a custom sender with `AutoService` annotation
```kotlin
package com.cornis.dronoblade_android

import android.content.Context
import android.util.Log
import com.google.auto.service.AutoService
import org.acra.config.CoreConfiguration
import org.acra.data.CrashReportData
import org.acra.sender.ReportSender
import org.acra.sender.ReportSenderFactory

class S3Reporter: ReportSender {
    override fun send(context: Context, errorContent: CrashReportData) {
        Log.i("S3Reporter", "Manually sending report: ${errorContent.toJSON()}")
    }
}

@AutoService(S3ReporterFactory::class)
class S3ReporterFactory: ReportSenderFactory {
    override fun create(context: Context, config: CoreConfiguration): ReportSender = S3Reporter()
}
```
However nothing seems to get called (nothing in the logcat), so I suspect the Service is not registered correctly (the Factory also appears unused in the IDE).

The [kotlin example](https://github.com/ACRA/acra/blob/master/examples/acra-basic-kotlin-example/src/main/java/org/acra/example/MyApplication.kt) is a bit confusing as it registers the http-sender, so I wonder if that is necessary to only use a custom sender ?

Where should I check if the `META-INF` metadata is correctly generated ?

Sorry if it's a naive problem, I've never used ServiceLoader before

**Comment by F43nd1r** [comment]
`@AutoService(ReportSenderFactory::class)` that's probably what you need.

**Comment by GregCornis** [comment]
Waw you saved my day! Thanks

**Comment by GregCornis** [comment]
Side note: there's a typo in the [Custom extensions](https://www.acra.ch/docs/Custom-Extensions), the snippet for kotlin in missing a `class` in `MyAdmin : ReportingAdministrator`

**Comment by F43nd1r** [comment]
Docs are in the web/ folder, feel free to create a PR :)
https://github.com/ACRA/acra/blob/master/web%2Fdocs%2FCustom-Extensions.mdx
