### ISSUE TITLE
Notification channel sound

### ISSUE THREAD

**Issue by ElliotAl86** [ACRA/acra#1395]
Hello.
I couldn't find this information anywhere in the documentation, so I'm asking here. Why is the sound for notifications forcibly [disabled](https://github.com/ACRA/acra/blob/2ae3f5028bb2428e1aa35551a1b583dea3486e57/acra-notification/src/main/java/org/acra/interaction/NotificationInteraction.kt#L60) for a notification channel, regardless of the importance level set for the channel? Is there a reason behind this? If not, it seems it would be useful to have an option in the configuration for this. In general, I would like to be able to use the default notification sound.

**Comment by F43nd1r** [comment]
v5.12.0 allows you to set up your own notification channel with whatever sound and other options you want - ACRA will not create a the channel in this case.
