### ISSUE TITLE
Force-close dialog always appears in ReportingInteractionMode.TOAST

### ISSUE THREAD

**Issue by robsred** [ACRA/acra#194]
There appears to be a bug when using ReportingInteractionMode.TOAST in the @ReportsCrashes(...) parameters' configuration header in Android 5.0 (Lollipop). Whenever an uncaught exception occurs the toast message does indeed show, but also the force-close dialog opens, while at the same time the application closes on the back. This behaviour only happens in Lollilop, whereas it remains as expected in older Android versions (only toast shows and only current activity window closes, not the entire app). 
Can anyone else confirm this behaviour? Is it actually a Lollipop-related bug...or am I missing something new? Thanks in advance.

**Comment by william-ferguson-au** [comment]
Can you test this again with current master.
I fixed a couple of loop holes that may have solved this issue.

**Comment by robsred** [comment]
I can confirm that it's working correctly now with the latest source changes. Showed the intended toast - without a force-close dialog - and restarted the app. 
Tested on a Nexus 5 with 5.0.1.

Thanks for taking the time

**Comment by william-ferguson-au** [comment]
Woohoo! Thanks for testing :-)


ᐧ
