### ISSUE TITLE
Getting SecurityException in Analytics for some devices

### ISSUE THREAD

**Issue by mblcdr** [ACRA/acra#207]
I am using ACRA 4.5.0 with my app and it seems that on some devices ACRA is producing this exception as it is reported by Analytics.
```java
java.lang.SecurityException: Not allowed to start activity Intent { flg=0x10000000 cmp=ir.headphone.app/org.acra.CrashReportDialog (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1696)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1488)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1074)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1056)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:284)
	at org.acra.ErrorReporter.a(ErrorReporter.java:757)
	at org.acra.m.run(ErrorReporter.java:732)
```
ACRA activity is present in AndroidManifest file (As the dialog shows fine on my test devices).
I'd be happy if you could help me fix this.

**Comment by AntonKosov** [comment]
Hello!

I have same problem (ACRA 4.5.0):
> java.lang.SecurityException: Not allowed to start activity Intent { flg=0x10000000 cmp=ххх/org.acra.CrashReportDialog (has extras) }
> android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1663)
> android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
> android.app.ContextImpl.startActivity(ContextImpl.java:1425)
> android.content.ContextWrapper.startActivity(ContextWrapper.java:334)
> org.holoeverywhere.app.Application.superStartActivity(SourceFile:186)
> org.holoeverywhere.app.Application.startActivity(SourceFile:167)
> org.holoeverywhere.app.Application.startActivity(SourceFile:159)
> org.acra.ErrorReporter.a(SourceFile:757)
> org.acra.ErrorReporter$4.run(SourceFile:732)

ANDROID_VERSION	4.4.2
BRAND	samsung
DEVICE	degaswifiue
MANUFACTURER	samsung
MODEL	SM-T230NU

VERSION CODENAME	REL
VERSION INCREMENTAL	T230NUUEU0ANK2
VERSION RELEASE	4.4.2
VERSION RESOURCES_SDK_INT	19
VERSION SDK	19
VERSION SDK_INT	19

**Comment by william-ferguson-au** [comment]
Can you reproduce this on a device you own?

**Comment by william-ferguson-au** [comment]
Also note that
`cmp=ххх/org.acra.CrashReportDialog (has extras) }`
suggest that this was on an app with packageId=xxx

**Comment by AntonKosov** [comment]
No, I can't. It is our user. It is silent exception. And more: Application version code = null!
xxx - I changed a packageId.

**Comment by AntonKosov** [comment]
Also, "Application version name" is null.

**Comment by william-ferguson-au** [comment]
So how many of these are you getting?
Are they from a single user?
Do you have logs?
What is causing the original failure?

Was the app fully installed? Since version name is null perhaps not.

**Comment by AntonKosov** [comment]
> So how many of these are you getting?
This is more than 500 per day.
> Are they from a single user?
Yes.
> Do you have logs?
I have only stacktrace. Logcat is not present.
> What is causing the original failure?
I don't know :(
> Was the app fully installed? Since version name is null perhaps not.
I don't know.

**Comment by william-ferguson-au** [comment]
Considering APK the symptoms it sounds like your user has a corrupted
install. I see a few of these every thousand installs.

It is probably crashing on startup.

Unfortunately there is not much you can do.

**Comment by AntonKosov** [comment]
A full acralyzer report is here: https://drive.google.com/file/d/0B-spz5MsBOu-cW14Q3NBeFN4RVk/view?usp=sharing

**Comment by AntonKosov** [comment]
For statistic: I see this exception first time. I have 100k+ active installs and 500k+ installs.

Thank you very much!

**Comment by mblcdr** [comment]
I was wondering what would happen if two uncaught exceptions were thrown? Is it even possible?
Would ACRA catch them both? Maybe one is caught and while ACRA is processing it, the other one messes up something, rendering the process unable to send start activity intents?
I remember the logcats which I had relating this issue, showed multiple uncaught exceptions.

**Comment by william-ferguson-au** [comment]
If while processing an uncaught exception another was thrown then I believe the 2nd would aldso be processed.

There is NO way that an application can cause a security exception to be thrown for invoking an intent for internal component.

**Comment by mblcdr** [comment]
So this sounds like there exist some problems with that specific device that this issue is occurring on, maybe a buggy framework (Custom ROM, etc) or bad install.

**Comment by william-ferguson-au** [comment]
Most likely a bad install. But if you are getting exceptions from other
devices with the same ROM then that could be it.
