### ISSUE TITLE
Update advanced instructions so that pre-Holo theme is not applied to report dialog

### ISSUE THREAD

**Issue by timrae** [ACRA/acra#209]
In the advanced instructions it says to add the following line to the Manifest:
```xml
android:theme="@android:style/Theme.Dialog"
```

The line above forces the dialog to use the Android 2.x dialog theme, which looks ugly, and more importantly has the order of "OK" and "Cancel" around the wrong way on post-Honeycomb devices. In order to apply the correct theme, the instructions should be changed to the following:

In your `AndroidManifest.xml`:
```xml
<application ...>

    ....

    <activity android:name="org.acra.CrashReportDialog"
        android:theme="style/Theme.Dialog"
        android:launchMode="singleInstance"
        android:excludeFromRecents="true"
        android:finishOnTaskLaunch="true" />

    ....

</application>
```

In your `res/values/styles.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    ....
  <style name="Theme.Dialog" parent="@android:style/Theme.Dialog" />
</resources>
```

In your `res/values-v11/styles.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    ....
  <style name="Theme.Dialog" parent="@android:style/Theme.Holo.Dialog" />
</resources>
```

**Comment by william-ferguson-au** [comment]
Thanks @timrae 
https://github.com/ACRA/acra/wiki/AdvancedUsage

**Comment by timrae** [comment]
Thanks! But It seems you accidentally put it in the notification subsection
instead of dialog

**Comment by timrae** [comment]
Oh and it has to be 
'android:theme="style/Theme.Dialog"'

**Comment by timrae** [comment]
I just realized it's a WIKI, so edited it myself;  thanks again!

**Comment by william-ferguson-au** [comment]
Great, thanks heaps Tim


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ
