### ISSUE TITLE
Point release?

### ISSUE THREAD

**Issue by timrae** [ACRA/acra#213]
Since the project isn't really on track for a 5.0 release anytime soon, could you please put out a 4.5.1 version? We'd like to include [this](https://github.com/ACRA/acra/commit/ff1800a8fdace0e5b1fda92a3272e7f38ecf5360) for example in our project, but would prefer to bring Acra in through gradle.

**Comment by william-ferguson-au** [comment]
yeah. Have been thinking about that.
There have been enough changes that 4.6.0 is more appropriate.

**Comment by timrae** [comment]
Sounds good. When do you think that would happen? We're currently in the process of switching AnkiDroid over to ACRA, so if it's going to be within a week or two we'll probably wait for 4.6.0

**Comment by william-ferguson-au** [comment]
I'm trying to get hold of Kevin to give me a run down of the release
process.
Will update you when I hear back.
ᐧ

**Comment by KevinGaudin** [comment]
Hey, I'm there, I hope to be able to send all the required information to William tonight.

Thanks a lot for all the work done on this new version !

**Comment by KevinGaudin** [comment]
I just managed to re-setup my packaging environment (brand new laptop...) and have been able to publish a 4.6.0RC1 on Maven Central.

Could you please test it ? In the meantime I'll try to define exactly how to transfer to @william-ferguson-au the procedure (including signing instructions) to let him release new versions on his own.

**Comment by timrae** [comment]
Thank you! I imported and tested that it's working as expected.
Since #199 are we supposed to set setSendReportsAtShutdown=False?
A changelog would be useful when you get time btw ;)

**Comment by timrae** [comment]
By the way, this is unrelated to the point release, but while I have your ears... We want to show a consent dialog the first time a crash is detected, where a privacy policy is shown and the user is recommended to put ACRA into `REPORT_ALWAYS` mode.

What would be the best way to achieve this? Preferably via the current code, but I'm also open to submitting a PR if required

**Comment by william-ferguson-au** [comment]
Changelog already exists :-)

Re #setReportsAtShutdown - that up to you.

Re consent dialog - that is not going to be easy to achieve. And it's not something I would want to incorporate into the project.

I would recommend going the other way and defaulting to REPORT_ALWAYS=true and include an app overview telling them how to switch it off, or making error reporting part of your terms and conditions (which is what I do)

But if you **really** want to do it I would suggest creating your own UncaughtExceptionHandler that your configure after ACRA that performs this dance and then delegates to ACRA if the user says yes.

**Comment by timrae** [comment]
I don't necessarily need to do it the way I suggested, but I have the following two objectives which seem pretty common sense for an open source app:

1) Don't send any data to our servers until the user explicitly agrees to it
2) Don't show an additional dialog the first time the app is started, as this is bad UX design. The user should have as few obstacles as possible to using the app the first time it's started.

Rather than trying to show an additional dialog, how about adding a checkbox "automatically report errors" to the existing dialog? We should be able to control whether it's shown, and the default checked state.

**Comment by timrae** [comment]
At the very least I think we should be able to specify a custom dialog Activity inheriting from `CrashReportDialog`

**Comment by william-ferguson-au** [comment]
OK. Send a pull request and I'll review it.
ᐧ

**Comment by timrae** [comment]
Do you mean both ideas would be acceptable, or only the custom dialog?

**Comment by william-ferguson-au** [comment]
Either one
ᐧ
