### ISSUE TITLE
NoSuchMethodError: org.apache.http.util.EntityUtils.toString$2ebddbce

### ISSUE THREAD

**Issue by arcao** [ACRA/acra#214]
HI Guys,

I use ACRA 4.5.0 in my application and sometimes I receive this crash report:

*Stack Trace:*

    java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.toString$2ebddbce
       at org.acra.util.HttpRequest.send(SourceFile:180)
       at org.acra.sender.HttpSender.send(SourceFile:225)
       at org.acra.SendWorker.sendCrashReport(SourceFile:179)
       at org.acra.SendWorker.checkAndSendReports(SourceFile:141)
       at org.acra.SendWorker.run(SourceFile:77)

*Device Info:*

    BOARD=MSM8974
    BOOTLOADER=I9506XXUCNI1
    BRAND=samsung
    CPU_ABI=armeabi-v7a
    CPU_ABI2=armeabi
    DEVICE=ks01lte
    DISPLAY=KOT49H.I9506XXUCNI1
    FINGERPRINT=samsung/ks01ltexx/ks01lte:4.4.2/KOT49H/I9506XXUCNI1:user/release-keys
    HARDWARE=qcom
    HOST=SWDD5807
    ID=KOT49H
    IS_DEBUGGABLE=false
    IS_SYSTEM_SECURE=false
    MANUFACTURER=samsung
    MODEL=GT-I9506
    PRODUCT=ks01ltexx
    RADIO=unknown
    SERIAL=deccbacb
    TAGS=release-keys
    TIME=1410890663000
    TYPE=user
    UNKNOWN=unknown
    USER=dpi
    VERSION.CODENAME=REL
    VERSION.INCREMENTAL=I9506XXUCNI1
    VERSION.RELEASE=4.4.2
    VERSION.RESOURCES_SDK_INT=19
    VERSION.SDK=19
    VERSION.SDK_INT=19

Seems the called method is not available in SDK 19.

**Comment by william-ferguson-au** [comment]
```EntityUtils#toString(Entity)``` is definitely available in API 19. 
It was there in API 1 and is still there in API 21.

What it looks like you are seeing is a bug in the ROM on the device.

```device=ks01lte``` seems to indicate that it is a Samsung Galaxy S4 but the majority of hits for 'ks01lte' are all to do with the Cyanogen ROM.
