### ISSUE TITLE
Unit tests started failing after including Acra

### ISSUE THREAD

**Issue by timrae** [ACRA/acra#224]
One of our unit tests has started failing in AnkiDroid after including Acra. We do some initialization of some variables in the `onCreate()` method of our application class which the unit test depends on, and if we include the line `ACRA.init(this);` before that unit variable is initialized, the unit test fails due to a NPE for that variable. Commenting out the ACRA.init line leads to the test passing again as usual, and putting ACRA.init at the end of onCreate also appears to fix the issue, though I'm not 100% sure about that.

Any ideas? I'm not really sure even how to debug this issue

**Comment by william-ferguson-au** [comment]
What does the stacktrace look like.
Something is using that variable before it is initialised. What?

**Comment by timrae** [comment]
Replacing `ACRA.init()` with `Thread.sleep(200)` seems to reproduce the issue, so it's not an ACRA problem... The main application and test runner seem to be running in different threads, it's kind of bizarre.
