### ISSUE TITLE
Dump stacktrace to log after sending the report?

### ISSUE THREAD

**Issue by timrae** [ACRA/acra#230]
It would make more sense for Acra to dump the stacktrace to the logcat *after* sending the report, as the stacktrace is already included in the crash report separately. Stacktraces can occasionally be very long, and if we only transmit the last 100 lines of the logcat it could completely wipe all useful debug information.

**Comment by william-ferguson-au** [comment]
But the report may not be sent until a long time later. Eg the next time the app is started (depending upon config).

We need an immediate record in logcat.

However I have noticed that we seem to get 2 logs of the stacktrace.
The second one should be nixed.

**Comment by timrae** [comment]
True I guess we can just use a logcat filter to remove the ACRA messages
anyway

**Comment by william-ferguson-au** [comment]
OK, closing this for now.
