### ISSUE TITLE
handling report failure on self implemented ReportSender

### ISSUE THREAD

**Issue by pauv** [ACRA/acra#232]
hi, 

I've implemented a self ReportSender and it works like a charm. However, in case the report sending fails (e.g: no internet available), there is no retrial, as it does when I delegate to ACRA the report sending. As far as I know, reports are stored somewhere in /data/data/package.name/files, but I'm not sure how to access them after the failed sending. 

Before reinventing the wheel, persisting the failed report and setting up a second sender to handle those reports, I was wondering if there is something already developed to allow accessing to those reports. 

Looking at the source code, I can see some saveCrashReportFile method in the ErrorReporter class, but I'm not sure I should call it from my Sender, nor if the report files are even generated when having my own sender (I definitely don't save them). 

I'd use CrashReportFinder to look for pending reports, but this class seems to be package-private and I can't access it from my code.

any hints? 

thanks in advance, 

pau.

**Comment by william-ferguson-au** [comment]
@pauv SendWorker does the work of calling the Senders.
It only deletes the CrashReport if at least one of the configured Senders has managed to send.

As long as your ReportSender is throwing a ReportSenderException when it can't deliver and you don't also have another Sender that is succeeding, your crash will get queued and resent again later (either when another crash occurs or when the app restarts).

Have a look at SendWorker#141

**Comment by pauv** [comment]
cool. thanks William, that did the trick!

pau.

**Comment by william-ferguson-au** [comment]
Awesome :-)
