### ISSUE TITLE
Different URLs for POSTing for prod and staging apps

### ISSUE THREAD

**Issue by somghosh** [ACRA/acra#234]
How can I put two different URI and username, pwd for sending crash reports for dev and main apps separately? I dont think I can define two annotations in the current scheme of things.

Thanks

    @ReportsCrashes(
            formKey = "",
            httpMethod = HttpSender.Method.PUT,
            reportType = HttpSender.Type.JSON,
            formUri = "http://acra.earthmiles.co.uk/myurl",
            formUriBasicAuthLogin = "XXXXX",
            formUriBasicAuthPassword = "YYYY"
    )
    
    public class App extends Application implements Application.ActivityLifecycleCallbacks {

**Comment by william-ferguson-au** [comment]
You can't.

Most people just close out any dev issues when they release.

You might be able top configure it using Gradle flavours (if you are using Gradle). But you'll wa nt to ask someone who uses Gradle.
