### ISSUE TITLE
ACRA 4.6.0 not in maven repository

### ISSUE THREAD

**Issue by arcao** [ACRA/acra#238]
Hi Guys,

Could you please publish ACRA 4.6.0 to Maven repository? The latest version here is 4.6.0RC2.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22ch.acra%22%20AND%20a%3A%22acra%22

**Comment by KevinGaudin** [comment]
Sorry, @william-ferguson-au missed a few steps in the Sonatype OSS Nexus interface.
I completed the release, it should be available on Maven Cenral within 2 hours.

**Comment by william-ferguson-au** [comment]
Kevin, could you post me a full set of steps?

**Comment by KevinGaudin** [comment]
Done ;-)
