### ISSUE TITLE
Can't switch between email report mode and HTTP report mode at runtime

### ISSUE THREAD

**Issue by timrae** [ACRA/acra#240]
`ACRA.getConfig().setMailTo()` has no effect at runtime; the only way I can get email reporting mode is to set it via the `@ReportsCrashes(` annotation. 

I want to switch to the email reporting method when `BuildConfig.DEBUG` is True so that we don't pollute our server with crashes from debug builds, and so that non-core developers who don't have access to our server can more easily see their stacktraces  when testing debug builds away from the computer.

**Comment by timrae** [comment]
It also seems to be the case

**Comment by timrae** [comment]
Sorry I accidentally closed the issue. I meant to say that you also can't change to HTTP method at runtime

**Comment by william-ferguson-au** [comment]
I don't think it was ever designed to be able to switch reporting modes at
runtime.
ᐧ

**Comment by timrae** [comment]
It can't be too hard... I might take a look if I get time

**Comment by william-ferguson-au** [comment]
OK, closing now.
Open a PR if you get there.
