### ISSUE TITLE
reportfield order?

### ISSUE THREAD

**Issue by JDOaktown** [ACRA/acra#243]
Great product Team Acra!  Thank you kindly.

I've looked thruout the discussion group/etc. and couldn't find any discussion of the following:
Using "4.5 stable"
A) It seems to me that the Reportfield order is fixed in the report and is not affected by the declaration in customReportContent?

B) it seems to me that STACK_TRACE (and other fields too) appear in the report regardless whether they're included in the customReportContent?

ie.

The following reports (I, II, & III)  will look EXACTLY the same:

Report I:
@ReportsCrashes(
	formUri = "https://10.0.0.7:8181/GaelWebSvcGF4/rest/location/ACRAexception"
    , formKey = "" // This is required for backward compatibility but not used
   , customReportContent = {
STACK_TRACE
APP_VERSION_CODE,
USER_IP
}

    , disableSSLCertValidation = true
    , httpMethod = org.acra.sender.HttpSender.Method.POST
    , reportType = org.acra.sender.HttpSender.Type.JSON
    , mode = ReportingInteractionMode.TOAST
    , resToastText = R.string.crash_toast_text 
)

Report II:
@ReportsCrashes(
	formUri = "https://10.0.0.7:8181/GaelWebSvcGF4/rest/location/ACRAexception"
    , formKey = "" // This is required for backward compatibility but not used
   , customReportContent = {
APP_VERSION_CODE,
USER_IP
STACK_TRACE
}

    , disableSSLCertValidation = true
    , httpMethod = org.acra.sender.HttpSender.Method.POST
    , reportType = org.acra.sender.HttpSender.Type.JSON
    , mode = ReportingInteractionMode.TOAST
    , resToastText = R.string.crash_toast_text 
    )

Report III:
@ReportsCrashes(
	formUri = "https://10.0.0.7:8181/GaelWebSvcGF4/rest/location/ACRAexception"
    , formKey = "" // This is required for backward compatibility but not used
   , customReportContent = {
USER_IP
APP_VERSION_CODE,
}

    , disableSSLCertValidation = true
    , httpMethod = org.acra.sender.HttpSender.Method.POST
    , reportType = org.acra.sender.HttpSender.Type.JSON
    , mode = ReportingInteractionMode.TOAST
    , resToastText = R.string.crash_toast_text 
    )

C) it seems that some Reportfields don't appear in the report (eg. USER_IP!! and others) if I request a FULL dump, ie. EVERY SINGLE REPORTFIELD AVAILABLE in the customReportContent .

Is such behaviour expected or a bug(s)? (either way, doc'n required...)

Thank you so very much for an awesome product.
-JD

**Comment by william-ferguson-au** [comment]
Hey @JDOaktown  

A) That is correct. Order of fields is determined by the ACRA, not the config. Endpoints are expected to look for fields based on name not position.

B) Correct. Some field are just intrinsic to a crash report. Have a look at `CrashReportDataFactory`.

C) If you request USER_IP it will be reported. But it is not one of the default fields. See `ACRAConstants.DEFAULT_REPORT_FIELDS` and `ACRAConstants.DEFAULT_MAIL_REPORT_FIELDS`.
