### ISSUE TITLE
Check for pending ACRA reports in service on Lollipop

### ISSUE THREAD

**Issue by Pe-te** [ACRA/acra#244]
Hello,

I ran into the delayed ACRA reports on Lollipop problem, and thought about how to solve it.

Since I have a service in my app anyway that runs repeated every few minutes, my idea was to do the same the lib does when the app starts: check for pending reports and then send them.

Anyone tried that yet? Would it be possible? Where can I start?

Best wishes,
Peter

**Comment by william-ferguson-au** [comment]
But isn't the delayed reports problem the fact that the report won;t be
sent until your app is restarted?

If your service is running then your will already have restarted, so the
report will already have been sent.
ᐧ

**Comment by Pe-te** [comment]
At the moment Acra is started in onCreate of the Application object, and then checks for the reports:

errorReporter.checkReportsOnApplicationStart();

Not sure right now if a service has an Application object, if the service keeps running, if it creates a new Application object when the timer is reached, or if it has already create an own one on service start and doesn't check again, if it will check at the same location the app will store the pending reports .. I'll try a debugging session this weekend unless someone already tried it and tells me my idea is not working. :)

**Comment by william-ferguson-au** [comment]
A service is like any other Android component. When any Android component
starts up, it is started up in the context of an Application.

So, if your app crashed, then it's process will be killed, including any
Service (unless you are running the Service in its own Process  which from
recollection can cause problems with ACRA). If your Service or any other
component (such as an Actiivty or BroadcastReceiver) starts, the
Application will be started first.
ᐧ

**Comment by Pe-te** [comment]
Okay, I added the service lately and did not check afterwards, if it influences ACRA. The problem is already solved!

After a crash, the service is started automatically and does the whole ACRA init stuff, including sending the pending reports. Yay!

If anyone needs the same, I basically followed this tutorial to get a periodic background task:
http://technology.jana.com/author/tashafa/
