### ISSUE TITLE
disk access inside Application.onCreate on main thread

### ISSUE THREAD

**Issue by Lakedaemon** [ACRA/acra#245]
As Acra is doing some disk access inside the Application.onCreate method on the main thread (says strict mode), at start, the user is shown a black screen. 

Isn't there a way to prevent those hapening on the main thread ? 
What if : 
the error handler was set in the Application.onCreate method, 
on caughting an exception, the acra preferences would be fetched from a singleton (lazily created) 
the check to see if previous unsent reports have to be sent through the network was happening in a worker thread

**Comment by william-ferguson-au** [comment]
The reason ACRA configures itself on start up is because it needs to send
any unsent reports at that time. This is necessary because it can't rely on
having enough time/capability to send the report when the crash occurs.

Nee to have a look, but the disk access is probably reading preferences. It
might be possible for ACRA to do that config async.

I'm surprised that you are seeing any modern devices that have a noticeably
pause while reading preferences. The last time I saw that was for the
original Samsung Galaxy S running Android 2.0 in 2010.
ᐧ

**Comment by Lakedaemon** [comment]
I noticed this because I had a big pause (like 5s) at startup in my apps with a black screen on my Galaxy S3 (To be fair, this was mostly due to my code). 

I investiguated this by going into strict mode in my debug build and discovered that quite a lot was happening in Application.onCreate :
some disk acess (1) by the android framework, for font support
some disk access (3) by acra (reading xml preferences)
a lot of disk access and singleton instanciation by my code

So, I cleaned my mess and oly do minimal stuff in onCreate now (no disk access, singleton instanciation now happens much later, lazily on demand when it is really needed and not on the ui thread)

Yet, I still have a black screen on my Galaxy S3 of about 1s/2s (checked now, on my 10MB debug build apk with strict mode on, it might make a difference, released apk is only 4MB ).

Acra like it is now is working just fine. I'm just saying that if something can be done outside Application.onCreate and outside the ui thread, maybee it should (there are millions of acra enabled devices that could profit).

**Comment by william-ferguson-au** [comment]
There is actually about a billion ACRA enabled devices that could benefit
:-)
Want to submit a pull request?
ᐧ

**Comment by Lakedaemon** [comment]
I have no code to offer for now.
I'll have a look to see if I can do something 
(but no promise/eta given there, got a lot of other things to do)

**Comment by william-ferguson-au** [comment]
ᐧ

> (but no promise/eta given there, got a lot of other things to do)
>
There always is. We all share that problem.

**Comment by william-ferguson-au** [comment]
Just had a quick look. This won't be a simple task.
You'll need to work out how to handle not having Preferences in `ErrorReporter` and in `CrashReportDataFactory`, both of which could be called at any point after `ACRA#init()`

I'm going to close this for now. But if you come up with a solution I'll be happy to review your pull request.

**Comment by willim173** [comment]
This is a good point. Disk access inside Application.onCreate can slow down app startup, especially if it runs on the main thread. Moving heavier checks to a worker thread is usually a better approach. For beginners learning Android app setup and basic app behavior, this simple [Android app basics guide](https://smartplayhub.com.br/) may also help.
