### ISSUE TITLE
When will ACRA be able to catch Native Code Errors?

### ISSUE THREAD

**Issue by PanWangJ** [ACRA/acra#247]
I know it said in the wiki that ACRA is currently not able to catch Native Code Errors (not sure if the wiki is out of date or not), but I've already seen similar companies offered the ability to catch Native Code Errors (such as Tencent Bugly http://bugly.qq.com/). Therefore I'm wondering is Native Code Errors catching possible for now or the near future?

**Comment by william-ferguson-au** [comment]
Of you can provide a way that this is possible I'd be happy to include it.

I have no idea how bugly believes it can do it.

**Comment by PanWangJ** [comment]
I'm also curious about how bugly did that, hope someone could figure it out sooner or later.

**Comment by william-ferguson-au** [comment]
If the native code has core dumped there is no way to catch it.

**Comment by william-ferguson-au** [comment]
Closing this, but submit a PR if you come up with some magic that can make it happen.

**Comment by PanWangJ** [comment]
sure》
