### ISSUE TITLE
Q: Should ACRA be used as an application Logger?

### ISSUE THREAD

**Issue by JDOaktown** [ACRA/acra#248]
I know ACRA CAN be used as an application Logger. 
Here's an example which I used from your doc'n:

public class GAELapplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ACRA.init(this);
        
	SystemException  INITIALIZATION_LOG =  new SystemException ();

//Log the beginning of this app session in order to record ALL devices.
        ACRA.getErrorReporter().handleSilentException(INITIALIZATION_LOG);
    }
}//GAELapplication

My question: Since ACRA has been designed to primarily log exceptions, are there any downsides to using it ALSO as an application logger? I am currently using Logback for Android (which I love) but I'm beginning to love ACRA even more and considering yanking Logback completely out and using ACRA exclusively.  Does anyone have any comments on this??

ACRA ROCKS!!!!  T H A N K  Y O U.

**Comment by JDOaktown** [comment]
http://stackoverflow.com/questions/29040411/acra-vs-logback-for-android

**Comment by william-ferguson-au** [comment]
I would definitely not be using ACRA as an application logger.

It's not what it was designed for. You would end up streaming an ACRA report over the net for each "log message". While you could cut the message down to a minimal set, there are some field that are intrinsic to crash reporting that are always sent.
