### ISSUE TITLE
A possible error found in the source code of ErrorReporter.java

### ISSUE THREAD

**Issue by PanWangJ** [ACRA/acra#249]
Hi, As I'm reading the source code of ACRA, when it comes to line **812** of the source code of ErrorReporter.java. 

Source code:

    new Thread() {

            @Override
            public void run() {
                // We have to wait for BOTH the toast display wait AND
                // the worker job to be completed.
                if (toastWaitEnded || (worker == null)) {
                    // Nothing to wait for.
                    Log.d(LOG_TAG, "Toast (if any) and worker completed - not waiting");
                } else {
                    Log.d(LOG_TAG, "Waiting for " + (toastWaitEnded ? "Toast " : " -- ") + (worker.isAlive() ? "and Worker" : ""));
                    while (!toastWaitEnded || worker.isAlive()) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException e1) {
                            Log.e(LOG_TAG, "Error : ", e1);
                        }
                    }
                    Log.d(LOG_TAG, "Finished waiting for Toast + Worker");
                }

In the run() method, we have to wait for **BOTH** the toast display wait **AND** the worker job to be completed. Therefore an if condition is put here to verify whether the **BOTH** toast and woker job are already done. But in the code I saw is:

    if (toastWaitEnded || (worker == null))....
It seems to me that it should be **"&&"**  rather than  **"||"**. By that I mean shouldn't it be:

    if (toastWaitEnded && (worker == null)).....

I'm not very sure if this is an error or simply I just got it wrong, please help me with this.

**Comment by william-ferguson-au** [comment]
Thanks. It's not quite as clean or simple as that.
But that code is poorly structured.

Have just committed a cleanup for it.

Thanks for pointing it out.

**Comment by PanWangJ** [comment]
Alright, thanks for the change, it's clearer now.
