### ISSUE TITLE
A question with regards to setting-up my project when using ACRA.

### ISSUE THREAD

**Issue by PanWangJ** [ACRA/acra#250]
Hi, I'm reading the wiki doc about Basic setup of ACRA. I found this when reading the part of "setting-up your project"(https://github.com/ACRA/acra/wiki/BasicSetup#setting-up-your-project):

    Create a new class in your package root If your app already contains an Application subclass, add ACRA to this class.

Does is mean that no matter my project contains an Application subclass or not, I will still have to create a new class to make ACRA work? Or just have I to add **ACRA.int()** to my Application subclass if there already exists one?

**Comment by KevinGaudin** [comment]
You must use your Application class if you already have one.

**Comment by PanWangJ** [comment]
Ok, thanks.
