### ISSUE TITLE
problem with sharedpreferences 

### ISSUE THREAD

**Issue by Blaster-777** [ACRA/acra#251]
I am developing application that uses sharedPreferences . but when i implementing ACRA library for crash reporting ,all of values from default sharedPreferences of my app is cleaned  and replaced with this  : 
![acra](https://cloud.githubusercontent.com/assets/6900291/6742353/5a90d072-cea4-11e4-8530-35cc7131a3eb.jpg)

**Comment by william-ferguson-au** [comment]
Where are you seeing that output?
What does your ACRA config look like?
What version of ACRA are you using?

**Comment by Blaster-777** [comment]
1- from eclipse file explorer (data/data/my-package/shared_prefs/my-package-preference.xml)
2- @ReportsCrashes(
		
        formUri = "http://my-server.com/report.php",
        customReportContent = {
        ReportField.APP_VERSION_CODE,
        ReportField.APP_VERSION_NAME,
        ReportField.ANDROID_VERSION,
        ReportField.PHONE_MODEL,
        ReportField.CUSTOM_DATA,
        ReportField.STACK_TRACE,
        ReportField.LOGCAT
        },
        mode = ReportingInteractionMode.SILENT
        
    )

3- ACRA 4.6.1

**Comment by william-ferguson-au** [comment]
ACRA doesn't overwrite or remove any non ACRA prefs.
Are you sure that your app had actually persisted some values there?
ᐧ

**Comment by Blaster-777** [comment]
yeah . without ACRA all things is ok

**Comment by william-ferguson-au** [comment]
I'm not familiar with being able to view a preference file from Eclipse.
Is this an app running on a device?
ᐧ
