### ISSUE TITLE
how exclude shared prefs from report?

### ISSUE THREAD

**Issue by AlexMercier** [ACRA/acra#252]
hello. when error occured, the acra send to me report, and with report i have data from 'SHARED_PREFERENCES'. I should not see this, because my app storing private user login and password in this file, and everytime when i got error report i violate privacy policy.
How exclude SHARED_PREFERENCES parameter from report?

**Comment by william-ferguson-au** [comment]
You can either exclude SharedPref keys using regular expressions:
https://github.com/ACRA/acra/wiki/AdvancedUsage#exclude-sharedpreferences-keys

Or you can choose which fields are included in the report and don't send the SharedPrefs field.:
https://github.com/ACRA/acra/wiki/AdvancedUsage#choosing-which-fields-to-be-included-in-reports

**Comment by AlexMercier** [comment]
oh, thats easy, thank you. 
excludeMatchingSharedPreferencesKeys={"login", "pass"} helped me

**Comment by william-ferguson-au** [comment]
Good to hear :-)


ᐧ
