### ISSUE TITLE
Empty report all the time to my backend server

### ISSUE THREAD

**Issue by ZeftAlteen** [ACRA/acra#254]
The following ACRA configuration sends empty report to my backend server:

@ReportsCrashes(
    formKey = "", // This is required for backward compatibility but not used
    formUri = "http://myserver/SubmitCrash.aspx",
    httpMethod=org.acra.sender.HttpSender.Method.POST,
    customReportContent = {ReportField.APP_VERSION_CODE, ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.STACK_TRACE, ReportField.LOGCAT },
    mode = ReportingInteractionMode.SILENT,
    resToastText = R.string.crash_toast_text
)
But if I reconfigure ACRA to send the report to email it sends it without any issue, do someone know why could ACRA send empty report to my backend server?

My backend server using simple c# code to read the form submited by ACRA, every time a crash appears the C# code insert an empty record to DB. C# code is tested carefully and nothing wrong with it.

I'm using the last version of ACRA and Android version 4.4.2

**Comment by william-ferguson-au** [comment]
But how does it take your server to spin up and handle the request?

**Comment by ZeftAlteen** [comment]
I handle the request using the below C# code:

             StringBuilder err = new StringBuilder();
            foreach (string name in Request.Form)
            {
                err.AppendLine(name + ": " + Request.Form[name]);
                
            }
            

            TextWriter tw = null;
            try
            {
                DB.Save_Crash(err.ToString());
                
                //tw = new StreamWriter("f:\\errorLogs\\error_" + DateTime.Now.Ticks + ".txt");
                //tw.WriteLine(err.ToString());
            }
            catch (Exception) { }
            finally
            {
                if (tw != null)
                    tw.Close();
            }

**Comment by ZeftAlteen** [comment]
Can someone help please?

**Comment by william-ferguson-au** [comment]
In our camping so I can't look at the source, bit in almost certain ACRA
doesn't post a HTML form. From recollection it's CR/LF separated list of
fields.

Read the request stream.

**Comment by ZeftAlteen** [comment]
Thank you for your reply. I already red the request stream and it's empty, and here is the C# code the I used it to read the request stream:

            MemoryStream memstream = new MemoryStream();
            Request.InputStream.CopyTo(memstream);
            memstream.Position = 0;
            using (StreamReader reader = new StreamReader(memstream))
            {
                string text = reader.ReadToEnd();
            }

**Comment by william-ferguson-au** [comment]
What does your log says at the point that ACRA is sending?

**Comment by william-ferguson-au** [comment]
And you might want to try setting `socketTimeout = 20000, // This is the milliseconds waiting for data.` to ensure that the HTTP request has enough time to transmit the data. It could be that your sever is not responding quickly enough and the client is killing the connection before anything is sent.

And I was wrong about the send format. By default ACRA will send as HTML form.

**Comment by ZeftAlteen** [comment]
Here is my Logcat:

    04-09 20:57:51.066: E/Trace(661): error opening trace file: No such file or directory (2)
    04-10 09:39:49.249: E/Trace(641): error opening trace file: No such file or directory (2)
    04-10 09:39:50.270: D/ACRA(641): ACRA is enabled for com.MyApp, intializing...
    04-10 09:39:50.352: D/ACRA(641): Looking for error files in /data/data/com.MyApp/files
    04-10 09:39:50.660: D/dalvikvm(641): GC_CONCURRENT freed 278K, 10% free 7423K/8199K,   paused 28ms+22ms, total 125ms
    04-10 09:39:50.680: D/AndroidRuntime(641): Shutting down VM
    04-10 09:39:50.680: W/dalvikvm(641): threadid=1: thread exiting with uncaught exception (group=0x40a13300)
    04-10 09:39:50.680: E/ACRA(641): ACRA caught a RuntimeException exception for com.MyApp. Building report.
    04-10 09:39:50.700: D/ACRA(641): Using default Report Fields
    04-10 09:39:51.510: D/dalvikvm(641): GC_CONCURRENT freed 354K, 11% free 7541K/8391K,  paused 32ms+26ms, total 143ms
    04-10 09:39:52.159: I/ACRA(641): READ_LOGS granted! ACRA can include LogCat and DropBox data.
    04-10 09:39:52.199: D/ACRA(641): Retrieving logcat output...
    04-10 09:39:52.419: D/dalvikvm(641): GC_CONCURRENT freed 540K, 12% free 7563K/8583K, paused 31ms+9ms, total 98ms
    04-10 09:39:52.419: D/dalvikvm(641): WAIT_FOR_CONCURRENT_GC blocked 33ms
    04-10 09:39:52.489: D/dalvikvm(641): GC_FOR_ALLOC freed 23K, 12% free 7561K/8583K,  paused 64ms, total 64ms
    04-10 09:39:52.489: I/dalvikvm-heap(641): Grow heap (frag case) to 7.869MB for 19690-byte allocation
    04-10 09:39:52.559: D/dalvikvm(641): GC_FOR_ALLOC freed 12K, 13% free 7567K/8647K, paused 56ms, total 56ms
    04-10 09:39:52.569: D/ACRA(641): Writing crash report file 1428658792000.stacktrace.
    04-10 09:39:52.709: D/dalvikvm(641): GC_FOR_ALLOC freed 153K, 13% free 7545K/8647K, paused 41ms, total 43ms
    04-10 09:39:52.759: D/ACRA(641): About to start ReportSenderWorker from #handleException
    04-10 09:39:52.759: D/ACRA(641): Mark all pending reports as approved.
    04-10 09:39:52.759: D/ACRA(641): Looking for error files in /data/data/com.MyApp/files
    04-10 09:39:52.781: D/ACRA(641): #checkAndSendReports - start
    04-10 09:39:52.781: D/ACRA(641): Looking for error files in /data/data/com.MyApp/files
    04-10 09:39:52.789: I/ACRA(641): Sending file 1428658792000-approved.stacktrace
    04-10 09:39:52.789: D/ACRA(641): Waiting for Toast + worker...
    04-10 09:39:53.029: D/dalvikvm(641): GC_FOR_ALLOC freed 197K, 13% free 7574K/8647K, paused 42ms, total 43ms
    04-10 09:39:53.110: D/dalvikvm(641): GC_FOR_ALLOC freed 36K, 12% free 7641K/8647K, paused 49ms, total 49ms
    04-10 09:39:53.110: I/dalvikvm-heap(641): Grow heap (frag case) to 7.992MB for 65552-byte allocation
    04-10 09:39:53.169: D/dalvikvm(641): GC_FOR_ALLOC freed 96K, 14% free 7609K/8775K, paused 50ms, total 51ms
    04-10 09:39:53.189: D/ACRA(641): Connect to http://myserver/SubmitCrash.aspx
    04-10 09:39:53.519: D/dalvikvm(641): GC_CONCURRENT freed 411K, 14% free 7630K/8775K, paused 21ms+5ms, total 63ms
    04-10 09:39:53.519: D/dalvikvm(641): WAIT_FOR_CONCURRENT_GC blocked 43ms
    04-10 09:39:53.599: D/ACRA(641): Sending request to http://myserver/SubmitCrash.aspx
    04-10 09:39:54.969: D/ACRA(641): #checkAndSendReports - finish
    04-10 09:39:55.039: D/ACRA(641): Wait for Toast + worker ended. Kill Application ? true
    04-10 09:39:55.059: E/AndroidRuntime(641): FATAL EXCEPTION: main
    04-10 09:39:55.059: E/AndroidRuntime(641): java.lang.RuntimeException:  Unable to start activity ComponentInfo{com.MyApp/com.MyApp.MainActivity}:  java.lang.RuntimeException: This is a crash
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread.access$600(ActivityThread.java:130)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.os.Handler.dispatchMessage(Handler.java:99)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.os.Looper.loop(Looper.java:137)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread.main(ActivityThread.java:4745)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at java.lang.reflect.Method.invokeNative(Native Method)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at java.lang.reflect.Method.invoke(Method.java:511)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at dalvik.system.NativeStart.main(Native Method)
    04-10 09:39:55.059: E/AndroidRuntime(641): Caused by: java.lang.RuntimeException: This is a crash
    04-10 09:39:55.059: E/AndroidRuntime(641):  at com.MyApp.MainActivity.onCreate(MainActivity.java:218)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.Activity.performCreate(Activity.java:5008)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
    04-10 09:39:55.059: E/AndroidRuntime(641):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
    04-10 09:39:55.059: E/AndroidRuntime(641):  ... 11 more
    04-10 09:39:59.819: I/Process(641): Sending signal. PID: 641 SIG: 9

**Comment by ZeftAlteen** [comment]
I checked my server, it sends request quickly.

**Comment by william-ferguson-au** [comment]
OK, I can't see anything unusual in the logs.
Just for sanity's sake, post the client code that you are using to test this.

**Comment by ZeftAlteen** [comment]
Here is my C# code: 

          foreach (string name in Request.Form)
            {
                err.AppendLine(name + ": " + Request.Form[name]);
            }

            try
            {
                DB_DAL.Save_Crash(err.ToString());
                
            }
            catch (Exception) { }
            finally
            {
                if (tw != null)
                    tw.Close();

                Response.StatusCode = 200;
                Response.SuppressContent = true;
                HttpContext.Current.ApplicationInstance.CompleteRequest();
            }

**Comment by william-ferguson-au** [comment]
No. What code are you using on your Android to test this.

**Comment by ZeftAlteen** [comment]
You mean this one?

    @ReportsCrashes(
    formKey = "", // This is required for backward compatibility but not used
    formUri = "http://myserver/SubmitCrash.aspx",
    httpMethod=org.acra.sender.HttpSender.Method.POST,
    customReportContent = {ReportField.APP_VERSION_CODE, ReportField.APP_VERSION_NAME,      ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.STACK_TRACE,    ReportField.LOGCAT },
    mode = ReportingInteractionMode.SILENT,
    resToastText = R.string.crash_toast_text
    )

**Comment by william-ferguson-au** [comment]
Try without the LOGCAT field.

And I actually meant, what code you are using to cause the ACRA to capture
the exception.
ᐧ

**Comment by ZeftAlteen** [comment]
I just throw exception in onCreate function of the main Activity like the following:
   
    throw new RuntimeException("This is a crash");

**Comment by ZeftAlteen** [comment]
Any update?

**Comment by william-ferguson-au** [comment]
No. I can't replicate it.
Have you looked at what is being sent using Wireshark?

**Comment by william-ferguson-au** [comment]
Did you capture it on wireshark?

**Comment by william-ferguson-au** [comment]
Closing due to lack of response

**Comment by raul1991** [comment]
Hi, i have been dealing with this issue, and i removed the logcat option and still it sends the blank request....

```java
formUri = "http://192.168.1.35:8000/docpad"+ParcheeHttpClient.CRASH_URL,
        customReportContent = {ReportField.APP_VERSION_CODE, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA, ReportField.STACK_TRACE, ReportField.LOGCAT },
        mode = ReportingInteractionMode.SILENT,
        reportType = HttpSender.Type.JSON
```

**Comment by william-ferguson-au** [comment]
socketTimeout = 3000 is very small.
Recommend you make it something much larger, eg 12000 and see how that goes.

**Comment by raul1991** [comment]
Sure, ill try it out... I have added a question on SO as well. If you need more details, you can have a look here http://stackoverflow.com/questions/33870617/acra-sends-empty-request?noredirect=1#comment55504502_33870617

**Comment by raul1991** [comment]
Nope that did not work out for me. Here's the update config..

```java
@ReportsCrashes (formUri = "http://192.168.1.35:8000/docpad"+ParcheeHttpClient.CRASH_URL,
        customReportContent = {ReportField.APP_VERSION_CODE, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA, ReportField.STACK_TRACE, ReportField.LOGCAT },
        mode = ReportingInteractionMode.SILENT,
        httpMethod = HttpSender.Method.POST,
        reportType = HttpSender.Type.JSON,
        socketTimeout = 120000
```

**Comment by william-ferguson-au** [comment]
I would recommend cutting a branch and adding some logging to show the fields of the request before it is sent.

**Comment by raul1991** [comment]
The fields are being sent when i set an email configuration instead of POST request.

**Comment by william-ferguson-au** [comment]
Then that suggests that it is problem with comms with your server.

**Comment by raul1991** [comment]
Can you give some suggestion to where to start looking at in the logs of my server, i added to the SO post as well. Do you mind taking a look at it and guiding me ? This error has been faced by many but could not find any solution anywhere.

**Comment by william-ferguson-au** [comment]
I would start by trimming the fields you are sending.
Start with logcat - that can be huge.

Try to get a base case happening.
