### ISSUE TITLE
ACRA.getErrorReporter().handleException(null) hangs on Samsung Galaxy S2 with ICS even with ACRA V4.6.1

### ISSUE THREAD

**Issue by DailyTimer** [ACRA/acra#255]
I filed this report as #20 long before but unfortunately issue was not fixed. I recently update ACRA for V4.6.1 and bit amazed I still see same issue. Below is mostly same when I filed long ago.

ACRA.getErrorReporter().handleException(null) hangs in my app. I noticed this issue recently on my Samsung Galaxy S2 (updated to ICS) when I'm implementing some function. For those who visit this site won't believe this I guess. First I thought I did some mistake but finally I could narrow down a condition that can reproduce this issue, but Samsung Garalxy S2 (ICS 4.0.3) is the only one phone I could reproduce the issue with that code. I have only one ICS phone, I could not reproduce the issue with 2.2 or 2.3 phones. And I could not make it fail on emulator.

I can send/upload a small project which you may be able to reproduce the issue with Samsung Garalxy S2 (ICS). I'm not sure you can, but my Galaxy S2 can.

Description of issue:

ACRA.getErrorReporter().handleException(null) hangs, won't return from it. App stops running.

ACRA's version:

4.6.1 (Previously found on 4.3.1 or 4.3.0)

Key to this issue:

Webview, call ACRA.getErrorReporter().handleException(null) in onCreate or onResume. Depends heavily on environment (phone + OS, not sure).

Please let me pass a project and try to run. ICS phone may be able to reproduce the issue.

Thanks in advance.

**Comment by william-ferguson-au** [comment]
I don't have a Galaxy S2 to test this on, and it **doesn't** happen on 4.0.3 on the emulator.
So I'm closing this until you can provide some more info.

**Comment by DailyTimer** [comment]
OK. I will test with another phone when I got any.
