### ISSUE TITLE
Add aar to mavenCentral with proguard rules

### ISSUE THREAD

**Issue by andrey-shikhov** [ACRA/acra#256]
It will be great to have aar available in repository instead of simple jar - there you can add proguard rules inside of archive and they automatically will be merged to project rules, so you only need to add acra to dependencies without touching proguard files.
It is also good when class structure of library changes, so no need in keeping proguard file up to date.

See 
http://stackoverflow.com/questions/24309950/create-aar-file-in-android-studio
to build aar(android library)

**Comment by william-ferguson-au** [comment]
Happy to take a pull request

**Comment by funtax** [comment]
As far as I know, ACRA 4.7 is packaged as an AAR. Does this already imply the Proguard-mappings, or is this still an open task?

**Comment by william-ferguson-au** [comment]
Adding the Proguard-mappings into the AAR is still an open task. This task.

**Comment by william-ferguson-au** [comment]
Resolved in #346
