### ISSUE TITLE
No catched error details (stackTrace) in IDE's logCat on Lolipop

### ISSUE THREAD

**Issue by mohaxspb** [ACRA/acra#257]
I'm using ACRA for getting crashes of my app.

It works fine (I receive crash-reports on my server with stackTrace and logCat info). But in my IDE (Eclipse) in logCat I see only this line, when I throw exception:

>E/ACRA(18776): ACRA caught a IndexOutOfBoundsException exception for com.example.myapp. Building report.

So I able to read stackTrace of catched error only on my server. 

I can reproduse it on 2 devices with Lolipop (ver 5.1 and 5.0.2). On devices with Android ver < 5 everything is all write (I receive stackTrace on server and in logCat of Eclipse I can also see it).

**Comment by mohaxspb** [comment]
In cmd (adb logcat) everything is OK - error detailes shows.

**Comment by william-ferguson-au** [comment]
So it is a problem with Eclipse or your Eclipse config.
