### ISSUE TITLE
ACRA wont send report after update from 4.5.0 to 4.6.2

### ISSUE THREAD

**Issue by pdauer** [ACRA/acra#271]
Hi,
i updated ACRA from v4.5.0 to v4.6.2 and now it wont send the reports to my server.

Here is my ACRA-Application-Class
 ```java
@ReportsCrashes()
public class UniversityGuide extends Application {

	@Override
	public void onCreate() {
		super.onCreate();

		try {
			ACRA.setConfig(getACRAConfiguration(this));
			ACRA.init(this);
		} catch (IOException e) {
			Log.e("Can not set up ACRA", e.getMessage());
		}

	}

        private ACRAConfiguration getACRAConfiguration(Application application) throws IOException {

		// get custom field values...
		// ...

		ACRAConfiguration config = ACRA.getNewDefaultConfig(this);
		// set the custom configuration
		config.setHttpMethod(Method.valueOf(httpMethod)); // set to PUT
		config.setReportType(Type.valueOf(reportType)); //set to JSON
		config.setCustomReportContent(fields);
		config.setFormUri(uri); // set to https://...:6984/acra...
		config.setFormUriBasicAuthLogin(uriBasicAuthLogin);
		config.setFormUriBasicAuthPassword(uriBasicAuthPassword);
//		config.setFormKey(key);
		config.setDisableSSLCertValidation(Boolean.valueOf(disableSSLCertValidation)); //set to true
		
		return config;
	}
}

```
LogCat with v4.5.0 prints out the following:
> ACRA caught ...
> ACRA using custom fields
> ACRA ReadLogs granted
> ACRA retrieving logcat output
> ACRA is enabled for ...
> looking for error files in ...
> About to start sender worker 
> check and send reports - start
> looking for error files in ... 
> ACRA sending file
> ACRA connect to ...
> ACRA sending request
> check and send reports - finsish

With 4.6.2
> ACRA caught ...
> ACRA prints here stack trace
> ACRA building report
> ACRA using default report fields
> ACRA read logs granted
> ACRA retrieving logcat output

The only thing i changed from 4.5.0 to 4.6.2 is that i had to remove the FormKey.
Whats wrong with this setup? 4.5.0 works without any problems... seems like they dont get my custom config...

**Comment by william-ferguson-au** [comment]
You need to call `ACRA.init(this, getACRAConfiguration());`

A change made in revision `f38bc95` to make it clearer how to manually configure ACRA. Perhaps it should also have made `ACRA.setConfiguration()` private.
