### ISSUE TITLE
ACRA.init(this); error

### ISSUE THREAD

**Issue by AppoPro** [ACRA/acra#272]
Error:(34, 13) error: no suitable method found for init(MainActivity)
method ACRA.init(Application,ACRAConfiguration,boolean) is not applicable
(actual and formal argument lists differ in length)
method ACRA.init(Application,ACRAConfiguration) is not applicable
(actual and formal argument lists differ in length)
method ACRA.init(Application) is not applicable
(actual argument MainActivity cannot be converted to Application by method invocation conversion)

```java
public class MainActivity extends ActionBarActivity {

    final String LOG_TAG = "myLogs";

    ListView lvMain;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Pushbots.sharedInstance().init(this);
        ACRA.init(this); // error here 



        lvMain = (ListView) findViewById(R.id.listView);

        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(
                this, R.array.Menues, R.layout.list_item);
        lvMain.setAdapter(adapter);

```

How i can fix ?

**Comment by william-ferguson-au** [comment]
You need top initialise ACRA from your Application, not your Activity.
