### ISSUE TITLE
If one crash collector crashes, no more are run

### ISSUE THREAD

**Issue by jarofgreen** [ACRA/acra#274]
I would like to suggest a change to 

CrashReportDataFactory -> createCrashData()

Currently it does:

    try
        get thing a 
        get thing b
    catch error
        log

the problem with this is that if Thing A crashes, then it doesn't even try to get Thing B.

For instance, I had this error: https://github.com/ACRA/acra/issues/273 So I remove MEDIA_CODEC_LIST from the field lists, now I get another error from something it wasn't even trying to get before.

In order to send the maximum number of fields per report, even in event of crash, can I suggest instead:

    try
        get thing a 
    catch error
        log

    try
        get thing b
    catch error
        log

Now if getting thing A crashes, thing B will still be attempted!

Unless there was performance or other considerations as to why you wouldn't want to do this?

Thanks,

**Comment by william-ferguson-au** [comment]
Looking forward to your pull request.

**Comment by jarofgreen** [comment]
Done a commit for this which is linked above. Not sure how to run tests in this repo tho.

Is this an Eclipse but not an Android Eclipse project; is that the best environment for editing this? Thought of converting this to an Android Studio project?

**Comment by william-ferguson-au** [comment]
This is a pure Java project. It uses Maven to build.

I don't believe in tying a project to an IDE, so I would never convert it to an Android Studio project.
And I don't see the point of and can't stand Gradle, so I'm not going there either.

**Comment by william-ferguson-au** [comment]
@jarofgreen 

When submitting a pull request, you need to
 * Create a branch from master
 * Commit your changes to the branch
 * Submit a pull request referencing your branch.

**Comment by jarofgreen** [comment]
> I don't believe in tying a project to an IDE, so I would never convert it to an Android Studio project.

Normally, yes. But in this case, seeing as it is just for Android  .... and if you haven't used it I recommend you try it, it is so much better than the old Eclipse + Android plugin.

> And I don't see the point of and can't stand Gradle, so I'm not going there either.

I find it a bit annoying to, but it is the way Android dev has gone. 

But let's maybe pick this up on the email list or at least a separate issue, this is a side consideration.

> When submitting a pull request, you need to

Yup, just wasn't sure how to run tests for it, I notice there are some in the repo? I'll try https://www.jetbrains.com/idea/ community edition later, busy today.

**Comment by william-ferguson-au** [comment]
I haven't used Eclipse since 2008.

All my development is done using IntelliJ and Maven.
I am also one of the committers for the Android Maven plugin (long before
Gradle came along).

But at this point the ACRA project has no Android resources and can be
shipped as a jar.
Ie it doesn't need to be shipped as an AAR.
ᐧ

**Comment by william-ferguson-au** [comment]
Resolved
