### ISSUE TITLE
How can I show customReportContent directly in dialog

### ISSUE THREAD

**Issue by zouyongdang** [ACRA/acra#275]
I want to report crash event using dialog mode and show the stack trace or logcat info directly in the dialog, rather than showing a fixed string resource. How can I do that?

**Comment by william-ferguson-au** [comment]
You would need to write your own custom reporting dialog, and configure
ACRA to invoke it.


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ
