### ISSUE TITLE
How to limit base by count errors or  in disk space

### ISSUE THREAD

**Issue by ldima** [ACRA/acra#276]
I consider the question of database restrictions on count errors or the amount of disk space.
I configuration ACRA  use Apache CouchDB with Cloudant hosting.
Situation following if it has accumulated a lot of error at the advent of the Internet all errors will be sent to the channel and block the Internet, or using all the user traffic.
I would like to have it as a tool to set the maximum number of Error. Exceeding these  quota errors cleans list error. Or the same thing by the volume disk space.
Is this possible?
Tnx friend.

**Comment by william-ferguson-au** [comment]
So your app is generating a lot of errors and you want to ignore all errors beyond a certain number?

There is no way in ACRA to do this.
The best solution is to fix the problem in your app.

**Comment by ldima** [comment]
Hi William ) 
William, I just think that this is possible, and I provide a mechanism of protection.
1) How to determine the number of recorded errors?
2) How to clear database errors?

**Comment by william-ferguson-au** [comment]
1) You can determine number of recorded errors by counting the number of error files.
2) You can clear the errors by deleting the error files.

But if you have lots of errors in your app they will keep coming back. Again and again and again.

**Comment by jarofgreen** [comment]
At the server side you could have something to remove old crashes to keep the size of the database small. Or even something to see if an incoming crash is already known, and not store the new one if so. However you also mention:

> or using all the user traffic

I assume you mean you want to reduce the "$1.00 per GB / month" Data volume charge Cloudant makes?

This is the bit you can't reduce. When ACRA gets an error, it does not know if the limit of errors is reached on the server or if this is a known crash and so it always sends the error to the server. It would not be possible for ACRA to know without contacting the server and using data anyway. So the only way to reduce this is to fix the errors in your app :-)
