### ISSUE TITLE
Compress data in email to send full logs

### ISSUE THREAD

**Issue by eytans** [ACRA/acra#283]
as sending data in email is limited i went on and made my own sender because i wanted more logs.
after trying  to zip logs into a file and attach to mail i found out it may be very problamatic as not all mail apps attach files properly. in the end i decided to compress and show it as base64 string so ill be able to put it in the end of the mail and inflate it at backend.

here is what i do (and after it how to inflate using python):

    @Override
    public void send(Context context, CrashReportData errorContent) throws ReportSenderException {

        final String subject = "Crash Report";
        String body = "You can add extra data here";

        ReportField[] fields = ACRA.getConfig().customReportContent();
        if(fields.length == 0) {
            fields = ACRAConstants.DEFAULT_MAIL_REPORT_FIELDS;
        }

        StringBuilder builder = new StringBuilder();
        for (ReportField field : fields) {
            builder.append(field.toString()).append("=");
            builder.append(errorContent.get(field));
            builder.append('\n');
        }

        // if old report exists delete it.
        // create zip with all the data
        boolean zipSuccess = false;
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            OutputStream zip = new DeflaterOutputStream(baos);
            zip.write(builder.toString().getBytes());
            zip.close();
            body += "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
            body += "Report Start\n";
            body += Base64.encodeToString(baos.toByteArray(), Base64.DEFAULT);
            body += "Report End\n";
            zipSuccess = true;
        } catch (FileNotFoundException e) {
            body += "\n";
            body += builder.toString();
        } catch (IOException e) {
            body += "\n";
            body += builder.toString();
        }
        Log.d("MailReport", "adding stuff to mail");
        final Intent emailIntent = new Intent(android.content.Intent.ACTION_SENDTO);
        emailIntent.setData(Uri.fromParts("mailto", ACRA.getConfig().mailTo(), null));
        emailIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        emailIntent.putExtra(android.content.Intent.EXTRA_SUBJECT, subject);
        emailIntent.putExtra(android.content.Intent.EXTRA_TEXT, body);
        context.startActivity(emailIntent);
        Log.d("MailReport", "finished");
    }

python:
import zlib
import base64
bytes = base64.b64decode(base64Data)
text = zlib.decompress(bytes).decode('utf-8')
fixedText = text.replace('\uae08', " ") #as it seems he had a problem with this charecter

**Comment by william-ferguson-au** [comment]
Interesting. But wouldn't it have been easier to post the error report via http?

**Comment by eytans** [comment]
Yes but some apps (including mine) should not have internet permissions. Which is actually the reason acra has an email sender.

**Comment by william-ferguson-au** [comment]
Point. So what's the intent of this issue that you raised?

**Comment by eytans** [comment]
Actually i just wanted to offer this as an enhancement and didn't find how to mark it as one. I posted this code to make it easier although its pretty simple. I thought maybe a mode you will want to add a mode/configuration in the default mail sender.

**Comment by william-ferguson-au** [comment]
The most appropriate way would be to provide a pull request that either
provides a 2nd email sender that sends it payload as base64 or config to
have existing email sender send payload as base 64.


ᐧ

**Comment by eytans** [comment]
So I will close the issue, never worked with github before so sorry for the inconvenience. And the data is actually compressed as a zip and then represented as base64 to be able to send it as zip. (the compressed size is 14% of original size)
