### ISSUE TITLE
Dialog is not shown when crash occurs in a background thread on API<17

### ISSUE THREAD

**Issue by Ereza** [ACRA/acra#284]
I have been testing the Dialog reporting mode and found out that when the app crashes on API<17, the dialog is only shown if the crash has occurred on the main thread. If it happens on a background thread, the app is just closed and no dialog is shown.

I attach a sample project to reproduce the issue: https://dl.dropboxusercontent.com/u/28776368/AcraDialogCrashTest.zip

I have been able to workaround it by adding `process=":error_report"` in my `org.acra.CrashReportDialog` activity definition, but I don't know if this may cause any unexpected issues.

If this is a valid workaround, documentation should be modified to state that a custom process must be set on the activity. Or maybe I'm missing something...?

**Comment by william-ferguson-au** [comment]
mm, thanks for the report.

Specifying a process for the CrashReportDialog should cause any undue issue. 
But I'm not sure why it is required.

I have updated the doco.

**Comment by Ereza** [comment]
Great, thanks!
