### ISSUE TITLE
send crash report on my email id.

### ISSUE THREAD

**Issue by Slake07** [ACRA/acra#285]
how can i send all crash reports on my email id.?

i did like below:

@ReportsCrashes( // will not be used
mailTo = "reports@yourdomain.com",
mode = ReportingInteractionMode.TOAST,
resToastText = R.string.crash_toast_text)

is it correct or not?

**Comment by william-ferguson-au** [comment]
You need to use ReportingInteractionMode. EMAIL

**Comment by Slake07** [comment]
there is no such type of option in that.

**Comment by william-ferguson-au** [comment]
Sorry,. Yes that is correct.
