### ISSUE TITLE
Use of Apache HTTP client

### ISSUE THREAD

**Issue by andrewpmoore** [ACRA/acra#287]
With android M preview removing the Apache HTTP client and suggesting using HttpURLConnection instead, are there any plans to migrate to using this?

I'd prefer not to have to import legacy libraries to get it working on newer builds.

**Comment by william-ferguson-au** [comment]
That's a really good idea.
Want to have a crack at a pull request?

**Comment by nelenkov** [comment]
AFAIK, there is a compatibility library as well, so no need to migrate the code immediately. Also the Apache libs are not removed, just hidden in M, so things won't break just yet.

**Comment by andrewpmoore** [comment]
It wouldn't build for me using the default code. I've not added in the legacy library into gradle but would prefer not to.

**Comment by william-ferguson-au** [comment]
What wouldn't build for you?

**Comment by nelenkov** [comment]
If you are targeting MNC, it won't build, because org.apache.* is no part of the public SDK anymore. Target 21, etc. and it will build and work.

**Comment by andrewpmoore** [comment]
Yes, I'm wanting to target MNC for getting an app ready for the new permissions features.

**Comment by javmarina** [comment]
Yes, that's definitely a good idea.

**Comment by javmarina** [comment]
IMPORTANT:
you have to include this in your build.gradle:

android {
    useLibrary 'org.apache.http.legacy'
}

Read https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client for more information.

**Comment by william-ferguson-au** [comment]
@javmarina I would think that you should only need to to that if you are compiling ACRA against MNC using Gradle. I wouldn't expect that requirement when compiling your APK (unless your app directly uses the Apache HTTP Client).

**Comment by javmarina** [comment]
Does that mean that, even if an app using Acra is targeting Android M but not using Apache Http libray, its not necessary to include those lines in the Acra's build.gradle??

**Comment by william-ferguson-au** [comment]
It would not be necessary to include those lines in your app's build.gradle

**Comment by Ph1b** [comment]
It seems necessary. My app does not compile in release mode using gradle the way it is now.

**Comment by william-ferguson-au** [comment]
What is the symptom?
What line of your app does not compile?

**Comment by Ph1b** [comment]
Its weird now. At some point gradle was just complaining about apache, but now it is fine. Guess it was a temporary error due to some leftover build files.

**Comment by bottiger** [comment]
I still feel there are something unresolved here: [I do have](https://github.com/bottiger/SoundWaves/commit/36b6e5422192b9585fe6249ca61a456e3d3f11db#diff-39e7d8c00954e920b98e7636f0ac30b2) use the apache legacy library in my build.gradle, [but still have build problems on F-droid](https://f-droid.org/wiki/page/org.bottiger.podcast/lastbuild_144)

**Comment by william-ferguson-au** [comment]
Yeah, looks like they have removed `Notification.setLatestEventInfo()` in Marshamallow.
It has been deprecated since they introduced Builder in API 17.

Looks like we are finally going to have to 
* Add a dependency upon the AppCompat V4 support library.
* Which means we will have to package as an AAR too.

**Comment by Ph1b** [comment]
I can build with proguard enabled: [error log](https://gist.github.com/Ph1b/63525653e1936337ebab)

**Comment by william-ferguson-au** [comment]
There are actually 2 issues here wrt compiling against Android M.
1) The Apache HTTP libraries have been hidden.
2) Some deprecated methods from Notification have been removed and the only replacement is available using the AppCompat V4 library.

**Comment by william-ferguson-au** [comment]
Resolving the fact that the Apache HTTP classes have been hidden is non-trivial because Google have not seen fit to publish the http legacy jar into an artifact repository but have instead jsut jammed it into the SDK\platforms\android-23\optional folder.

Any thoughts on how to best add it as a dependency?

**Comment by william-ferguson-au** [comment]
I think using https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html might be the best solution.

**Comment by william-ferguson-au** [comment]
I'm going to cut a release candidate.
Please test against that.
