### ISSUE TITLE
ReportSenderException

### ISSUE THREAD

**Issue by AlexBurk** [ACRA/acra#288]
Hi,

first, sorry for the long ugly post, don't know how to cut it down without hiding information.

I got the exception added below. I feel that the webmethod is just no right. Its in ASP .NET.
To be honest I didnt understand the docs for receiving a crash using POST correctly. There's a FORM incoming? How would the method look like to get a Field?

@ReportsCrashes(
//        formKey = "", // This is required for backward compatibility but not used
        formUri = "http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod", 
        httpMethod = HttpSender.Method.POST,
	mode = ReportingInteractionMode.SILENT,
	customReportContent = {APP_VERSION_CODE},
)

WebMethod:
        [WebMethod(Description = "crash test method.")]
        public String TestMethod(String APP_VERSION_CODE)
        {
            // I only send 1 field, APP_VERSION_CODE. How to retrieve this?
        }

Exception:
06-26 16:22:18.298: E/ACRA(7631): ACRA caught a IllegalStateException for my.app
06-26 16:22:18.298: E/ACRA(7631): java.lang.IllegalStateException: Could not execute method of the activity
06-26 16:22:18.298: E/ACRA(7631): 	at android.view.View$1.onClick(View.java:3591)
06-26 16:22:18.298: E/ACRA(7631): 	at android.view.View.performClick(View.java:4084)
06-26 16:22:18.298: E/ACRA(7631): 	at android.view.View$PerformClick.run(View.java:16966)
06-26 16:22:18.298: E/ACRA(7631): 	at android.os.Handler.handleCallback(Handler.java:615)
06-26 16:22:18.298: E/ACRA(7631): 	at android.os.Handler.dispatchMessage(Handler.java:92)
06-26 16:22:18.298: E/ACRA(7631): 	at android.os.Looper.loop(Looper.java:137)
06-26 16:22:18.298: E/ACRA(7631): 	at android.app.ActivityThread.main(ActivityThread.java:4895)
06-26 16:22:18.298: E/ACRA(7631): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-26 16:22:18.298: E/ACRA(7631): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-26 16:22:18.298: E/ACRA(7631): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-26 16:22:18.298: E/ACRA(7631): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
06-26 16:22:18.298: E/ACRA(7631): 	at dalvik.system.NativeStart.main(Native Method)
06-26 16:22:18.298: E/ACRA(7631): Caused by: java.lang.reflect.InvocationTargetException
06-26 16:22:18.298: E/ACRA(7631): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-26 16:22:18.298: E/ACRA(7631): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-26 16:22:18.298: E/ACRA(7631): 	at android.view.View$1.onClick(View.java:3586)
06-26 16:22:18.298: E/ACRA(7631): 	... 11 more
06-26 16:22:18.298: E/ACRA(7631): Caused by: java.lang.RuntimeException: This is a crash
06-26 16:22:18.298: E/ACRA(7631): 	at my.app.activities.misc.DashboardActivity.onClick(DashboardActivity.java:846)
06-26 16:22:18.298: E/ACRA(7631): 	... 14 more

06-26 16:22:18.298: D/ACRA(7631): Building report
06-26 16:22:18.298: D/ACRA(7631): Using custom Report Fields
06-26 16:22:18.318: I/ACRA(7631): READ_LOGS granted! ACRA can include LogCat and DropBox data.
06-26 16:22:18.318: D/ACRA(7631): Writing crash report file 1435328538000.stacktrace.
06-26 16:22:18.328: D/ACRA(7631): About to start ReportSenderWorker from #handleException
06-26 16:22:18.328: D/ACRA(7631): Mark all pending reports as approved.
06-26 16:22:18.328: D/ACRA(7631): Looking for error files in /data/data/my.app/files
06-26 16:22:18.328: D/ACRA(7631): #checkAndSendReports - start
06-26 16:22:18.328: D/ACRA(7631): Looking for error files in /data/data/my.app/files
06-26 16:22:18.328: I/ACRA(7631): Sending file 1435325855000-approved.stacktrace
06-26 16:22:18.338: D/ACRA(7631): Waiting for Toast
06-26 16:22:18.338: D/ACRA(7631): Finished waiting for Toast
06-26 16:22:18.338: D/ACRA(7631): Waiting for Worker
06-26 16:22:18.348: D/ACRA(7631): Connect to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.348: D/ACRA(7631): Sending request to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.558: E/ACRA(7631): Failed to send crash report for 1435325855000-approved.stacktrace
06-26 16:22:18.558: E/ACRA(7631): org.acra.sender.ReportSenderException: Error while sending FORM report via Http POST
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:250)
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.SendWorker.sendCrashReport(SendWorker.java:178)
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.SendWorker.run(SendWorker.java:76)
06-26 16:22:18.558: E/ACRA(7631): Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.52.146:63490 refused
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.util.HttpRequest.send(HttpRequest.java:158)
06-26 16:22:18.558: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:247)
06-26 16:22:18.558: E/ACRA(7631): 	... 3 more
06-26 16:22:18.558: E/ACRA(7631): Caused by: java.net.ConnectException: failed to connect to /192.168.52.146 (port 63490) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.558: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:224)
06-26 16:22:18.558: E/ACRA(7631): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
06-26 16:22:18.558: E/ACRA(7631): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
06-26 16:22:18.558: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
06-26 16:22:18.558: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
06-26 16:22:18.558: E/ACRA(7631): 	at java.net.Socket.connect(Socket.java:832)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
06-26 16:22:18.558: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
06-26 16:22:18.558: E/ACRA(7631): 	... 10 more
06-26 16:22:18.558: E/ACRA(7631): Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.558: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
06-26 16:22:18.558: E/ACRA(7631): 	... 17 more
06-26 16:22:18.568: I/ACRA(7631): Sending file 1435326775000-approved.stacktrace
06-26 16:22:18.568: D/ACRA(7631): Connect to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.578: D/ACRA(7631): Sending request to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.588: E/ACRA(7631): Failed to send crash report for 1435326775000-approved.stacktrace
06-26 16:22:18.588: E/ACRA(7631): org.acra.sender.ReportSenderException: Error while sending FORM report via Http POST
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:250)
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.SendWorker.sendCrashReport(SendWorker.java:178)
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.SendWorker.run(SendWorker.java:76)
06-26 16:22:18.588: E/ACRA(7631): Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.52.146:63490 refused
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.util.HttpRequest.send(HttpRequest.java:158)
06-26 16:22:18.588: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:247)
06-26 16:22:18.588: E/ACRA(7631): 	... 3 more
06-26 16:22:18.588: E/ACRA(7631): Caused by: java.net.ConnectException: failed to connect to /192.168.52.146 (port 63490) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.588: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:224)
06-26 16:22:18.588: E/ACRA(7631): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
06-26 16:22:18.588: E/ACRA(7631): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
06-26 16:22:18.588: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
06-26 16:22:18.588: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
06-26 16:22:18.588: E/ACRA(7631): 	at java.net.Socket.connect(Socket.java:832)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
06-26 16:22:18.588: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
06-26 16:22:18.588: E/ACRA(7631): 	... 10 more
06-26 16:22:18.588: E/ACRA(7631): Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.588: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
06-26 16:22:18.588: E/ACRA(7631): 	... 17 more
06-26 16:22:18.588: I/ACRA(7631): Sending file 1435328538000-approved.stacktrace
06-26 16:22:18.588: D/ACRA(7631): Connect to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.588: D/ACRA(7631): Sending request to http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod
06-26 16:22:18.598: E/ACRA(7631): Failed to send crash report for 1435328538000-approved.stacktrace
06-26 16:22:18.598: E/ACRA(7631): org.acra.sender.ReportSenderException: Error while sending FORM report via Http POST
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:250)
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.SendWorker.sendCrashReport(SendWorker.java:178)
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.SendWorker.run(SendWorker.java:76)
06-26 16:22:18.598: E/ACRA(7631): Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.52.146:63490 refused
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.util.HttpRequest.send(HttpRequest.java:158)
06-26 16:22:18.598: E/ACRA(7631): 	at org.acra.sender.HttpSender.send(HttpSender.java:247)
06-26 16:22:18.598: E/ACRA(7631): 	... 3 more
06-26 16:22:18.598: E/ACRA(7631): Caused by: java.net.ConnectException: failed to connect to /192.168.52.146 (port 63490) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.598: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:224)
06-26 16:22:18.598: E/ACRA(7631): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
06-26 16:22:18.598: E/ACRA(7631): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
06-26 16:22:18.598: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
06-26 16:22:18.598: E/ACRA(7631): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
06-26 16:22:18.598: E/ACRA(7631): 	at java.net.Socket.connect(Socket.java:832)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
06-26 16:22:18.598: E/ACRA(7631): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
06-26 16:22:18.598: E/ACRA(7631): 	... 10 more
06-26 16:22:18.598: E/ACRA(7631): Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
06-26 16:22:18.598: E/ACRA(7631): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
06-26 16:22:18.598: E/ACRA(7631): 	... 17 more
06-26 16:22:18.598: D/ACRA(7631): #checkAndSendReports - finish
06-26 16:22:18.638: D/ACRA(7631): Finished waiting for Worker
06-26 16:22:18.638: D/ACRA(7631): Wait for Toast + worker ended. Kill Application ? true
06-26 16:22:18.638: D/ACRA(7631): Handing Exception on to default ExceptionHandler
06-26 16:22:18.638: E/AndroidRuntime(7631): FATAL EXCEPTION: main
06-26 16:22:18.638: E/AndroidRuntime(7631): java.lang.IllegalStateException: Could not execute method of the activity
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.view.View$1.onClick(View.java:3591)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.view.View.performClick(View.java:4084)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.view.View$PerformClick.run(View.java:16966)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.os.Handler.handleCallback(Handler.java:615)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.os.Handler.dispatchMessage(Handler.java:92)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.os.Looper.loop(Looper.java:137)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.app.ActivityThread.main(ActivityThread.java:4895)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at dalvik.system.NativeStart.main(Native Method)
06-26 16:22:18.638: E/AndroidRuntime(7631): Caused by: java.lang.reflect.InvocationTargetException
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at android.view.View$1.onClick(View.java:3586)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	... 11 more
06-26 16:22:18.638: E/AndroidRuntime(7631): Caused by: java.lang.RuntimeException: This is a crash
06-26 16:22:18.638: E/AndroidRuntime(7631): 	at my.app.activities.misc.DashboardActivity.onOrder(DashboardActivity.java:846)
06-26 16:22:18.638: E/AndroidRuntime(7631): 	... 14 more

**Comment by william-ferguson-au** [comment]
The content of the HTTP POST are the report fields as key value pairs, with the key and value separated by '=' and the pairs separated by '&' which is the same format as a HTTP FORM
log message is not accurate. It's not posting a HTTP FORM. Both Key and Value are UTF-8 encoded.

But your problem seems to ne that your web server is either not at ```http://192.168.52.146:63490/xxx/Transfer.asmx?op=TestMethod``` or is not accepting requests. Suggest you test it manually using curl or similar.

**Comment by AlexBurk** [comment]
You were right, the problem was the webserver. I now get a value, thanks a lot! :)
Though I'm struggling to add more than one parameter, I get a Host returned error code 500 for multiple reportfields.

**Comment by william-ferguson-au** [comment]
HTTP 500 is a server error.
You need to debug what is happening on your server.
