### ISSUE TITLE
New way to create custom view in CrashDialog

### ISSUE THREAD

**Issue by javmarina** [ACRA/acra#290]
Right now, the CrashDialog is using a LinearLayout with a few views inside. It doesn't seem to be a problem. However, I'm developing a Material app and I want to use Theme.AppCompat.Dialog instead of Theme.Dialog in order to have the best design possible. I tried it, but the result is very ugly (see screenshot, padding and margins are not correct).
Fortunately, there is a way to correct it (or at least it should work). According to Android Developers documentation, "if you want to display a more complex view, look up the FrameLayout called "custom" and add your view to it:"

FrameLayout fl = (FrameLayout) findViewById(android.R.id.custom);
 fl.addView(myView, new LayoutParams(MATCH_PARENT, WRAP_CONTENT));

(see http://developer.android.com/reference/android/app/AlertDialog.html)

And then creating views inside that FrameLayout.
Thanks in advance.

PS: the icon is also ugly, but I'll probably change it by myself.

![_20150707_235238](https://cloud.githubusercontent.com/assets/2737599/8558302/917293e0-2503-11e5-86cb-0f67492995b5.JPG)

**Comment by william-ferguson-au** [comment]
Do you have a pull request?

**Comment by javmarina** [comment]
No

**Comment by william-ferguson-au** [comment]
OK, in that case I'm closing this.
If you want to submit a pull request then I'll look at it.
