### ISSUE TITLE
Android M permission support

### ISSUE THREAD

**Issue by javmarina** [ACRA/acra#292]
With the new permissions system, apps have to request permissions in order to use them. If I want to include the logcat output in the crash report, I need the READ_LOGS permission, which isn't included in the "normal" category (see https://developer.android.com/preview/features/runtime-permissions.html#best-practices at the bottom). Therefore, it would be good if Acra library handled the permission by itself. For example, not including the logcat output if the permission was not granted by the user.
I know this is not a high priority issue, but it will help a lot of developers in the future, when the final version is released.
Thanks in advance.

**Comment by william-ferguson-au** [comment]
ACRA already excludes logs if the READ_LOGS permission has not been granted.
See https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/collector/CrashReportDataFactory.java#L432

Note that post JELLY_BEAN an application only has access to log records it has written in any case.

Do you think more needs to be done?

**Comment by javmarina** [comment]
Well, this checks if READ_LOGS has been defined in the manifest. On Android M, you have to explicity request the permission to the user **at runtime**, showing a dialog (if you're targeting this version).

However, I've been thinking about it and READ_LOGS permission is not used since Jelly Bean 4.1. Therefore, it's apparently not neccessary to change anything at all. It's really confusing.

**Comment by william-ferguson-au** [comment]
No, it doesn't check if READ_LOGS has been defined in the Manifest.

It checks if READ_LOGS has been granted by the user. This is whole of app permission prior to M or per permission in M+.

And yes, READ_LOGS is not particularly interesting since 4.1 as you only have access to the logs generated by your app in any case.

**Comment by javmarina** [comment]
So starting with Jelly Bean, READ_LOGS permission can't be granted to an app, it's not shown to the user at install time and methods to read logs generated by the app itself don't require any permission. That means that we have to include that permission in the manifest for backwards compatibility. So no changes are needed in the code.

Thanks.
