### ISSUE TITLE
The element sharedPreferencesName is not complete for the annotation

### ISSUE THREAD

**Issue by bernardn98** [ACRA/acra#297]
Can someone shed some light to why I'm getting this?  I'm stuck on this issue for the entire day now.

Version used: acra-4.6.0RC2.jar

Caused by: java.lang.annotation.IncompleteAnnotationException: The element sharedPreferencesName is not complete for the annotation org.acra.annotation.ReportsCrashes

08-12 20:00:23.319: E/AndroidRuntime(4160): 	at org.acra.ACRAConfiguration.sharedPreferencesName(ACRAConfiguration.java:1090)
08-12 20:00:23.319: E/AndroidRuntime(4160): 	at org.acra.ACRA.getACRASharedPreferences(ACRA.java:295)
08-12 20:00:23.319: E/AndroidRuntime(4160): 	at org.acra.ACRA.init(ACRA.java:168)
08-12 20:00:23.319: E/AndroidRuntime(4160): 	at org.acra.ACRA.init(ACRA.java:135)
08-12 20:00:23.319: E/AndroidRuntime(4160): 	at org.acra.ACRA.init(ACRA.java:120)

My configuration
@ReportsCrashes(
httpMethod = org.acra.sender.HttpSender.Method.PUT,
reportType = org.acra.sender.HttpSender.Type.JSON,
formUri = "http://192.168.1.17:5984/acra-myapp/_design/acra-storage/_update/report",
formUriBasicAuthLogin = "testdemo",
formUriBasicAuthPassword = "p4ss0rd"
)

Greatly appreciated if someone can help me.

--Bernard

**Comment by william-ferguson-au** [comment]
Hi @bernardn98 looks like you may not be keeping annotations in your Proguard config.
See http://stackoverflow.com/questions/5582383/problem-with-proguard-and-roboguice-with-inject-annotations

**Comment by bernardn98** [comment]
Yay that fixed it.  Thank you William!!! 

Added this line to Proguard config.  This is the 2nd time I got bitten by Proguard.

-keepattributes *Annotation*
