### ISSUE TITLE
Acra package is not a constant error

### ISSUE THREAD

**Issue by bernardn98** [ACRA/acra#298]
After fixing one error now another.  I googled and found the link below but the answer didn't help me.  Shouldn't this work out of the box? 

Failed to send crash reports for fc0bd930-ed39-431b-a546-164c57c78a3e.stacktrace
java.lang.IllegalArgumentException: Package is not a constant in org.acra.ReportField
	at java.lang.Enum.valueOf(Enum.java:200)

http://stackoverflow.com/questions/22390233/acra-package-is-not-a-constant-error-android-studio

Thanks,
--Bernard

**Comment by william-ferguson-au** [comment]
ACRA does work OOTB. You are only the 2nd person to report that issue. I have no idea what is causing it.

Did you try clearing the app data as I suggested in the SO post?

**Comment by bernardn98** [comment]
Found the cause of the problem, please close ticket.  You're right William ACRA does work OOTB.  It happened because I was using another crash reporting library. HockeyApp's crash reporting was conflicting with ACRA.  I disabled it by commenting out the method checkForCrashes() and the error went away.  

Also if you're using Google Analytics comment out this line.  It caused my app to hang and block ACRA from posting all errors.

tracker.enableExceptionReporting(true);

Thank you
--Bernard

**Comment by william-ferguson-au** [comment]
Thanks for the update @bernardn98 
Glad you got it working.
