### ISSUE TITLE
I see no option to close the App after send the crash Report

### ISSUE THREAD

**Issue by HowardSchmaeu** [ACRA/acra#299]
... sorry if i missed something... but i could not found any option to "finish()" my App after a Crash. Is there any Option that i haven't found??

THX

**Comment by william-ferguson-au** [comment]
Your app will just exit.
ACRA either hands off the initial UnhandledExceptionHandler or calls exit(-1)

**Comment by HowardSchmaeu** [comment]
Okay ... u are right with a "normal" Crash :-) ... BUT i'm in the middle of a Observable Subscription... 
I get the ACRA - Dialog (or the Toast) and also i got the Result on my CouchDB. But the Subscriber ends up in the onError() (depends on my source)
so that means i need something to also stop the Subsriber or from ACRA a "OnCrash()" - Function to Stop all that Stuff by my own...OR??

**Comment by william-ferguson-au** [comment]
I don't understand what you are trying to do.

**Comment by HowardSchmaeu** [comment]
okay i made a small project u found it here: https://github.com/HowardSchmaeu/SpikeACRA
the thing is if you hit the first button all work how expected... but the both other Buttons just runs in the subscription Error and did not show any Dialog...

**Comment by william-ferguson-au** [comment]
Are you using Proguard?
I can't see any of the required ACRA config in your Proguard rules.

**Comment by HowardSchmaeu** [comment]
hmm ... it's just a standard Android Project... with no special settings from my side... is Proguard on by default?? Then i use it :-D ... i've no Experience with Proguard till now...

**Comment by william-ferguson-au** [comment]
Well I don't use Gradle - so I can't tell you if its on by default.
You have a Proguard file and you ref Proguard in your Gradle config.
Are your classes getting obfuscated?

I'm asking because if you are using Proguard and you haven't applied the Proguard config for ACRA then this could be causing you issues.

**Comment by HowardSchmaeu** [comment]
okay from this Site: https://developer.android.com/tools/help/proguard.html
" ProGuard runs only when you build your application in release mode, so you do not have to deal with obfuscated code when you build your application in debug mode. Having ProGuard run is completely optional, but highly recommended."

so that means Proguard should not be the Problem right?? i only have the Debug Mode!! As i know :-)

**Comment by william-ferguson-au** [comment]
OK, looking at your code I understand why ACRA gets invoked when you click the first button - because you throw a NullPointerException at line 47.

But I can't see where any other unhandled exception is generated for buttons 2 and 3. Why do you expect an Exception to be thrown?

**Comment by HowardSchmaeu** [comment]
okay just look at this: https://github.com/HowardSchmaeu/SpikeACRA2/blob/master/app/src/main/java/com/zertificon/spikeacra/MyObserver.java
There is the NullPointer... it's for myObserver and myObserver2 from the onCreate() in MainActivity.java

**Comment by william-ferguson-au** [comment]
Line 24 of MyObserver is never called in any of the code you provide.
Clicking on button 2 or button 3 just subscribes the observer, it doesn't causes any event to fire that would cause your observer to fire, so line 24 is never run.

Explain your problem from the top.
When you click on button 2, **exactly** what behaviour do you see?

**Comment by HowardSchmaeu** [comment]
OKAY... may you have a different Source or something :-) in MyObserver the Line 24 is this:
 System.out.println("-> " + temp.charAt(9));
so if I Debug that this Line IS called... (i really never Debug that before... my fault) 
BUT if i Step farther i see the Reason because ACRA is never called:
in the OperatorMap Class from rxjava is a try/catch in the call() - Function... and THAT catch the NullPointer ... and then it goes to the onError() of the Subscriber...

Okay i think THIS is not a Solution but the Reason... not ACRA Fault just another behavior 

The only Question that stays is: why at your Side Line 24 never called :-D

**Comment by william-ferguson-au** [comment]
So rxjava is handling the Exception.
That is why ACRA is never invoked.
