### ISSUE TITLE
Unable to compile against API 23 with ACRA 4.6.2

### ISSUE THREAD

**Issue by arcao** [ACRA/acra#301]
The latest version of ACRA 4.6.2 can't be processed by proguard and probably it will cause crash on devices with Android 6 without running proguard. The problem is already described in issue #102, but not fixed yet.

```
:proguardRelease
Warning: org.acra.ErrorReporter: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification
Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Exception while processing task
java.io.IOException: Please correct the above warnings first.
        at proguard.Initializer.execute(Initializer.java:473)
        at proguard.ProGuard.initialize(ProGuard.java:233)
        at proguard.ProGuard.execute(ProGuard.java:98)
        at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
        at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
        at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
        at com.android.builder.tasks.Job.runTask(Job.java:48)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
        at java.lang.Thread.run(Thread.java:745)
:dexRelease
:validateReleaseSigning
:packageRelease FAILED
```

**Comment by william-ferguson-au** [comment]
OK, so do you have a pull request?

**Comment by bottiger** [comment]
I have the same problem - sort of. My application fails to build on f-droid because of this problem.

However, I am unable to reproduce it locally on my computer.

**Comment by william-ferguson-au** [comment]
@arcao actually can you qualify your statement.
ACRA-4.6.2 definitely **can** be processed by proguard.

I suspect you mean to say that it  may not be able to be processed by Proguard against a particular version of the Android SDK. But I have yet to see any evidence.

**Comment by d4rken** [comment]
Probably related to Apache HTTP being removed in API23:
https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by william-ferguson-au** [comment]
@d4rken I suspect you may be right.
So the work around is to add 'org.apache.http.legacy' as a dependency if compiling and Proguarding against API23.

**Comment by d4rken** [comment]
Yes it compiles that way, not sure if anything broke.
The longterm solution would be a PR that replaces the code.
I'll probably do that if no one else did this until then when I'm done with everything else.

**Comment by william-ferguson-au** [comment]
@d4rken a PR would be most welcome.
Preferably one that obviates the need for the Apache Http Client.

**Comment by clemp6r** [comment]
can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

The original error is not related to Apache Http Client but to the removal of `Notification.setLatestEventInfo()`.

See: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-notifications

**Comment by arcao** [comment]
Note: It's now fixed in v4.7 by this commit: d1ada5289411f9a45e24329d460f0f8451e5b3b3

**Comment by neilyoung** [comment]
Is there a binary deployment of 4.7 somewhere?

**Comment by william-ferguson-au** [comment]
4.7.0.RC1 is available on MavenCentral but it's not ready for production.
It has issues with authentication and with OkHttp potentially trying to
start a Thread on VM shutdown.
