### ISSUE TITLE
Response code 201 should be considered success as well as 200

### ISSUE THREAD

**Issue by andrewthecoder** [ACRA/acra#306]
https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/util/HttpRequest.java#L135

`if (responseCode == HttpURLConnection.HTTP_OK)`

should be

`if (responseCode == HttpURLConnection.HTTP_OK || responseCode == HttpURLConnection.HTTP_CREATED)`

Otherwise we get log entries such as:

```
09-26 17:59:46.213 13015-13042/com.podfather.podfather D/ACRA: Request response : 201 : Created
09-26 17:59:46.213 13015-13042/com.podfather.podfather W/ACRA: Could not send ACRA Post - request will be discarded
```

**Comment by william-ferguson-au** [comment]
I'm thinking that we should accept any of the 2XX status codes as success and move on.
@andrewthecoder want to provide a pull request?
