### ISSUE TITLE
acara and proguard problem

### ISSUE THREAD

**Issue by abc2005** [ACRA/acra#309]
I've enabled proguard for my application and I've added acara jar file to my libs and it works fine . The only problem is when I want to export my app and I get this error : 

Warning:org.acra.ErrorReporter: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

This is my proguard-rules.txt in android studio : 
-keep class org.acra.** { *; }
-keepattributes *Annotation*
-dontwarn org.acara.**

How can I solve this problem ?

**Comment by william-ferguson-au** [comment]
Either don't build for Android M (6.0) or wait until ACRA-4.7.0 is released when we ave work around for all the Android M changes.
