### ISSUE TITLE
ACRA 4.6.1 custom ReportSender send method called twice

### ISSUE THREAD

**Issue by jakubmak** [ACRA/acra#312]
Hey,
thanks for the library it's great, and super easy to configure, but i'm struggling with one issue. I wrote a custom report sender calling a webmethods service (backend of my app). For some reason send method of my ReportSender is called twice with the same CrashReportData object (or at least the same toString() representation) . I added code which crashes app to method called by one of the buttons, and the button method is called only once. The debugger wont stop on a breakpoint inside send method so i don't have a clue what to look at next. Here's code for ACRA initialization :

    @ReportsCrashes(
    mode = ReportingInteractionMode.DIALOG,
    resToastText = R.string.crash_toast_text, // optional, displayed as soon as the crash occurs, before collecting data which can take a few seconds
    resDialogText = R.string.crash_dialog_text,
    resDialogIcon = android.R.drawable.ic_dialog_info, //optional. default is a warning sign
    resDialogTitle = R.string.crash_dialog_title, // optional. default is your application name
    resDialogCommentPrompt = R.string.crash_dialog_comment_prompt, // optional. When defined, adds a user text field input with this text resource as a label
    resDialogOkToast = R.string.crash_dialog_ok_toast,  // optional. displays a Toast message when the user accepts to send a report.
    customReportContent = { ReportField.APP_VERSION_CODE, ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA,         ReportField.STACK_TRACE, ReportField.LOGCAT, ReportField.USER_COMMENT } )
    public class MHABApplication extends Application
    {
    @Override
    public void onCreate() {

    // The following line triggers the initialization of ACRA
    ACRA.init(this);
    CrashESBReportSender esbSender = new CrashESBReportSender();
    ACRA.getErrorReporter().setReportSender(esbSender);

    super.onCreate();
    }

**Comment by william-ferguson-au** [comment]
CrashESBReportSender is only added once. And will only be called once for each crash.
It may be called subsequent times for a crash if it was not able to send the crash report and the failure to send was deemed likely to be intermittent.

Show your device log when the crash is reported twice.

**Comment by william-ferguson-au** [comment]
As noted on StackOverflow this is likely to do with a socket timeout on the client.

Try increasing the socket timeout
https://github.com/ACRA/acra/wiki/AdvancedUsage#adjusting-the-socket-timeout
