### ISSUE TITLE
ACRA 4.3.0 caused removal of application from Google Play

### ISSUE THREAD

**Issue by gpiancastelli** [ACRA/acra#314]
An application I have been working on has recently been removed from Google Play. In the email notification announcing the removal, it was stated that the reason was a violation of the Personal and Confidential Information provision of the Content Policy; specifically, it was stated that the application was collecting information on other apps installed on the user's device.

Google allowed an appeal for the resinstatement of the application. Asked for more information about the cause of the violation, they specifically pointed out that data uploads were happening to a Google Docs address. That address was used by the application as the remote endpoint for ACRA crash reporting.

Upon further investigation on one of the phones I use as development devices, I indeed noticed that some information collected by ACRA was highly likely to have triggered the removal. In particular, in the [System Settings](https://github.com/ACRA/acra/wiki/ReportContent#settings_system) section of that particular phone, I found the following data:

    LOCK_SCREEN_SHORTCUT_APP_LIST=com.android.contacts/com.android.contacts.activities.DialtactsActivity;com.sec.chaton/com.sec.chaton.HomeActivity;com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.SearchActivity;com.android.browser/com.android.browser.BrowserActivity;com.sec.android.app.camera/com.sec.android.app.camera.Camera;
    LOCK_SCREEN_SHORTCUT_NUMBER_OF_APPS=5

There were other ilsts like that on such keys as `NOTIFICATION_PANEL_ACTIVE_APP_LIST`, `READING_MODE_APP_LIST`, and so on and so forth. The presence of such lists depends on phone model, I believe, since the System Settings documentation that I linked above, taken as an example from a Nexus One device, does not feature it. Nonetheless, collecting such data is evidently a very risky thing to do: not only the application was removed, but users that opted in to the security overwatching service that Play sometimes asks to activate when installing new applications received a message that the application was potentially compromising their privacy and an expliciting suggestion to immediately uninstall it.

From what I was able to understand, as an application developer, if I still intend to collect those data, I must upfront inform the user that the application might, at some point, do that, and probably offer the user some kind of opt-out. Collecting those data without an explicit/informed user consent will nuke the application out of Play - if the application is ever caught doing it, of course, since this kind of after-publication reviews seems to be performed in a totally random fashion.

As a developer of ACRA, I believe your option could be to change the default for System Settings inclusion in crash reports, from yes to no.

Note that I explicitly stated the ACRA version I use because I don't know if something changed regarding to collected information on crashes in more recent versions. If you feel your users may be at risk, please address this issue as soon as possible.

FWIW, I ended up removing ACRA altogether from the application; I was using an old version anyway, and I was already planning to survey some alternative options regarding crash reporting libraries.

**Comment by william-ferguson-au** [comment]
Thanks for the feedback. I'll take it into consideration for the next version of ACRA.

**Comment by HimanshuNarang** [comment]
Using Acra 4.7.0, but again got the same warning from google play
