### ISSUE TITLE
Empty request problem

### ISSUE THREAD

**Issue by naumenkogs** [ACRA/acra#319]
I have an empty request on my server whatever I use. My last config is: 

@ReportsCrashes(
        formUri = "http://someaddress:8000/acra/_design/acra-storage/_update/report/",
        httpMethod = org.acra.sender.HttpSender.Method.POST,
        reportType = HttpSender.Type.JSON)
public class WalletApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ACRA.init(this);
    }
}

I tried JSON as well as FORM, POST/PUT and a different combinations of them. I also tried to include login/password pair.

**Comment by naumenkogs** [comment]
Here is my log: 

10-30 19:11:15.092 7277-7277/? D/ACRA: ACRA is enabled for distributedlab.wallet, initializing...
10-30 19:11:15.095 7277-7277/? D/ACRA: Using default Report Fields
10-30 19:11:15.105 7277-7277/? D/ACRA: Looking for error files in /data/user/0/distributedlab.wallet/files
10-30 19:11:15.105 7277-7277/? V/ACRA: About to start ReportSenderWorker from #checkReportOnApplicationStart
10-30 19:11:15.106 7277-7277/? E/naumenkogs:: acra.enable
10-30 19:11:15.106 7277-7298/? D/ACRA: #checkAndSendReports - start
10-30 19:11:15.107 7277-7298/? D/ACRA: Looking for error files in /data/user/0/distributedlab.wallet/files
10-30 19:11:15.107 7277-7298/? I/ACRA: Sending file 1446222736819-approved.stacktrace
10-30 19:11:15.127 7277-7298/? D/ACRA: Sending report using org.acra.sender.HttpSender
10-30 19:11:15.128 7277-7298/? D/ACRA: Connect to http://192.168.88.51:8000/acra/_design/acra-storage/_update/report/
10-30 19:11:15.190 7277-7302/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
10-30 19:11:15.252 7277-7302/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
10-30 19:11:15.255 7277-7302/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-30 19:11:17.316 7277-7298/? D/ACRA: Sending request to http://192.168.88.51:8000/acra/_design/acra-storage/_update/report/
10-30 19:11:18.496 7277-7323/? I/LinuxSecureRandom: Secure randomness will be read from /dev/urandom only.
10-30 19:11:18.845 7277-7298/? D/ACRA: Request response : 500 : INTERNAL SERVER ERROR
10-30 19:11:18.846 7277-7298/? E/ACRA: Failed to send crash report for 1446222736819-approved.stacktrace
10-30 19:11:18.846 7277-7298/? E/ACRA: org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.sender.HttpSender.send(HttpSender.java:248)
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.run(SendWorker.java:76)
10-30 19:11:18.846 7277-7298/? E/ACRA:  Caused by: java.io.IOException: Host returned error code 500
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.util.HttpRequest.send(HttpRequest.java:148)
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.sender.HttpSender.send(HttpSender.java:245)
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.sendCrashReport(SendWorker.java:181) 
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140) 
10-30 19:11:18.846 7277-7298/? E/ACRA:     at org.acra.SendWorker.run(SendWorker.java:76) 
10-30 19:11:18.846 7277-7298/? I/ACRA: Sending file 1446222747138-approved.stacktrace
10-30 19:11:18.858 7277-7298/? D/ACRA: Sending report using org.acra.sender.HttpSender

**Comment by william-ferguson-au** [comment]
Your server is reporting HTTP 500 to ACRA.
That is, there is a fault on your server.

**Comment by naumenkogs** [comment]
Nope. I use https://github.com/Simpsonpt/django-acra for my server. It reports 500 because of the empty request. I log the request on the first step and the logs says that it is empty.

**Comment by william-ferguson-au** [comment]
Suggest you mod ACRA to log the fields as they as being written then.
Have never seen this before.

**Comment by naumenkogs** [comment]
e.putCustomData("myKey", "myValue");
            e.handleException(null);

Even this gives an empty request.

**Comment by william-ferguson-au** [comment]
Suggest you try increasing the SocketTimeout in the ACRA config.
If the client doesn't get a response from the server quickly enough then it will close the stream leading to empty fields.
