### ISSUE TITLE
How to use 2 applications

### ISSUE THREAD

**Issue by golontico** [ACRA/acra#321]
I need to know how to use ACRA with volley both need extends application.....

**Comment by william-ferguson-au** [comment]
There is no conflict. As long as you create your own class that extends Application, then you are good.

**Comment by golontico** [comment]
But in both cases needs this in the manifest
android:name=".AcraClass"
and volley android:name=".Myvolley"
both  need be declared in the application manifest? o just extends application?

**Comment by william-ferguson-au** [comment]
Create a single class that extends Application. Have your ACRA config and code and your Volley config and code in it.
In your AndroidManifest declare `android:name=".MyApplicationClass"`

**Comment by golontico** [comment]
Both in the same class ACRA and volley?
Both instances inside of onCreate like this?

@Override
public void onCreate() {
    super.onCreate();
Volley intance= this;
ACRA.init(this);
}

**Comment by william-ferguson-au** [comment]
Yes

**Comment by golontico** [comment]
Sweet thanks!!

**Comment by william-ferguson-au** [comment]
NP
