### ISSUE TITLE
Using separete process service for sending reports.

### ISSUE THREAD

**Issue by romansl** [ACRA/acra#327]
Related to #313.

Seems I found the solution for this problem. You should just put the `SendWorker` into separete process.

Here is example of my HockeyApp Sender: https://gist.github.com/romansl/5c5c8e756ad20001ba8f

What do you think?

**Comment by william-ferguson-au** [comment]
That's a pretty neat idea.

I'm inclined to think that we should use that as the default sender.
It would mean that the crash could always get reported immediately.

Want to put together a PR?

**Comment by romansl** [comment]
Here: https://github.com/ACRA/acra/pull/329

**Comment by william-ferguson-au** [comment]
Thanks for your help on this @romansl
