### ISSUE TITLE
Bug report over Wi-Fi only

### ISSUE THREAD

**Issue by DenisZhadan** [ACRA/acra#328]
In my application user can set setting "Data transfer only via Wi-Fi".
How about setting "send bug reports only via Wi-Fi" for ACRA?

Unfortunately I didn't find such setting in ACRA.
Do You plan to make it in the future?

**Comment by william-ferguson-au** [comment]
No plans at this time.

The general flow is that ACRA only sends data when your app crashes. So generally speaking ACRA won't be sending much if any data.
