### ISSUE TITLE
ACRA 4.6.2 crashes on Android 4.0.4 when targetSDKVersion 23 is set and project is built using SDK 23

### ISSUE THREAD

**Issue by sarkanyi** [ACRA/acra#333]
I'm not sure if anyone is aware of this issue, so I've though about reporting it.
As the title says, stacktrace looks like in the attached [log.txt](https://github.com/ACRA/acra/files/50659/log.txt)

**Comment by funtax** [comment]
Please have a look on ACRA 4.7 (currently RC3) - this one is compatible with SDK 23.

**Comment by sarkanyi** [comment]
I begin to suspect it's because of multidex. Still, how can i get from maven the RC3?

**Comment by william-ferguson-au** [comment]
4.7.0-RC.3 is available from Maven central.
And I have just released 4.7.0 too.
