### ISSUE TITLE
collectLogFile and getFilesDir()

### ISSUE THREAD

**Issue by gregd** [ACRA/acra#334]
Below is code fragment used to read an application log file
```
if (fileName.contains("/")) {
    return new BufferedReader(new InputStreamReader(new FileInputStream(fileName)), 1024);
} else {
    return new BufferedReader(new InputStreamReader(context.openFileInput(fileName)), 1024);
}
```
The problem is when a log file is in the main package sub directory. 
```
@ReportsCrashes(
        applicationLogFile = "files/logs/app.log",
        applicationLogFileLines = 200,
```
ACRA won't find a such file. Because `new FileInputStream()` uses root directory as starting point on Android. So one have to hard code an absolute path, for example `/data/data/com.example.app/files/logs/app.log`. For many reasons this is not a good practice. A fix is very simple
```
if (fileName.startsWith("/")) {
```
I really can't imagine any edge case when `fileName.contains("/")` is more correct. `new FileInputStream()` should be used only when a full path is passed to the ACRA config. And a full path should always start with `/`.

**Comment by william-ferguson-au** [comment]
Yeah, that looks like a straight out error to me.
Want to submit a PR?

**Comment by gregd** [comment]
Done
https://github.com/ACRA/acra/pull/335

**Comment by gregd** [comment]
https://github.com/ACRA/acra/pull/336
It turned out that the fix is a little bit more complicated because openFileInput doesn't work with path separators. The code from the pull request assumes that when a relative log file path is passed to ACRA, then it must be in the `files` directory or its sub-directory, for example `applicationLogFile = "logs/app.log"` I tested this with logback-android and the fix works fine.

**Comment by william-ferguson-au** [comment]
#336 Merged - thanks.
