### ISSUE TITLE
Getting Error : java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by Macchha** [ACRA/acra#337]
Got issue on specific android device
Acra version used : 4.6.2
Android version : 4.2.1
Device :Micromax A210 
Content Type :	application/json

Here is the stack trace
`java.lang.AbstractMethodError: abstract method not implemented
at org.acra.e.f.retryRequest(SourceFile)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:443)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.acra.sender.HttpSender.send(SourceFile:4158)
at org.acra.ad.a(SourceFile:178)
at org.acra.ad.a(SourceFile:140)
at org.acra.ad.run(SourceFile:76)`

Can i know where is the problem?

**Comment by william-ferguson-au** [comment]
Try running it without obfuscation. That way we will now what class/method it is attempting to invoke.

**Comment by Macchha** [comment]
Thanks for the reply.Yes i am obfuscating my apk and it's necessary. 
but i am not obfuscating acra in my project.
This happened for 1 in 1000 case.

Here is my proguard which is configured for acra
`
-keep class org.acra.ACRA {
    *;
}`
`-keep class org.acra.ReportingInteractionMode {
    *;
}`
`-keepnames class org.acra.sender.HttpSender$** {
    *;
}`
`-keepnames class org.acra.ReportField {
    *;
}`
`-keep public class org.acra.ErrorReporter {
    public void addCustomData(java.lang.String,java.lang.String);
    public void putCustomData(java.lang.String,java.lang.String);
    public void removeCustomData(java.lang.String);
}`
`-keep public class org.acra.ErrorReporter {
    public void handleSilentException(java.lang.Throwable);
}`
Can i have any other alternative option?
When i de compile my apk i can get the exact acra source.
Should i need to add anything further in above lines?

**Comment by william-ferguson-au** [comment]
You are obfuscating ACRA. You are just exempting some classes from that
obfuscation.

In your stacktrace the following 4 lines are obfuscated

org.acra.e.f.retryRequest(SourceFile)
at org.acra.ad.a(SourceFile:178)
at org.acra.ad.a(SourceFile:140)
at org.acra.ad.run(SourceFile:76)
Try including
-keep class org.acra.** {}

Are you able to replicate the error on demand?

**Comment by Macchha** [comment]
@william-ferguson-au No i can't able to reproduce since the consumer is facing in particular handset. right now It's happening only on one device. I will add those lines and let me monitor for some day. Thanks.

**Comment by william-ferguson-au** [comment]
If it is readily reproducible on a particular consumer's device, you could send them a new version right now with the ACRA classes unobfuscated.

**Comment by mrmaffen** [comment]
I'm getting the same error:
```
24	01-27 15:47:36.143 E/ACRA (15426): ACRA caught a AbstractMethodError for org.tomahawk.tomahawk_android
25	01-27 15:47:36.143 E/ACRA (15426): java.lang.AbstractMethodError: abstract method \"boolean org.apache.http.client.HttpRequestRetryHandler.retryRequest(java.io.IOException, int, org.apache.http.protocol.HttpContext)\"
26	01-27 15:47:36.143 E/ACRA (15426): at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:439)
27	01-27 15:47:36.143 E/ACRA (15426): at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
28	01-27 15:47:36.143 E/ACRA (15426): at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
29	01-27 15:47:36.143 E/ACRA (15426): at org.acra.sender.HttpSender.send(HttpSender.java:247)
30	01-27 15:47:36.143 E/ACRA (15426): at org.tomahawk.tomahawk_android.utils.TomahawkHttpSender.send(TomahawkHttpSender.java:49)
31	01-27 15:47:36.143 E/ACRA (15426): at org.acra.SendWorker.sendCrashReport(SendWorker.java:178)
32	01-27 15:47:36.143 E/ACRA (15426): at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
33	01-27 15:47:36.143 E/ACRA (15426): at org.acra.SendWorker.run(SendWorker.java:76)
34	01-27 15:47:36.143 D/ACRA (15426): Building report
35	01-27 15:47:36.180 D/ACRA (15426): Using default Report Fields
```

link to my source code: https://github.com/tomahawk-player/tomahawk-android
not sure if my proguard is properly set up: https://github.com/tomahawk-player/tomahawk-android/blob/ccf924f1b8af0f1283f0727d578e0807178b1766/proguard-android.txt#L167

**Comment by william-ferguson-au** [comment]
@mrmaffen I'm confused. Your gradle config lists ACRA-4.7.0 as a dependency, but your stacktrace is not from ACRA-4.7.0

**Comment by mrmaffen** [comment]
@william-ferguson-au I have only recently upgraded to ACRA-4.7.0. The crash report was sent with an older version which still uses 4.6.2.

**Comment by william-ferguson-au** [comment]
If you were running on Android 6+ then it is entirely possible to get that crash with ACRA-4.6 and earlier as Android 6 no longer ships with those classes.

**Comment by mrmaffen** [comment]
@william-ferguson-au The crash happens on several different devices from Android 5.0 to Android 6.0.1. And also important to note is that it doesn't at all crash every time the user tries to send a crash report. At least from as far as I can tell.

**Comment by william-ferguson-au** [comment]
I'm not sure what is going on.

The Http request is failing for some reason, perhaps due to timeout, and the version of the Apache HttpClient being used on those devices doesn't seem to implement a HttpRequestRetryHandler but still call it.

This is not something that I intend to solve, or think I could anyway. ACRA no longer uses the HttpClient classes

**Comment by mrmaffen** [comment]
So with 4.7.0 this crash should no longer occur?

**Comment by william-ferguson-au** [comment]
That is correct. Though there are some issues with 4.7.0 due to the way OkHttp handles threads during shutdown. 

The trunk deals with the OkHttp threading issues, but hasn't been released yet.
I have some code cleanup issues that I am working on this weekend before rolling out 4.8, but if you are in a rush then you could build the trunk yourself.

**Comment by mrmaffen** [comment]
Ok cool. I'll come back to this issue when there's something useful to add to the conversation.
Thanks a lot for taking the time to answer my questions. Acra was one of those projects that I already loved for being free, open-source and super useful. Now I see that there's also some very good support here on github :)
Keep up the great work!
