### ISSUE TITLE
key acra.enable

### ISSUE THREAD

**Issue by DenisZhadan** [ACRA/acra#342]
example:
1. key "acra.enable" = true, network - offline.

2. application make 1 error.

3. key "acra.enable" = false, network - offline.

4. application close.

5. application open.

from logs:
E/ACRA: Failed to send crash report for 1451474859132-IS_SILENT.stacktrace
I/ACRA: Sending file 1451476299777-IS_SILENT.stacktrace
D/ACRA: Sending report using org.acra.sender.HttpSender

Is it normal, for sending logs, because user set setting: don't send ACRA LOG?

**Comment by william-ferguson-au** [comment]
@DenisZhadan I'm not sure what you are asking.

**Comment by DenisZhadan** [comment]
When the application starts ACRA automatically sending all errors (stored in the file).
ACRA does not check the setting(acra.enable) before sending, it is possible that before the user has denied use ACRA.

**Comment by william-ferguson-au** [comment]
Resolved with #347
