### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by yongjiliu** [ACRA/acra#348]
Amazing project and I'm so interested in doc/model/applicationLifeCycles.uml ,could you tell me what tools you use?Thanks

**Comment by william-ferguson-au** [comment]
That file is very old and is probably out of date. To be honest, I was unaware it existed.
I suspect it was created using Eclipse.

**Comment by KevinGaudin** [comment]
Yup it's really old. Written in PlantUML syntax.

You can render it with the PlantUML proxy:
http://www.plantuml.com/plantuml/proxy?idx=0&src=https://github.com/ACRA/acra/raw/master/doc/model/applicationLifeCycles.uml

![http://www.plantuml.com/plantuml/proxy?idx=0&src=https://github.com/ACRA/acra/raw/master/doc/model/applicationLifeCycles.uml](http://www.plantuml.com/plantuml/proxy?idx=0&src=https://github.com/ACRA/acra/raw/master/doc/model/applicationLifeCycles.uml)
