### ISSUE TITLE
Update Documentation for 4.8.0 Breaking API Changes

### ISSUE THREAD

**Issue by commonsguy** [ACRA/acra#352]
https://github.com/ACRA/acra/wiki/AdvancedUsage#implementing-your-own-sender

These instructions still show `ACRA.getErrorReporter().setReportSender(yourSender);`, and `setReportSender()` does not seem to exist anymore. By eyeball, it appears as though it is now `ACRA.getConfig().setReportSenderFactoryClasses(new ReportSender[] { yourSender.class})`, though I'm not 100% certain of that, and I'm typing this into GitHub and so don't get any compile errors if I have that syntax wrong...

The documentation, in that same section, lists a bunch of related methods (e.g., `addReportSender()`, `removeReportSender()`) that no longer seem to exist due to the new class-based, `SenderService`-managed reporting mechanism.

Thanks!

**Comment by william-ferguson-au** [comment]
Thanks for the pick up Mark.

I have hopefully clarified the requirements at https://github.com/ACRA/acra/wiki/Report-Destinations#implementing-your-own-sender (NB I split that section out of the already too long AdvancedUsage document).

I have also updated the changelog to be more explicit about the breaking changes.
https://github.com/ACRA/acra/wiki/ChangeLog#acra-480-30-jan-2016

I'm sure I've missed others too.
If you spot any, let me know.

**Comment by commonsguy** [comment]
Looks good. I had missed the annotation attribute option, which is certainly cleaner. Adjusting my book chapter now... :-)

Thanks!

**Comment by william-ferguson-au** [comment]
Mark, another change to the ACRA API that would be good to get out there is the ConfigurationBuilder introduces in ACRA-4.8.1. To be used by those that need/want to configure ACRA programmatically.

See https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---programmatically

I introduced the builder because I intend to make ACRAConfiguration immutable in the near future.

**Comment by commonsguy** [comment]
Actually, what I cover in my book doesn't get into `ACRAConfiguration`, so I'm safe there, but thanks!

**Comment by william-ferguson-au** [comment]
All good then :-)

**Comment by AsilkhanLisak** [comment]
Hi.
I am trying to setup my own sender, but ACRA.getErrorReporter().setReportSender(yourSender) is not available - what I am doing wrong??

**Comment by william-ferguson-au** [comment]
THat is the instruction for pre 4.8 versions of ACRA.
WHat version of ACRA are you using?

The way of performing this in ACRA 4.8+ is 
```
final ACRAConfiguration config = new ConfigurationBuilder(this)
            .setReportSenderFactoryClasses(myReportSenderFactoryClasses)
            .build();
```
as described in https://github.com/ACRA/acra/wiki/Report-Destinations#implementing-your-own-sender

**Comment by AsilkhanLisak** [comment]
now I am trying to use 4.9.0 version. But when I tryied for 4.8.0 - it was not be available too. 
Ok i will try you recomendation(but i tryied reportSenderFactoryClasses = {your.funky.ReportSenderFactory.class, other.funky.ReportSenderFactory.class} - because "This is the recommended approach.").
