### ISSUE TITLE
Get rid of @ReportsCrashes annotation

### ISSUE THREAD

**Issue by pfn** [ACRA/acra#355]
It's a neat little toy, but it doesn't buy anything. Nothing about it makes reporting configurable and instead incurs a runtime reflection cost. Instead, move all configuration options to code, an init/set blahblah would work better, IMO.

**Comment by william-ferguson-au** [comment]
Not happening. Buys heaps. Reflection time cost is trivial.

If you really want to configure ACRA programmatically then you can. No one is stopping you.
https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---programmatically

**Comment by pfn** [comment]
I get this crash when attempting to programmatically configure.
```
 E  (22097) AndroidRuntime: Process: com.hanhuy.android.irc.lite, PID: 22097
 E  (22097) AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'org.acra.config.ACRAConfiguration org.acra.config.ACRAConfiguration.setFormUri(java.lang.String)' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.hanhuy.android.irc.Application' appears in /data/app/com.hanhuy.android.irc.lite-1/base.apk)
 E  (22097) AndroidRuntime: 	at com.hanhuy.android.irc.Application.onCreate(Application.scala:19)
 E  (22097) AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
 E  (22097) AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
 E  (22097) AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
 E  (22097) AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
 E  (22097) AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
 E  (22097) AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
 E  (22097) AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 E  (22097) AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
 E  (22097) AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 E  (22097) AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 
```

**Comment by william-ferguson-au** [comment]
This means that the ACRA version you compiled against is not the one you are executing against.

**Comment by pfn** [comment]
Yes, I know that's what the error means, however that isn't possible in my build (completely clean builds, no reference to any other version of acra)--I believe the classes.jar in the acra aar is somehow corrupted.

**Comment by pfn** [comment]
Ugh, looks like it might be this issue rearing its head https://issues.scala-lang.org/browse/SI-5397

**Comment by william-ferguson-au** [comment]
classes.jar is not corrupted.

ACRA has no dependency on Scala, so I don't understand the reference to the issue you linked.

It is likely that you have a dependency on another library that uses an older version of ACRA and that older version is being included in your APK. You don't mention your build setup or build framework or your dependencies.

in any case this has nothing do with the @ReportCrashes annotation.

**Comment by pfn** [comment]
the problem is a bug in scalac, it's generating an invokeinterface instruction when it should generate invokevirtual. it is not an acra problem.
