### ISSUE TITLE
CrashReportDialog Theme on 4.8.1

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#362]
On Android 5.1 it still shows old style dialog, see attached. Is there any way to customise it? 

![screenshot_2016-02-05-10-21-12](https://cloud.githubusercontent.com/assets/14060247/12843657/aef81160-cbf2-11e5-9358-2fe69734b3a1.jpg)

**Comment by william-ferguson-au** [comment]
The default ACRA crash report dialog uses `android.app.AlertDialog.Builder` to create the dialog using the default Theme. See line#55 of CrashReportDialog.

If that is not sufficient then you can create and specify your own dialog using the `ReportsCrashes#reportDialogClass` attribute.
