### ISSUE TITLE
Init ConfigurationBuilder using ReportsCrashes annotation

### ISSUE THREAD

**Issue by hexonxons** [ACRA/acra#364]
Is there any way to init acra without using annotations on `Application` class but on my custom class?
For example 

	@ReportsCrashes(
			httpMethod = HttpSender.Method.PUT,
			reportType = HttpSender.Type.JSON,
			formUri = "http://example.com",
			formUriBasicAuthLogin = "reporter",
			formUriBasicAuthPassword = "reporter",
			mode = ReportingInteractionMode.TOAST,
			resToastText = R.string.crash_toast_text,
			customReportContent = {
					ReportField.REPORT_ID,
					ReportField.APP_VERSION_CODE,
					ReportField.APP_VERSION_NAME,
					ReportField.PACKAGE_NAME,
					ReportField.PHONE_MODEL,
					ReportField.ANDROID_VERSION,
					ReportField.BUILD,
					ReportField.BRAND,
					ReportField.PRODUCT,
					ReportField.TOTAL_MEM_SIZE,
					ReportField.AVAILABLE_MEM_SIZE,
					ReportField.CUSTOM_DATA,
					ReportField.STACK_TRACE,
					ReportField.CRASH_CONFIGURATION,
					ReportField.DISPLAY,
					ReportField.USER_APP_START_DATE,
					ReportField.USER_CRASH_DATE,
					ReportField.LOGCAT,
					ReportField.EVENTSLOG,
					ReportField.IS_SILENT,
					ReportField.DEVICE_ID,
					ReportField.INSTALLATION_ID,
					ReportField.DEVICE_FEATURES,
					ReportField.ENVIRONMENT,
					ReportField.THREAD_DETAILS
			},
			logcatArguments = {"-t", "500", "-v", "long", "*:D"}
	)
	public final class CrashReporters {
		...
	}

In acra 4.6.2 there was `ACRAConfiguration(ReportsCrashes)` constructor, but I found no way to do same thing in acra 4.8.1 and all other cases relies on application. Another way is to implement `ConfigurationBuilder(Application app)`'s logic, but it is quite strange.

**Comment by william-ferguson-au** [comment]
The `@ReportCrashes` annotation **must** be on an Application class.

If you want to programmatically configure ACRA, it is quite simple. You just populate the ConfigurationBuilder with the values you want and then use it to create the ACRAConfiguration to use. 

See https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---programmatically

**Comment by hexonxons** [comment]
@william-ferguson-au Well, ok, but there is **no** `@ReportCrashes` annotation on `MyApplication` class in that example. And `.build();` method fails with 

	Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at org.acra.config.ACRAConfiguration.copyArray(ACRAConfiguration.java:1232)
	at org.acra.config.ACRAConfiguration.<init>(ACRAConfiguration.java:113)
	at org.acra.config.ConfigurationBuilder.build(ConfigurationBuilder.java:163)

cause [additionalDropBoxTags](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/config/ConfigurationBuilder.java#L110) is `null`.

Is it wrong doc there?

**Comment by william-ferguson-au** [comment]
Damn. That's an oversight.
I'll fix it tonight.

**Comment by william-ferguson-au** [comment]
I have opened #365 to track the error.
