### ISSUE TITLE
Proguard: keep ReportSenderFactory implementations

### ISSUE THREAD

**Issue by romansl** [ACRA/acra#372]
If you use optimized proguard configuration, it obfuscates the `ReportSenderFactory` implementations to somephing like this:

```java
public final class ben {}
```

Please add this line to the proguard configuration:
```
-keep public class * implements org.acra.sender.ReportSenderFactory { public <methods>; }
```

Note `-keepclassmembers` does not work.

**Comment by william-ferguson-au** [comment]
Can you please submit a PR
