### ISSUE TITLE
Appendix: Error creating report dialog

### ISSUE THREAD

**Issue by Koani** [ACRA/acra#383]
Due to the fact the other issue has been closed, here my opinion to your findings:

First of all thank you for pointing out it is only bots causing the problem. But: The fact it does not impact on the "real" user does not mean it doesn't have to be fixed. If every library I use would behave like this I would waste much time dealing with needless exceptions (as in this case), which should not be my business. Since we know automated testing tools exist, one must ensure "correct" behaviour even in such circumstances. So you should at least do some NP comparision and not go ahead if the requirements to run the activity are not met - which one should always do, btw.
Thank you.

Regards
~Koani

**Comment by william-ferguson-au** [comment]
@Koani thanks for your 2 cents

It is possibly a bot. 
It is also possibly someone hacking your app. 
It is also possibly your app behaving badly.

An Android Activity is created and launched by the Android framework itself. 
ACRA has zero capability to stop an Activity from launching.

ACRA could choose to not properly construct the Activity when it has been invoked without the appropriate Intent, but then it would just crash later. Generally speaking your build libraries which are robust as possible. But when someone chooses to **abuse** the library, which is *exactly* what is occurring here, then all warranties are off.
