### ISSUE TITLE
ACRA Does not Catch Device Exception

### ISSUE THREAD

**Issue by chathura1** [ACRA/acra#384]
I am using the latest ACRA library to get crash report from a real Android device. However, when app crashes ACRA Toast does show and I cannot get crash report.

Here is my MainApplication.java:

```
package com.mydomain.myapp;

import android.app.Application;
import android.content.res.Configuration;

import org.acra.ACRA;
import org.acra.ReportField;
import org.acra.ReportingInteractionMode;
import org.acra.annotation.ReportsCrashes;

@ReportsCrashes(formUri = "http://example.com/debug.php", mailTo = "myname@mydomain.com", //formUri ="http://yourserver.com/yourscript",
  customReportContent = { ReportField.APP_VERSION_CODE,    ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA, ReportField.STACK_TRACE, ReportField.LOGCAT },
  mode = ReportingInteractionMode.TOAST,
resToastText = R.string.crash_toast_text) //, logcatArguments = { "-t", "100", "-v", "long", "ActivityManager:I", "MyApp:D", "*:S" }
public class MyMapApp extends Application {

@Override
public void onConfigurationChanged(Configuration newConfig) {
  super.onConfigurationChanged(newConfig);
}

@Override
public void onCreate() {
  ACRA.init(this); //switching this did not work with super.onCreate()
  super.onCreate();

  // The following line triggers the initialization of ACRA



}

@Override
public void onLowMemory() {
  super.onLowMemory();
}

@Override
public void onTerminate() {
  super.onTerminate();
}


}
```

AndroidMainfest.xml

```
<application
android:name=".MyMapApp"

...

<service
android:name="org.acra.sender.SenderService"
android:exported="false"
android:process=":acra" />
```

build.gradle:

```
dependencies {
  compile 'ch.acra:acra:4.6.2'
}
```

strings.xml

```
<resources>
    <string name="crash_toast_text">Ooooops ! I crashed, but a report has been sent to my developer to help fix the issue !</string>
</resources>
```

However,
I insert following code on MainActivity.java
`
throw new RuntimeException("This is a crash");  //Test`

on my simulator and I show toast briefly but no email was send out.  I have email client installed. However on real device nothing happens.

**Comment by william-ferguson-au** [comment]
Latest version of ACRA is 4.8.2 not 4.6.2
ACRA-4.6.2 does NOT have the SenderService.

You have specified `reportUri` as well as `mailTo`.
Because of this ACRA will try to send your report via HTTP to the target at `reportUri`.

When debugging issues, look at your logcat.

**Comment by chathura1** [comment]
Hi, william,
The reason I have to install ACRA on a device because I cannot use connect via adb to that device. Device Driver issue.  I just compiled to 4.8.2 still no TOAST on app crash on actual device.

**Comment by chathura1** [comment]
If I manuall inject following runtimeexception:

`//throw new RuntimeException("This is a crash");  //Test`

ARCA will catch it.  Why is ARCA not capturing all exceptions?

**Comment by william-ferguson-au** [comment]
I'm sorry @chathura1, I'm not understanding.

Is ACRA is working on the emulator?
Is ACRA working on any device?
What device is ACRA not working on?
What do the logs look like on the device that ACRA is not working on?

**Comment by chathura1** [comment]
I am trying to capture the logcat data from
ANDROID_VERSION=5.1.1
PHONE_MODEL=LG-H345

My test app does not crash on emulator but crashes on this device. I am trying to findout the logcat data for crash.  In the actual device, if I manually inject runtimeexception shown above it will crash and ARCA will catch it with email.  However, if I do not inject above runtimeexception in the MainActivity.java, ARCA will not catch it and app crashes.  I do not have logs to device that is why I am trying to use ACRA to capture it.

**Comment by william-ferguson-au** [comment]
So ACRA is working just fine on your app. If an app is trigger within the Java VM, ACRA successfully catches it, generates a Toast and sends the crash via email. Correct?

But you have an instance in your app on one particular phone where your app is crashing and ACRA is not catching it. Correct?

It sounds like your app is crashing in native code. Ie your app is crashing in a C library somewhere and not within the Java VM. In which cause your app will be generating a core dump on your device and there is nothing ACRA or the Android framework can do to help catch or diagnose your issue.

**Comment by william-ferguson-au** [comment]
Suggest you sort out the ADB driver you need to see the log on your device.
You should then be able to see the core dump happening and even pull it off your device.

**Comment by chathura1** [comment]
I installed a third party logcat app on the android device (Logcat Extreme) and pulled in the log file.

This is all I got extra:

03-02 12:22:11.681 18968 18968 F libc : Fatal signal 11 (SIGSEGV), code 2, fault addr 0xa16df000 in tid 18968 (hhopper.android)

03-02 12:22:11.681 18968 18968 I libc : Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0

How do I see a core dump on log file generated.?

[https://github.com/graphhopper/graphhopper/issues/671)](https://github.com/graphhopper/graphhopper/issues/671)

**Comment by william-ferguson-au** [comment]
This is well outside the boundary of ACRA.
This ref might be useful https://shizen008.wordpress.com/2012/01/06/links-to-how-to-read-android-core-dumps-and-crashes/
