### ISSUE TITLE
Why my Thread run on ACRA process ?

### ISSUE THREAD

**Issue by EMIN3M1986** [ACRA/acra#386]
Hi.
I'm using ACRA 4.8 with sender service in separate process.
When I start new thread in My app sometimes the thread runs on ACRA process and sometimes not.
how can I force my thread to run on the main process not ACRA process?

tnx.

**Comment by william-ferguson-au** [comment]
The only time your Thread could possibly run on the `acra` process is if was started from that Process.

How are you diagnosing that it is running on the `acra` process?

**Comment by EMIN3M1986** [comment]
I debug my app in DDMS. 
My Thread contains a While(true)  and a Service keeps main process always alive. Usually after clear recent apps thread goes to ACRA process.

**Comment by william-ferguson-au** [comment]
POst an example of what you are seeing.

**Comment by william-ferguson-au** [comment]
@EMIN3M1986, I'm closing this as I don't believe that a new Thread started within your app **is** actually being started in the ACRA process. If you have evidence of this please reopen this issue and post that evidence.
