### ISSUE TITLE
Any plans to support binary file attachments?

### ISSUE THREAD

**Issue by TheChuckster** [ACRA/acra#398]
It would be very useful for us Android NDK C++ developers who are using something like breakpad to gather crash minidumps so that we can send them over the wire using acra. It seems to be becoming a common use case now with things like GearVR practically demanding NDK usage for high performance.

**Comment by william-ferguson-au** [comment]
When these minidumps are generated do they coincide with an unhandled Exception in the Java VM?
If not, how would you expect ACRA to be notified of a crash and be able to respond?

**Comment by TheChuckster** [comment]
I'm not exactly sure how my particular signal-catching implementation is relevant to adding support for binary attachments, but details follow:

My current solution involves setting up custom signal handlers for SIG* (in particular SIGSEGV) which then call back into Java via JNI to start a new crash handler activity, then call the old signal handler to allow the old process to die.

More details:
http://stackoverflow.com/questions/1083154/how-can-i-catch-sigsegv-segmentation-fault-and-get-a-stack-trace-under-jni-on/1789879#1789879

**Comment by TheChuckster** [comment]
Just throwing out there that another solution could involve just dumping the files in a known location, having the activity restart itself automatically upon crash -- I've been able to do this from inside a different JNI thread -- and then using handle(Silent)Exception inside ACRA after checking for the existence of prior minidumps.

**Comment by william-ferguson-au** [comment]
The signal catching is relevant, because binary attachment is not of much value without some means of catching the signal.

I have no plans on adding this because I have zero need for it. But if you'd like to propose something via a PR, I'll happily review it.

**Comment by TheChuckster** [comment]
I'll let you know if I throw something together.

If I pass a byte array converted to a string to a putCustomData value, could that work in the meantime?

**Comment by william-ferguson-au** [comment]
It might, but you are likely to quickly reach size limits in the request either from the client or the server.

**Comment by TheChuckster** [comment]
Perhaps, but I do not see any limits being imposed on the client -- at least here (and it looks like custom data is just a normal String Map):
https://github.com/ACRA/acra/blob/cd27b026b8eabf4d9d63bc7c972de035d2f7d45d/src/main/java/org/acra/collector/CrashReportDataFactory.java

I own the server; I'll happily adjust my limits for my use case.

**Comment by william-ferguson-au** [comment]
When I was referring to the client I meant particular Android versions. But you are probably right it if you can adjust your server then it;s likely to be ok.

How big are the binaries?

**Comment by william-ferguson-au** [comment]
OK, well I'm closing this for now.
Flick us a pull request if you put something together.
