### ISSUE TITLE
[Discussion] Make BaseCrashReportDialog bulletproof

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#400]
My ideas to #380 & #383 : 

- If `onCreate`, `cancelReports `and `sendCrash `were made final, subclasses wouldn't be able to break things in this class. 
- This would require a new abstract method like `init(Bundle)`, in which subclasses can do initialization.
- There would be no need to throw exceptions in onCreate. Instead it could just finish, make a toast, etc and not call `init` in case of a problem.
- So, even in the case of a illegal call the user can get notified (without him knowing what logcat is) and developers won't receive weird bug reports.
- The only downside I see is that it introduces a breaking change for subclasses.

I can implement this if it is wanted.

**Comment by william-ferguson-au** [comment]
Let me think it over, there's no rush.
I just released 4.8.3 - thanks for all the PRs, I really appreciate it.

**Comment by william-ferguson-au** [comment]
Do it.
