### ISSUE TITLE
ACRA doco not up to date and methods error

### ISSUE THREAD

**Issue by IcepaxKnight** [ACRA/acra#404]
============
ISSUE No 1
============
The instructions for setting up ACRA 4.8+ is confusing in that this link:

[https://github.com/ACRA/acra/wiki/BasicSetup](https://github.com/ACRA/acra/wiki/BasicSetup)

ask to initialise ACRA at the "attachBaseContext(Context base)" method. Whilst this link:

[https://github.com/ACRA/acra/wiki/Report-Destinations](https://github.com/ACRA/acra/wiki/Report-Destinations)

ask to initialise ACRA at the "onCreate()" method. So, which method should one initialise ACRA with?

============
ISSUE No 2
============
This link:

[https://github.com/ACRA/acra/wiki/Report-Destinations](https://github.com/ACRA/acra/wiki/Report-Destinations)

provides some info to create your own ReportSender. However, the example given is either wrong or incomplete. For example, if I have my own ReportSender class declared as:

`public class ErrorReportSender implements ReportSender {
       @Override
        public void send(Context context, CrashReportData report) throws ReportSenderException {
}
}`

I cannot reference this class by either using the ACRA annotation:

`@ReportCrashes{
   ...
   reportSenderFactoryClasses = {ErrorReportSender.class} 
}`

because I'm getting "_Cannot convert from Class<ErrorReportSender> to Class<? extends ReportSenderFactory>_". So, what is it expecting here.

I got a similar error with:

"_Cannot convert from ErrorReportSender to Class[]_"

If I declared it programmatically as follow:

`final ACRAConfiguration config = new ACRAConfigurationFactory().create(this);
final Class[] myReportSenderClasses = new ErrorReportSender();
config.setReportSenderFactoryClasses(myReportSenderClasses);`

Maybe an example in the ACRA docs might help.

**Comment by william-ferguson-au** [comment]
Thanks for the feedback.

Issue#1
Up until very recently we recommended that ACRA be initialised in `Application.onCreate`. But it was found that ContentResolvers are initialised prior to that and may effectively fail BEFORE `Application.onCreate` is ever called. So we change our recommendation to use `Application.onAttachBaseContext`.

I am not surprised that we missed an item of config. I have updated it that you.

Issue#2
The doco was indeed out of date. Moving to the SenderService required us to switch from configuring ReportSenders to configuring ReportSenderfactory classes as the name and input type of the `ConfigurationBuilder.setReportSenderFactoryClasses` method suggest.

I have amended that doco too.

**Comment by IcepaxKnight** [comment]
Issue#1
Okay, thanks for the clarification,

Issue#2
So, does it mean I have to change the report sender class from:

`public class ErrorReportSender implements ReportSender`

to:

`public class ErrorReportSender implements ReportSenderFactory`

I'm confused by your comment and the doco.

**Comment by william-ferguson-au** [comment]
Issue#2
No. You need to have a `ReportSender`, but you also need to have a `ReportSenderFactory` that is capable of creating the `ReportSender`.

I see that the first part of the doco is not clear on that and still referred to configuring the ReportSender.class. I have now updated the doco.

**Comment by IcepaxKnight** [comment]
Ah, thanks for updating the doco, William. Yes, the update does help me understand what you were referring to in your previous reply. Much appreciated.
