### ISSUE TITLE
ACRA 4.7.2+ is affecting AsyncTask's behavior which should not be

### ISSUE THREAD

**Issue by DailyTimer** [ACRA/acra#408]
Up to API level 12, AsyncTask can run in parallel. For API level 13+, AsyncTask runs one by one by default. With ACRA 4.6.2, my app works as expected but with ACRA 4.7.2+ (not sure precise boundary) ACRA (or configuration related to ACRA) is affecting AysncTask's behaviour.

I wrote simple enough app to verify this issue. I will send Android Studio project shortly by email. Please take a look.

How to test this issue with simple app.
1. Build and run app. You can see 2 lines are updating it's number.
2. Change ACRA's version from 4.6.2 to 4.8.5 and build, run. You see only first line
    is updating it's number.
3. Open MainActivity.java and change
      testTask1.execute();
    to
      testTask1.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
   this fixes issue but this workaround should not be necessary.

**Comment by DailyTimer** [comment]
I don't know your email address, and zipped file is larger than 12MB. Where can I send/upload project?

**Comment by william-ferguson-au** [comment]
ACRA-4.8.5 doesn't use AsyncTask - at all.
So I'm not sure why/how you think ACRA is involved in AsyncTask's change of behaviour.
It is more likely that AsyncTask's behaviour might be modified based upon the version of the Android support libraries that are included in your app. ACRA-4.8.5 use support-v4-23.2.0

NB You don't mention on what device/Android version you are testing.

If you still think there is an issue with ACRA then create a github project with your project and post the link.

**Comment by DailyTimer** [comment]
I understand your feelings. Reason why I think ACRA is affecting to AsyncTask's behaviour is:

-Works as expected with ACRA 4.6.2.
-AsyncTask behaves like targetting API level 13+ with ACRA 4.7.2+.
-Only ACRA#init() is called. No other ACRA's function is called.

I tested with Xperia Z4 with OS5.0.2

Please get project from [github](https://github.com/DailyTimer/SimpleApp/tree/master) and just changing ACRA's version will make a difference.

**Comment by william-ferguson-au** [comment]
So, if you comment out `ACRA.init()`, what's the behaviour?

**Comment by DailyTimer** [comment]
Commenting out ACRA.init() did not make difference.

I tested my wild guess. Linking with ACRA 4.7.2+ changes targetSdkVersion which I did not set in manifest. I updated simple app to show targetSdkVersion at run time. And understood why it is changing AsyncTask's behavior.

Original app (huge one) and simple app (to reproduce issue) has no targetSdkVersion and minSdkVersion is 9. With ACRA 4.6.2, targetSdkVersion is 9 at run time as expected.
But with ACRA 4.8.5, targetSdkVersion is 23, which is compileSdkVersion. This is a cause that changed AsyncTask's behavior. When I set targetSdkVersion to 9, targetSdkVersion was not changed to 23.

So we need to declare targetSdkVersion, otherwise ACRA 4.7.2+ will change this.

You may close this issue as I know a solution now.
