### ISSUE TITLE
Separate process causes Application.onCreate() called twice

### ISSUE THREAD

**Issue by m6s** [ACRA/acra#414]
We got burned by this:

> SenderService now invoked to send all report in a separate process.

I don't think that's a good idea for an external framework. In our case, we are initiating database migrations via `SQLiteOpenHelper` from `Application.onCreate()`. After upgrading to ACRA 4.8.1, we were faced with dozens of crashes caused by concurrent database access.

I don't actually know how to easily work around the issue, other than duplicating the process name check that ACRA does internally. Or switching to lazy initialization of our singletons, but I'd rather remove ACRA. If you want to stick with a separate process, providing an `AcraApplication` base class seems advisable to me.

**Comment by william-ferguson-au** [comment]
See #410 

ACRA **has** to do this in order to ensure that the crash can be sent.

You just need to check in `Application.onCreate()` to determine whether this is the `:acra:` process or not. In the next version of ACRA (4.8.6) we expose the same method that ACRA uses to determine this. In the meantime, check the process name.

A base `ACRAApplication` class won't work. There are lots of frameworks that people use that already require a base Application class, hence the annotations.

**Comment by m6s** [comment]
Thanks for replying, should have checked the closed issues. This can be closed as well. I propose prominently stating the fact that a separate process is created in the documentation. It's easy to miss and causes hard to trace issues, if you don't know where you need to look for.

**Comment by william-ferguson-au** [comment]
Good call. Where would you propose it be added?

**Comment by m6s** [comment]
Maybe a major version increment would be appropriate, as one might consider it an incompatible API change. I assume some other apps that extend `Application` for doing work besides ACRA initialization are affected as well. Some probably don't know it yet.

In our case we were upgrading ACRA alongside feature work, and this (rather insidious issue) got lost under the radar. We didn't catch it during development, because we disable ACRA for `DEBUG` builds, and the concurrency nature of it meant it only surfaced with the larger user base after releasing. We're using a second crash reporting tool in parallel. Not even sure if we would have noticed if we used only ACRA as the service would crash in those cases.

Other than that, leaving a note on the main Readme for a few weeks/months, and including it in both *Configuring ACRA - Declaratively* and *Configuring ACRA - programmatically* could be good. (But probably wouldn't have helped in our case)

**Comment by william-ferguson-au** [comment]
Well it was introduced in 4.8.0, perhaps we could have jumped to 5.0

**Comment by m6s** [comment]
Yep. OTOH, I might be making too big a deal out of it. I just happen to have spent the last days to isolate the issue, while watching the crash count rise :-)

**Comment by william-ferguson-au** [comment]
@m6s I have added this new section to the Wiki
https://github.com/ACRA/acra/wiki
