### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#416]
As the project now includes its own AndroidManifest, it is not anymore required for users to declare the SenderService. The corresponding section in the wiki should be removed.

**Comment by william-ferguson-au** [comment]
Well, it depends on whether their apps are configured to automatically merge manifests.
Is this configurable in Gradle? It is in Maven.

Though I think we should definitely **strongly encourage** them to get the ACRA config via manifest and Proguard merging.

if it is the default in Gradle then go for it.
Anyone can change the ACRA Wiki.

**Comment by F43nd1r** [comment]
I'm not sure if you can turn off manifest merging in gradle. It is on by default.

Ok,  I wasn't aware of that, I'll do it.
