### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by koral--** [ACRA/acra#424]
```java
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
 	at org.acra.ACRA.getCurrentProcessName(ACRA.java:279)
 	at org.acra.ACRA.isACRASenderServiceProcess(ACRA.java:270)
 	at org.acra.ACRA.init(ACRA.java:173)
 	at org.acra.ACRA.init(ACRA.java:156)
 	at org.acra.ACRA.init(ACRA.java:139)
```
ACRA version:
`compile 'ch.acra:acra:4.8.5'`
According to the [ActivityManager#getRunningAppProcesses() javadoc](https://developer.android.com/reference/android/app/ActivityManager.html#getRunningAppProcesses()):

> Returns a list of RunningAppProcessInfo records, or null if there are no running processes

**Comment by william-ferguson-au** [comment]
@koral-- In what environment are you getting this NPE? It's seems quite strange because you clearly have a process otherwise you couldn't be executing the code.

**Comment by F43nd1r** [comment]
> The ActivityManager solution contains a sneaky bug, particularly if you check your own process name from your Application object. Sometimes, the list returned from getRunningAppProcesses simply doesn't contain your own process, raising a peculiar existential issue.
> -- http://stackoverflow.com/a/21389402/4388512

Sidenote 1: Why does `getCurrentProcessName` take an `Application` parameter, if it only calls methods of a `Context` on it?

Sidenote 2: I assume this method is only there to check if the current process is the SenderService process. If so, wouldn't it be easier to use the following?
```
Process.myUid() == Process.getUidForName(ACRA_PRIVATE_PROCESS_NAME);
```

**Comment by william-ferguson-au** [comment]
OK crappy implementation of `ActivityManager.getRunningAppProcesses()`.

Sidenote 1: no idea (lack of sleep when coding?)
In any case I like David Burstrom's solution http://stackoverflow.com/a/21389402/493682. we should replace #getCurrentProcessName with that.

**Comment by koral--** [comment]
@william-ferguson-au I see that there is a fix ready, so maybe this info is outdated, but to be complete, that exception occurred on Nexus 5 (the newest stock ROM). As can be seen in [source](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/app/ActivityManager.java#2347) `ActivityManager.getRunningAppProcesses()` uses remote service and `null` is returned in case of `RemoteException`.

I have also on final comment. Process name can be read without using `android.os.Process.myPid()`. This is shorter version: `new FileInputStream("/proc/self/cmdline")`.

**Comment by william-ferguson-au** [comment]
Hi @koral--, thanks for the pointer re `/proc/self/cmdline`, that is cleaner again.
