### ISSUE TITLE
ACRA - empty report

### ISSUE THREAD

**Issue by DenisZhadan** [ACRA/acra#435]
Hi!
I get very interesting empty report.

Array
 (
     [USER_EMAIL] =>
     [USER_COMMENT] =>
     [SETTINGS_GLOBAL] =>
     [APPLICATION_LOG] =>
     [DEVICE_FEATURES] =>
     [PHONE_MODEL] =>
     [SETTINGS_SECURE] =>
     [INSTALLATION_ID] =>
     [SETTINGS_SYSTEM] =>
     [THREAD_DETAILS] =>
     [SHARED_PREFERENCES] =>
     [IS_SILENT] =>
     [ANDROID_VERSION] =>
     [PACKAGE_NAME] =>
     [APP_VERSION_CODE] =>
     [CRASH_CONFIGURATION] =>
     [EVENTSLOG] =>
     [USER_CRASH_DATE] =>
     [DUMPSYS_MEMINFO] =>
     [BUILD] =>
     [BUILD_CONFIG] =>
     [STACK_TRACE] =>
     [PRODUCT] =>
     [DISPLAY] =>
     [USER_IP] =>
     [LOGCAT] =>
     [APP_VERSION_NAME] =>
     [RADIOLOG] =>
     [MEDIA_CODEC_LIST] =>
     [AVAILABLE_MEM_SIZE] =>
     [USER_APP_START_DATE] =>
     [CUSTOM_DATA] =>
     [STACK_TRACE_HASH] =>
     [BRAND] =>
     [INITIAL_CONFIGURATION] =>
     [TOTAL_MEM_SIZE] =>
     [FILE_PATH] =>
     [ENVIRONMENT] =>
     [REPORT_ID] =>
 )

Is it possible? Do You have such reports before?
Any ideas?

**Comment by william-ferguson-au** [comment]
I can recall getting blank reports like that back in early versions of ACRA  circa 3.6 when being sent to a Google forms/sheets backend. It was always down to connection timeout. Ie Google forms/sheet would post the row after timeout instead of discarding the report.

**Comment by DenisZhadan** [comment]
I make ACRA backend for bachelor degree.
Now it is working as alpha version, only for my apps.

from server data:
$_SERVER["HTTP_USER_AGENT"] = Android

I use ACRA library 4.8.2

P.S. Empty report only from one IP address (5 times).
P.P.S. I will try get more info.

**Comment by william-ferguson-au** [comment]
That sounds like the std symptom. The client keeps connecting but it times out.
The are 2 things you can do to solve

1. On your server, validate the the input first and throw away partial requests.
2. Increase the connection timeout in your ACRA config on your client.

**Comment by DenisZhadan** [comment]
sorry, I find out cause (REDIRECT).
It is was first version for apps and with another domain (user do not make update).

P.S. In this moment ACRA set in field [HTTP_USER_AGENT] => Android
How about small update, add ACRA version in this field.
Example: [HTTP_USER_AGENT] => Android ACRA 4.8.4
It is can help see ACRA version from client.

**Comment by william-ferguson-au** [comment]
That's sounds like a good idea.
Want to provide a pull request?

**Comment by DenisZhadan** [comment]
for org/acra/util/HttpRequest.java
need add function:

```java
    /**
     * @return library version or "" if libraryVersion was not available or not defined.
     */
    private String getLibraryVersion(@NonNull Context context) {
        final PackageManager pm = context.getPackageManager();
        if (pm == null) {
            return "";
        }
        try {
            final PackageInfo packageInfo = pm.getPackageInfo(ACRA.class.getPackage().getName(), 0);
            String libraryVersionName = (packageInfo == null) ? "" : packageInfo.versionName;
            return (libraryVersionName == null) ? "" : libraryVersionName;
        } catch (Exception e) {
            // put here code on exception
            return "";
        }
    }
```
change code line:
```java
urlConnection.setRequestProperty("User-Agent", "Android");
```
to:
```java
urlConnection.setRequestProperty("User-Agent", String.format("Android ACRA %1$s", getLibraryVersion(context)));
```
But result from getLibraryVersion is empty.
Must be package "org.acra" or "ch.acra.acra"?

for get package version name I use:
```xml
ACRA.class.getPackage().getName() => package="org.acra"
```
but in ch.acra\acra\4.8.5\AndroidManifest.xml 
```xml
android:versionName="UPDATED-BY-BUILD" package="ch.acra.acra">
```

I use anything wrong?

**Comment by william-ferguson-au** [comment]
You aren't going to be able to use 
`final PackageInfo packageInfo = pm.getPackageInfo(ACRA.class.getPackage().getName(), 0);`
to determine the version of ACRA. That will return the version of your App. It can never return the version of a library that your app uses.

Getting the ACRA version will require a bit more thought. You would need to generate that value at build time and make it available to be consumed at runtime. Eg something like generating a resource with the ACRA version and then reading it at runtime.

How badly do you want the version?

**Comment by DenisZhadan** [comment]
Is the library's manifest not included in the final APK?

**Comment by william-ferguson-au** [comment]
No. An APK only has a single AndroidManifest - it's own.
The manifest's of any AAR libraries are merged into the APK's manifest.

**Comment by F43nd1r** [comment]
> You would need to generate that value at build time and make it available to be consumed at runtime

Android does that for you. The value is in `ch.acra.acra.BuildConfig.VERSION_NAME`.

**Comment by DenisZhadan** [comment]
for  ch.acra.acra.BuildConfig.VERSION_NAME 
error: cannot find symbol variable VERSION_NAME
or is it internal variable?

BTW: ch.acra.acra.BuildConfig.DEBUG - can read (present).

**Comment by william-ferguson-au** [comment]
@F43nd1r maybe you get that with Gradle. I don't have it.

**Comment by F43nd1r** [comment]
That is possible. Here is my BuildConfig: 
```
public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "ch.acra.acra";
  public static final String BUILD_TYPE = "debug";
  public static final String FLAVOR = "";
  public static final int VERSION_CODE = 1;
  public static final String VERSION_NAME = "undefined";
}
```

**Comment by DenisZhadan** [comment]
Is it BuildConfig for ACRA library or for project?
for example:
```java
package ch.acra.acra;

public final class BuildConfig {
  public static final boolean DEBUG = true;
}
```

```java
/**
 * Automatically generated file. DO NOT MODIFY
 */
package eu.sparksoft.discountfinder;

public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "eu.sparksoft.discountfinder";
  public static final String BUILD_TYPE = "debug";
  public static final String FLAVOR = "";
  public static final int VERSION_CODE = 103;
  public static final String VERSION_NAME = "1.0.3 (524)";
}
```

**Comment by F43nd1r** [comment]
It lives in ch.acra.acra

I don't even have an attached app, so it is the libraries BuildConfig.

**Comment by DenisZhadan** [comment]
BuildConfig overrided by app?

**Comment by F43nd1r** [comment]
@DenisZhadan I'm building Acra myself. 

@william-ferguson-au according to [this](https://docs.google.com/document/d/1ggvF7ZV1tTiTqKNlQ-e07z6kbzctytOylk_ySPGDcz0/edit), you could replicate this easily with maven.

**Comment by william-ferguson-au** [comment]
Thanks @F43nd1r I've never bothered with BuildConfig before.. That looks like it might work.
I'll have a play.

**Comment by william-ferguson-au** [comment]
@DenisZhadan I have just pushed a commit that adds a VERSION_NAME attribute to ACRA's BuildConfig class. So you should be able to use that now.

**Comment by DenisZhadan** [comment]
ch.acra.acra.BuildConfig  - not found
can't get access to ACRA BuildConfig.
![sample5](https://cloud.githubusercontent.com/assets/5443568/14677706/5c5c3ce2-071b-11e6-80c8-ab24501f014b.png)

May be I do anything wrong? 
P.S. Using Android Studio 2.0

**Comment by william-ferguson-au** [comment]
Did you checkout and build ACRA master?
Add ACRA-4.8.6-SNPASHOT into your Android project?

**Comment by DenisZhadan** [comment]
https://github.com/ACRA/acra/archive/master.zip
1 hour 40 min ago

**Comment by william-ferguson-au** [comment]
Yes, but did you build it?
The source doesn't contain BuildConfig. It is generated at build time.
If you run 'mvn install' it will be generated in target\classes and will be packaged into the classes.jar in the ACRA AAR

**Comment by DenisZhadan** [comment]
Can I do it with Gradle?

**Comment by F43nd1r** [comment]
@DenisZhadan yes.

**Comment by DenisZhadan** [comment]
sorry, my mistake, fixed.
@F43nd1r thanks.
