### ISSUE TITLE
Android studio can't use ACRA v4.8.5

### ISSUE THREAD

**Issue by MrLoveQD** [ACRA/acra#441]
Hi.
I'm using Android studio 1.5.1.
When i use:
`compile 'ch.acra:acra:4.6.2'`
in build.grade, all normal except i can't generate signed APK.
Error:
`You probably need to update the library versions.`

If i use:
`compile 'ch.acra:acra:4.8.5'`
in Application class, error: Cannot resolve symbol 'ReportsCrashes', 'ACRA',...

How do i do ?
Thanks for all.

**Comment by F43nd1r** [comment]
Have you tried cleaning your project?

**Comment by MrLoveQD** [comment]
I have tried (clean, sync Project, rebuild,...) but it's no change :-(

**Comment by F43nd1r** [comment]
Switch to the `Project` view and verify that ACRA is there (under `External Libraries`)

**Comment by MrLoveQD** [comment]
If i use `compile 'ch.acra:acra:4.6.2'`, ACRA is there.
but i use `compile 'ch.acra:acra:4.8.5'`, ACRA was not there.

Why ? and how do i do ?
Please help me.

**Comment by F43nd1r** [comment]
That means gradle was not able to load veriosn 4.8.5 into the cache. Check your internet connection, Antivirus & Firewall settings.

**Comment by MrLoveQD** [comment]
Can you help me check it ?
My skype: **mrlove.vn**
Thanks you so much.

**Comment by MrLoveQD** [comment]
I have solved the problem.
I clear gradle cache, then sync project, Clean Project.
Thanks for all.
