### ISSUE TITLE
Crash on first start after install cannot be reported

### ISSUE THREAD

**Issue by str4d** [ACRA/acra#443]
If a crash happens on first start after install, this happens:

- App starts
  - ACRA is initialised in the app process
  - ACRA does first-start setup, such as migrating old unsent reports
- App crashes at some point
  - ACRA writes crash report to the unapproved directory
  - ACRA starts `BaseCrashReportDialog` in a new process
- `BaseCrashReportDialog` starts
  - ACRA is initialised in the new process
  - ACRA does first-start setup, such as migrating old unsent reports
- `BaseCrashReportDialog` fails to open the crash report

This bug only occurs if the app crashes during its first start after install; after a single destroy-create cycle, crash reports exist when the error process attempts to open them.

I found this bug while [implementing ACRA support in Briar](https://code.briarproject.org/akwizgran/briar/merge_requests/140).

**Comment by str4d** [comment]
I have found the source of the error:

- [ACRA checks for approved reports to send](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/ACRA.java#L224) even if it is in the error process.
- Within that, it [checks to delete old unsent reports](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/ACRA.java#L226).
- `ApplicationStartupProcessor` determines if this is a new version by [checking the current version against a stored preference](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/util/ApplicationStartupProcessor.java#L36).
- The error process is **for some reason** using a different `SharedPreferences` on first start, and thus does not see the version that was set by the initialisation of the main app.
- The error process therefore deletes the report written by the app process.

**Comment by str4d** [comment]
Hmm, it turns out that this is probably caused by some privacy-preserving behaviour I was unaware of - Briar [clears out all its local files](https://code.briarproject.org/akwizgran/briar/blob/master/briar-android/src/org/briarproject/android/util/AndroidUtils.java#L81), including `SharedPreferences`, [when it doesn't find an account on startup](https://code.briarproject.org/akwizgran/briar/blob/master/briar-android/src/org/briarproject/android/SplashScreenActivity.java#L65).

Disabling deletion of old unsent reports on startup fixes the issue for us (which doesn't matter in our case because we always either convert the plaintext ACRA reports into encrypted reports or delete them immediately).

Assuming that this bug can't be recreated outside of Briar, perhaps the best fix for this issue is to document the behaviour in the wiki for the benefit of future developers?

**Comment by F43nd1r** [comment]
This sounds like a pretty specific problem, but adding a sidenote somewhere shouldn't be a problem. 

I read through your discussion:
 - the debug option is mistakenly final, this will be fixed in a new version 
 - the next version contains breaking changes around BaseCrashReportDialog (just fyi) 
 - I see you had problems because BaseCrashReportDialog doesn't extend from AppCompatActivity. Acra doesn't include support-v7, so this is no option. Alternative solution ideas welcome.

**Comment by str4d** [comment]
Thanks :)

> I see you had problems because BaseCrashReportDialog doesn't extend from AppCompatActivity. Acra doesn't include support-v7, so this is no option. Alternative solution ideas welcome.

Perhaps the core `BaseCrashReportDialog` methods could be factored out into a helper, with `BaseCrashReportDialog` being a wrapper. Then a new config option `legacyReportDialogClass` (or `advancedReportDialogClass`) could be added that takes an `Activity`, and leaves the calling of the helper methods to the implementer. This would not affect any existing usage, but enable the use of `AppCompatActivity` (with the subclass duplicating the helper calls in `BaseCrashReportDialog`), which is required for apps using appcompat-v7 to get correct theming of e.g. checkboxes (which I use for allowing the user to exclude report fields at crash time).

**Comment by william-ferguson-au** [comment]
Nice investigation of your problem @str4d 

@str4d if you'd like to submit a PR to allow use of AppCompatActivity for the CrashDialog, I'll be happy to review.

**Comment by str4d** [comment]
Sure, I can make a PR :)

How am I supposed to build ACRA, by the way? The existing `build.gradle` was insufficient; I had to add a bunch of extra config to be able to build a local debug AAR.

**Comment by william-ferguson-au** [comment]
ACRA is built using Maven.
Recommend using Maven-3.3 or greater

**Comment by F43nd1r** [comment]
> The existing build.gradle was insufficient

The existing build.gradle is meant for a module. You normally have one project build.gradle (the parent)  and one build.gradle per module. The parent build.gradle can be used unchanged from the one Android Studio/IntelliJ generates.

**Comment by F43nd1r** [comment]
> Then a new config option legacyReportDialogClass (or advancedReportDialogClass) could be added that takes an Activity, and leaves the calling of the helper methods to the implementer.

I think it would be no problem to just lower the requirement of `reportDialogClass` to `Acitivty`.

**Comment by william-ferguson-au** [comment]
Closing this issue as it is really not an ACRA issue.

Theming of the ReportDialog class is possible already: Use a helper instead of AppCompatActivity. http://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html

This is definetly the better way to solve this problem
