### ISSUE TITLE
Send report by email not working

### ISSUE THREAD

**Issue by kusan-thana** [ACRA/acra#444]
Sending report by email not working on last release.

I tried 4.7 and it's working on that release.

**Comment by william-ferguson-au** [comment]
You need to be quite a bit more specific.

Start by posting your ACRA config.
And your logcat.
And perhaps your Android Manifest. Are you using Manifest merging?

Then explain the symptoms you are seeing.

**Comment by william-ferguson-au** [comment]
Closing this issue due to lack of information.
