### ISSUE TITLE
DeviceID not sent

### ISSUE THREAD

**Issue by xi67** [ACRA/acra#446]
Hello,

We use acra 4.8.5 with acralyzer on a "private" app (dedicated devices).

In my manifest, I have "android.permission.READ_PHONE_STATE" in my Android.xml.

And our Acra configuration is basic : 
@ReportsCrashes(
        httpMethod = HttpSender.Method.PUT,
        reportType = HttpSender.Type.JSON,
        formUri = "http://xxxxx:5984/acra-aog/_design/acra-storage/_update/report",
        formUriBasicAuthLogin = "xxxx",
        formUriBasicAuthPassword = "xxxxx",
    mode = ReportingInteractionMode.TOAST,
    resToastText = R.string.acra_crash_text)

Any idea ?

**Comment by F43nd1r** [comment]
DEVICE_ID is not in the default reported fields, you have to add it manually.
