### ISSUE TITLE
Privacy of send data

### ISSUE THREAD

**Issue by proninyaroslav** [ACRA/acra#449]
Hello. The send data are protected against third parties? Will ACRA collect additional information and send it to third parties (for example, Google)? I'm concerned about the protection personal data of users of my application, but not sure about the safety of using ACRA. Hopefully soon the answer to my question.

**Comment by william-ferguson-au** [comment]
ACRA sends the crash data to whereever **YOU** configure it to send to.
ACRA just performs the interception of the crash, collection of the data and the sending.

You get to choose where ACRA sends it data.
ACRA doesn't send to Google or to any 3rd party unless you specifically configure ACRA to do that.

**Comment by proninyaroslav** [comment]
@william-ferguson-au 
Many thanks for the detailed answer.
