### ISSUE TITLE
Manual configuration gotcha

### ISSUE THREAD

**Issue by samskivert** [ACRA/acra#463]
If you don't have @ReportsCrashes on your app and you use manual configuration, you don't get any of the default values provided by the ReportsCrashes annotation. This results in lots of crazy failures down the line, so many so that it seems like you should disallow this use case and have ConfigurationBuilder throw an AssertionError if it doesn't see the annotation on your app.

Alternatively, you could populate the configuration builder manually with the default values that *would* have been provided by the @ReportsCrashes annotation, perhaps by creating a fake instance of the annotation, or using reflection to get the default value for the annotation methods.

Either way, something other than how it works would save potential future hours of debugging on the part of unsuspecting users who switch to manual configuration and don't realize that they're shooting themselves in the foot by omitting the @ReportsCrashes annotation.

**Comment by F43nd1r** [comment]
That's not correct. ConfigurationBuilder ensures that all values contain defaults when building a Configuration.

**Comment by samskivert** [comment]
Weird, ACRA was crashing when I tried to manually trigger the bug report dialog and reporting that resDialogPositiveButtonText and resDialogNegativeButtonText values were set to 0x0, but now when I try to recreate those crashes, they're not happening.

Maybe something else weird was going on, but I don't see how I should have been able to cause that sort of misconfiguration. Anyhow, I'll provide more details if I ever see it again.

**Comment by F43nd1r** [comment]
There was a bug: The defaults were mistakenly set to 0. It was fixed in #456. I don't know when the bug was introduced, but 4.9.0-RC2 contains that fix.
