### ISSUE TITLE
I tried to upgrade to latest version from 4.5.0 to 4.8.5 It's giving org.acra package not found compilation error

### ISSUE THREAD

**Issue by KanagarajMuniraj** [ACRA/acra#467]

**Comment by william-ferguson-au** [comment]
For what class?
Some moved to the org.acra.configuration package etc.

Check the release notes.

NB ACRA-4.9.0-RC2 is the latest.

**Comment by KanagarajMuniraj** [comment]
I could manage to get the app compiled up to 4.7.0 version. From 4.8.0 It's not recognizing any of the classes in the package. I've followed BasicSetup page to configure the app.

**Comment by william-ferguson-au** [comment]
From 4.8.0+ ACRA ships as an AAR not a JAR.

**Comment by KanagarajMuniraj** [comment]
Thanks for the quick reply. I did the following,
1. compile 'ch.acra:acra:4.8.5' then synced the project. It gave compilation error. 
2. Downloaded .aar file of 4.8.5 version. I've created a new module from this .aar file and added compile project(':Acra') in build.gradle then synced the project. Got same compilation error. 

Following are the compilation errors.
Error:(591, 16) error: cannot find symbol class ErrorReporter
Error:(572, 11) error: cannot find symbol class ErrorReporter
Error:(592, 9) error: cannot find symbol class ErrorReporter
Error:(595, 5) error: cannot find symbol variable ACRA
Error:(596, 11) error: cannot find symbol variable ACRA
Error:(597, 29) error: cannot find symbol class HttpSender
Error:(599, 12) error: cannot find symbol class ACRAConfiguration
Error:(599, 39) error: cannot find symbol variable ACRA
Error:(601, 30) error: cannot find symbol class EmailIntentSender
Error:(607, 11) error: cannot find symbol variable ACRA

**Comment by F43nd1r** [comment]
(1) Should work, no need to create a module.

Have you tried to fix the imports of these classes? The packages have changed.

**Comment by KanagarajMuniraj** [comment]
I fixed it by changing ch.acra:acra:4.8.5 dependencies scope to provided then changed back to compile in a module, under Project Structure in AndroidStudio. 

Thank you so much for your assistance.

**Comment by william-ferguson-au** [comment]
You don't need ACRA as a module.
I suspect that doing a clean build would have been sufficient.
