### ISSUE TITLE
Unexpected error while executing in Android Studio

### ISSUE THREAD

**Issue by Prof-MohamedAtef** [ACRA/acra#473]
# **excuse me, i am looking for a help !!! your response will be appreciated in advance.**

## **During the Debug time usually android studio output the results in the debug box as follows : **
--------------------
06/17 17:23:38: Launching app
$ adb push D:\Android_Studio\Android_Projects\prejava\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.example.prof_mohamed.prejava
$ adb shell pm install -r "/data/local/tmp/com.example.prof_mohamed.prejava"
	pkg: /data/local/tmp/com.example.prof_mohamed.prejava
Success

$ adb shell am start -n "com.example.prof_mohamed.prejava/com.example.prof_mohamed.prejava.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D

## **but unusually, it surprised me with this exception in a red color :**
-------------------
Unexpected error while executing: am start -n "com.example.prof_mohamed.prejava/com.example.prof_mohamed.prejava.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Error while Launching activity....

## **This is my Manifest : **
---------------
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.prof_mohamed.prejava">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

## **This is my MainActivity XML File : **
----------------
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.prof_mohamed.prejava.MainActivity"
    android:background="#FFFFFF"
    >

    <TextView
        android:textColor="#000000"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="@+id/activity_main"
        app:layout_constraintLeft_toLeftOf="@+id/activity_main"
        app:layout_constraintRight_toRightOf="@+id/activity_main"
        app:layout_constraintTop_toTopOf="@+id/activity_main" />

</android.support.constraint.ConstraintLayout>

## **This is my MainActivity java code file : **
-------------
package com.example.prof_mohamed.prejava;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}

## **and finally, This is my Build.gradle file :**
-----------------
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.example.prof_mohamed.prejava"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha3'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runne r:0.5'
    androidTestCompile 'com.android.support:support-annotations:24.0.0'
}
### Your response will be majorly appreciated . Thanks

**Comment by F43nd1r** [comment]
First: Always format your code! This is horrible to read.
Second: You don't seem to use ACRA, why are you posting here?

**Comment by Prof-MohamedAtef** [comment]
First : The Formatting tool didn't enable me to format my code.
Second : Although, this error, i am am working on using ACRA from about 8 hours.
Third : I promise that i will solve my problem without your aid, then i will post secondly here to ask you about using ACRA.

**Comment by F43nd1r** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

By the way - it is pretty unlikely that anyone can help you without a stacktrace of the error.

**Comment by william-ferguson-au** [comment]
Not an ACRA issue. Closing.
