### ISSUE TITLE
Public access api to retrieve ACRA report fields manually

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#476]
When a user sends me some feedback through my app, I want to add the BUILD data to the mail.

Any way to get acra fields for usage outside of an acra crash report?

**Comment by F43nd1r** [comment]
Do you want to retrieve the Fields itself?

```
Acra.getConfig().getReportFields()
```

Or get collection results?

```
new CrashReportFactory(...).createCrashData(...)
```

**Comment by MFlisar** [comment]
The sedond thing. I'm sure I tried that and got null as return value... I have the `BUILD` data in my default setup (via annotations), but following is not working:

    CrashReportData crd = new CrashReportDataFactory(this, ACRA.getConfig(), ACRA.getACRASharedPreferences(), Calendar.getInstance(), null)
                        .createCrashData(new ReportBuilder());
    String content = crd.getProperty(ReportField.BUILD);

`content` is `null`...

**Comment by F43nd1r** [comment]
Tested with 

```
@ReportsCrashes(
        customReportContent = {ReportField.BUILD}
)
public class MainApp extends Application {
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        ACRA.init(this);
    }
}
```
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        CrashReportData crd = new CrashReportDataFactory(this, ACRA.getConfig(), ACRA.getACRASharedPreferences(), Calendar.getInstance(), null)
                .createCrashData(new ReportBuilder());
        String content = crd.getProperty(ReportField.BUILD);
        Log.d("Content", content);
    }
}
```
and it worked.

**Comment by MFlisar** [comment]
This is my setup:

	@ReportsCrashes(
		formUri = "", // will not be used
		mailTo = "test@gmail.com",
		mode = ReportingInteractionMode.DIALOG,
		customReportContent = {
				ReportField.USER_COMMENT,
				ReportField.REPORT_ID,
				ReportField.APP_VERSION_NAME,
				ReportField.APP_VERSION_CODE,
				ReportField.ANDROID_VERSION,
				ReportField.PHONE_MODEL,
				ReportField.PACKAGE_NAME,
				ReportField.CRASH_CONFIGURATION,
				ReportField.CUSTOM_DATA,
				ReportField.STACK_TRACE,
				ReportField.APPLICATION_LOG
		},
		resToastText = R.string.crash_toast_text, // optional, displayed as soon as the crash occurs, before collecting data which can take a few seconds
		resDialogText = R.string.crash_dialog_text,
		resDialogIcon = R.mipmap.ic_launcher, //optional. default is a warning sign
		resDialogTitle = R.string.crash_dialog_title, // optional. default is your application name
		resDialogCommentPrompt = R.string.crash_dialog_comment_prompt // optional. When defined, adds a user text field input with this text resource as a label
		//resDialogEmailPrompt = R.string.crash_mail, // optional. When defined, adds a user email text entry with this text resource as label. The email address will be populated from SharedPreferences and will be provided as an ACRA field if configured.
		//resDialogOkToast = R.string.crash_dialog_ok_toast // optional. displays a Toast message when the user accepts to send a report.
	)
	public class MainApp extends BaseApp
	{
		public void onCreate()
		{
			super.onCreate();

			final ACRAConfiguration config = new ConfigurationBuilder(this)
					.setApplicationLogFile(L.getLogFilePath(logPath, "app"))
					.setApplicationLogFileLines(250)
					.build();

			ACRA.init(this, config);
			ACRA.getErrorReporter().putCustomData("AppName", getString(R.string.app_name));
			ACRA.getErrorReporter().putCustomData("Developer", String.valueOf(Tools.isDeveloper(this)));
		}
	}

Do you see anything I'm doing wring? Crash reports work fine, all data I want is attached...

**Comment by MFlisar** [comment]
stupid mistake I made... It's working. Thanks

**Comment by F43nd1r** [comment]
Sidenote - If you are only interested in Build info you should probably create a new ACRAConfiguration object with only this Field to not waste time on unused collection.

**Comment by MFlisar** [comment]
I'll do that. Thanks
