### ISSUE TITLE
Dialog and Notification not shown

### ISSUE THREAD

**Issue by hannesa2** [ACRA/acra#478]
I'm able to send with http PUT, but when I use 
`ReportingInteractionMode.DIALOG`
or
`ReportingInteractionMode.NOTIFICATION`
only a toast is shown. Short: I'm not able to make it work

Is there a sample app where I can see, how does it works ?

I use 

> compile 'ch.acra:acra:4.9.0'

Thank you !

**Comment by F43nd1r** [comment]
Example is here: https://github.com/ACRA/acra/wiki/AdvancedUsage#dialog
If tghat doesn't help, show some code.

**Comment by hannesa2** [comment]
I know this, I'm looking for some (cloneable) running code.
```
@Override
protected void attachBaseContext(Context base) {
	super.attachBaseContext(base);
	ConfigurationBuilder configurationBuilder = new ConfigurationBuilder(this);
	//http
	configurationBuilder
		.setHttpMethod(HttpSender.Method.PUT)
		.setFormUri(getString(R.string.crash_report_url))
		.setReportType(HttpSender.Type.JSON);
	//dialog
	configurationBuilder
		.setResDialogTitle(R.string.crash_dialog_title)
		.setResDialogText(R.string.crash_dialog_text)
		.setResDialogCommentPrompt(R.string.crash_dialog_comment_prompt)
		.setResDialogEmailPrompt(R.string.crash_dialog_email_prompt)
		.setResDialogOkToast(R.string.crash_dialog_ok_toast)
		//notification
		.setResNotifTickerText(R.string.crash_dialog_text)
		.setResNotifTitle(R.string.crash_dialog_text)
		.setResNotifText(R.string.crash_dialog_text)
		.setResToastText(R.string.crash_dialog_text)
		.setReportingInteractionMode(ReportingInteractionMode.DIALOG);
	configuration = configurationBuilder.build();
	ACRA.init(this, configuration, true);
}
```
and in main app, for test purpose I do this in in an button onClick()
`	init i = 1/0;`
or this
```
		AsyncTask task = new AsyncTask() {
			@Override
			protected Object doInBackground(Object[] params) {
				int i = 5/0;
				return null;
			}
		};
		task.execute();
```
with the result, of a short toast, and my app disappears.
My most preferred behavior is a dialog and a not disappeared app

**Comment by hannesa2** [comment]
I figured out, when I first time start form Android Studio, the app disappears. Then app is disconnected to debugger.
After a second start, without debugging, it shows the dialog (or notification)
Here is a screen cast (fist time is connected to debugger)

[screencast-acra-dialog.webm.zip](https://github.com/ACRA/acra/files/340854/screencast-acra-dialog.webm.zip)

I also made a simple test app, to demonstrate https://github.com/hannesa2/acra_dialog

**Comment by F43nd1r** [comment]
I have seen the debugger influencing ACRA too. I have no idea what the debugger does, but it seems to be a problem for ACRA.

**Comment by william-ferguson-au** [comment]
#495 makes using a debugger with ACRA much nicer.
