### ISSUE TITLE
Sending with Dialog crash

### ISSUE THREAD

**Issue by hannesa2** [ACRA/acra#482]
When I use 
> .setReportingInteractionMode(ReportingInteractionMode.DIALOG);

a Dialog appears without Ide #478 after filling comment and email, acra crashes.
Acra has a problem with opening report, I checked 
> reportFile.exists()

and the file exists !
but this appear

![acra_filenotfound](https://cloud.githubusercontent.com/assets/3314607/16515262/44511f12-3f71-11e6-8725-c88ee1cd437d.png)

**Comment by william-ferguson-au** [comment]
If the File exists then it sounds like you have some kind of a problem with permissions for that file. I haven't seen this before.

**Comment by william-ferguson-au** [comment]
No further input - closing
