### ISSUE TITLE
Adding in own custom text between prefixes

### ISSUE THREAD

**Issue by GamersCave** [ACRA/acra#483]
customReportContent = { ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.STACK_TRACE, ReportField.LOGCAT },

How can I add my own text betwen each of those? The text is the same every time and is meant to split the text file(I'm using a different backend) and shove it into a SQL database

**Comment by F43nd1r** [comment]
You should be able to achieve this by [implemetning your own sender](https://github.com/ACRA/acra/wiki/Report-Destinations#implementing-your-own-sender).
