### ISSUE TITLE
acra cant send

### ISSUE THREAD

**Issue by wshfzhwj** [ACRA/acra#484]
when i use acra4.8.5 in eclipse . minsdk 9 . it cant sender to server .when i search reason from logcat  i found has a log  

" W/ActivityManager(1819): Unable to start service Intent { cmp=com.xxx.xxx/org.acra.sender.SenderService (has extras) } U=0: not found"

and HttpSender cant auto import  ,must import by code.

please tell me how to check it 
thanks

**Comment by william-ferguson-au** [comment]
Do you have a SenderService defined in your AndroidManifest?

See https://github.com/ACRA/acra/blob/master/src/main/AndroidManifest.xml

If you are importing the AAR in the standard way then the ACRA Manifest should be merged into your application's Manifest.

**Comment by wshfzhwj** [comment]
Thank You!  The problem is solved . I hava another question . if i use ACRA  in eclipse  , i only import jar  and register SenderService , Whether I user ACRA correctly?
