### ISSUE TITLE
Have BaseCrashReportDialog extend FragmentActivity

### ISSUE THREAD

**Issue by str4d** [ACRA/acra#485]
In Briar's crash report and feedback activity, we were considering [using fragments to improve the crash UX for users](https://code.briarproject.org/akwizgran/briar/issues/335). However, `FragmentActivity` has no delegate alternative (unlike `AppCompatActivity`, which we can replicate in our subclass of `BaseCrashReportDialog` using `AppCompatDelegate`), and because ACRA only accepts subclasses of `BaseCrashReportDialog`, it is currently not possible to use fragments with ACRA.

The easiest and IMHO best solution is to simply change `BaseCrashReportDialog` to extend `FragmentActivity` instead of `Activity`. This is a one-line change (plus import), should have zero effect on existing usages, and does not require any additional dependencies (because `FragmentActivity` is part of support-v4, which is already leveraged by ACRA).

**Comment by str4d** [comment]
Note that it is possible to do something similar by using `FrameLayout` and showing/hiding a series of views (like used to be commonly done before fragments were introduced), but that is messier to implement, and requires more work to handle transitions between views.

**Comment by william-ferguson-au** [comment]
Happy to review a pull request.

**Comment by william-ferguson-au** [comment]
Closed with merge of #488
