### ISSUE TITLE
Add apk signature as another default Crash report data

### ISSUE THREAD

**Issue by yvolk** [ACRA/acra#493]
This is very handy to identify problems in Open Source projects and identify a source of the package. E.g. AndStatus application is distributed both by Development team and by f-droid, with different signatures. And users can also build the application themselves and then send their crash reports...

And this feature is very easy to implement, please see https://www.airpair.com/android/posts/adding-tampering-detection-to-your-android-app

**Comment by william-ferguson-au** [comment]
Would it be more useful to only report if your apk signature was invalid?

**Comment by yvolk** [comment]
In short: reporting if the signature is valid is necessary also, but not enough.

More details:
First of all, for the case of most of applications, available in f-droid repository (see https://f-droid.org/ ) more than one "valid" signature exists, because f-droid builds and signes apks itself. Plus development team, naturally, signs its build of apk with the dev team's signature. So we have large number of users with these two "valid" signatures.
It also happens that a user decides to build apk himself (real cases!).

Now imagine that I receive a crash report saying that it occurred in AndStatus application v.27.04 and I cannot reproduce the bug reported or I cannot believe that the crash could happen. Having an apk signature in the report will immediately give me an answer about the origin of the apk: f-droid, me (Google Play store mostly) or unknown user's signature.

**Comment by william-ferguson-au** [comment]
This simplest way of doing this is by adding the signature as a custom property
https://github.com/ACRA/acra/wiki/AdvancedUsage#adding-your-own-custom-variables-or-traces-in-crash-reports-breadcrumbs

**Comment by yvolk** [comment]
Thank you, will implement and let you know (in this issue) so you may decide if you want to include this as a default "report data".

**Comment by william-ferguson-au** [comment]
Thanks @yvolk but this isn't something that I would to add to ACRA core.

**Comment by yvolk** [comment]
@william-ferguson-au As you wish. Two days ago I also didn't realize that I need this :-)

**Comment by yvolk** [comment]
Implemented in AndStatus application.
See https://github.com/andstatus/andstatus/issues/407
