### ISSUE TITLE
This is not possible to send email

### ISSUE THREAD

**Issue by yurevich1** [ACRA/acra#494]
I'm using arca-4.9.0.jar file.
But while crashing this is not possible to send a email. Just a simple toast. No more:(

The code is pretty simple:

```
@ReportsCrashes(
mailTo = "the.best.email@example.com",
customReportContent = { ReportField.APP_VERSION_CODE, ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA, ReportField.STACK_TRACE, ReportField.LOGCAT },                
mode = ReportingInteractionMode.TOAST,
resToastText = R.string.crash_toast_text)
public class _ extends Application{
....
@Override
	public void onCreate() {
		
        super.onCreate();
        
        ACRA.init(this);
        // FORCE ERROR CALLING:
Intent intent = null;
    intent.getAction();

// END. THE APP apparently CRASHED. I SEE A TOAST BUT I CANT SEND EMAIL. NOTHING HAPPENS.

    }
...
}
```

Obviously, the log shows `NullPointerException`:

> 
> 08-12 11:45:57.277: D/ActivityThread(23409): handleBindApplication:com.example.app
> 08-12 11:45:57.277: D/ActivityThread(23409): setTargetHeapUtilization:0.75
> 08-12 11:45:57.277: D/ActivityThread(23409): setTargetHeapMinFree:2097152
> 08-12 11:45:57.417: I/dalvikvm(23409): Could not find method android.widget.TimePicker.getHour, referenced from method com.example.app._.getTime
> 08-12 11:45:57.417: W/dalvikvm(23409): VFY: unable to resolve virtual method 11841: Landroid/widget/TimePicker;.getHour ()I
> 08-12 11:45:57.417: D/dalvikvm(23409): VFY: replacing opcode 0x6e at 0x0022
> 08-12 11:45:57.427: I/dalvikvm(23409): Could not find method android.app.ActivityManager.getAppTasks, referenced from method com.example.app._.launchIntent
> 08-12 11:45:57.427: W/dalvikvm(23409): VFY: unable to resolve virtual method 90: Landroid/app/ActivityManager;.getAppTasks ()Ljava/util/List;
> 08-12 11:45:57.427: D/dalvikvm(23409): VFY: replacing opcode 0x6e at 0x0029
> 08-12 11:45:57.427: I/dalvikvm(23409): Could not find method android.widget.TimePicker.setHour, referenced from method com.example.app._.setTime
> 08-12 11:45:57.427: W/dalvikvm(23409): VFY: unable to resolve virtual method 11845: Landroid/widget/TimePicker;.setHour (I)V
> 08-12 11:45:57.427: D/dalvikvm(23409): VFY: replacing opcode 0x6e at 0x0015
> 08-12 11:45:57.627: I/ACRA(23409): ACRA is enabled for com.example.app, initializing...
> 08-12 11:45:57.637: D/AndroidRuntime(23409): Shutting down VM
> 08-12 11:45:57.637: W/dalvikvm(23409): threadid=1: thread exiting with uncaught exception (group=0x4167dd58)
> 08-12 11:45:57.637: E/ACRA(23409): ACRA caught a RuntimeException for com.example.app
> 08-12 11:45:57.637: E/ACRA(23409): java.lang.RuntimeException: Unable to create application com.example.app._: java.lang.NullPointerException
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4467)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.ActivityThread.access$1500(ActivityThread.java:145)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.os.Looper.loop(Looper.java:136)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.ActivityThread.main(ActivityThread.java:5137)
> 08-12 11:45:57.637: E/ACRA(23409): 	at java.lang.reflect.Method.invokeNative(Native Method)
> 08-12 11:45:57.637: E/ACRA(23409): 	at java.lang.reflect.Method.invoke(Method.java:515)
> 08-12 11:45:57.637: E/ACRA(23409): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
> 08-12 11:45:57.637: E/ACRA(23409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
> 08-12 11:45:57.637: E/ACRA(23409): 	at dalvik.system.NativeStart.main(Native Method)
> 08-12 11:45:57.637: E/ACRA(23409): Caused by: java.lang.NullPointerException
> 08-12 11:45:57.637: E/ACRA(23409): 	at com.example.app._.onCreate(_.java:446)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
> 08-12 11:45:57.637: E/ACRA(23409): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4464)
> 08-12 11:45:57.637: E/ACRA(23409): 	... 10 more
> 

The same behaviour appears if I move 

```
Intent intent = null;
intent.getAction();
```
 into any Activity class.

Yes , I have correct `AndroidManifest.xml` file.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app"
    android:versionCode="62"
    android:versionName="2.0.0.7" >
.....
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_LOGS"/>
 <application
        android:allowBackup="true"
        android:icon="@drawable/ico"
        android:label="@string/app_name"
        android:name="com.example.app._"
        android:largeHeap="true"
        android:theme="@style/AppTheme" >

.....
</application>
```

I'm using Eclipse. Of course, I've added jar file to project.

**Comment by F43nd1r** [comment]
See #490.

@william-ferguson-au would it be possible to deactivate the jar upload for future versions?

**Comment by yurevich1** [comment]
Do you mean `jar` doesn't work properly ? That is, it is impossible to use ACRA for Eclipse project?

**Comment by F43nd1r** [comment]
While ADT does not support aars, that doesn't mean it's impossible to use them.
https://github.com/ksoichiro/gradle-eclipse-aar-plugin
http://simpligility.github.io/android-maven-plugin/
https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html

**Comment by yurevich1** [comment]
Sadly, but I can see the same behaviour.

I've downloaded .aar file, extracted classes.jar (renamed into acra.jar) and changed androidmanifest.xml by appending this:
```


	<activity
		android:excludeFromRecents="true"
		android:finishOnTaskLaunch="true"
		android:launchMode="singleInstance"
		android:name="org.acra.dialog.CrashReportDialog"
		android:theme="@android:style/Theme.Dialog"/>

	<service
		android:exported="false"
		android:name="org.acra.sender.SenderService"
		android:process=":acra"/>
```

The same behavoiur. The same log. No email.

**Comment by F43nd1r** [comment]
Your log excerpt stops before the interseting parts, we can't see what acra does with the crash.

Anyways, I think there is a problem if the crashing method is the same as the on which registered acra. Try to create a crash in an activity instead.

**Comment by yurevich1** [comment]
@F43nd1r , you are right. It works now.
