### ISSUE TITLE
CrashReportDialog has to be called with extra ACRAConstants#EXTRA_REPORT_CONFIG

### ISSUE THREAD

**Issue by yhercouet** [ACRA/acra#499]
Hi everyone,

I am getting the following bug with ACRA, I have no idea where it is coming from, I am not using CrashReportDialog:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aiguo.handydiary/org.acra.dialog.CrashReportDialog}: java.lang.IllegalStateException: CrashReportDialog has to be called with extra ACRAConstants#EXTRA_REPORT_CONFIG`

Any idea on how to fix this problem?

Thank you

**Comment by F43nd1r** [comment]
Use acra 4.9.0

**Comment by yhercouet** [comment]
I was indeed using 4.8.5, just updated to 4.9.0, are you sure 4.9.0 will solve the problem?

**Comment by F43nd1r** [comment]
Yes. I implemented the fix. 

By the way, this is caused by crawlers. They start every activity registered in the manifest. I don't know exactly why people run these, but they may search for security holes and the like.

**Comment by yhercouet** [comment]
Thanks a lot for the information and your quick answer!
