### ISSUE TITLE
NPE crash in SenderService.onHandleIntent due to null Intent

### ISSUE THREAD

**Issue by MarcBernstein** [ACRA/acra#500]
After updating ACRA to 4.9.0, we started seeing these crash traces showing up:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
       at org.acra.sender.SenderService.onHandleIntent(SenderService.java:35)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

We're using the .aar to include the ACRA lib.

Taking a look at [SenderService.onHandleIntent(Intent)](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/sender/SenderService.java#L32-L33), it has the Intent parameter annotated as `@NonNull` but the IntentService that SenderService is extending has this parameter marked as `@Nullable`.

See source for [IntentService.onHandleIntent(Intent)](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/IntentService.java#169).

It states that the intent passed in can occasionally be null when the service is being restarted. In this case I guess just a null check and return in `SenderService.onHandleIntent` would resolve the bug. Upon service restart I'm guessing the intent will then be non-null and the report can be sent. I can submit a PR if this is the direction you want to take.

**Comment by william-ferguson-au** [comment]
Thanks Mark. I have merged @F43nd1r 's changes which fix this.

Your beard has grown much thicker since Google IO 2012.

**Comment by MarcBernstein** [comment]
Great, thanks for the heads up @william-ferguson-au. Small world, isn't it? 😉

**Comment by MarcBernstein** [comment]
By the way, what is the ACRA project's policy on RC builds? Just curious as to when we can start using this change, as it's currently our app's highest crash rate.

**Comment by F43nd1r** [comment]
I think as almost all changes since the last release were made by me and I test everything individually before proposing PRs, the master should be pretty stable. 
Integration testing is pending. 

@william-ferguson-au I think we could aim for a release of 4.9.1 within the next month. I'd like to see #495 and #510 in there. It also should include either #502 or #478 and #488 as an intermediate solution.

**Comment by william-ferguson-au** [comment]
I'm inclined towards #487 and #488 instead of #502.
#502 looks like overkill
