### ISSUE TITLE
app (running on android 5.1 - sdk22) crashes and ACRA does not send report and app is not restarted

### ISSUE THREAD

**Issue by carlosfvieira** [ACRA/acra#508]
Hi, i've an app running on sdk 23, and when it crashes it send crash reports and the app is restarted siliently.

The problem here is that the same app in sdk 22 crashes (closes silently), but ACRA does not send any crash report, and the app does not get restarted....

Problem is that i cannot have access to the phone running the app, and can see logcat, so i don't know what's hapening...

Any idea of what could be hapening?
 - i'm using ACRA 4.9.0
 - if by somehow, when app crashes ACRA can't send the report, how can it send the report when the app is manullay opened after crash?

Thanks!

**Comment by F43nd1r** [comment]
I've never observed differences with ACRA in Api 22 vs 23. Without logs its pretty much impossible to give a diagnosis.

**Comment by william-ferguson-au** [comment]
As @F43nd1r says, without logs it is very hard to comment.

But one way that an app can crash without being recorded by ACRA is if a native library core dumps as ACRA can only catch crashes that occur within Java code. If that is occurring then ACRA won't even have a record of the crash.

**Comment by usmanhashmi2123** [comment]
@william-ferguson-au 
@F43nd1r 
@carlosfvieira 
I have the same issue.
 itird to add crasgreport in external storage. by implementing my own ReportSender class and ReportSenderFactoryclass by follwoing the provided documentation.

public ReportSender create(@NonNull Context context, @NonNull ACRAConfiguration config) is never called in myownreportsender factory class.

You can see my code her.
Have i done anything wrong

[log.txt](https://github.com/ACRA/acra/files/461062/log.txt)

**Comment by william-ferguson-au** [comment]
@usmanhashmi2123 from your log it doesn't appear that the SenderService started.
Are you including the ACRA aar or ACRA jar?

**Comment by usmanhashmi2123** [comment]
i am using eclipse.
i am using Acra jar

**Comment by carlosfvieira** [comment]
i've found today that the issue, in the case i've reported, has nothing to do with ACRA... the app was being killed by battery saver feature present in my client's device...

**Comment by carlosfvieira** [comment]
Hi @usmanhashmi2123 , please check #497 , where @F43nd1r help me out with something similar.

Since you're using .jar as i am, you need to add this in your manifest file:
```
<activity android:excludeFromRecents="true" android:finishOnTaskLaunch="true" android:launchMode="singleInstance" android:name="org.acra.dialog.CrashReportDialog" android:theme="@android:style/Theme.Dialog"/>
<service android:exported="false" android:name="org.acra.sender.SenderService" android:process=":acra"/>
```

**Comment by usmanhashmi2123** [comment]
@carlosfvieira   thanks.
issue resolved.
it was because of missing service in manifest
<service
            android:name="org.acra.sender.SenderService"
            android:exported="false"
            android:process=":acra" />
