### ISSUE TITLE
progurad

### ISSUE THREAD

**Issue by usmanhashmi2123** [ACRA/acra#512]
@william-ferguson-au 
@F43nd1r 
I am using eclipse.
after adding new Acra 4.9.0jar
these progurad error occur while making signed apk with progurad enabled
`Note: there were 3068 duplicate class definitions.
'Warning: org.acra.collector.MediaCodecListCollector: can't find referenced method 'MediaCodecList(int)' in class android.media.MediaCodecList
Warning: org.acra.collector.MediaCodecListCollector: can't find referenced method 'android.media.MediaCodecInfo[] getCodecInfos()' in class android.media.MediaCodecList
      You should check if you need to specify additional program jars.
'Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile them and try again.
         Alternatively, you may have to specify the option 
         '-dontskipnonpubliclibraryclassmembers'.
'java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:321)
	at proguard.ProGuard.initialize(ProGuard.java:211)
	at proguard.ProGuard.execute(ProGuard.java:86)
	at proguard.ProGuard.main(ProGuard.java:492)
`
This is my proguard file.
before this it was working fine.
i have added  progurad settings  of Acra proguardi n my application proguard
[proguard-project.txt](https://github.com/ACRA/acra/files/461592/proguard-project.txt)

thanks

**Comment by william-ferguson-au** [comment]
YOu should be using the ACRA aar not jar.

**Comment by F43nd1r** [comment]
This looks like you're compiling against an old android api. Use at least 21.

**Comment by usmanhashmi2123** [comment]
@william-ferguson-au    i am suing eclipse so i think i can,t user aar
@F43nd1r  i amusing android api 23

**Comment by william-ferguson-au** [comment]
Closing - you have to build against the AAR.
Force your build system to do so or use a build system that can.
