### ISSUE TITLE
React-Native

### ISSUE THREAD

**Issue by GeoffreyPlitt** [ACRA/acra#514]
Does this work with React-Native?

**Comment by F43nd1r** [comment]
I've never tried it, but as React supports native components it should work.

**Comment by GeoffreyPlitt** [comment]
I think the correct answer is no. React-Native support means it's ready to be included in a React-Native project, which requires a wrapper and React-Native-specific tooling.

**Comment by F43nd1r** [comment]
There is a difference between "would it work" and "it is supported". Yes it would work, but no there is no wrapper. 

Also, in a general sense: It would be a better idea to use a platform independent bug reporting tool if your codebase is platform independent.

**Comment by GeoffreyPlitt** [comment]
I like that idea, can you recommend any?

**Comment by F43nd1r** [comment]
As I said,  I haven't used React-Native. A quick google search popped up several options, which you'll have to evaluate yourself.

**Comment by NikolaBorislavovHristov** [comment]
I am using it in my ReactNative project with Tracepot and it works perfectly. Just modify your MainApplication class.

**Comment by sonbuiGFD** [comment]
hi @NikolaBorislavovHristov,
Can you give more detail about modify Mainapplication class. I'm a newbie and having trouble with logging crash info in my react native app.

**Comment by NikolaBorislavovHristov** [comment]
@sonbuiGFD 
Example:

in your [Application successor class](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/android/app/src/main/java/com/facebook/react/uiapp/UIExplorerApplication.java#L29) you have to override attachBaseContext method and also you have to use @ReportsCrashes annotation. It is shown in the [ACRA wiki](https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---declaratively)

**Comment by sonbuiGFD** [comment]
@NikolaBorislavovHristov 
Thanks for your reply,
I have setups the same ACRA wiki on MainApplication.java. The bundle builds fine.
Then in index.android.js, I set a timeout function to threw a RuntimeException. 
But in Tracepot, I don't get any data.

**Comment by NikolaBorislavovHristov** [comment]
@sonbuiGFD 
Wait a few hours and check again.
If the runtime exception is thrown in debug mode you have to include this:

```Java
@ReportsCrashes(
    formUri = "http://www.backendofyourchoice.com/reportpath",
    sendReportsInDevMode = true
)
```

**Comment by sonbuiGFD** [comment]
@NikolaBorislavovHristov 
Thanks for your help,
I tried it but it's seem not working, maybe I will try something else
Thank you again
