### ISSUE TITLE
Switch internal structure to JSON

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#517]
Related to #492.
I've done most of the work to switch internals to json. See https://github.com/F43nd1r/acra/tree/json
I tested and verified it is working with Acralyzer. However, now that internals are json, we need a conversion from JSON to POST.
And I do not have any POST backend or experience with it, so I can't really say if my conversion works as it should.
Note that comments are not yet updated.

@william-ferguson-au thoughts?

**Comment by william-ferguson-au** [comment]
What's an awful lot of changes.
It will need a lot of vetting and testing.

What will it buy us?
When you say POST, do you mean posting as Http Form?

**Comment by F43nd1r** [comment]
Thats why I didn't create a PR right away. It might be a good idea to first release the current state and then look at this.

Advantages include:
-no formatting issues related to dots
-speed for json output (however i guess at the cost of speed for post)
-lower memory footprint due to no duplicated information
-a crashreportdialog could now be allowed to access the report and e.g. display a localized message transported in custom data
-the file representation of reports could switch to json, making the custom standard obsolete.
-custom senders can transform the data more easily.
-in general it lifts a limitation. It probably does more than I can think of right now.

When I say post i mean whatever happens when the reporttype is set to post.

**Comment by F43nd1r** [comment]
By the way, the changes may look more than they actually are, as each collector had to be modified. But most of them could be modified in the same scheme: Replace strings with SimpleElement and replace StringBuilder with ComplexElement.

**Comment by william-ferguson-au** [comment]
Makes sense to leave until after next release.
Sorting out the formatting issue for dots is good, as is storing as JSon.
What do you mean about lower footprint due to no duplicated info?

**Comment by F43nd1r** [comment]
> What do you mean about lower footprint due to no duplicated info?

For example the display id is included about 30 times in the report string. The json structure contains it exactly once. While this certainly has an impact, after looking through a complete report I think the impact is not big, as the report tree is not that deep. I don't think the difference is measurable.
