### ISSUE TITLE
Feature: plugin for Android Studio

### ISSUE THREAD

**Issue by Scrounger** [ACRA/acra#519]
It would be awesome to have a acra plugin for Android Studio to debug all crash reports directly in AS.
Is it planed to integrate such a feature?

**Comment by F43nd1r** [comment]
While this is certainly an interesting idea, as it would allow for several shortcuts (like automatic proguard mapping or deep line links), ACRA already has an official backend and afaik there are no plans to create another one.

**Comment by william-ferguson-au** [comment]
This is not on the cards. 
Such a plugin is more to do with a display of the crash reports on a crash server and not with ACRA as each report server can have a very different interface.
