### ISSUE TITLE
"Unfortunately, MyApp has stopped" dialog not shown

### ISSUE THREAD

**Issue by TimCastelijns** [ACRA/acra#520]
Since I started using ACRA in my apps, they do not show "Unfortunately, MyApp has stopped" when it crashes anymore. 

It happens with debug as well as release apks, for all my projects.  
It happens in v4.9.0. Don't know about older versions.

Reproduce with following code

```
compile 'ch.acra:acra:4.9.0'
```

Manifest

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="nl.phasefour.myapplication">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

MainActivity

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        int a = 1/0; // Trigger ArithmeticException
    }
}
```

App

```
@ReportsCrashes(
        formUri = "https://myserver.com/crash_reports",
        httpMethod = HttpSender.Method.POST,
        reportType = HttpSender.Type.JSON
)
public class App extends Application {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        ACRA.init(this);
    }
}
```

This is a new blank project with basic ACRA setup. The wiki says that by default, it should still show the crash dialogs, but it doesn't. It's likely my own fault, but I can't figure out the mistake. I have searched through existing issues but found no match for my case.

**Comment by F43nd1r** [comment]
Please point me to the wiki page saying that. It is wrong, but there is an option 'alsoReportToAndroidFramework' which will turn on native crash report dialogs.

**Comment by TimCastelijns** [comment]
Thanks for the quick response.

The README says

> If a crash occurs, your application does not add user notifications over existing system's crash notifications or reporting features. If you use the Toast, Status bar notification or direct dialog modes, the "force close" dialog is not displayed anymore

and https://github.com/ACRA/acra/wiki/AdvancedUsage#user-interaction says

> The default behavior of ACRA is to send crash reports silently. From the application user point of view, the app has crashed with the usual "Force Close" dialog, and that's all.

**Comment by TimCastelijns** [comment]
I have tried your suggestion. Adding `alsoReportToAndroidFramework = true` works great. Perhaps the documentation I pointed to could use some clarification.

Anyway, thanks!

**Comment by F43nd1r** [comment]
I think this was actually a (probably undocumented) behaviourchange in 4.9, which we overlooked. I've updated the wiki. Calling @william-ferguson-au to update the readme.

**Comment by william-ferguson-au** [comment]
@F43nd1r what do you suggest wrt wording?

**Comment by F43nd1r** [comment]
I've just now read the wohle thing. Here are all issues I identified:

> ACRA is a library enabling Android Application to automatically post their crash reports to a GoogleDoc form.

Replace doc with backend

> google doc reports can be shared with a whole development team. Other benefits from the Google Docs platform are still to be investigated (stats, macros...)

Just remove it i guess

> If you use the Toast, Status bar notification or direct dialog modes, the "force close" dialog is not displayed anymore and devices where the system native reporting feature is enabled do not offer the user to send an additional report.

»By default the "force close" dialog is not displayed anymore...«

**Comment by william-ferguson-au** [comment]
Done
