### ISSUE TITLE
Failed to send crash report for...

### ISSUE THREAD

**Issue by naserkhosravi** [ACRA/acra#527]
every thing is simple but i get this error in log cat.
Failed to send crash report for /data/user/0/com.hamyarsam.hamyarsam/app_ACRA-approved/2016-10-15T18:09:15.109+03:30.stacktrace

I have Internet Permission and refrence to class MyApplication in android manifiest;
 <application android:name=".MyApplication".....
<uses-permission android:name="android.permission.INTERNET" />

and this is My Application class :
@ReportsCrashes(formUri = "http://xxx.xxxxxxx.xx/app/MySQLi/report.php")
public class MyApplication extends Application {

```
@Override
public void onCreate() {
    super.onCreate();
    CalligraphyConfig.initDefault(new  CalligraphyConfig.Builder()
            .setDefaultFontPath("SYEKAN.TTF")
            .setFontAttrId(R.attr.fontPath)
            .build());

}

@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(newBase);
    ACRA.init(this);
}
```

}

thanks for good library.

**Comment by F43nd1r** [comment]
If something fails there will be a stacktrace in the log. Paste it here.

**Comment by F43nd1r** [comment]
Closing - No more information
