### ISSUE TITLE
Basic Setup issue - logcat returning TypeNotPresentException

### ISSUE THREAD

**Issue by vmsJames** [ACRA/acra#529]
The basic setup appears to be very well documented, however I'm experiencing an exception during the initialization of ACRA:  ACRA.init(this), and don't know why?

I'm using intellij idea, and have acra.jar (renamed from classes.jar) in the /libs folder - added as a dependency under Project/Modules. The logcat is logging:

E/dalvikvm: Could not find class 'org.acra.dialog.CrashReportDialog', referenced from method org.acra.config.ConfigurationBuilder.build

even though it does exist in the acra.jar.  What might I be missing?

[manifest]
[manifest.txt](https://github.com/ACRA/acra/files/551832/manifest.txt)

[application]
[application.txt](https://github.com/ACRA/acra/files/551850/application.txt)

[logcat]
[logcat.txt](https://github.com/ACRA/acra/files/551830/logcat.txt)

**Comment by william-ferguson-au** [comment]
At a guess you have stripped org.acra.dialog.CrashReportDialog from your APK using Proguard or similar.

You should be declaring a dependency on the ACRA aar not the jar file. The ACRA aar includes the extra proguard config you need for ACRA.

**Comment by vmsJames** [comment]
Ok, I put and selected the acra-4.9.1.aar from the /libs folder - now
@ReportCrashes is not resolving?

Being new to importing libraries, hoping I'm structuring correctly. In
project structure-Libraries, I selected the .arr, but IntelliJ doesn't know
what kind of files it contains - classes/jar dir/sources.. I tried classes,
but still no go - the import statements are flagged as unused..  I'm
missing a step somewhere - need help.

James

On Oct 25, 2016, at 2:51 PM, William Ferguson <notifications@github.com>
wrote:

At a guess you have stripped org.acra.dialog.CrashReportDialog from your
APK using Proguard or similar.

You should be declaring a dependency on the ACRA aar not the jar file. The
ACRA aar includes the extra proguard config you need for ACRA.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ACRA/acra/issues/529#issuecomment-256186745>, or mute
the thread

**Comment by william-ferguson-au** [comment]
OK, it's aar not arr.

Are you using Android Studio or plain IntelliJ?
What are you using as your build tool? Gradle, Maven, something else?

**Comment by vmsJames** [comment]
I'm using Intellij idea 2016.2 - upgraded from 14, and using whatever the default build tool was at that time (?) - this project was an old one initially created some time ago, and I've never really understood what build tool it was/is using.  From the Toolbar | Build I just select Rebuild Project.  There is an ant.properties file, so maybe it is using ant(?).

I've been trying, without success, to get any of the ACRA resources to resolve - the ACRA imports are showing as unused now?  Java cannot find symbol class ReportsCrashes,..  it's like I haven't correctly added the acra library?

I've read on stackOverflow that intellij can't deal with .aar in the /libs folder, but via gradle there is a way to overcome this.  I'm not sure I understand how to make this project use gradle if that is my only recourse using intellij.

**Comment by F43nd1r** [comment]
To set up a gradle project from old sources it might be a good idea to create a new gradle project (IntelliJ should have an Android preset) and then pull sources and resources in.

**Comment by vmsJames** [comment]
(arr mate - happy halloween -  aar it is)

I'm using Intellij idea 2016.2 - upgraded from 14, and using whatever the
default build tool was at that time (?) - this project was an old one
initially created some time ago, and I've never really understood what it
was using.  If I click on Maven projects, it's empty. From the Toolbar |
Build I just select Rebuild Project.

I know that now, if I create a new project, it is configured for Gradle -
this is an area of weakness for me, understanding how to manage/edit the
correct build scripts.

I've been trying, without success, to get any of the ACRA resources to
resolve - the ACRA imports are showing as unused now?  Java cannot find
symbol class ReportsCrashes,..  it's like I haven't correctly added the
library?

**Comment by vmsJames** [comment]
Ok, I created a new project (which by default is configured to use gradle), and added my files.  First thing i notice is a more complicated project structure than before - an extra 12 libraries, and 3 facets, just for hello world?  And takes much longer to build than before - hope there's some things I can do to speed things up.

Much different than what I've been used to, but at least I can proceed forward using the acra api.
Excited to try it -- thanks for the support.
