### ISSUE TITLE
Dependency issue with Intellij IDEA 2016.2.5 and gradle

### ISSUE THREAD

**Issue by vmsJames** [ACRA/acra#533]
Having a problem trying to get a running example to compile/run correctly.

Firstly, could not simply place the .aar file into the /libs folder without getting this error after a gradle sync: 
Only Jar-type local dependencies are supported. Cannot handle ..\libs\acra-4.9.1.aar

Tried moving the aar file to an external location, and added this line to the \app\build.gradle:
provided fileTree(dir: '../../sdk/extras/acra', include: 'acra-4.9.1.aar' )

but still got the same error.
I then created a new folder under \app\src\main\aarLibs and placed the file there.
Added the following to the \app\build.gradle:

repositories{
  flatDir{
    dirs 'arrLibs'
  }
}

dependencies{
  compile( name: 'acra-4.9.1', ext: 'arr')
}

and that eliminated the gradle sync error - compiles fine - but then...
whenever the application is first started, get an acra error during the ACRA.init(this) call:
logcat: Unable to resolve superclass of Lorg/acra/dialog/BaseCrashReportDialog;

logcat contents:
[acraGradleIssue.txt](https://github.com/ACRA/acra/files/607664/acraGradleIssue.txt)

So, not sure if this gradle sync resolve is actually working here?
This appears to be a jetBrains issue, but reaching out for any useful insight that might help get us working.

James

**Comment by F43nd1r** [comment]
If you include the aar manually you are circumventig the dependency managment. As a result, you have to ensure that all transitive dependencies are fulfilled. As you are using gradle I recommend to use its dependency managment. To do this use the following dependency: 
```groovy
compile 'ch.acra:acra:4.9.1'
```

**Comment by vmsJames** [comment]
Ok, that is much simpler - I may have mucked up what I started with initially - due to not understanding how the project dependency management finds and uses the required library in the first place.  If I may inquire, how 'does' this line work -> compile 'ch.acra:acra:4.9.1'

**Comment by F43nd1r** [comment]
Somewhere in your gradle scripts, you have something like this:
```
    repositories {
        maven {url = "https://oss.jfrog.org/libs-snapshot/" }
        jcenter()
    }
```
This defines urls where gradle will look for artifacts. (jcenter is predefined, but custom are possible as you see with the first one.) If gradle finds these artifacts, they are loaded into the cache, which is usually located at C:\Users\<username>\.gradle\caches. This specific aar will land in \modules-2\files-2.1\ch.acra\acra\4.9.1 (together with sources and dependency information), where your script will find it and load it into the project. 
You can browse jcenter or maven central online, e.g. here is where acra comes from https://bintray.com/bintray/jcenter/ch.acra%3Aacra

**Comment by vmsJames** [comment]
That's awesome, thank you for the info - the example app is now compiling and running (yeae).

Just one more question please - in a multiple activity module, if Acra catches an error in another activity, how do we force close the remaining, or rather ensure the application closes?
This example has a MainApplication, MainActivity, and a TestActivity.
ACRA.init is in the MainApplication.attachBaseContext
MainActivity is the startup activity
TestActivity is where we force an error.
After Acra captures this error  (using ReportingInteractionMode.DIALOG), the MainActivity displays.
We would actually like to auto-close the application at this point - if that is possible?

**Comment by F43nd1r** [comment]
I would expect all your activities to be in the same process. This process is killed by ACRA (unless you are debugging it). All activities in a process die at that point. If that is not the case, you'd have to implement your own solution. Have a look at ReportPrimers. They were not intended for this use, but it should work.
