### ISSUE TITLE
Setting configuration on the fly

### ISSUE THREAD

**Issue by dupuisdavid** [ACRA/acra#537]
Hello,

I'm just discovered ACRA (4.9.1) project today. I see that configuration can be done programmatically in application attachBaseContext method. For my project, I must request my server to get the final url to request with ACRA, consequently I can't do the setup in attachBaseContext.
I have tried to use following code :

```
ACRAConfiguration config = ACRA.getConfig();
config.setFormUri("http://server.com/script");
ACRA.setConfig(config);
```
or 
```
ACRAConfiguration config = ACRA.getNewDefaultConfig();
config.setFormUri("http://server.com/script");
ACRA.setConfig(config);
```

but `ACRA.getConfig();` `setFormUri()`, or `ACRA.getNewDefaultConfig()` are not available...
Any help ?

**Comment by F43nd1r** [comment]
ACRA does not support configuration changes after initialization. You have to wait with the `ACRA.init` call until you can specify your configuration.

**Comment by dupuisdavid** [comment]
Thank you for this answer. Your response also means that there is not any obligation of doing ACRA.init in application attachBaseContext method (I can init ACRA after a user interaction like a button tap for example, or in a HTTP request response handler), is it right ?

**Comment by F43nd1r** [comment]
The earlier you call it, the more crashes you'll be able to catch. Behaviour with a later call is untested but should work.

**Comment by benibela** [comment]
That is bad

I had an option to let the user choose which data to send in the report. ( https://github.com/benibela/videlibri/blob/master/android/android/src/de/benibela/videlibri/VideLibriApp.java#L89-L112 ) which is really important for privacy and needs to change the config when the user changes the option

**Comment by F43nd1r** [comment]
Acra loads configuration only once per process. You can start a new one if you want to change configuration

**Comment by william-ferguson-au** [comment]
Let's be clear, ACRA is designed to report unhandled exceptions within your app. You should only provide enough information in the crash report to be able to debug it.
