### ISSUE TITLE
aar doesn't have mandatory entries

### ISSUE THREAD

**Issue by ChaitanyaPramod** [ACRA/acra#538]
ACRA's aar doesn't have the mandatory entries defined in https://developer.android.com/studio/projects/android-library.html#aar-contents
Specifically, `/res/` and `/R.txt` are missing.

This causes some stricter build systems (like buck) to fail when depending on ACRA. See https://github.com/facebook/buck/issues/1055

**Comment by william-ferguson-au** [comment]
I believe an update to android-maven-plugin:4.4.1 or higher will be sufficient to make this happen.

**Comment by william-ferguson-au** [comment]
Resolved in ACR-4.9.2
