### ISSUE TITLE
ACRA loading time

### ISSUE THREAD

**Issue by pyricau** [ACRA/acra#54]
Hi !

I measured the execution of `ACRA.init()` a few times on my Galaxy Nexus, and it took between 50ms and 180ms.

This means the UI thread is blocked from 4 to 12 frames on application startup. And that's on a galaxy nexus, a pretty good phone.

My "measurement method" was pretty simple and may be biaised:

``` java
    @Override
    public void onCreate() {
        super.onCreate();
        long start = System.currentTimeMillis();
        ACRA.init(this);
        Log.d("TEST", "ACRA init in ms: " + (System.currentTimeMillis() - start));
    }
```

Anyway, I started traceview to get an insight of what's happening, and I then rebuilt ACRA with measurement logs to be more precise (I started traceview in debug which impacts the perfs). Here is what I found out:
### SharedPreferences

`ACRA.shouldDisableACRA()` accounts for ~50% of the init time. 

Android loads `SharedPreferences` in background, so `getSharedPreferences()` returns immediately. 

However, trying to retrieve a value from the preferences is a blocking operation until the preferences are loaded. `ACRA.shouldDisableACRA()` calls `prefs.getBoolean()` which waits for the loading in background to complete.

It's worth noting that if you test multiple times, the file may load immediately thanks to file caches.

A simple way to fix this issue is to use a callback mechanism to read the values once the preference is loaded. However, this means handling the fact that we don't know immediately whether ACRA is enabled or not.
### Reading the annotation

`mApplication.getClass().getAnnotation(ReportsCrashes.class)` takes between 5 and 10ms. It can be completely avoided with a few minor changes that enable an alternate programmatic configuration.
### Creating the ErrorReporter

`new ErrorReporter()` takes the rest of the time budget. I didn't measure precisely enough to know what's going on there exactly.

**Comment by pyricau** [comment]
:) that was two years ago.

**Comment by KevinGaudin** [comment]
And we're still waiting for your PR ! :o)
