### ISSUE TITLE
Update config on crash

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#540]
I've recently changed my logging to create one file per day. Before I had one file only, that was truncated.

In the past I used a configuartion like following:

    ACRAConfiguration config = new ConfigurationBuilder(this)
                    .setApplicationLogFile(logFilePath)
                    .setApplicationLogFileLines(250)
                    .build();

**Question**

* is it possible to add mutliple log files via a file name pattern + folder definition? That would be nice...
* alternatively, I just want to add the NEWEST log file, but this means, I must update the config (and adjust the log file path to the currently newest log file). How can I do that? Instead of passing a fixed log path, I would need to pass in a function that is executed in case of a crash...

**Comment by william-ferguson-au** [comment]
If I understand you correctly, you have a rolling log file policy where you create a new log file each day. Each log file has a unique name.

The standard mechanism for rolling log files is that the current log is called something my "myapplicaton.log" and older logs are called "myapplication.log.1", "myapplication.log.2" etc or "myapplication.log.<yesterdays-date>".

**Comment by MFlisar** [comment]
I know, I can do that. I would prefer to add at least 2 log files anyways (I do that as well if the user sends me some feedback via the app, I append all log files).

Is there really no place where I can manually add a few files? In a custom error reporter or similar?

I will change the naming of my log files if there is really no better choice...

**Comment by F43nd1r** [comment]
> Is there really no place where I can manually add a few files? In a custom error reporter or similar?

You can create a ReportPrimer, although you'd have to send the log as CUSTOM_DATA instead of LOG_FILE.

**Comment by MFlisar** [comment]
@F43nd1r I really want to have files appended, having multiple files as text appended is not that overseeable... I would attach even another file if adding files would be possible...

I just decided to use a size based rollover for my log files and to have the active log always have the default log name...

Still, it would be nice to be able to append multiple log files to the error report...

**Comment by F43nd1r** [comment]
ACRA is not built to send anything else than one String. It should allow you to plug-in custom components if you're not happy with that, but there are no plans to implement additional file transfer.
