### ISSUE TITLE
Custom data in report on first hirachy

### ISSUE THREAD

**Issue by orangecoding** [ACRA/acra#544]
Hi,

Don't know where to ask this elsewhere.. I'm sending reports to my backend. Now I have the need to send some custom data (like apiKey) on the first hierarchy of the report.

For instance:

```
{ 
REPORT_ID: '70789614-5e8c-4370-a28c-7cf1bdc20620',
  APP_VERSION_CODE: 1,
  APP_VERSION_NAME: '1.0',
  PHONE_MODEL: 'Android SDK built for x86',
  ANDROID_VERSION: 7.1,
  key: 'SOME STRING'
}
```

It is important that the key is not wrapped in CUSTOM_DATA. Is this somehow possible?

**Comment by F43nd1r** [comment]
This is not intended. You can achieve this with a custom sender though. Copy the HttpSender an modify the json in [line 217](https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/sender/HttpSender.java#L217)

**Comment by F43nd1r** [comment]
I've created a PR which would allow you to extend HttpSender instead of copy-pasting most of its code: #545

**Comment by orangecoding** [comment]
This is incredible. When will this be available?

**Comment by orangecoding** [comment]
And another question.
I have some debug points in my custom sender. also some Logs, but neither the debug points nor the logs will ever be reached. Still it seems to send out my reports. Why is this so?

**Comment by F43nd1r** [comment]
Reportsender are run in a separate process, you'd have to debug that process to be able to use breakpoints.
