### ISSUE TITLE
Question: work with firebase?

### ISSUE THREAD

**Issue by ryc16** [ACRA/acra#546]
Hi, does ACRA work with firebase for crash report? If so, can share any sample how to wire it up? I found firebase crash report just have stacktrace. I would like to include logcat as ACRA does to send to firebase.

**Comment by orangecoding** [comment]
I guess you have to write your own reporter like I did.

**Comment by F43nd1r** [comment]
You can create a pull request if you have a working sender for firebase, it might get included in the project.
