### ISSUE TITLE
Q: How do I debug problems in reporter

### ISSUE THREAD

**Issue by orangecoding** [ACRA/acra#548]
Hi,

I'm getting a bit crazy here.. I would like to debug why my crashes are note being send. I worked as long as I have Acra installed into my demo app, but now when serving Acra with as a wrapped lib, crash reports won't be send anymore. 

I can debug it until it gets to the point where it should send stacks. Seems like this is handled in another Thread and not even Log.i is coming through.

Also it would be nice to at least print out the list of reporters Acra uses while DEV_LOGGING is true.

**Comment by william-ferguson-au** [comment]
The Log is being generated. Just in another process.
Point your Logcat to the other Process.

**Comment by orangecoding** [comment]
Thanks mate!
