### ISSUE TITLE
How to send the logcat periodically or in real time?

### ISSUE THREAD

**Issue by NikitaFeodonit** [ACRA/acra#553]
How to send logcat periodically or in real time?

For example, user has opened a dialog with list of files from directory, list is empty, but directory contains a files. In logcat is message, which can help to understand a problem, but application has not crashed.

I think, sending of the logcat independently from crash will be very useful.

**Comment by william-ferguson-au** [comment]
ACRA was never designed to do this.
It is not a good fit for the library.
