### ISSUE TITLE
Switch between DIALOG_MODE and auto accept mode won working in 4.9.2

### ISSUE THREAD

**Issue by ghost** [ACRA/acra#554]
Hi) In ACRA 4.9.0 i was able to switch between dialog mode and autoaccept mode. But when i updated ACRA to 4.9.2 - reports are sending only in dialog mode. Setting "acra.alwaysaccept" to "true" - now not working for me( Could you help me to solve this issue?) Thanks

**Comment by F43nd1r** [comment]
For me `acra.alwaysaccept` is working correctly in 4.9.1, 4.9.2 and in the current master branch.
