### ISSUE TITLE
String instead of json object in reports

### ISSUE THREAD

**Issue by karolszklarski** [ACRA/acra#556]
I 've configured ACRA to send JSON reports via HTTP. There seems to be a problem with values that contain json objects. Sometimes I correcly get an object:

`"INITIAL_CONFIGURATION":{"locale":"pl_PL","FlipFont":0,"compatScreenHeightDp":546}`

But sometimes I get a string instead of an object:

`"INITIAL_CONFIGURATION":"locale=pl_PL\nFlipFont=0\ncompatScreenHeightDp=546\n\n"`

I suppose this happens when ACRA saves report to disk on mobile device and then after some time reads it back and tries again.

**Comment by F43nd1r** [comment]
All reports are saved to a file before they are sent, so that is not the problem

**Comment by F43nd1r** [comment]
Could not reproduce - closing
