### ISSUE TITLE
Binary file attachments

### ISSUE THREAD

**Issue by DrakkLord** [ACRA/acra#561]
Hello @F43nd1r!

I would really like to see a generic binary attachment option, I'm currently using ACRA for native crash reports via https://github.com/google/breakpad my use case is that I have 90% native code however breakpad lacks a proper ready to use architecture unlike ACRA + Acralyzer so I ended up using ACRA anyway because it's rather easy to setup and use.
Then it turned out that I can't attach the native crash dump file which is a binary, my temporary solution was to convert the binary file into Base64 and just use it as a custom field, which may require an extra step in Acralyzer to convert back and store. Using e-mail sender is out of the question for me since I'm running my code on android wear where sending an email from the device is very troublesome so automatic sending is much more preferable. What would be nice instead of this workaround is an ability to add a binary files to the crash report that are handled by all senders and Acralyzer as well, if Acralyzer would allow me to download each attached file it would be nice.

**Comment by F43nd1r** [comment]
Sending files via http is working, although not thoroughly tested. I am not working on ACRAlyzer and don't plan on doing so, as I have no real knowledge of javascript.

**Comment by DrakkLord** [comment]
Thanks, that's good news that HTTP file sending is working.
