### ISSUE TITLE
Proposal: Generate essentially duplicated code

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#563]
Whenever I add a new Configuration option to ACRA, I have to add it in three places: The annotation, the Configuration Builder, and the configuration iself. This should not be necessary, because the code for each option is essentially the same. 

So, I decided to write a code generator, which creates the builder and the configuration classes based on the annotation class. This would save work in the future, as changes and additions are way easier to realize.

This comes with a few changes: 

- `mode` was renamed to `reportingInteractionMode`, as this was the only option not consistently named.
- a few arrays are transformed to lists instead of sets, as the type is determined automatically and can't decide if duplicates should be allowed.
- the annotation processor needs to live in a separate jar. To implement this, I had to switch to a multiproject build. I chose gradle for this, as it is easier to use with android in every single aspect, but it would be possible to do this with maven.

Project can be found here https://github.com/F43nd1r/acra/tree/generator

TODO: Add upload capabilities. @william-ferguson-au do you normally upload to jcenter or directly to maven central?

**Comment by william-ferguson-au** [comment]
Maven Central
