### ISSUE TITLE
Cannot resolve method 'build()' when i try use project clone in Git

### ISSUE THREAD

**Issue by VincenzoWiman** [ACRA/acra#568]
Hi i try compile the project in git but when i try create new ACRAConfiguration with ConfigurationBuilder  i have this error

**Comment by F43nd1r** [comment]
Please post a stacktrace

**Comment by VincenzoWiman** [comment]
![schermata 2017-04-03 alle 13 39 33](https://cloud.githubusercontent.com/assets/26813554/24607677/395eb200-1873-11e7-844c-54b724148afb.png)

Error:(26, 21) error: cannot find symbol method build()

**Comment by F43nd1r** [comment]
Just a guess here: go into ConfigurationBuilder and remove the @hide
annotation from build()

Am 03.04.2017 1:41 nachm. schrieb "VincenzoWiman" <notifications@github.com

**Comment by VincenzoWiman** [comment]
Now i have this error when compile project

![schermata 2017-04-03 alle 13 48 51](https://cloud.githubusercontent.com/assets/26813554/24607914/5253cd8a-1874-11e7-9f51-7606e36c011c.png)
`Error:(230, 47) error: incompatible types: ACRAConfiguration cannot be converted to Map`

**Comment by F43nd1r** [comment]
Yes, I knew it would cause other problems. But now that I'm aware of the conflict I can fix it. Give me 5 minutes.

**Comment by F43nd1r** [comment]
Okay, it should work if you pull again now.

**Comment by VincenzoWiman** [comment]
I delete  @NoPropagation annotation but i have same error

`Error:(233, 47) error: incompatible types: ACRAConfiguration cannot be converted to Map`

**Comment by F43nd1r** [comment]
Keep the annotation. It was a naming conflict, but it is resolved now. No need to remove anything.

**Comment by VincenzoWiman** [comment]
If not remove annotation i have first error 
`Error:(28, 21) error: cannot find symbol method build()`

**Comment by F43nd1r** [comment]
Please rebuild your project.

**Comment by VincenzoWiman** [comment]
I do clear e rebuild project but have same error

**Comment by F43nd1r** [comment]
Okay, now fixed for real. Thanks for reporting, this was more serious than I initially thought.

**Comment by VincenzoWiman** [comment]
Okay now work. Thanks very much for support!
