### ISSUE TITLE
Android 7: Error message resent to backend over and over

### ISSUE THREAD

**Issue by GamersCave** [ACRA/acra#574]
As you know, Android 7 runs on a completely different framework when it comes to crash reports.

I have been running some tests on a backend, and because of that I have been causing crashes on my Android 7 tablet. When the app crashes, it keeps attempting to reopen the app, and through that repeats the crash over and over. The crash is an error I made myself(using throw new RuntimeException) and is the first thing that happens when the app stars. And because of that it repeats the crash infinitely. 

For mid-app crashes(caused by usage) that is fine. But if the crash is for an instance on boot, ACRA doesn't show the default crash dialog, and doesn't always show the Toast either. 

TL:DR; WHen a crash occurs on Android 7, ACRA doesn't behave as expected. It doesn't always show the Toast, and when the crash happens instantly, it keeps reopening the app for ever ,retriggering the error for ever. Meaning there is a chance to receive hundreds of reports for the same error.

The testing was done with ACRA 4.9.2, Android 7 on a NVIDIA Shield tablet.

Further testing shows that it only happens when the crash is instantly. This causes the bug:

```

public class Splash extends Activity {
    @Override
    public void onCreate(Bundle sis){
        super.onCreate(sis);
        throw new RuntimeException("");
 
    }
}

```

But this does not:

```

public class Splash extends Activity {
    @Override
    public void onCreate(Bundle sis){
        super.onCreate(sis);
        new Handler().postDelayed(new Runnable(){
            @Override
            public void run() {

                throw new RuntimeException("");
            }
        }, 2500);

    }
}

```

**Comment by F43nd1r** [comment]
The app should not be reopened at all, do you have a clue why that is happening?

**Comment by GamersCave** [comment]
I only know what I have said here: Looked through logs but it doesn't explain it. The error only happens when there isn't a delay(by 2.5 seconds). It may be as a result of Android OS trying to reopen because something happened by accident when it crashes that fast. But if I try the first sample(instant crash) it can send a ton of reports and doesn't stop until I close the app. This may be a bug in ACRA, an inconsistency in the ANdroid OS, or if it happens in that scenario. I raised the issue because I have no clue as to what causes it. It can be because the  app doesn't have time to completely boot ACRA, and as such it cannot create the service fully and be able to handle the crash, which causes looping(crash->close->reopen->(restart))

**Comment by GamersCave** [comment]
Update: This does not happen on Android 6.0.1. The app shows a white screen a few seconds after the crash, but it closes and shows the Toast as intended. 

Android 7 shows the option to reopen after the crash, so it is possible that ACRA doesn't override that, and when it crashes, sends the report, it automatically reopens because it is handled silently instead of through the normal system crash window. This may be solved by updating ACRA to match the newer OS(API 25) and its requirements(and I don't mean just upgrading the target API and such).

**Comment by su1216** [comment]
I am also running into this problem. acra 4.9.2 android 7.0.

**Comment by su1216** [comment]
But if I disable acra toast/notification/dialog, then acra works fine.

**Comment by su1216** [comment]
I test in another activity, app crash and restart again and again, even if I acra toast/notification/dialog

**Comment by su1216** [comment]
still happen with acra 4.10.0 android 7.1. android system auto restart my Activity again and again.  But I throw an exception for test in method onCreate, so it crash again and again. It's easy to reproduce this bug.

**Comment by F43nd1r** [comment]
Might be fixed by #591. 

Please test with 

    compile` 'com.faendir:acra:4.9.3-SNAPSHOT'

repository:

    maven {url = "https://oss.jfrog.org/libs-snapshot/" }

**Comment by su1216** [comment]
@F43nd1r 4.10.1-SNAPSHOT works fine.

**Comment by F43nd1r** [comment]
Close after merge of #591
