### ISSUE TITLE
How to get ACRA crash reports from service

### ISSUE THREAD

**Issue by Pe-te** [ACRA/acra#575]
Hi, we are not getting crash reports for a background service of a library we use.

I remember seeing something in the documentation how to wrap an own service with ACRA around the other one to get the reports, but can't find it anymore. Or maybe it was somewhere else or just a dream. ;-)

So my questions are:
- Should we be getting those crashes automatically? 
- If not, does the above idea work and is it documented anywhere?

**Comment by F43nd1r** [comment]
> Should we be getting those crashes automatically?

As far as I know, yes. 

How did you notice that there are exceptions at all?

**Comment by F43nd1r** [comment]
Please paste your application class here (minus personal/confidential lines
of course).

2017-04-13 1:30 GMT+02:00 Pe-te <notifications@github.com>:

**Comment by Pe-te** [comment]
> Please paste your application class here (minus personal/confidential lines of course).

Here we go, do you have anything special in mind?

```
package com.xxxxxxx.app;

import android.app.Application;
import android.content.Context;

import org.acra.ACRA;
import org.acra.ErrorReporter;
import org.acra.ReportingInteractionMode;
import org.acra.annotation.ReportsCrashes;

import static org.acra.ReportField.ANDROID_VERSION;
import static org.acra.ReportField.APP_VERSION_CODE;
import static org.acra.ReportField.APP_VERSION_NAME;
import static org.acra.ReportField.AVAILABLE_MEM_SIZE;
import static org.acra.ReportField.BRAND;
import static org.acra.ReportField.CUSTOM_DATA;
import static org.acra.ReportField.PACKAGE_NAME;
import static org.acra.ReportField.PHONE_MODEL;
import static org.acra.ReportField.PRODUCT;
import static org.acra.ReportField.REPORT_ID;
import static org.acra.ReportField.STACK_TRACE;
import static org.acra.ReportField.TOTAL_MEM_SIZE;
import static org.acra.ReportField.USER_APP_START_DATE;
import static org.acra.ReportField.USER_CRASH_DATE;

@ReportsCrashes(
reportType = org.acra.sender.HttpSender.Type.JSON,
customReportContent = {
		REPORT_ID,
		BRAND,
		PHONE_MODEL,
		PRODUCT,
		ANDROID_VERSION,
		APP_VERSION_CODE,
		APP_VERSION_NAME,
		PACKAGE_NAME,
		USER_APP_START_DATE,
		USER_CRASH_DATE,
		CUSTOM_DATA,
		TOTAL_MEM_SIZE,
		AVAILABLE_MEM_SIZE,
		STACK_TRACE },
mode = ReportingInteractionMode.SILENT
)
public class XxxxxxxApp extends Application {
	
	public void onCreate() {
		super.onCreate();

		ACRA.init(this);
		ACRA.getConfig().setFormUri("<our reporting url>");

		ErrorReporter errorReporter = ACRA.getErrorReporter();
		long maxMemory = Runtime.getRuntime().maxMemory();
		errorReporter.putCustomData("CUSTOM_MAX_MEMORY", Long.toString(maxMemory));
		errorReporter.setDefaultReportSenders();
	}
}
```

**Comment by F43nd1r** [comment]
Yes - Broadcast receivers are initialized before onCreate is called. Move your code to attachBaseContext.
See https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---declaratively

**Comment by Pe-te** [comment]
Wow, will have to test that in the office tomorrow, but it sounds exactly like what we need, thanks a lot!

**Comment by Pe-te** [comment]
Hi, this didn't work either, but from logcat it looks like they are using JNI and it crashes there.

> JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception 'java.security.ProviderException' thrown in unknown throw location

As far as I understand it, ACRA cannot catch crashes inside the native code without registering for signals in the native code?

We know now it's the same problem with a missing algorithm on the device, but it's scary to see that we have a lot of crashes and don't get any reports, so any more insight would be cool.

**Comment by Pe-te** [comment]
That's probably stuff for another issue once we get there, so closing here. Thank you for your help!
