### ISSUE TITLE
Enable/Disable ACRA using Build Variants

### ISSUE THREAD

**Issue by Carlos-Ot** [ACRA/acra#584]
Is there any way to add this functionality to ACRA, today I'm developing an App that uses ACRA for crash reports on my own server, while I'm developing I need to disable ACRA manually on shared preferences on my MainActivity. It will be great if there is an option to Enable/Disable ACRA according to Build Variants, like, if I'm running a debug apk the ACRA will be disabled by default.

**Comment by F43nd1r** [comment]
You can use either `sendReportsInDevMode` or, for more control wrap the `ACRA.init` call in a condition - you can get the current build variant in your `BuildConfig` class.
