### ISSUE TITLE
Change ACRA config at runtime

### ISSUE THREAD

**Issue by aloz77** [ACRA/acra#593]
What is the right method to change the ACRA config at runtime from activity? Applying ACRA.init() with the new settings doesn't seem to work. The wiki isn't clear on this point for the latest versions either.

**Comment by F43nd1r** [comment]
ACRA is designed to use exactly one configuration in a process. 
Excluded from that are the options configurable through shared preferences, see https://github.com/ACRA/acra/wiki/AdvancedUsage#letting-your-users-control-acra

**Comment by aloz77** [comment]
There is no chance to change the formUri dynamically based on the customer setting?

**Comment by F43nd1r** [comment]
You can create your own ReportSenderFactory, and use the ReportSender constructor which accepts a custom formUri.

**Comment by aloz77** [comment]
Thank you! Can I use it like this to set the formUri at crash time?

    public class MySenderfactory implements ReportSenderFactory {

        public ReportSender create(Context context, ACRAConfiguration config) {

            try {
                final ACRAConfiguration myConfig = new ConfigurationBuilder((MyApplication) (context.getApplicationContext()))
                        .setFormUri(MySettings.getCrashUrl())
                        .setReportingInteractionMode(ReportingInteractionMode.TOAST)
                        .setResToastText(R.string.crash_toast_text)
                        .build();
                return new HttpSender(myConfig, HttpSender.Method.POST, HttpSender.Type.FORM, null);
            }
            catch (Exception e) {
                e.printStackTrace();
                return new HttpSender(config, HttpSender.Method.POST, HttpSender.Type.FORM, null);
            }

        }
    }

**Comment by F43nd1r** [comment]
Should work, but it'd be easier to just call

    return new HttpSender(config, config.httpMethod(), config.reportType(), MySettings.getCrashUrl(), null);

**Comment by aloz77** [comment]
Thx! This is indeed much easier!

**Comment by aloz77** [comment]
Hmm.. Now I get org.acra.config.ACRAConfigurationException: Class MyApplication$MySenderFactory is missing a no-args Constructor. What exactly should I add?

**Comment by F43nd1r** [comment]
make MySenderFactory static. Inner classes have an implicit constructor parameter of the parent class.

**Comment by aloz77** [comment]
Thank you, no exception now. However I have trouble accessing the current DefaultSharedPreferences from the ACRA process. This is what I do:

    public ReportSender create(Context context, ACRAConfiguration config) {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
        String crashUrl = prefs.getString("crashURL", "");
        Log.d(TAG,"MyCrashSenderFactory for "+crashUrl);
        return new HttpSender(config, config.httpMethod(), config.reportType(), crashUrl, null);
    }

The crashUrl keeps always on the value as for the application start time. Do you have an idea how to access the _current_ preferences which were changed by the activities?

**Comment by aloz77** [comment]
Ok, seems to works better with

`SharedPreferences prefs = context.getSharedPreferences(context.getPackageName() + "_preferences",Context.MODE_MULTI_PROCESS);`

But is a deprecated approach :-(

**Comment by F43nd1r** [comment]
According to the docs 

> MODE_MULTI_PROCESS does not work reliably in some versions of Android, and furthermore does not provide any mechanism for reconciling concurrent modifications across processes. Applications should not attempt to use it. Instead, they should use an explicit cross-process data management approach such as ContentProvider

a `ContentProvider` is the way to go here.
