### ISSUE TITLE
sending Custom data that would potentially change during runtime

### ISSUE THREAD

**Issue by BlackITCat** [ACRA/acra#594]
I was looking for a way to generate and send CUSTOM_DATA when the exception occurs from a database read since it could have change from initialization (User settings, options)...

I didn't know how to accurately ask the question to "Google" so I thought I'd ask here

**Comment by F43nd1r** [comment]
Use a `ReportPrimer`

**Comment by BlackITCat** [comment]
I can't seem to find an example...  is it placed below the ACRA.init(this)? 

ReportPrimer reportPrimer = new ReportPrimer() {
            @Override
            public void primeReport(Context context, ReportBuilder builder) {
                getCustomFields(context,builder);
                builder.customData("","");
            }
        };

.....

  void getCustomFields(Context context,ReportBuilder builder) {

builder.customData("foo", "bar");
}

**Comment by F43nd1r** [comment]
You have to pass your custom `ReportPrimer` class in the configuration (`reportPrimerClass` in the `@ReportsCrashes` annotation)

**Comment by BlackITCat** [comment]
perfecto!
