### ISSUE TITLE
I have caught exception on start up

### ISSUE THREAD

**Issue by redradist** [ACRA/acra#599]
Hello guys,

I have faced with issue when on start up caught exception message seems like sent but actually it is not arrived to email:
10-12 22:19:53.526 22337-22364/? I/ACRA: Sending report /data/user/0/*.*/app_ACRA-approved/2017-10-12T22:19:53.149+03:00-IS_SILENT.stacktrace
10-12 22:19:53.572 22337-22364/? W/ACRAReportSender: Sending email ...
10-12 22:19:53.580 22337-22364/? W/ACRAReportSender: Email sent
10-12 22:19:53.879 22373-22373/? I/ACRA: ACRA is enabled for *.*, initializing...

I guess it is because of IS_SILENT.stacktrace ??

**Comment by F43nd1r** [comment]
No, silent or non-silent reports behave the same in regards to sending.
Your log looks like you are using an old acra version. please ensure you are using the latest version.

**Comment by redradist** [comment]
Hello F43nd1r,

I have 2-Step Verification in my GMail account. Seems like message was sent but it was rejected or ignored by GMail.

Maybe I need to use OAuth2 authentication algorithm ? Or maybe you had previously similar issue ?

**Comment by F43nd1r** [comment]
Note that ACRA's emailsender prompts the user to send the email using an email client like gmail. It does not send the email itself.
