### ISSUE TITLE
error: cannot find symbol method getNewDefaultConfig(Application)

### ISSUE THREAD

**Issue by huttarl** [ACRA/acra#602]
I'm trying to use ACRA.getNewDefaultConfig(Application) as described at https://github.com/ACRA/acra/wiki/AdvancedUsage#dynamic-configuration. But I get the above error. I see from the ChangeLog that getNewDefaultConfig() has been around since at least 4.3. And in my build.gradle, in Android Studio, I'm using this dependency:

`    compile 'ch.acra:acra:4.9.2'`

Other aspects of ACRA work fine, such as

`final ACRAConfiguration config = new ConfigurationBuilder(this);`

Apparently, somehow I'm getting an old version of ACRA, or something. Maybe it's a gradle problem but I don't know what it could be. I deleted everything ACRA-related under ~/.gradle/caches, just to force a refresh, but it didn't help.

Besides the above unfound method, these methods aren't found either:

```
error: cannot find symbol method setEmailTo(String)
error: cannot find symbol method setConfig(ACRAConfiguration)
```

coming from the lines

```
                    acraConfiguration.setEmailTo(text);
                    ACRA.setConfig(acraConfiguration);
```

Looks like the same problem, whatever it is.

Any suggestions are appreciated.

**Comment by F43nd1r** [comment]
Read carefully: those methods were available up until 4.9.0, in 4.9.2 you
have to use ConfigurationBuilder

**Comment by huttarl** [comment]
@F43nd1r Thanks for responding.

1. I encountered this error first in 4.9.0 (`compile 'ch.acra:acra:4.9.0'`), so it's apparently **not** just a post-4.9.0 problem. I only upgraded to 4.9.2 in order to try to fix the problem.

2. Here's what I read:

> Until 4.9.0 The method ACRA.getConfig() returns an ACRAConfiguration object which provides a setter for each @ReportsCrashes configuration item.

If we take this to imply that `ACRA.getConfig()` doesn't return an ACRAConfiguration object after 4.9.0, that still doesn't tell me why `ACRA.getNewDefaultConfig()` is not found, nor `acraConfiguration.setEmailTo()` or `ACRA.setConfig()`.

You seem to be suggesting that the following paragraph, "You can even use ACRA.getNewDefaultConfig(Application)...", applies only up to 4.9.0, despite being in the present tense and having no indication that it comes under the same restriction as the previous paragraph.

> Current ACRA **can be** configured using a ConfigurationBuilder which then has to be passed to ACRA.init

OK. And this has been the case since before 4.9.0; I'm doing it when the app starts. This paragraph seems to suggest that we **can** also do it dynamically throughout the app's execution. Is it supposed to mean this is now the **only** way to do dynamic configuration?

AFAIU, dynamic configuration until now has allowed the programmer to leave current settings unmodified, by using `getConfig()` to get current settings, however they may have been modified so far. But ConfigurationBuilder() doesn't seem to allow that.

The ConfigurationBuilder constructor is described as follows:

```
// Create an ConfigurationBuilder. It is prepopulated with values **specified via annotation**.
// Set any additional value of the builder and then use it to construct an ACRAConfiguration.
```

No information is given here as to how `ConfigurationBuilder(app)` can take into account existing settings other than those specified statically via annotation. Has that ability been removed, so that we now have to carry around any settings that have been applied and re-apply them whenever dynamic configuration occurs? Or maybe `ConfigurationBuilder(app)` is now also prepopulated with the current ACRA config settings? I couldn't find any documentation that says so.

**Comment by F43nd1r** [comment]
> I encountered this error first in 4.9.0 (compile 'ch.acra:acra:4.9.0'), so it's apparently not just a post-4.9.0 problem. I only upgraded to 4.9.2 in order to try to fix the problem.

4.9.0 was the first version without those methods. Sorry for the misunderstanding.

ACRA is initialized once per process, and afterwards settings can't change. The dynamic Configuration paragraph refers to configuration made before ACRA is initialized (so essentially: static configuration = compile time configuration, dynamic configuration = runtime configuration, but only before ACRA is initialized).

**Comment by huttarl** [comment]
Thanks for the clarification. I guess I misunderstood what dynamic configuration meant.

Our use case is for the app to read in a configuration file, and have one of its settings determine the email address to send ACRA reports to. If we delay ACRA configuration till after the config file is read, then any crashes that occur prior to this can't be reported. However we can live with that.

**Comment by F43nd1r** [comment]
- Revisiting this issue -
For future reference, how this usecase should be implemented:
```java
try {
    //read config file
    Coreconfiguration configuration = ... //create configuration with read values
    ACRA.init(this, configuration);
} catch (Exception e) {
    Coreconfiguration configuration = ... //create configuration with default values
    ACRA.init(this, configuration);
    ACRA.getErrorReporter().handleException(e);
}
```

However, I recommend localizing strings using androids built-in locale support instead of this approach.

**Comment by huttarl** [comment]
@F43nd1r Thanks for your response. I agree using Android's built-in support for localized strings (determined at build time) is usually the best solution. In our case we had to support multiple languages in the same build, so it wasn't an option.

**Comment by F43nd1r** [comment]
@huttarl afaik resource loading is done at runtime and does not require more than one build. https://developer.android.com/guide/topics/resources/localization.html

**Comment by huttarl** [comment]
You're right in the sense that the app can choose at run-time from sets of UI strings, which are predetermined at build time and can't be modified or created at run-time. In our use case, a requirement was to allow our app's UI strings to be customized by a client in the field, without their having to set up their own build environment or rely on our help. Admittedly it's an unusual case.

**Comment by F43nd1r** [comment]
That does indeed sound unusual. However, we try to make everything possible with ACRA. The more common something is, the less code it should need, but nothing should be downright impossible, as long as it is in the scope of the project.

Is the code above a feasible solution to your usecase?
