### ISSUE TITLE
SMTP Module?

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#604]
What was the reason for removing experimental SMTP sender with https://github.com/F43nd1r/acra/commit/e4662793e63ce55191ed0ef64d99fc6bb02a3522

Issues with OAuth?

**Comment by F43nd1r** [comment]
The current implementation requires a plain password to be compiled into the apk. I am unsure if it is a good idea to use one sending email, or if it would be better to request access to the users email. I might revisit it in the future to reimplement it using OAuth, but for now I wanted to focus on finalizing and documenting the current API. (I'd happily accept a PR if it avoids compiling a secret into the apk which allows generic access to the sender account.)

**Comment by NLLAPPS** [comment]
Thanks

**Comment by F43nd1r** [comment]
As you seem to be following the development of ACRA 5 closely, would you mind giving some feedback on the new (WIP) pages for [setup](https://github.com/F43nd1r/acra/wiki/ACRA5.0.0) and [migrating](https://github.com/F43nd1r/acra/wiki/Migrating) ?

**Comment by NLLAPPS** [comment]
They look great. As you know, I've had to ask few questions until I was able to migrate to new module based version.

It should be be quite simple for one to migrate by reading those.

Having said that I only use email module which is quite simple compared to server based reporting setups. So, it did not require too much effort to migrate.
