### ISSUE TITLE
5.0.0-rc1 mail module creates json formatted report

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#606]
As per subject. Instead of plain text report , body of the email is something like

{"USER_COMMENT":null,"PACKAGE_NAME":"com.appr","APP_VERSION_NAME":"0.3","ANDROID_VERSION":"6.0.1","BRAND":"samsung","PHONE_MODEL":"SM-N9100","CUSTOM_DATA":{},"STACK_TRACE":".....

**Comment by F43nd1r** [comment]
Because of https://github.com/F43nd1r/acra/commit/f1cad838f94af759665ef4ed3e1a5ca9192b4779, the sender now support json and uses the global default (which is json). To switch to the old format, use
```java
AcraCore(reportFormat=StringFormat.KEY_VALUE_LIST)
```

**Comment by NLLAPPS** [comment]
`reportFormat= StringFormat.KEY_VALUE_LIST,
        reportContent = {
                ReportField.USER_COMMENT,
                ReportField.PACKAGE_NAME,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.BRAND,
                ReportField.PHONE_MODEL,
                ReportField.CUSTOM_DATA,
                ReportField.STACK_TRACE,
                ReportField.LOGCAT
        }`

Generates

USER_COMMENT=null
PACKAGE_NAME=null
APP_VERSION_NAME=null
ANDROID_VERSION=null
BRAND=null
PHONE_MODEL=null
CUSTOM_DATA=null
STACK_TRACE=null
LOGCAT=null

**Comment by F43nd1r** [comment]
Ugh, maybe I should write some automated tests... anyway thanks for testing, fixed in rc2

**Comment by NLLAPPS** [comment]
👍
