### ISSUE TITLE
how to set body for post method

### ISSUE THREAD

**Issue by AAmeriyan** [ACRA/acra#608]
is it possible to set body for post method?

**Comment by F43nd1r** [comment]
you can choose between json and formdata. If you want more customization, you can write your own sender and plug it into ACRA.

**Comment by AAmeriyan** [comment]
I want to write my own Report sender and send data to my API with Retrofit I made the sender but I don't know how to attach it to ACRA?

**Comment by AAmeriyan** [comment]
what are these three dots ?? what should I put instead of them?

`        final Class<? extends ReportSenderFactory>[] myReportSenderFactoryClasses =...
        final ACRAConfiguration config = new ConfigurationBuilder(this)
                .setReportSenderFactoryClasses(myReportSenderFactoryClasses )
                .build();
        ACRA.init(this,config);`

**Comment by F43nd1r** [comment]
Define Factory:
```java
    public static class MyReportSenderFactory implements ReportSenderFactory {

        @NonNull
        @Override
        public ReportSender create(@NonNull Context context, @NonNull ACRAConfiguration config) {
            return new MyReportSender();
        }
    }
```
Register with:
```java
 final ACRAConfiguration config = new ConfigurationBuilder(this)
                .setReportSenderFactoryClasses(MyReportSenderFactory.class)
                .build();
```
or:
```java
@ReportsCrashes(reportSenderFactoryClasses = MyReportSenderFactory.class)
```
