### ISSUE TITLE
MailSenderConfiguration - setup file name

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#611]
I can enable to send a crash as an email with an attachment file like following:

     configBuilder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                    .setEnabled(true)
                    .setMailTo(app.getString(R.string.email))
                    .setReportAsFile(true);

1. Setup attachment file name

Can you add a field to set up an alternate file name for the attachment file (instead of the default "acra-report.stacktrace").

I'm using gmail in my browser very often, so I would prefer a ".txt" file extension so that I can open file in my browser directly as well (it does not allow me to do this with the ".stacktrace" extension)

2. Setup mail title

I would like to be able to setup a custom mail title instead of "com.my.app Crash Report"

**Comment by F43nd1r** [comment]
Note: 5.0.1 released today. For new options see https://www.faendir.com/wordpress/acra-javadoc/org/acra/annotation/AcraMailSender.html

**Comment by MFlisar** [comment]
Great, thanks. I would prefer support of string for the subject, because I want to add a subject like following:

    private static String getDefaultSubject(Application app) {
        return app.getString(R.string.app_name) + " - Crash Report v" + Tools.getAppVersionName(app);
    }

Which is not possible currently and as an alternative I would need to maintain the app version name in a resource.

Thanks for the great support though

**Comment by F43nd1r** [comment]
With #623 builders support both resource ids and strings. Do not expect this to get merged before 5.1.0 though, as it contains some minor breaking changes.

**Comment by MFlisar** [comment]
Thanks a lot. It's not that urgent anyways, it's just a cosmetic improvement...
