### ISSUE TITLE
Version 5.0.0 not released to maven central

### ISSUE THREAD

**Issue by koral--** [ACRA/acra#617]
At the time of writing the current version on bintray is 5.0.0 while on maven central it is still 4.9.2. Here are the badges:
[ ![Bintray](https://api.bintray.com/packages/acra/maven/ACRA/images/download.svg) ](https://bintray.com/acra/maven/ACRA/_latestVersion)
[![Maven Central](https://img.shields.io/maven-central/v/ch.acra/acra.svg)](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22ch.acra%22%20AND%20a%3A%22acra%22)

**Comment by harrywangchina** [comment]
Same issue, latest version 5.0.1 is not work too.

**Comment by F43nd1r** [comment]
Sorry, currently only the previous maintainers have access to the maven repo. I've already requested access from them. Please be patient.

**Comment by william-ferguson-au** [comment]
@KevinGaudin can you add @F43nd1r to the Sonatype ch.acra staging profile?

**Comment by GiovanniBattista** [comment]
Any news on this issue?

**Comment by F43nd1r** [comment]
Yes, we're currently waiting on [this](https://issues.sonatype.org/browse/OSSRH-38493) sonatype issue.

**Comment by F43nd1r** [comment]
5.1.1 was synced to maven central.
