### ISSUE TITLE
NullPointerException when getting plugin configuration in acra v5

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#618]
Here's my code for initialising ACRA v5 (I have my old code commented, the one that worked without problems in the past):

    public static void init(Application app, FileLoggingSetup fileLoggingSetup, int appIcon) {
        try {
            // NEW VERSION (>= v5.0.0)
            CoreConfigurationBuilder configBuilder = new CoreConfigurationBuilder(app)
                    .setEnabled(true)
                    .setReportFormat(StringFormat.KEY_VALUE_LIST)
                    .setReportContent(
                            //ReportField.USER_COMMENT,
                            ReportField.REPORT_ID,
                            ReportField.APP_VERSION_NAME,
                            ReportField.APP_VERSION_CODE,
                            ReportField.ANDROID_VERSION,
                            ReportField.PHONE_MODEL,
                            ReportField.PACKAGE_NAME,
                            ReportField.CRASH_CONFIGURATION,
                            ReportField.CUSTOM_DATA,
                            ReportField.STACK_TRACE,
                            ReportField.APPLICATION_LOG,
                            ReportField.BUILD)
                    .setAttachmentUris(Uri.parse("content://" + app.getPackageName() + ".acra/root" + FileLoggingUtil.getDefaultLogFile(fileLoggingSetup)).toString())
                    // .setBuildConfigClass(BuildConfig.class)
                    ;
            configBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
                    .setEnabled(true)
                    .setResIcon(appIcon)
                    .setResText(R.string.crash_dialog_text)
                    .setResTitle(R.string.crash_dialog_title);
            configBuilder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                    .setEnabled(true)
                    .setMailTo(app.getString(R.string.email))
                    .setReportAsFile(true);
            CoreConfiguration config = configBuilder.build();

            // OLD VERSION (< v5.0.0)
            // ACRAConfiguration config = new ConfigurationBuilder(app)
            //         .setMailTo(app.getString(R.string.email))
            //         .setReportingInteractionMode(ReportingInteractionMode.DIALOG)
            //         //.setApplicationLogFile(FileLoggingUtil.getDefaultLogFile(FILE_LOG_SETUP))
            //         //.setApplicationLogFileLines(250)
            //         .setResDialogIcon(appIcon)
            //         .setResDialogText(R.string.crash_dialog_text)
            //         .setResDialogTitle(R.string.crash_dialog_title)
            //         .setCustomReportContent(
            //                 //ReportField.USER_COMMENT,
            //                 ReportField.REPORT_ID,
            //                 ReportField.APP_VERSION_NAME,
            //                 ReportField.APP_VERSION_CODE,
            //                 ReportField.ANDROID_VERSION,
            //                 ReportField.PHONE_MODEL,
            //                 ReportField.PACKAGE_NAME,
            //                 ReportField.CRASH_CONFIGURATION,
            //                 ReportField.CUSTOM_DATA,
            //                 ReportField.STACK_TRACE,
            //                 ReportField.APPLICATION_LOG,
            //                 ReportField.BUILD)
            //        .setAttachmentUris(Uri.parse("content://" + app.getPackageName() + ".acra/root" + FileLoggingUtil.getDefaultLogFile(fileLoggingSetup)).toString())
            //        .setReportSenderFactoryClasses(EmailFileIntentSender.CustomSenderFactory.class)
            //        .build();

            ACRA.init(app, config);
            if (!ACRA.isACRASenderServiceProcess()) {
                ACRA.getErrorReporter().putCustomData("AppName", app.getString(R.string.app_name));
                ACRA.getErrorReporter().putCustomData("Developer", String.valueOf(Tools.isDeveloper(app)));
            }
        } catch (ACRAConfigurationException e) {
            L.e(e);
            ACRA.init(app);
        }
    }

**Issues**

I suddenly get a lot of  `java.lang.NullPointerException` for this code line (can't reproduce it on my phone or emulator, so it is not happening on all phones; but dev console shows me it's happening on many different phones and android versions 4.4, 5, 6, 7, 7.1):

    configBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class) // <= this line is reported as throwing the exception
                    .setEnabled(true)
                    .setResIcon(appIcon)
                    .setResText(R.string.crash_dialog_text)
                    .setResTitle(R.string.crash_dialog_title);

Any ideas why? Or what I can do to solve this?

**Comment by F43nd1r** [comment]
Do you have a stacktrace for that exception?

**Comment by MFlisar** [comment]
Sure, but I think it is not very helpful (not more than my description above):

	java.lang.RuntimeException: 
		at android.app.LoadedApk.makeApplication (LoadedApk.java:680)
		at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6473)
		at android.app.ActivityThread.access$1800 (ActivityThread.java:229)
		at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1887)
		at android.os.Handler.dispatchMessage (Handler.java:102)
		at android.os.Looper.loop (Looper.java:148)
		at android.app.ActivityThread.main (ActivityThread.java:7410)
		at java.lang.reflect.Method.invoke (Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
		at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
	Caused by: java.lang.NullPointerException: 
		at com.my.app.acra.AcraUtil.a (SourceFile:54)
		at com.my.app.application.BaseApp.b (SourceFile:123)
		at com.my.app.application.BaseApp.attachBaseContext (SourceFile:92)
		at android.app.Application.attach (Application.java:211)
		at android.app.Instrumentation.newApplication (Instrumentation.java:1021)
		at android.app.Instrumentation.newApplication (Instrumentation.java:1005)
		at android.app.LoadedApk.makeApplication (LoadedApk.java:670)

`com.my.app.acra.AcraUtil.a (SourceFile:54)` is the line I marked above in my last code block

**Comment by F43nd1r** [comment]
Very interesting. According to that stacktrace, the crash is not in the method, but the call itself. That means if the line number is accurate, either `configBuilder` or `DialogConfigurationBuilder.class` must be null. Neither is possible afaik.

**Comment by MFlisar** [comment]
Could it be an issue with proguard maybe? Maybe the `DialogConfigurationBuilder.class` is obfuscated, but still this should not matter imho in this case...

**Comment by F43nd1r** [comment]
Possibly, but unlikely. Proguard issues usually impact all devices. Also, I don't see how prouard could produce a problem here (but it's magic, so who knows).

**Comment by F43nd1r** [comment]
I can't reproduce the issue either. Which is bad, because I'm very unlikely to find the issue without trial and error. I suppose you don't have access to logcat?

**Comment by MFlisar** [comment]
I currently "solved" the issue by catching the `NullPointerException` as my app is in production only and nobody contacted me so that I could check a logcat or similar, sorry... Don't know anyone who had this issue...

**Comment by F43nd1r** [comment]
I see you have a fallback acra configuration. Could you enable ACRA_DEV_LOGGING and send that NullPointerException using your fallback? That would grant access to log and other details.

**Comment by MFlisar** [comment]
You mean like following:

	try {
		ACRA.DEV_LOGGING = true;
		ACRA.init(app, config);
		...
		// crash
		...
		ACRA.DEV_LOGGING = false; // disable it again if no crash occurred
	} catch (ACRAConfigurationException | NullPointerException e) {
		L.e(e);
		ACRA.init(app);

		// handle exception manually?
                // ACRA.getErrorReporter().handleSilentException(e); => won't work without internet connection I think????
	}

The last thing (reporting) is somehow difficult, because my app does not have internet permissions so I can't silently report an issue, can I? I can't silently report an issue to the google dev console without crashing my app, can I?

**Comment by F43nd1r** [comment]
Without internet permission, only mail will work, which can't be completely silent. (you can still call handleSilentException, which will suppress all interactions, but the sender isn't affected by the silent flag.)

**Comment by MFlisar** [comment]
So I will do following in cas eof an exception:

	ACRA.init(app);
	// report this issue only once, we don't want to disturb the user more often
	if (!preferences.acraExceptionHappened()) {
                // this would not use the email reporter in this case
		// ACRA.getErrorReporter().handleSilentException(e); 
               // make an intent, add the exception stacktrace and send it per mail
               // ....
		preferences.acraExceptionHappened(true);
	}
  
Anything else that is interesting other than the stacktrace with `ACRA.DEV_LOGGING = true`?

**Comment by greenscreens-io** [comment]
Hi,

I have the same problem, maybe this will help...

Annotation configuration 

```
@AcraDialog(
        resText = R.string.crash_dialog_text,
        resTheme = R.style.AppTheme_Dialog,
        resIcon = android.R.drawable.ic_dialog_info,
        resTitle = R.string.crash_dialog_title,
        resCommentPrompt = R.string.crash_dialog_comment_prompt
)
public class App extends Application {
 ...
}
```

and crash log

``` 
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference 
    at org.acra.config.NotificationConfigurationBuilder.resTitle(NotificationConfigurationBuilder.java:132)
    at org.acra.config.NotificationConfiguration.<init>(NotificationConfiguration.java:72)
    at org.acra.config.NotificationConfigurationBuilder.build(NotificationConfigurationBuilder.java:418)
    at org.acra.config.NotificationConfigurationBuilder.build(NotificationConfigurationBuilder.java:23)
    at org.acra.config.BaseCoreConfigurationBuilder.preBuild(BaseCoreConfigurationBuilder.java:71)
    at org.acra.config.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:689)
    at org.acra.ACRA.init(ACRA.java:162)
    at org.acra.ACRA.init(ACRA.java:146)
    at org.acra.ACRA.init(ACRA.java:129)
```

**Comment by F43nd1r** [comment]
@MFlisar DEV_LOGGING incresed logcat output. Stacktraces will be unchanged.

@greenscreens-io that issue is unrelated, please open a new bug.

**Comment by MFlisar** [comment]
Here's the result using v5.0.1. I don't see any additional informations that looks helpful though...

**Code**

    public static boolean init(Application app, FileLoggingSetup fileLoggingSetup, int appIcon) {
        ACRA.DEV_LOGGING = true;
        try {
            CoreConfigurationBuilder configBuilder = new CoreConfigurationBuilder(app)
                    .setEnabled(true)
                    .setReportFormat(StringFormat.KEY_VALUE_LIST)
                    .setReportContent(
                            //ReportField.USER_COMMENT,
                            ReportField.REPORT_ID,
                            ReportField.APP_VERSION_NAME,
                            ReportField.APP_VERSION_CODE,
                            ReportField.ANDROID_VERSION,
                            ReportField.PHONE_MODEL,
                            ReportField.PACKAGE_NAME,
                            ReportField.CRASH_CONFIGURATION,
                            ReportField.CUSTOM_DATA,
                            ReportField.STACK_TRACE,
                            ReportField.APPLICATION_LOG,
                            ReportField.BUILD)
                    .setAttachmentUris(Uri.parse("content://" + app.getPackageName() + ".acra/root" + FileLoggingUtil.getDefaultLogFile(fileLoggingSetup)).toString())
                    ;
            configBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
                    .setEnabled(true)
                    .setResIcon(appIcon)
                    .setResText(R.string.crash_dialog_text)
                    .setResTitle(R.string.crash_dialog_title);
            configBuilder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                    .setEnabled(true)
                    .setMailTo(app.getString(R.string.email))
                    .setReportFileName(getDefaultReportFileName())
                    //.setSubject(getDefaultSubject(app))
                    .setReportAsFile(true);
            CoreConfiguration config = configBuilder.build();

            ACRA.init(app, config);
            if (!ACRA.isACRASenderServiceProcess()) {
                ACRA.getErrorReporter().putCustomData("AppName", app.getString(R.string.app_name));
                ACRA.getErrorReporter().putCustomData("Developer", String.valueOf(Tools.isDeveloper(app)));
            }
            ACRA.DEV_LOGGING = false;
            return true;
        } catch (ACRAConfigurationException | NullPointerException e) {
            L.e(e);
            ACRA.init(app);

			try {
				String content = ExceptionUtil.getStackTrace(e);
				File outputDir = app.getCacheDir();
				File acraFile = File.createTempFile("acra", ".txt", outputDir);
				acraFile = FileUtil.createFile(acraFile, content);

				FeedbackManager.newBuilder(app)
						.addFile(new File(FileLoggingUtil.getDefaultLogFile(fileLoggingSetup)))
						.addFile(acraFile)
						.startNotification(
								app,
								"Exception Report",
								"Rare error found",
								"Please report this error by clicking this notification, thanks",
								appIcon,
								REPORT_ACRA_ERROR_NOTIFICATION_CHANNEL_ID,
								9999);

			} catch (IOException e1) {
				L.e(e1);
			}
			ACRA.DEV_LOGGING = false;
        }
        return false;
    }


**Stacktrace**

	java.lang.NullPointerException: Attempt to invoke virtual method 'org.acra.config.DialogConfigurationBuilder org.acra.config.DialogConfigurationBuilder.a(boolean)' on a null object reference
		at com.my.app.acra.AcraUtil.a(Unknown Source)
		at com.my.app.application.BaseApp.a(Unknown Source)
		at com.my.app.app.MainApp.e(Unknown Source)
		at com.my.app.application.BaseApp.onCreate(Unknown Source)
		at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4786)
		at android.app.ActivityThread.access$1600(ActivityThread.java:165)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:150)
		at android.app.ActivityThread.main(ActivityThread.java:5546)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

	
**Log**

	2018-01-11 14:50:35,231	[AcraUtil:-1 a]: java.lang.NullPointerException: Attempt to invoke virtual method 'org.acra.config.DialogConfigurationBuilder org.acra.config.DialogConfigurationBuilder.a(boolean)' on a null object reference
		at com.my.app.acra.AcraUtil.a(Unknown Source)
		at com.my.app.application.BaseApp.a(Unknown Source)
		at com.my.app.app.MainApp.e(Unknown Source)
		at com.my.app.application.BaseApp.onCreate(Unknown Source)
		at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4786)
		at android.app.ActivityThread.access$1600(ActivityThread.java:165)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:150)
		at android.app.ActivityThread.main(ActivityThread.java:5546)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

	2018-01-11 14:50:35,279	[AcraUtil:-1 b]: ACRA: Using default Report Fields
	2018-01-11 14:50:35,290	[AcraUtil:-1 b]: ACRA: ACRA processName='com.my.app'
	2018-01-11 14:50:35,304	[AcraUtil:-1 c]: ACRA: Migrating unsent ACRA reports to new file locations
	2018-01-11 14:50:35,308	[AcraUtil:-1 b]: ACRA: Looking for error files in /data/user/0/com.my.app/files
	2018-01-11 14:50:35,313	[AcraUtil:-1 c]: ACRA: Migrated 0 unsent reports
	2018-01-11 14:50:35,324	[AcraUtil:-1 c]: ACRA: Converting unsent ACRA reports to json
	2018-01-11 14:50:35,342	[AcraUtil:-1 c]: ACRA: Converted 0 unsent reports
	2018-01-11 14:50:35,347	[AcraUtil:-1 c]: ACRA: ACRA is enabled for com.my.app, initializing...

**Comment by F43nd1r** [comment]
Missing logs can also indicate something. Specifically, there should be a log saying 
`"Discovered and loaded plugin of type DialogConfiguration"` (or `"Unable to load ConfigurationBuilderFactory"`). Please confirm you are seeing that line when running on an emulator.

Sidenote: I'm 99% sure your initial line marking was one off. The next line having a NullPointer makes way more sense.

**Comment by MFlisar** [comment]
I'm using a custom logger like this (before creating the config):

    ACRA.setLog(new ACRALog() {
            @Override
            public int v(String tag, String msg) {
                L.v("%s: %s", tag, msg);
                return 0;
            }

            @Override
            public int v(String tag, String msg, Throwable tr) {
                L.v("%s: %s (%s)", tag, msg, tr.getMessage());
                return 0;
            }

            @Override
            public int d(String tag, String msg) {
                L.d("%s: %s", tag, msg);
                return 0;
            }

            @Override
            public int d(String tag, String msg, Throwable tr) {
                L.d("%s: %s (%s)", tag, msg, tr.getMessage());
                return 0;
            }

            @Override
            public int i(String tag, String msg) {
                L.i("%s: %s", tag, msg);
                return 0;
            }

            @Override
            public int i(String tag, String msg, Throwable tr) {
                L.i("%s: %s (%s)", tag, msg, tr.getMessage());
                return 0;
            }

            @Override
            public int w(String tag, String msg) {
                L.w("%s: %s", tag, msg);
                return 0;
            }

            @Override
            public int w(String tag, String msg, Throwable tr) {
                L.w("%s: %s (%s)", tag, msg, tr.getMessage());
                return 0;
            }

            @Override
            public int w(String tag, Throwable tr) {
                L.w("%s: %s", tag, tr.getMessage());
                return 0;
            }

            @Override
            public int e(String tag, String msg) {
                L.e("%s: %s", tag, msg);
                return 0;
            }

            @Override
            public int e(String tag, String msg, Throwable tr) {
                L.e(tr, "%s: %s", tag, msg);
                return 0;
            }

            @Nullable
            @Override
            public String getStackTraceString(Throwable tr) {
                return ExceptionUtil.getStackTrace(tr);
            }
        });

When I start my app on my phone in debug, I don't see any ACRA logs but one single information:

    ACRA: ACRA is enabled for commy.app.debug, initializing...

At sidenote: I'm quite sure you're right, that's why I posted the full code block in my question because the line number did not make sense for me either.

**Comment by F43nd1r** [comment]
You might have to enable debug level logging in your custom logging
solution too.

**Comment by F43nd1r** [comment]
Yes, I'm aware that this message is logged at info. That is why I asked
about debug level. There should be several additional messages with debug
enabled.

On 12 Jan 2018 19:28, "MFlisar" <notifications@github.com> wrote:

This line ACRA: ACRA is enabled for commy.app.debug, initializing... is
logged at info level, so everything is logged correctly, I'm not disabling
any logging in my logger, as I normally just use debug level mostly...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ACRA/acra/issues/618#issuecomment-357311111>, or mute
the thread

**Comment by F43nd1r** [comment]
Btw, I coudn't test this, but I think 5.1 series has this one fixed.

**Comment by MFlisar** [comment]
After getting a lot of reports with no new info (just the few lines of logs I wrote above already) I recently disabled the notification...

Will activate it again in my next update and will report you if the issue is solved

**Comment by F43nd1r** [comment]
I'm assuming this issue is solved. Please reopen if it is still relevant to you.
