### ISSUE TITLE
invalid 'this' ptr 0x1 ni HttpSenderConfigurationBuilder (KitKat)

### ISSUE THREAD

**Issue by greenscreens-io** [ACRA/acra#625]
Hi, 

On Android 4.4.4. Acra 5.0.1 crash and application won't start. 

Update: (only on dalvikvm, on art it is fine)

I can see only this short message in logs...

```
01-17 04:05:12.196 1656-1656/io.greenscreens.terminal E/dalvikvm: HEY: invalid 'this' ptr 0x1 (Lorg/acra/config/HttpSenderConfigurationBuilder;.enabled ()Z)
01-17 04:05:12.196 1656-1656/io.greenscreens.terminal E/dalvikvm: VM aborting
01-17 04:05:12.200 1656-1656/io.greenscreens.terminal A/libc: Fatal signal 6 (SIGABRT) at 0x00000678 (code=-6), thread 1656 (creens.terminal)
```

**Comment by F43nd1r** [comment]
Could not reproduce on an Android Kitkat emulator. No idea what would cause something like that.

**Comment by greenscreens-io** [comment]
I've figure it out!!

One of app modules use Acra 5.0.0 instead 5.0.1. 
Looks like compiling created some class incompatibility.

After fixing that, app works fine.
Still, I don't understand why error is shown only on Dalvik.
