### ISSUE TITLE
Registering custom ReportInteraction?

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ACRA/acra#632]
I want to replace the built-in `ToastInteraction` with a more fancy and nice-looking toast. However, I wasn't able to find any way to register a custom `ReportInteraction`. Custom report senders, however, can be registered using `reportSenderFactoryClasses`. 

Am I missing something, or is it a missing API case?

**Comment by F43nd1r** [comment]
ReportInteractions are loaded using `ServiceLoader`.
Add
```groovy
compileOnly "com.google.auto.service:auto-service:1.0-rc4"
```
and
```java
@AutoService(ReportInteraction.class)
public class MyCustomInteraction extends ReportInteraction {
...
}
```

**Comment by F43nd1r** [comment]
Note to self: Document this in the wiki.

**Comment by ZimM-LostPolygon** [comment]
@F43nd1r 
Got it. But is there any reason why report senders can be set without `ServiceLoader`, but report interactors *have* to be registered using `ServiceLoader`?  It seems like adding `auto-service` also adds Guava and some other dependencies, which is something I would like to avoid.

Also, 
```
compileOnly "com.google.auto.service:auto-service:1.0-rc4"
```
Didin't work for me. This did, however:
```
    compile "com.google.auto.service:auto-service:1.0-rc4"
    annotationProcessor "com.google.auto.service:auto-service:1.0-rc4"
```


`reportSenderFactoryClasses` is **so** much easier and straightfoward.

**Comment by F43nd1r** [comment]
auto-service just generates files. You can add those files manually, see https://developer.android.com/reference/java/util/ServiceLoader.html

Also, compileOnly doesn't add the dependency to your apk, that is why it is preferred over compile. Update gradle to use it.

**Comment by ZimM-LostPolygon** [comment]
Thanks for the pointer about adding files manually!

As for compileOnly - you are right, but I use Dagger 2 in my app, and when
Dagger 2 sees Guava in the classpath, it generates code with Guava types
that are more efficient, only to crash spectacularly with
NoClassDefFoundException since Guava isn't actually there. So I either have
to use compile or not use auto-service.

On Feb 3, 2018 21:40, "F43nd1r" <notifications@github.com> wrote:

auto-service just generates files. You can add those files manually, see
https://developer.android.com/reference/java/util/ServiceLoader.html

Also, compileOnly doesn't add the dependency to your apk, that is why it is
preferred over compile. Update gradle to use it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ACRA/acra/issues/632#issuecomment-362852526>, or mute
the thread

**Comment by F43nd1r** [comment]
Now documented in https://github.com/ACRA/acra/wiki/Custom-Extensions - closing
