### ISSUE TITLE
Running code before app is killed

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ACRA/acra#633]
I want to restart my app after a crash. However, I can't find any good way to execute some piece of code before app is killed. I thought about using `ReportingAdministrator` or `ReportInteractionExecutor`, but I am using `AcraLimiter`, so it's not going to work. If `LimitingReportAdministrator` detects that report must not be collected or sent, my `ReportingAdministrator` will never run.

Is there any workaround?

**Comment by ZimM-LostPolygon** [comment]
Proposal: `ReportingAdministrator.notifyReportDropped` should be called on all enabled ReportingAdministrator's, not just the blocking one.

**Comment by F43nd1r** [comment]
You can use shouldKillApplication in 5.1.0. Also, any ReportingAdministrator method is guaranteed to be called on all ReportingAdministrators.

**Comment by ZimM-LostPolygon** [comment]
That's exactly what I needed, and it works great. Thank you!
