### ISSUE TITLE
undocumented change - lazy string loading has side effect

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#643]
Following is one change I saw by accident:

	configBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
		.setEnabled(true)
		.setResIcon(appIcon)
		.setResText(R.string.crash_dialog_text)
		.setResTitle(R.string.crash_dialog_title)
		// following is necessary in v5.1.1 but was not in v5.0.2
		.setResPositiveButtonText(android.R.string.ok)
		.setResNegativeButtonText(android.R.string.cancel)
        ;

Seems like some default values are not set anymore

**Comment by F43nd1r** [comment]
Only happens when the annotation is not present. So, as a workaround add `@AcraDialog` (with no configuration) to your Application class. Will be fixed in next version.
