### ISSUE TITLE
Couldn't find ConfigurationBuilder HttpSenderConfigurationBuilder

### ISSUE THREAD

**Issue by jpelczar** [ACRA/acra#646]
Hi,
On some builds I have problem with Http sender configuration plugin, I get:
`W/ACRA: Couldn't find ConfigurationBuilder HttpSenderConfigurationBuilder. ALL CALLS TO IT WILL BE IGNORED!`

I use version 5.1.0 from bintray, use multidex but acra is initialized after multidex install and also proguard contains rules for `org.acra.** {*;}`. Tested on Android 6.0.1 and 8.0.0.

In `build.gradle` I have only `implementation "ch.acra:acra-http:5.1.0"`

Configuration:
```
final CoreConfigurationBuilder coreConfigurationBuilder = new CoreConfigurationBuilder(app)
				.setAlsoReportToAndroidFramework(true)
				.setReportFormat(StringFormat.JSON)
				.setReportContent(
						ReportField.APPLICATION_LOG,
						ReportField.ANDROID_VERSION,
						ReportField.APP_VERSION_CODE,
						ReportField.APP_VERSION_NAME,
						ReportField.AVAILABLE_MEM_SIZE,
						ReportField.BRAND,
						ReportField.BUILD,
						ReportField.CRASH_CONFIGURATION,
						ReportField.CUSTOM_DATA,
						ReportField.DEVICE_FEATURES,
						ReportField.DISPLAY,
						ReportField.DUMPSYS_MEMINFO,
						ReportField.ENVIRONMENT,
						ReportField.FILE_PATH,
						ReportField.INITIAL_CONFIGURATION,
						ReportField.INSTALLATION_ID,
						ReportField.LOGCAT,
						ReportField.PACKAGE_NAME,
						ReportField.PHONE_MODEL,
						ReportField.PRODUCT,
						ReportField.REPORT_ID,
						ReportField.SHARED_PREFERENCES,
						ReportField.STACK_TRACE,
						ReportField.TOTAL_MEM_SIZE,
						ReportField.USER_APP_START_DATE,
						ReportField.USER_CRASH_DATE,
						ReportField.USER_EMAIL);

		final File externalStorage = Environment.getExternalStorageDirectory();
		if (externalStorage != null) {
			coreConfigurationBuilder.setApplicationLogFile(new File(externalStorage, DebugLog
					.getLogFilename()).getAbsolutePath());
			coreConfigurationBuilder.setApplicationLogFileLines(LOG_FILE_LINES);
		}

		coreConfigurationBuilder
				.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
				.setUri(ACRA_FORM_URI)
				.setBasicAuthLogin(ACRA_URI_BASIC_AUTH_LOGIN)
				.setBasicAuthPassword(ACRA_FORM_URI_BASIC_AUTH_PASSWORD)
				.setHttpMethod(HttpSender.Method.PUT)
				.setEnabled(true);

		ACRA.init(app, coreConfigurationBuilder);
```

Is exist any workaround for this issue? Or what is the root cause of that?

In addition, It appears only on builds from CI, local gradle builds work fine (they use same tasks and commands). It looks like problem with apk but decompiled apk contains `HttpSenderConfigurationBuilder`.

Previously, I used version 4.8.5 and it worked, but there were crashes on Oreo.

**Comment by F43nd1r** [comment]
Please check if the apk contains exactly one file named `org.acra.config.ConfigurationBuilderFactory` in META-INF/services, which contains a line `org.acra.config.HttpSenderConfigurationBuilderFactory`

**Comment by F43nd1r** [comment]
Also set `ACRA.DEV_LOGGING=true` before ACRA.init to see what is going on.
Especially, there should be either "Discovered and loaded plugin of type HttpSenderConfiguration" or "Unable to load ConfigurationBuilderFactory" in the logs.

**Comment by jpelczar** [comment]
At this point, it looks like a CI configuration problem, we've done `zip -d $ FILENAME META-INF / *`. In this case, this ticket looks invalid. Your comment showed us the right way to analyze what was wrong. Thank you!

**Comment by F43nd1r** [comment]
I'm wondering if there should be a warning for this. Was this caused by your specific configuration, or could this happen in any CI build?

**Comment by jpelczar** [comment]
It was cause by our specific configuration. After gradle task CI executed `zip -d $ FILENAME META-INF/*`. Today I added exclude for `services` and ACRA start working again.
