### ISSUE TITLE
[new feature] Custom validation in AcraLimiter

### ISSUE THREAD

**Issue by chpasha** [ACRA/acra#648]
Hello guys, 

nice idea with having AcraLimiter. I still miss one feature though - in ACRA 4 I had my own ReportSenderFactory generating custom HttpSender class which was omitting some Exceptions that were not real bugs and we didn't need them to be reported. Now AcraLimiter could actually do the job, but it lacks the easy possibility to extend the functionality (is it possible anyhow ?). In my opinion it would be great to have another field in AcraLimiter annotation of type Class<? extends Predicate> predicate() 
where Predicate is an interface with signature  boolean evaluate(CrashReportData data)
so that every report which fails evaluation would not be send. Of course one would need one default implementation which just returns true.
What do you think

**Comment by chpasha** [comment]
I've read about custom extensions - this is surely an option

**Comment by F43nd1r** [comment]
This is a job for a custom `ReportingAdministrator`. 
Basically `shouldStartCollecting` has access to the exception, and is the place I would choose for such a decision. But if you rely on `CrashReportData`, you can use `shouldSendReport`.

Note that you can use this in addition to the Limiter, and if either returns false, report processing will stop.

I would argue againt a predicate conifguration option, as we'd have to have one for every method of ReportingAdministrator.
