### ISSUE TITLE
ACRA ver. 5 JobService NotFound

### ISSUE THREAD

**Issue by redradist** [ACRA/acra#649]
I have updated library to newer version and got the following exception when **ACRA** tries to call **JobService**:

I/System.out: Calling by::className:org.acra.collector.MemoryInfoCollector  MethodName:collectMemInfo
I/art: Do partial code cache collection, code=243KB, data=191KB
I/art: After code cache collection, code=236KB, data=187KB
I/art: Increasing code cache capacity to 1024KB
I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
I/art:     at void android.support.v4.app.JobIntentService.enqueueWork(android.content.Context, java.lang.Class, int, android.content.Intent) (JobIntentService.java:500)
I/art:     at void org.acra.sender.SenderServiceStarter.startService(boolean, boolean) (SenderServiceStarter.java:54)
I/art:     at void org.acra.builder.ReportExecutor.startSendingReports(boolean) (ReportExecutor.java:239)
I/art:     at void org.acra.builder.ReportExecutor.execute(org.acra.builder.ReportBuilder) (ReportExecutor.java:174)
I/art:     at void org.acra.builder.ReportBuilder.build(org.acra.builder.ReportExecutor) (ReportBuilder.java:183)
I/art:     at void org.acra.reporter.ErrorReporterImpl.uncaughtException(java.lang.Thread, java.lang.Throwable) (ErrorReporterImpl.java:148)
I/art:     at void java.lang.ThreadGroup.uncaughtException(java.lang.Thread, java.lang.Throwable) (ThreadGroup.java:1068)
I/art:     at void java.lang.ThreadGroup.uncaughtException(java.lang.Thread, java.lang.Throwable) (ThreadGroup.java:1063)
I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.job.JobServiceEngine" on path: DexPathList[[zip file "/data/app/<my_package>-1/base.apk", zip file "/data/app/<my_package>-1/split_lib_dependencies_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_0_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_1_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_2_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_3_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_4_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_5_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_6_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_7_apk.apk", zip file "/data/app/<my_package>-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.
I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at void android.support.v4.app.JobIntentService.enqueueWork(android.content.Context, java.lang.Class, int, android.content.Intent) (JobIntentService.java:500)
I/art:     at void org.acra.sender.SenderServiceStarter.startService(boolean, boolean) (SenderServiceStarter.java:54)
I/art:     at void org.acra.builder.ReportExecutor.startSendingReports(boolean) (ReportExecutor.java:239)
I/art:     at void org.acra.builder.ReportExecutor.execute(org.acra.builder.ReportBuilder) (ReportExecutor.java:174)
I/art:     at void org.acra.builder.ReportBuilder.build(org.acra.builder.ReportExecutor) (ReportBuilder.java:183)
I/art:     at void org.acra.reporter.ErrorReporterImpl.uncaughtException(java.lang.Thread, java.lang.Throwable) (ErrorReporterImpl.java:148)
I/art:     at void java.lang.ThreadGroup.uncaughtException(java.lang.Thread, java.lang.Throwable) (ThreadGroup.java:1068)
I/art:     at void java.lang.ThreadGroup.uncaughtException(java.lang.Thread, java.lang.Throwable) (ThreadGroup.java:1063)
W/ACRA: Warning: Acra may behave differently with a debugger attached
I/art: Starting a blocking GC HomogeneousSpaceCompact

Did anybody have such issue or how to fix it ???

**Comment by F43nd1r** [comment]
You're probably missing the support-v4 dependency, or using an old version of it.

**Comment by redradist** [comment]
I have the following dependencies:

    compile('com.android.support:appcompat-v7:+') {
        exclude module: 'httpmime'
    }
    compile 'com.android.support:design:+'
    compile 'com.android.support:support-v4:+'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:+'
    compile 'com.android.support:gridlayout-v7:+'

It is the latest dependencies for android support library. I do not think it is an issue in dependencies

**Comment by F43nd1r** [comment]
Try to disable instant run, clean and recompile your project etc.

**Comment by redradist** [comment]
What do you mean instant run ?
I have been cleaning and recompiling it every time, but it does not help !!

**Comment by F43nd1r** [comment]
It looks like you are trying to run an app compiled for Oreo on an pre-oreo device, which might've been an instant run issue. I've never seen this issue and I can't reproduce it, so I can only guess.

**Comment by redradist** [comment]
Seems like you are right. I have in my build-gradle:

```
compileSdkVersion **27**
    buildToolsVersion '**27.0.2**'
    defaultConfig {
        applicationId "<my_app>"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }
```

But if I put the following:

```
compileSdkVersion **25**
    buildToolsVersion '**26.0.2**'
    defaultConfig {
        applicationId "<my_app>"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }
```

Then we have:
/home/redra/.gradle/caches/transforms-1/files-1.1/design-26.0.2.aar/d2c64c9a4269471a0fcd67f3f95fabef/res/values-v26/values-v26.xml
Error:(3, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/home/redra/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/38c728977cff4a64b29de4eca1a9c62e/res/values-v26/values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/home/redra/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/38c728977cff4a64b29de4eca1a9c62e/res/values/values.xml
Error:(252, 5) error: resource android:attr/keyboardNavigationCluster not found.
Error:(252, 5) error: resource android:attr/fontStyle not found.
Error:(252, 5) error: resource android:attr/font not found.
Error:(252, 5) error: resource android:attr/fontWeight not found.
/home/redra/Projects/NewToggleTimer/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:(18) style attribute 'android:attr/keyboardNavigationCluster' not found.
/home/redra/Projects/NewToggleTimer/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Error:(212) resource android:attr/keyboardNavigationCluster not found.
Error:(429) resource android:attr/fontStyle not found.
Error:(429) resource android:attr/font not found.
Error:(429) resource android:attr/fontWeight not found.

**Comment by F43nd1r** [comment]
I recommend:
 - set compile & target to 27
 - remove buildtoolsversion line
 - also use version 27 for dependencies:
```
compile 'com.android.support:design:27.+'
compile 'com.android.support:support-v4:27.+'
compile 'com.android.support:recyclerview-v7:27.+'
compile 'com.android.support:cardview-v7:27.+'
compile 'com.android.support:gridlayout-v7:27.+'
```

**Comment by redradist** [comment]
I did as you suggested, but still failed ... I am testing on Android 7 Phone

**Comment by F43nd1r** [comment]
can you send me your project, so I can test myself?

**Comment by redradist** [comment]
Sorry, I cannot it is private project ... I use in my project ProGuard, maybe it is some how relates to ?

**Comment by F43nd1r** [comment]
Can you create a minimal example project showcasing the bug?
Proguard can always be an issue, turn it off to test for that.

**Comment by redradist** [comment]
@F43nd1r I have created a test application where it is reproducible
[TestACRA.tar.gz](https://github.com/ACRA/acra/files/1778832/TestACRA.tar.gz)

**Comment by F43nd1r** [comment]
I was able to eliminate the problem by disabling instant run.

**Comment by redradist** [comment]
@F43nd1r Big thanks it is helped !! I do not completely understand why it helps
Do you know the reason that helped ?

**Comment by F43nd1r** [comment]
Only on a very abstract level: ClassNotFoundException is thrown by classloaders. Instant run uses a custom classloader to improve apk deployment. That classloader was probably throwing this exception.
