### ISSUE TITLE
Trigger sending of unsent reports

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ACRA/acra#650]
Is there a way to trigger sending of unsent reports programmatically? From what I gather, an attempt to send unsent report is only made when a crash occurs.

**Comment by F43nd1r** [comment]
There is an additional attempt at every application start. 

To trigger it yourself, call

```java
final SenderServiceStarter starter = new SenderServiceStarter(context, config);
starter.startService(false, false);
```

**Comment by ZimM-LostPolygon** [comment]
Thank you. Related: is there a way to check if there are any unsent reports? Sounds like a waste to start the `SenderService` even if there is no need for that.

**Comment by F43nd1r** [comment]
Check [ApplicationStartupProcessor](https://github.com/ACRA/acra/blob/master/acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java) for internals. 
However, be advised that those classes inluding SenderServiceStarter are not considered part of the public API and may change in upcoming versions without special notice.
