### ISSUE TITLE
ACRA fails when android:sharedUserId is set

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ACRA/acra#656]
ACRA fails to detect any components if `android:sharedUserId` is set. This is because in that case, `Thread.currentThread().getContextClassLoader()` is replaced with a dummy, and `ServiceLoader` fails to locate the resources. The fix is to replace all code like
```
ServiceLoader.load(ReportSenderFactory.class)
```
with
```
// Really any class from current context can be used instead of getClass()
ServiceLoader.load(ReportSenderFactory.class, getClass().getClassLoader()) 
```

Additional info:
https://github.com/grpc/grpc-java/issues/1272
https://stackoverflow.com/questions/13407006/android-class-loader-may-fail-for-processes-that-host-multiple-applications

**Comment by F43nd1r** [comment]
Thanks for pointing this out.
