### ISSUE TITLE
Restart app after crash

### ISSUE THREAD

**Issue by ChrisB85** [ACRA/acra#660]
Hi,

first of all - thanks for great job you're doing! I have just upgraded ACRA from version 4 to 5 and i have noticed that app is not restarting after crash - like it was in version 4. I cannot find nothing about this behaviour in docs (or maye i'm missing something?). Is it still possible to auto restart app after crash?

**Comment by F43nd1r** [comment]
ACRA was never restarting your app. Android may do that for you. However, this shouldn't change when upgrading, because the relevant code wasn't modified at all. Which ACRA 4 Version were you using?

**Comment by ChrisB85** [comment]
That's odd, becouse i'm sure that app was auto-restarting before upgrade and not only on my device. I was using 4.9.2 version.

**Comment by F43nd1r** [comment]
According to [this](https://stackoverflow.com/a/13173279/4388512), Android was only restarting apps up until Android 4, so we cannot make use of that. 
I'm currently evaluating a solution involving AlarmManager.

**Comment by hannesa2** [comment]
`AlarmManager` is not a good idea, because all apps will get a lower Google ranking because of higher energy consumption.
I recommend using https://developer.android.com/reference/android/app/job/JobScheduler or better for devices < api21 https://github.com/firebase/firebase-jobdispatcher-android

**Comment by F43nd1r** [comment]
using firebase is not an option. Acra is designed to be used on devices without play services.
However, the next version will include a plugin which uses [Evernotes android-job](https://github.com/evernote/android-job). That plugin will also have an option to restart the app.

The library uses JobScheduler and jobdispatcher if available and falls back to AlarmManager.

**Comment by mikehardy** [comment]
Maybe worth noting that Evernotes android-job is saying they will self-deprecate and you should move to WorkManager (which appears to also work with the design constraint of working on non-Play devices, based on a quick read). You probably already saw that but I thought I'd note it 
https://github.com/evernote/android-job#workmanager
https://developer.android.com/topic/libraries/architecture/workmanager
