### ISSUE TITLE
Custom BaseCrashReportDialog  dialog show twice

### ISSUE THREAD

**Issue by wshfzhwj** [ACRA/acra#668]
Hi ~
        When I want to use a custom crash dialog via extends BaseCrashReportDialog,  my CustomCrashReportDialog show twice . Please tell what should I do。 CustomCrashReportDialog is Copy from CrashReportDialog。 Thank you！

@AcraCore(reportFormat= StringFormat.JSON)
@AcraHttpSender(uri = BuildConfig.ACRA_URL,
        httpMethod = HttpSender.Method.PUT,
        basicAuthLogin = BuildConfig.ACRA_USER,
        basicAuthPassword = BuildConfig.ACRA_PWD)
@AcraDialog(resText = R.string.crash_toast_text,
        resCommentPrompt = R.string.dialog_comment,
        reportDialogClass = CustomCrashReportDialog.class,
        resTheme = android.R.style.Theme_Holo_Light_Dialog)

**Comment by F43nd1r** [comment]
Add `android:process=":acra"` to your `CustomCrashReportDialog`s manifest entry.

**Comment by F43nd1r** [comment]
Now documented in https://github.com/ACRA/acra/wiki/Interactions#dialog
