### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by WebSabaki** [ACRA/acra#669]
Good afternoon.

Regarding GDPR compliance, I think that ACRA could play a good role here.

However, would it be possible to export easily user data?

AFAIK, there is a unique installation ID that can be use track user. is that correct?
In that case, this is good as there is a way to kind of easily retrieve user data but this makes it also mandatory, if a user request it.

Questions are thus : 
a) how to get this installation ID on the app side so that user can submit it with there request
b) is there an easy way to export user record and delete them on backend side (such as acralyzer) ?

**Comment by jngr** [comment]
A couple of (unofficial) thoughts that may partially answer your questions:

a) I believe the APPLICATION_ID is stored in a file named ACRA-INSTALLATION in your apps local storage. You can probably find a way to retrieve it from there.
b) A question for Acralyzer or other backend you are using?

It is probably extremely difficult if not impossible to trace a crash report back to an individual user based on the random installation id generated by ACRA -- if you configure ACRA such that you don't collect any personal or personally identifiable data along with it. The one thing you may want to do in Acralyzer or other backend is remove the IP-Address from your reports. I don't see how that could even be useful.

**Comment by WebSabaki** [comment]
Thank you for these precisions

for a, yes, it seems I can get in through in fact a very basic method
as per https://github.com/soundcloud/acra/blob/master/src/main/java/org/acra/collector/CrashReportDataFactory.java, checking with the following seems to work:

`Installation.id(mContext); 
`
for b, it seems that as per https://github.com/ACRA/acra/issues/295 the issue is on the backend, not the report. However, things changed since 2015 and indeed, IP is private info and, in Europe, its collection mut be justified if not anonymized (I think /24 is sufficient).

To deal with that, what I (will) have now is
1. SSL Client auth on backend reporting
2. Privacy instructions with explanation about how to send us data request with installation ID (cf. a)
3. as I proxy the bug reporting  (for security and for 1.), I simply have to now FW the user IP so that 
user_ip field is set at 127.0.0.1. Log rotation over NGINX will then take care of the privacy over user IP.

**Comment by F43nd1r** [comment]
Data collected by ACRA cannot be connected to a person, unless fields like email address are included. 
As such this data should not fall under the GDPR. (Please correct me if I'm wrong.)

> a) how to get this installation ID on the app side so that user can submit it with there request

`Installation.id(Context)` can and should be used to extract the instance id from within the app.

> b) is there an easy way to export user record and delete them on backend side (such as acralyzer) ?

I'm not aware of any solution involving Acralyzer or any other backend. Acralyzer currently has no active maintainer, which means it is unlikely that new features will be added in the near future.

**Comment by jngr** [comment]
So, if you simply not record the IP in your back-end (including server logs) at all - doesn't that fully solve your problem? I can't think of any "legitimate purpose" for recording the IP to help solving crashes, so one important action to be in compliance with the GDPR would be to remove it from your logs altogether and not rely on log rotation. Is the installation ID still an issue after that?

**Comment by WebSabaki** [comment]
In fact, the "Not record IP" seems a problem on Acralyzer side that I "solved" with local proxy hack.

Regarding other potential PII, that is rather hard to say. Hence I rather allow users to be able to get the installation ID from App (settings / others) page if they were still curious to know what is collected.

But as a general question, I would think that not recording IP on backend + not recording email (which is ok by default), then yes, GDPR compliance shall be met.

**Comment by jngr** [comment]
> In fact, the "Not record IP" seems a problem on Acralyzer side that I "solved" with local proxy hack.

Yes, though instead of moving the problem elsewhere you could just [modify Acralyzer](https://github.com/ACRA/acralyzer/issues/128#issuecomment-249416149) to drop the IP address from your reports. I'm no longer using it but Acralyzer has not been updated for a while, so this should still work as described.

**Comment by F43nd1r** [comment]
If you're interested, I Implemented report export both by email and by installation id in my own backend https://github.com/F43nd1r/Acrarium

**Comment by KerstinMaur** [comment]
Does ACRA have a privacy policy?

https://github.com/nisrulz/app-privacy-policy-generator/pull/45
