### ISSUE TITLE
Set custom headers after ACRA was initialized

### ISSUE THREAD

**Issue by tatitr** [ACRA/acra#670]
Hello, 

I'm using ACRA in my android application and sending crash reports to a server, which I have no control of. The server requires some additional information in http headers of crash reports (e.g. authentication key, device id). This information is stored in Realm DB. It can also be retrieved only after ACRA has already started. This information is device specific and can not be hard coded. 

At the same time I reluctant to change the init order, because then if application crashes in Realm before ACRA, there will be no report.

Is there a way to change http headers at runtime with ACRA already initialized? Or maybe any other workaround? 

Thanks.

**Comment by F43nd1r** [comment]
Create your own subclass of `HttpSender` and override `sendHttpRequests`
