### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [ACRA/acra#672]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by F43nd1r** [comment]
Acra's logo is on its website acra.ch (source https://github.com/ACRA/acra.github.com) and could use a redesign

**Comment by jbeguna04** [comment]
Dear PO, so is this mean i can make new designs from your old logo?

**Comment by F43nd1r** [comment]
I'm unsure if I can give you that permission. Afaik @KevinGaudin created that icon and thus holds the rights to it.

**Comment by F43nd1r** [comment]
I'm unsure if I can give you that permission. Afaik @KevinGaudin created that icon and thus holds the rights to it.

**Comment by jbeguna04** [comment]
Sir good day, im capable of creating new logo design for your application, if you wanted to allow me to do for your future plans. I would like to help by proposing this issue. Thank you for your reaponse

**Comment by F43nd1r** [comment]
Yes, go ahead

**Comment by F43nd1r** [comment]
Inactive - closing
