### ISSUE TITLE
Empty report on server

### ISSUE THREAD

**Issue by hiddeneyes02** [ACRA/acra#673]
I am using ACRA like this:

```
@AcraCore(buildConfigClass = BuildConfig.class)
@AcraHttpSender(
      uri = "http://mydomaine/myscript.php",
      httpMethod = HttpSender.Method.POST,
      socketTimeout = 20000)
@AcraDialog(resText = R.string.app_crash)
```

And I am getting reports using PHP and PDO on my server like this:

```
<?php

class model extends PDO {

    function __construct() {
        $dsn = 'mysql:host=$host;dbname=$db;charset=utf8';
        parent::__construct($dsn, $user, $pass);
        $this->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }

}

$db = new model();

$report = json_encode($_POST);

$st = $db->prepare("INSERT INTO apps_crash (report) VALUES (:r)");

$st->execute(array('r' => $report));
```

The problem is I am getting empty data inserted in the Database.

What am I doing wrong?

**Comment by F43nd1r** [comment]
I am no expert with php, but using `json_encode` looks wrong, acra does already send json. If anything, you should decode it

**Comment by hiddeneyes02** [comment]
@F43nd1r $_POST is always an array, but I don't know how ACRA send data in that array. Storing $_POST directly in the database or decoding it is meaningless. I tried anyway all possibilities, but nothing; data is always not what it should be.

**Comment by F43nd1r** [comment]
Try setting `@AcraCore.reportFormat = StringFormat.KEY_VALUE_LIST`.

**Comment by hiddeneyes02** [comment]
That was it, but was it documented somewhere? because I didn't found it anywhere!

Thanks anyway.

**Comment by F43nd1r** [comment]
https://github.com/ACRA/acra/wiki/Migrating under point 3 or https://www.faendir.com/wordpress/acra-javadoc/org/acra/annotation/AcraCore.html#reportFormat--

**Comment by hiddeneyes02** [comment]
Yes, indeed. Thanks a lot!
