### ISSUE TITLE
EmailIntentSender: showChooser dialog not giving enough time

### ISSUE THREAD

**Issue by melnibon** [ACRA/acra#676]
Hi,

I am not sure whether it is an issue with Acra or not. On my smartphone, I have two email clients : gmail and mail. When Acra wants to send a report, it briefly shows a chooser showing both email applications, but does not wait for me to choose. This chooser dialog immediately disappears.

I think it is related to https://github.com/ACRA/acra/blob/05c0312f183122c414774f25556999b8d18dd2c7/acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java#L185

I have never played with Intent.ACTION_CHOOSER, and I do not understand how it "returns" to sending mail after choosing an application, because it seems to me that the sending is never resumed. Some kind of startActivityForResult may be necessary ?

And it would be nice to give the opportunity to select an application by default for the next calls.

Many thanks for your work,
Best regards,
Pierre

**Comment by F43nd1r** [comment]
> This chooser dialog immediately disappears.

For me the chooser doesn't disappear unless I choose an option.

> I have never played with Intent.ACTION_CHOOSER, and I do not understand how it "returns" to sending mail after choosing an application, because it seems to me that the sending is never resumed. Some kind of startActivityForResult may be necessary ?

The chooser launches the user selection.

> And it would be nice to give the opportunity to select an application by default for the next calls.

Sadly, not possible. It'll use the system default if there is one, but it can't set the default. We cannot use the default chooser (which could set the default), because it would show other applications in the list, like google drive or skype.

**Comment by melnibon** [comment]
I am sorry to waste your time: I just tested again in a different way to generate the error, and now it works as expected, same as you described in your answer.

I was throwing an exception (for testing) just after a call to `startActivity`, at the end of an `onClick` method. This is not a good idea, since Android was starting a new activity from my main application, and in the same time, starting this `ACTION_CHOOSER` caused by the exception in another thread.

I don't know what to do in such a case. The conclusion is a call to `startActivity` must be the very last action of a method, to not throwing exceptions after.

Many thanks again for ACRA !
