### ISSUE TITLE
Missing BaseConfigurationBuilder class source file in lts-4 branch.

### ISSUE THREAD

**Issue by ignusin** [ACRA/acra#677]
Hi guys. We highly appreciate your development.
Our team is interested to make ACRA work with Xamarin, however we don't use annotation initialization and use ConfigurationBuilder approach instead.
We wanted to make sure that initialization we perform is correct by looking into the sources.
We use 4.11 version, however lts-4 branch is missing BaseConfigurationBuilder class source file.
Could you please add it to the repo? Thank you!

**Comment by F43nd1r** [comment]
That class is generated by the annotation processor module and then bundled into the aar. You can look at the source by running a gradle build and then checking the build/generated/source folder.

**Comment by F43nd1r** [comment]
That class is generated by the annotation processor module and then bundled into the aar. You can look at the source by running a gradle build and then checking the build/generated/source folder.

**Comment by ignusin** [comment]
Thanks a lot for explaining.
