### ISSUE TITLE
Switch to workmanager

### ISSUE THREAD

**Issue by F43nd1r** [ACRA/acra#681]
As noted in #660 we probably should switch from android-job to workmanager.
Waiting for WorkManager to leave alpha before doing this.

**Comment by mikehardy** [comment]
Hey @F43nd1r - just curious if this will block 5.2.0? The whole jetpack thing seems like it will take a while but I'd love to see a 5.2.0-rc published somewhere so I could use the testing capabilities and clear Android-P compatibility off my checklist in AnkiDroid. Maybe this could be a 5.3 :-)

**Comment by F43nd1r** [comment]
Yeah, it is taking longer than I expected. I don't want to publish the current advanced-scheduler as a stable release, because the api will definetly change when we switch to workmanager. But the rest of the release is ready. I think I'll release it without the advanced-scheduler for now.

**Comment by mikehardy** [comment]
Or you could do what all the trendy kids do and mark it as "incubating" ;-). I'm mostly kidding though that does work. At any rate, I'll let you know if I see anything with 5.2.0 as I integrate it. Thanks again for all the work on ACRA, it's a core component for us

**Comment by mikehardy** [comment]
also if there's a repo I could gradle-integrate to see the 5.2.0-rc's I could do that, I just haven't seen them pushed out anywhere so I haven't been able to test it

**Comment by F43nd1r** [comment]
Release candidates are on bintray https://bintray.com/acra/maven/ACRA
However, there seems to be a problem with the release upload (or at least I can't see 5.2.0 yet)

**Comment by F43nd1r** [comment]
Oh, and to avoid name confusion: bintray repo equals `jcenter()` in gradle, which is used as default repo in most android apps.

**Comment by F43nd1r** [comment]
Alright, I got the release fixed. `5.2.0` is now available on `jcenter`, and will be available on `maven central` within the next few hours.
