### ISSUE TITLE
Honeywell CK75 Android

### ISSUE THREAD

**Issue by andrewarrow** [ACRA/acra#683]
I have a custom android app for the CK75 Android scan gun:

https://www.barcodegiant.com/honeywell/ck75.htm

Runs Android 6.0 but when I try and compile in the ACRA stuff I get “Parse error” unable to parse package of the .apk every time.

Do you think the CK75 is not allowing ACRA on purpose?

**Comment by F43nd1r** [comment]
I don't think anyone would block acra specifically, but maybe something acra does. I can't tell you whats going on exactly without more info though.

**Comment by andrewarrow** [comment]
Thank you, this has changed everything for me.
