### ISSUE TITLE
Android 2.2 advertised but gradle error for minSdkVerison 9

### ISSUE THREAD

**Issue by niccokunzmann** [ACRA/acra#687]
I have minSdkVerison 9.
I read 

> usable with ALL versions of Android from 2.2 onwards. [source](https://github.com/ACRA/acra)

Android 2.2 is version 8, see https://developer.android.com/guide/topics/manifest/uses-sdk-element
This is inconsistent with the advertised version 14.

When I use ACRA as written in https://github.com/ACRA/acra/wiki/BasicSetup#0-prerequisites, I get this error in Android Studio.

```
Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 14 declared in library [ch.acra:acra-mail:5.1.3] /home/user/.gradle/caches/transforms-1/files-1.1/acra-mail-5.1.3.aar/fbea402aa9e8a926fb8ca55bd3e47c29/AndroidManifest.xml as the library might be using APIs not available in 9
	Suggestion: use a compatible library with a minSdk of at most 9,
		or increase this project's minSdk version to at least 14,
		or use tools:overrideLibrary="org.acra.mail" to force usage (may lead to runtime failures)
```

Two questions:
- How can I use an old version of acra with sdk version 9?
- Can we correct the README.md file?

**Comment by F43nd1r** [comment]
While there are old versions of acra supporting minSdk 8, I strongly recommend to use the latest versions with a minSdk of at least 14, as all those old versions do not support android 8.0+. This incompatibility was caused by google. There is no way to support both 8-13 and 26+.
