### ISSUE TITLE
using in china

### ISSUE THREAD

**Issue by sagar-navsoft** [ACRA/acra#691]
Can i use this in china. My client does not want to use services by google like firebase. does ACRA use anything by google in its backend ?

**Comment by F43nd1r** [comment]
ACRA was designed to work without google play services. It does not rely on anything on- or off-device except your app (and your server if using the http sender).

**Comment by F43nd1r** [comment]
See also in readme
 > works for any application even if not delivered through Google PLay => great for devices/regions where the Google Play is not available, beta releases or for enterprise private apps
