### ISSUE TITLE
unable to implement ch.acra:acra-advanced-scheduler with v5.2.0

### ISSUE THREAD

**Issue by alexkeong** [ACRA/acra#693]
I try to implement the ACRA advanced scheduler but something wrong with the v5.2.0

below was the message I got. 
Failed to resolve: ch.acra:acra-advanced-scheduler:5.2.0

**Comment by mikehardy** [comment]
It was disabled for the official release, use the release candidates to test it? I think it was too new vs the stability of everything else... The notes have info

**Comment by F43nd1r** [comment]
As @mikehardy said, it is not included. The plugin will be part of the next stable release. If you want to use it, use ch.acra:acra-advanced-scheduler:5.2.0-rc2, but be aware that the API will change before the next release, so you'll have to update your config when you upgrade it.
This is also noted in the [release notes](https://github.com/ACRA/acra/releases/tag/acra-5.2.0)
