### ISSUE TITLE
Need to clear limiter data completely on certain occasions

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#694]
Hi there - we've got a use case in AnkiDroid where in response to the user specifically changing ACRA reporting mode (from never to ask or always, in our app - usually in response to support request or developer testing something) we want to clear all reporting history so a report will definitely go out again.

We like to do the same thing on app version upgrades so we can see if there was an impact on a particular report or if it still occurs.

That's our motivation - but I don't see a blessed way to do that in ACRA via config or via API calls other than sub-classing one of the limiter objects to add a "delete all data" method or similar. What I'm looking for is something very easy to call like `public static void LimitingReportAdminstrator.deleteLimiterData(Context context())`

Is this possible? Should I just delete the limiter JSON manually for now, or is there some chain of APIs I could call already to achieve this purpose?

Thanks in advance

**Comment by F43nd1r** [comment]
Just deleting the json file will definetly work, and there is currently no alternative.
Clearing it on version upgrade sounds like a feature that could be included. Maybe that'll result in some method I can expose publicly for custom calls.
