### ISSUE TITLE
UncaughtExceptionHandler chaining?

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#699]
I'm not sure this is an issue, but it's a use-case that ACRA makes more difficult.

The use case is to use Google Analytics in conjunction with ACRA, and to have both handle UncaughtExceptions

Google Analytics grabs a handle to the current handler during initialization when you enable uncaught exception handling, just as ACRA does, and reinstalls it when you disable

The difference is that Google Analytics, after handling the exception will then chain to the previous handler and pass it on every time. ACRA only chains to the previous handler if it is disabled, or if ACRA handling fails

The implication is that to use both, I must initialize ACRA first, then Analytics, so they chain correctly. This seems fine.

However, and this is the part I'm not 100% sure on, it looked like if ACRA was initialized as disabled to start, then you enable it later (via a preferences dialog), it alters the uncaught exception handler again? I had to re-initialize Analytics after setting ACRA to on so that the Analytics handler was in there again.

My preference would be for ACRA to either always chain handling to the previous handler or for that to be a configurable option. However, if I'm missing a subtlety with these handlers and chaining (maybe loop possibilities?) I do have a solution that works now

**Comment by F43nd1r** [comment]
Just toggle [alsoReportToAndroidFramework](http://www.acra.ch/javadoc/latest/org/acra/annotation/AcraCore.html#alsoReportToAndroidFramework--) on, it'll chain to the existing handler.

**Comment by mikehardy** [comment]
Interesting! I swear I looked, but I missed that completely.

I don't think that's the behavior I want either though, as the guidance on that method is solid - I don't want the system close dialog to come up since we use a dialog and/or toast.

I'll just continue to initialize in a specific order to get the specific behavior I want, and to reset the order myself (as I am now) if I toggle ACRA. That's okay. Thanks as always for the speedy response

**Comment by F43nd1r** [comment]
Actually, you could also install your own `UncaughtExceptionHandler` first, then let everybody pass through to that, e.g.
```java
class SilentUncaughtExceptionHandler {
    public void uncaughtException(Thread t, Throwable e) {
         Process.killProcess(Process.myPid());
         System.exit(10);
    }
}
```
