### ISSUE TITLE
LimiterData:ReportMetadata constructor can throw StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#703]
We just pushed a release of AnkiDroid using the Limiter and for reasons separate from ACRA it took an exception in some native code, but the Limiter choked on the exception - it looks like it makes an assumption that a ':' will appear in the first line, but that does not appear to be the case always. Seems like ACRA successfully contained the exception and reported the crash but I suppose that would have actually been an error if the report should be limited.

Pasting the root cause and the acra traces in a moment - but I should note that we backported the ACRA limiter implementation into a more long-term branch for us which supports API to 10, so I chose the ACRA 5.0.2 release. If this fix is easy and it's possible to cherry-pick it to ACRA 5.0.x could we get a 5.0.3 since it supports those old APIs? if it is a lot of effort no worries - it effectively falls back to the same case we had before (no limiter) so it's not a big deal

10-02 15:28:00.581: E/ACRA(10796): ACRA caught a IllegalStateException
for com.ichi2.anki
10-02 15:28:00.581: E/ACRA(10796): java.lang.IllegalStateException
10-02 15:28:00.581: E/ACRA(10796): at android.media.MediaRecorder.stop(Native Method)
10-02 15:28:00.581: E/ACRA(10796): at com.ichi2.anki.multimediacard.AudioView.notifyStopRecord(AudioView.java:192)
10-02 15:28:00.581: E/ACRA(10796): at com.ichi2.anki.multimediacard.AudioView$RecordButton$1.onClick(AudioView.java:411)
10-02 15:28:00.581: E/ACRA(10796): at android.view.View.performClick(View.java:6256)
10-02 15:28:00.581: E/ACRA(10796): at android.view.View$PerformClick.run(View.java:24697)
10-02 15:28:00.581: E/ACRA(10796): at android.os.Handler.handleCallback(Handler.java:789)
10-02 15:28:00.581: E/ACRA(10796): at android.os.Handler.dispatchMessage(Handler.java:98)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:50)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.Tap.c(Tap.java:9)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.Tap.a(Tap.java:19)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.Tap$1.b(Tap.java:2)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:78)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:94)
10-02 15:28:00.581: E/ACRA(10796): at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
10-02 15:28:00.581: E/ACRA(10796): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-02 15:28:00.581: E/ACRA(10796): at android.os.Handler.handleCallback(Handler.java:789)
10-02 15:28:00.581: E/ACRA(10796): at android.os.Handler.dispatchMessage(Handler.java:98)
10-02 15:28:00.581: E/ACRA(10796): at android.os.Looper.loop(Looper.java:164)
10-02 15:28:00.581: E/ACRA(10796): at android.app.ActivityThread.main(ActivityThread.java:6541)
10-02 15:28:00.581: E/ACRA(10796): at java.lang.reflect.Method.invoke(Native Method)
10-02 15:28:00.581: E/ACRA(10796): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-02 15:28:00.581: E/ACRA(10796): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-02 15:28:00.644: W/VideoCapabilities(10796): Unrecognized profile 2130706433 for video/avc
10-02 15:28:00.644: W/VideoCapabilities(10796): Unrecognized profile 2130706434 for video/avc
10-02 15:28:00.667: I/VideoCapabilities(10796): Unsupported profile 4 for video/mp4v-es
10-02 15:28:00.673: W/VideoCapabilities(10796): Unrecognized profile 2130706433 for video/avc
10-02 15:28:00.674: W/VideoCapabilities(10796): Unrecognized profile 2130706434 for video/avc
10-02 15:28:00.685: I/VideoCapabilities(10796): Unsupported profile 4 for video/mp4v-es
10-02 15:28:00.688: W/ACRA(10796): ReportingAdministrator org.acra.config.LimitingReportAdministrator threw exception
10-02 15:28:00.688: W/ACRA(10796): java.lang.StringIndexOutOfBoundsException: length=31; index=159
10-02 15:28:00.688: W/ACRA(10796): at java.lang.String.substring(String.java:1971)
10-02 15:28:00.688: W/ACRA(10796): at org.acra.config.LimiterData$ReportMetadata.(LimiterData.java:84)
10-02 15:28:00.688: W/ACRA(10796): at org.acra.config.LimitingReportAdministrator.shouldSendReport(LimitingReportAdministrator.java:87)
10-02 15:28:00.688: W/ACRA(10796): at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:142)
10-02 15:28:00.688: W/ACRA(10796): at org.acra.builder.ReportBuilder.build(ReportBuilder.java:183)
10-02 15:28:00.688: W/ACRA(10796): at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.java:158)
10-02 15:28:00.688: W/ACRA(10796): at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-02 15:28:00.688: W/ACRA(10796): at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
10-02 15:28:00.688: W/ACRA(10796): at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

**Comment by F43nd1r** [comment]
> I should note that we backported the ACRA limiter implementation into a more long-term branch for us which supports API to 10, so I chose the ACRA 5.0.2 release.

According to google 0.3% of devices still use < Android 4. I don't think supporting those is worth the risk of having issues on >= Android 8 (~20% of devices), which is why I discourage the use of any ACRA 4.x (except 4.11) or 5.0.x.

> If this fix is easy and it's possible to cherry-pick it to ACRA 5.0.x could we get a 5.0.3 since it supports those old APIs?

For the reason given above I won't put out any updates to those versions. 
(You could try the 5.2.x limiter with 5.0.2, but no guarantees.)

> if it is a lot of effort no worries - it effectively falls back to the same case we had before (no limiter) so it's not a big deal

It is good to know that ACRA is resistant to bugs in a plugin.

**Comment by mikehardy** [comment]
Probably the right balance of risks and the fallback behavior is okay. Thanks for the quick fix. Ironically I have a limiter test and it works so this must just trigger when it's a native code stack frame even if it's definitely in error, so probably not hit often regardle

**Comment by F43nd1r** [comment]
This bug will show up exactly if there is a `:` in the stacktrace, but none in the first line of the stacktrace.
Which means it is likely to occur for all exceptions without a message.
