### ISSUE TITLE
TargetSdk = 27 problems in Oreo (or API23+)

### ISSUE THREAD

**Issue by haamaanaa** [ACRA/acra#708]
TargetSdk = 27 forces projects to use compileSdk = 27, which then forces security implications of android devices over API 23 to become in use.

https://github.com/ACRA/acra/blob/e3c76a673f89ba18abddc7cfb4d42dbaec98c84e/gradle.properties#L31

Our app is compile/min/target API 21 (we do not want to use higher APIs for now), but if we want to use ACRA for crash reporting, we must use compile sdk value 27.

Why?

**Comment by F43nd1r** [comment]
Because we are using support library features introduced in recent versions. I think everything required (especially `JobIntentService`) was added in v26, so it would be possible to drop to 26, but not lower.

**Comment by F43nd1r** [comment]
Runtime permissions were introduced for a reason, maybe just do the jump and upgrade.
If you do not want or are unable to upgrade your compilesdk, you'll have to stay with old ACRA versions. Note that those are likely to have issues on android 8+. I will not favor 3+ years old version compatibilty over most recent version compatibility.
