### ISSUE TITLE
ACRA 5.2.0 config via ServiceLoader has issues

### ISSUE THREAD

**Issue by william-ferguson-au** [ACRA/acra#709]
With the following ACRA config and acra-core, acra-http dependencies the HttpSender is never found and the NullSender reports that "reports will NOT be sent - no valid ReportSender was found!"

```
@AcraCore(
    buildConfigClass = BuildConfig.class,
    reportFormat = StringFormat.KEY_VALUE_LIST,
    reportContent = { // These are the field used by Bugsense. I need to trim down because the Post was too big and Bugsense was canning it with a Http-400.
        ReportField.DISPLAY,
        ReportField.SETTINGS_SECURE,
        ReportField.STACK_TRACE,
        ReportField.CUSTOM_DATA,
        ReportField.USER_CRASH_DATE,
        ReportField.PHONE_MODEL,
        ReportField.APP_VERSION_NAME,
        ReportField.APP_VERSION_CODE,
        ReportField.PACKAGE_NAME,
        ReportField.ANDROID_VERSION
    }
)
@AcraHttpSender(httpMethod = HttpSender.Method.POST, uri = "http://www.bugsense.com/api/acra?api_key=someApiKey")
```

The issue is the use of the ServiceLoader mechanism.

The ServiceLoader mechanism requires a text file in the META-INF/services folder named after the interface class and containing the implementation classes.

The ACRA libs don't ship with such text files and there is no documentation in the ACRA wiki to indicate they are required.

Furthermore, the Android build tooling doesn't handle inclusion of Java resources particularly well so there is no simple way of declaring these in your project and having them stitched into your APK in the appropriate place.

NB In order to get this to work I need to manually add these 2 files to my APK.

META-INF/services/org.acra.config.ConfigurationBuilderFactory
```
org.acra.config.HttpSenderConfigurationBuilderFactory
org.acra.config.DialogConfigurationBuilderFactory
```

META-INF/services/org.acra.sender.ReportSenderFactory
```
org.acra.sender.HttpSenderFactory
```

**Comment by F43nd1r** [comment]
> The ACRA libs don't ship with such text files

The files are in the aar inside the classes.jar

> The issue is the use of the ServiceLoader mechanism.

As noted in https://github.com/ACRA/acra/issues/706#issuecomment-427012106 I want to move away from ServiceLoader, but I haven't found a good replacement

**Comment by william-ferguson-au** [comment]
The ServiceLoader mechanism works fine.
The problem is with the Android toolset. ApkBuilder specifically excludes resources file in the META-INF folder.

**Comment by F43nd1r** [comment]
I know it works usually, that's why I used it in the first place.
It's just that there are so many edge cases (mostly in apk assembly) breaking it, that I'd rather have something else.

**Comment by william-ferguson-au** [comment]
What about  a factoryClass on each annotation?

**Comment by F43nd1r** [comment]
@william-ferguson-au you mean something like this? https://github.com/F43nd1r/acra/commit/513f6a031daef3e7ce460981146e2eaa02b1b08d

It does work, but I dislike the centralized plugin configuration, because it requires to edit an otherwise unrelated class whenever a plugin is added. It also forces the annotations upon users, which is not the case right now.

**Comment by william-ferguson-au** [comment]
No. I was thinking more along the lines of for the AcraHttpSender and AcraDialog annotations that they have a factoryClass attribute, which could be defaulted.

The Collectors are slightly different. Might need another solution.

**Comment by F43nd1r** [comment]
I think that would be a step back in terms of reusability.

**Comment by william-ferguson-au** [comment]
Really? In what way?

Apps could be configured with multiple @AcraHttpSender annotation each one configured for a potentially different HttpSender factory.

A user can compose the config of ACRA however they wish. What do you see as a step back?

**Comment by F43nd1r** [comment]
It would mean that the core module needs to know that plugin annotations exist and where to find the factory on them. Custom senders would once again require a different mechanism. Handling custom and official plugins differently is what I view as a step back.

**Comment by william-ferguson-au** [comment]
Just have a (core) set of annotations. There are only a few ways that you can send a failure or provide notification. The core can know about them. Each has a factoryClass attribute

They each have their default factories (this is the official plugin). Anyone who wants a custom plugin can set their own factory class.

**Comment by F43nd1r** [comment]
Closing with #713. Will reopen if issues persist.
