### ISSUE TITLE
prevent dialog when the app is closed

### ISSUE THREAD

**Issue by izjumovfs** [ACRA/acra#711]
Hi.
Could you help me to solve a very strange issue. ACRA shows me ErrorReport dialog event if my app is closed and i am working with other apps or navigating in my launcher. Why this is happening?
This is my ACRA config

> @AcraCore(
        reportContent = {
            APP_VERSION_NAME,
            ANDROID_VERSION,
            PHONE_MODEL,
            BRAND,
            STACK_TRACE,
            USER_COMMENT,
            USER_EMAIL
        },
        buildConfigClass = BuildConfig.class,
        reportFormat = StringFormat.KEY_VALUE_LIST
)
@AcraHttpSender(uri = "someurl",
        httpMethod = HttpSender.Method.POST
)
@AcraDialog(resText = R.string.crash_dialog_text,
        resCommentPrompt = R.string.crash_dialog_comment_prompt,
        resEmailPrompt = R.string.crash_user_email_label,
        resIcon = android.R.drawable.ic_dialog_info,
        resTitle = R.string.crash_dialog_title,
        reportDialogClass = ErrorReportDialog.class
)

**Comment by F43nd1r** [comment]
ACRA will catch all crashes inside your code, including background services or paused activities.

**Comment by izjumovfs** [comment]
Thanks. How can i prevent it from catching crashes in background?

**Comment by mikehardy** [comment]
I can't imagine a case I wouldn't want to know about background crashes, but I suppose you could listen to lifecycle events and in the listener you could toggle ACRA on or off completely, or configure it to continue catching crashes but handle them differently

https://developer.android.com/reference/android/arch/lifecycle/ProcessLifecycleOwner

https://medium.com/@arturogdg/background-and-foreground-events-with-android-architecture-components-233fdd9fa855

**Comment by mikehardy** [comment]
This isn't an ACRA issue though - it's an application design thing

**Comment by F43nd1r** [comment]
I could see a point being made for delaying the crash report dialog until the application comes to the front, not interrupting users is always good. Not currently possible though.

**Comment by izjumovfs** [comment]
In our app ACRA caught a lot of crashes from AdMob. I think that these crashes do not stop our app or kill it, but ACRA is catching them and shows ErrorReport dialog which disturbs users. Can we turn off handling some type of crashes via ACRA?

**Comment by F43nd1r** [comment]
i think this would be a job for a custom `ReportingAdministrator`, which checks if the exception comes from admob and then marks those for dropping.

**Comment by F43nd1r** [comment]
Eventually yes. But if no one steps in a makes a pull request, it could take a while, as I do not have much time to allocate to this project right now.
