### ISSUE TITLE
Acra on android library modules

### ISSUE THREAD

**Issue by ahmed56734** [ACRA/acra#715]
I am working on an android library,
I want to know if it's possible to use Acra to  detect and collect crashes related to my library not the app module ?

**Comment by F43nd1r** [comment]
Should be possible by registering a custom `ReportingAdministrator` which filters out everything except those with your package name in the stacktrace.

A more common pattern would be to have app developers catch crashes as they want to and let them report to upstream if a library is causing issues.

**Comment by F43nd1r** [comment]
Override [shouldStartCollecting](http://www.acra.ch/javadoc/latest/org/acra/config/ReportingAdministrator.html#shouldStartCollecting-android.content.Context-org.acra.config.CoreConfiguration-org.acra.builder.ReportBuilder-) with something like 

```java

    class MyAdmin implements ReportingAdministrator {

        @Override
        public boolean shouldStartCollecting(@NonNull Context context, @NonNull CoreConfiguration config, @NonNull ReportBuilder reportBuilder) {
            if (reportBuilder.getException() != null) {
                StringWriter stringWriter = new StringWriter();
                reportBuilder.getException().printStackTrace(new PrintWriter(stringWriter));
                return stringWriter.toString().contains("your.package.name");
            }
            return false;
        }
    }
```

**Comment by F43nd1r** [comment]
2. https://github.com/ACRA/acra/wiki/Custom-Extensions#registering-an-extension

**Comment by ahmed56734** [comment]
![screen shot 2018-11-26 at 1 31 23 pm](https://user-images.githubusercontent.com/10393214/49011643-a23f5400-f17f-11e8-8957-49caadcd0d18.png)
can't find the annotation processor classpath anywhere

**Comment by ahmed56734** [comment]
@F43nd1r

**Comment by F43nd1r** [comment]
https://docs.gradle.org/4.6/release-notes.html#convenient-declaration-of-annotation-processor-dependencies

**Comment by ahmed56734** [comment]
![screen shot 2018-11-29 at 1 17 20 pm](https://user-images.githubusercontent.com/10393214/49218531-51c33300-f3d9-11e8-9731-f493229c93e3.png)
I already did that
