### ISSUE TITLE
dynamic URL string AcraHttpSender instead of constant?

### ISSUE THREAD

**Issue by erlangp** [ACRA/acra#717]
i want to fetch url and apikey before make an request to acra server..
thanks

**Comment by erlangp** [comment]
@F43nd1r

**Comment by erlangp** [comment]
any builder to make an AcraHttpSender on runtime sir?

**Comment by mikehardy** [comment]
Dude! You logged an issue 8 hours ago and have already bumped it twice. It's the weekend. F43nd1r is super responsive but this looks like unreasonable expectations to me.

**Comment by erlangp** [comment]
owh, hhehe.. sorry, sir.. XD

**Comment by erlangp** [comment]
solved 
1. implement `ReportSenderFactory` as `CustomSenderFactory` class.
2. inside `create()` method, return `new HttpSender( ... )` instance with non-constant URL as param.
3. create `CoreConfigurationBuilder` instance
4. call builder method `.setReportSenderFactoryClasses(CustomSenderFactory.class)`
5. call `ACRA.init(context, builder)`

**Comment by F43nd1r** [comment]
@erlangp  please try to solve your problems first before posting here. But thanks for providing the solution for future users with similar issues.

Also @mikehardy is right, please do not bump threads unless you want to contribute something new or the issue is months old.
