### ISSUE TITLE
Email not working?

### ISSUE THREAD

**Issue by Sean-Brown-Digi** [ACRA/acra#718]
I just added ACRA to our project and placed some invalid code in startup to make it crash. I added ACRA's "Toast" component and the "Email" component. The toast message shows, however no email is ever sent. I check the debugger and it says something like `unable to start service Intent {AttachmentService} not found`. I followed the directions in the wiki: any idea what I am doing wrong?  I'm on an Android Pixel device and the AndroidManifest has the INTERNET user permission set, if that helps.

**Comment by F43nd1r** [comment]
Internet permission is not required for mail.
This looks like a bug in your mail app. Can you test with another mail client?

**Comment by Sean-Brown-Digi** [comment]
What's the expected result supposed to be? I was expecting ACRA to silently send an email in the background, are you saying that it's supposed to open a mail client and the user has to send the email themselves?

**Comment by F43nd1r** [comment]
Yes, that's how it works. 

Problem with sending mail directly is that you need access to a mail account. Requesting this from the user would probably be received badly from users. Compiling in a password makes the account vurnerable to being stolen for e.g. spam bots.

**Comment by Sean-Brown-Digi** [comment]
Ah ok, thanks for the explanation!

**Comment by F43nd1r** [comment]
> I put the crash code later in the program's execution and it opens the email program properly

Good to know that it works.

> during my testing I put in code which caused the app to crash right after ACRA.init()

Acra will retry to send reports on the next launch. Which means unless the application start crashes every time, reports will reach you eventually.
If the application start crashes every time, there is no way to get the report out anyway.

> I assume because the MainApplication wasn't fully created before the crash

Acra might even be able to catch crashes in Application.onCreate, but I'm not sure on this.
It will catch crashes in Activity/Service startup, where initialization of your app should be.

**Comment by Sean-Brown-Digi** [comment]
That's really good to know and you are right, I put the crash in `onCreate()` and ACRA handled it correctly. Previously I put the crash code in `attachBaseContext()` and I would only see the toast message but not get any email dialog.

**Comment by F43nd1r** [comment]
Makes sense, a toast is not an activity, while the mail dialog is an activity (and on top of that is launched by ACRAs service).
It would've surprised me if the android system let us create activities before creating the application.
