### ISSUE TITLE
STACK_TRACE_HASH

### ISSUE THREAD

**Issue by MichalKrasowski** [ACRA/acra#719]
By default ACRA doesn't populate the ReportField.STACK_TRACE_HASH

Please update the [ReportContent wiki documentation](https://github.com/ACRA/acra/wiki/ReportContent#stack_trace) with information that this is not enabled by default, and some configuration is required.

I use the following calls to CoreConfigurationBuilder to enable STACK_TRACE_HASH reporting:

        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(app)
                .setBuildConfigClass(buildConfig)
                .setReportContent(ReportField.STACK_TRACE, ReportField.STACK_TRACE_HASH);
        ACRA.init(app, builder);

**Comment by F43nd1r** [comment]
The acra wiki is publicly editable, you may update it yourself.
