### ISSUE TITLE
Android 8.1.0 SenderService don't called

### ISSUE THREAD

**Issue by xiaxiayige** [ACRA/acra#725]
help me

mobile: OPPOP PACM00  Android 8.1.0,SenderService don't work 
ACRA version: 5.2.1

My Step:

step1:

`val builder = CoreConfigurationBuilder(application)
            builder.setBuildConfigClass(configClass).setReportFormat(StringFormat.JSON)
            builder.setReportField(ReportField.BUILD, true)
                    .setReportField(ReportField.DEVICE_FEATURES, false)
                    .setReportField(ReportField.FILE_PATH, false)
                    .setReportField(ReportField.PRODUCT, false)
                    .setReportField(ReportField.IS_SILENT, false)
                    .setReportField(ReportField.INITIAL_CONFIGURATION, false)
                    .setReportField(ReportField.CRASH_CONFIGURATION, false)
                    .setReportField(ReportField.USER_COMMENT, false)
                    .setReportField(ReportField.USER_EMAIL, false)
                    .setReportField(ReportField.DUMPSYS_MEMINFO, false)
                    .setReportField(ReportField.INSTALLATION_ID, false)
                    .setReportField(ReportField.ENVIRONMENT, false)
                    .setReportField(ReportField.LOGCAT, false)
            builder.setReportSenderFactoryClasses(ReportOwnSenderfactory::class.java)
            if (enable){
                ACRA.init(application, builder)
            }`

step2:
ACRA.getErrorReporter().handleException(NullPointerException("test NullPointerException"))

step3 

Logcat:

`01-10 10:43:41.382 18906 19279 D ACRA    : Calling collector org.acra.collector.MediaCodecListCollector
01-10 10:43:41.382 18906 19279 D ACRA    : Collector org.acra.collector.MediaCodecListCollector completed
01-10 10:43:41.383 18906 19278 D ACRA    : Collector org.acra.collector.SimpleValuesCollector completed
01-10 10:43:41.384 18906 19274 D ACRA    : Collector org.acra.collector.TimeCollector completed
01-10 10:43:41.384 18906 19272 D ACRA    : Collector org.acra.collector.PackageManagerCollector completed
01-10 10:43:41.388 18906 19273 D ACRA    : Collector org.acra.collector.DisplayManagerCollector completed
01-10 10:43:41.389 18906 18906 D ACRA    : Writing crash report file /data/user/0/test.demo.myapplication/app_ACRA-unapproved/2019-01-10T10:43:41.382+08:00-IS_SILENT.stacktrace
01-10 10:43:41.396 18906 18906 D ACRA    : Mark 2019-01-10T10:43:41.382+08:00-IS_SILENT.stacktrace as approved.
01-10 10:43:41.397 18906 18906 D ACRA    : Schedule report sending
01-10 10:43:41.397 18906 18906 D ACRA    : About to start SenderService
01-10 10:43:41.404 18906 18906 D ACRA    : Wait for Interactions + worker ended. Kill Application ? false

`

**Comment by F43nd1r** [comment]
Look similar to this https://github.com/ACRA/acra/issues/718#issuecomment-442852679

**Comment by xiaxiayige** [comment]
> 看起来类似于这个[＃718（评论）](https://github.com/ACRA/acra/issues/718#issuecomment-442852679)

thank you for your reply，I am calling in the Activity call `ACRA.getErrorReporter（）。handleException（NullPointerException（“test NullPointerException”））` ，a button onclick method，
Other phones are running normally，'OPPOP PACM00 Android 8.1.0' not work

**Comment by F43nd1r** [comment]
Maybe related to #707, both claim 8.1.0 to be part of the issue

**Comment by F43nd1r** [comment]
I was unable to reproduce this on either API 27 or 28 using a generic device and ACRA 5.3.0-b03. Maybe test if the beta works for you as well?

**Comment by xiaxiayige** [comment]
> I was unable to reproduce this on either API 27 or 28 using a generic device and ACRA 5.3.0-b03. Maybe test if the beta works for you as well?
sorry, I'm  home  now，,device in the  company, In a few days, I will try to use ACRA 5.3.0-b03 version test。thank you  follow up problem。

**Comment by xiaxiayige** [comment]
use ACRA 5.3.0-b03  test log:

`--------- beginning of main
02-12 14:09:31.146  9623  9945 D ACRA    : Calling collector org.acra.collector.DropBoxCollector
02-12 14:09:31.147  9623  9945 D ACRA    : Collector org.acra.collector.DropBoxCollector completed
02-12 14:09:31.147  9623  9946 D ACRA    : Calling collector org.acra.collector.LogCatCollector
02-12 14:09:31.147  9623  9946 D ACRA    : Collector org.acra.collector.LogCatCollector completed
02-12 14:09:31.147  9623  9946 D ACRA    : Calling collector org.acra.collector.CustomDataCollector
02-12 14:09:31.148  9623  9946 D ACRA    : Collector org.acra.collector.CustomDataCollector completed
02-12 14:09:31.148  9623  9945 D ACRA    : Calling collector org.acra.collector.DeviceFeaturesCollector
02-12 14:09:31.148  9623  9945 D ACRA    : Collector org.acra.collector.DeviceFeaturesCollector completed
02-12 14:09:31.149  9623  9947 D ACRA    : Calling collector org.acra.collector.StacktraceCollector
02-12 14:09:31.149  9623  9948 D ACRA    : Calling collector org.acra.collector.ConfigurationCollector
02-12 14:09:31.149  9623  9948 D ACRA    : Collector org.acra.collector.ConfigurationCollector completed
02-12 14:09:31.149  9623  9946 D ACRA    : Calling collector org.acra.collector.DisplayManagerCollector
02-12 14:09:31.150  9623  9949 D ACRA    : Calling collector org.acra.collector.DeviceIdCollector
02-12 14:09:31.150  9623  9945 D ACRA    : Calling collector org.acra.collector.MemoryInfoCollector
02-12 14:09:31.150  9623  9949 D ACRA    : Collector org.acra.collector.DeviceIdCollector completed
02-12 14:09:31.150  9623  9949 D ACRA    : Calling collector org.acra.collector.ReflectionCollector
02-12 14:09:31.150  9623  9948 D ACRA    : Calling collector org.acra.collector.SettingsCollector
02-12 14:09:31.150  9623  9948 D ACRA    : Collector org.acra.collector.SettingsCollector completed
02-12 14:09:31.150  9623  9947 D ACRA    : Collector org.acra.collector.StacktraceCollector completed
02-12 14:09:31.150  9623  9947 D ACRA    : Calling collector org.acra.collector.SimpleValuesCollector
02-12 14:09:31.150  9623  9945 D ACRA    : Collector org.acra.collector.MemoryInfoCollector completed
02-12 14:09:31.151  9623  9948 D ACRA    : Calling collector org.acra.collector.TimeCollector
02-12 14:09:31.151  9623  9947 D ACRA    : Collector org.acra.collector.SimpleValuesCollector completed
02-12 14:09:31.151  9623  9949 D ACRA    : Collector org.acra.collector.ReflectionCollector completed
02-12 14:09:31.151  9623  9949 D ACRA    : Calling collector org.acra.collector.MediaCodecListCollector
02-12 14:09:31.152  9623  9947 D ACRA    : Calling collector org.acra.collector.ThreadCollector
02-12 14:09:31.152  9623  9947 D ACRA    : Collector org.acra.collector.ThreadCollector completed
02-12 14:09:31.152  9623  9949 D ACRA    : Collector org.acra.collector.MediaCodecListCollector completed
02-12 14:09:31.153  9623  9948 D ACRA    : Collector org.acra.collector.TimeCollector completed
02-12 14:09:31.153  9623  9951 D ACRA    : Calling collector org.acra.collector.SharedPreferencesCollector
02-12 14:09:31.153  9623  9950 D ACRA    : Calling collector org.acra.collector.PackageManagerCollector
02-12 14:09:31.154  9623  9952 D ACRA    : Calling collector org.acra.collector.LogFileCollector
02-12 14:09:31.154  9623  9952 D ACRA    : Collector org.acra.collector.LogFileCollector completed
02-12 14:09:31.155  9623  9951 D ACRA    : Collector org.acra.collector.SharedPreferencesCollector completed
02-12 14:09:31.156  9623  9950 D ACRA    : Collector org.acra.collector.PackageManagerCollector completed
02-12 14:09:31.158  9623  9946 D ACRA    : Collector org.acra.collector.DisplayManagerCollector completed
02-12 14:09:31.158  9623  9623 D ACRA    : Writing crash report file /data/user/0/test.demo.cclogDemo/app_ACRA-unapproved/2019-02-12T14:09:31.152+08:00-IS_SILENT.stacktrace
02-12 14:09:31.163  9623  9623 D ACRA    : ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
02-12 14:09:31.165  9623  9623 D ACRA    : Found services ([]) for class : interface org.acra.interaction.ReportInteraction
02-12 14:09:31.166  9623  9623 D ACRA    : Mark 2019-02-12T14:09:31.152+08:00-IS_SILENT.stacktrace as approved.
02-12 14:09:31.167  9623  9623 D ACRA    : Schedule report sending
--------- beginning of system
02-12 14:09:31.176  9623  9623 D ACRA    : Wait for Interactions + worker ended. Kill Application ? false`

ReportOwnSenderfactory .kt 

`class ReportOwnSenderfactory : ReportSenderFactory {

    fun ReportOwnSenderfactory() {

    }

    override fun create(context: Context, config: CoreConfiguration): ReportSender {
        return ReportOwnSender()
    }

    override fun enabled(config: CoreConfiguration): Boolean {
        return true
    }
}`

ReportOwnSender.kt 

`class ReportOwnSender : ReportSender {
    fun ReportOwnSender() {
    }

    override fun send(context: Context, errorContent: CrashReportData) {
        Log.d("ReportOwnSender",errorContent.toJSON())
    }
}`

never dont work. ' Log.d("ReportOwnSender",errorContent.toJSON())'  Log no print

**Comment by F43nd1r** [comment]
Please test if this issue is device specific (e.g. test if it works in an emulator). Because if it is specific to this device, I'll assume that this issue is similar to #707, which would mean that it can't be fixed.

**Comment by benibela** [comment]
> I'll assume that this issue is similar to #707, which would mean that it can't be fixed.

If a background service does not work, perhaps you can use a foreground service?

**Comment by F43nd1r** [comment]
Stale - closing
