### ISSUE TITLE
Problem with direct IP call

### ISSUE THREAD

**Issue by rafa19** [ACRA/acra#733]
Starting with Android 9.0 (API level 28), cleartext support is disabled by default.

If you are just stated ACRA and did not use a domain name(like me), you probably can't see crash reports on your server. I have wasted 4 hours on it. Finally figured out why it is not working. Here is the solution

Add  `android:usesCleartextTraffic="true"` this on your applucation tag.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```

You can see more solutions from this link
[https://stackoverflow.com/a/50834600](url)

**Comment by F43nd1r** [comment]
If you want to, you can insert this info into the wiki.
