### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked

### ISSUE THREAD

**Issue by praatiy** [ACRA/acra#734]
Hi All,

I am getting below exception in my application for ACRA process

SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode

I have also attached the full exception trace below.
[ExceptionTrace.pdf](https://github.com/ACRA/acra/files/2898126/ExceptionTrace.pdf)

I have also attached my application class where I am configuring ACRA and also the DatabaseUtil class which is a singleton class to get instance of Firebase database.
[JavaCode.pdf](https://github.com/ACRA/acra/files/2898134/JavaCode.pdf)

**Comment by F43nd1r** [comment]
Read https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#applicationoncreate
