### ISSUE TITLE
Make BaseCrashReportDialog extend AppCompatActivity

### ISSUE THREAD

**Issue by sampalmer** [ACRA/acra#735]
### Background

I'm currently developing a custom crash report dialog, and I want it to be a [full-screen dialog](https://material.io/design/components/dialogs.html#full-screen-dialog), as shown below:
![Screenshot_20190311-121431](https://user-images.githubusercontent.com/4566802/54094796-83e02a00-43f7-11e9-89ce-24fd5603106d.png)

I've extended `BaseCrashReportDialog`, and I need to add the "X" in the top-left corner and the "Send" button in the top-right corner. I am using the following code:

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        ActionBar supportActionBar = getSupportActionBar();
        assert supportActionBar != null;
        supportActionBar.setDisplayHomeAsUpEnabled(true);
        supportActionBar.setHomeAsUpIndicator(R.drawable.close);
        super.onCreateOptionsMenu(menu);
        getMenuInflater().inflate(R.menu.report_problem, menu);
        return true;
    }

### Problem

However, I cannot call `getSupportActionBar()` because the base class doesn't extend `AppCompatActivity`. As a result, I cannot put an "X" in the top-left corner in a way that works on all OS versions.

### Solutions

I can think of a few ways to deal with this:

* Use [`AppCompatDelegate`](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html) as [suggested](https://github.com/ACRA/acra/issues/443#issuecomment-217671243) in #443. The problem with this is it requires me to write a large amount of boilerplate code so is quite messy. Plus, there are still some behaviours that are built into `AppCompatActivity` but not `AppCompatDelegate`.
* Change `BaseCrashReportDialog` to extend from `AppCompatActivity`. I think this is a more reasonable base class than the current `FragmentActivity`. But I suppose this could be a breaking change... 😞
* Change `BaseCrashReportDialog` into a fragment that developers can include into their own activities. This way you still get a lot of control and the ability to hook into the activity but without dictating the class hierarchy for the activity itself.

Edit: actually I ended up deciding not to go ahead with ACRA (due to GDPR), but I'll still leave this issue open in case you're interested.

**Comment by F43nd1r** [comment]
I think I'd prefer to allow any activity as dialog, and encapsulate all logic in `BaseCrashReportDialog` in a POJO.

**Comment by Mikanoshi** [comment]
And I would prefer to get rid of any AppCompat stuff completely :) Never use them, so it just adds useless classes into apk.

**Comment by F43nd1r** [comment]
@Mikanoshi acra-core is already free of appcompat (and all other) dependencies, and I'm working on reducing it to the minimum in all plugins as well.

**Comment by Mikanoshi** [comment]
That's because I also extend BaseCrashReportDialog

**Comment by Mikanoshi** [comment]
Where is the **org.acra.config.DialogConfiguration** defined?

**Comment by F43nd1r** [comment]
There are no sources in the repository for it, as this  "Class [is] generated based on [AcraDialog](http://www.acra.ch/javadoc/latest/org/acra/annotation/AcraDialog.html)"

(Quote from http://www.acra.ch/javadoc/latest/org/acra/config/DialogConfiguration.html)
