### ISSUE TITLE
AutoService artifact structure changed

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#738]
This is more of a notice then a bug report, though you may have to make changes

AutoService changed artifact package structure and I had to update my gradle dependencies in order to get my ACRA library consumer app to work again

I updated the Wiki here with what I changed, in case it is useful, and this is also sort of informal notice that I made the edit so you can correct it if my change was incorrect

https://github.com/ACRA/acra/wiki/Custom-Extensions/_compare/b7066dbb1a9b89281e0648ba4400258a35b4b3e9...1d3f2d919689c85c4e349ed1f1ed877e96bc9b07

Cheers!

**Comment by F43nd1r** [comment]
The processor is still just `auto-service`. I've corrected that.
