### ISSUE TITLE
Android Q heads up (background activity starts)

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#739]
I am using Notification option for bug reports where user taps to  Send to open their email app.
It looks like it is affected by https://developer.android.com/preview/privacy/background-activity-starts

Is there a quick workaround for this?

**Comment by F43nd1r** [comment]
This has nothing to do with the notification, just the mailsender in general. 
I really hate that change, it screws with the whole architecture.
No, there is no quick workaround, I need to rewrite several core components to make this work.
