### ISSUE TITLE
The serialization issue during upgrade from 4.+ to 5.1

### ISSUE THREAD

**Issue by iammini5** [ACRA/acra#741]
I am getting this crash after the upgrade.

Caused by java.lang.RuntimeException
Parcelable encountered IOException reading a Serializable object (name = org.acra.config.ACRAConfiguration)
android.os.Parcel.readSerializable

and : 
Caused by java.io.InvalidClassException
org.acra.collections.ImmutableSet; local class incompatible: stream classdesc serialVersionUID = 1609855643214165107, local class serialVersionUID = 3896411131200884899

java.io.ObjectStreamClass.initNonProxy (ObjectStreamClass.java:625)
java.io.ObjectInputStream.readNonProxyDesc (ObjectInputStream.java:1625)
java.io.ObjectInputStream.readClassDesc (ObjectInputStream.java:1520)
java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:1776)
java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1353)
java.io.ObjectInputStream.defaultReadFields (ObjectInputStream.java:2002)
java.io.ObjectInputStream.readSerialData (ObjectInputStream.java:1893)
java.io.ObjectInputStream.readOrdinaryObject (ObjectInputStream.java:1803)
java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1353)
java.io.ObjectInputStream.readObject (ObjectInputStream.java:373)
android.os.Parcel.readSerializable (Parcel.java:2943)
android.os.Parcel.readValue (Parcel.java:2735)
android.os.Parcel.readArrayMapInternal (Parcel.java:3053)
android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:288)
android.os.BaseBundle.unparcel (BaseBundle.java:232)
android.os.BaseBundle.containsKey (BaseBundle.java:504)
android.content.Intent.hasExtra (Intent.java:7923)
org.acra.sender.SenderService.onHandleWork (SourceFile:51)

**Comment by F43nd1r** [comment]
This might happen if acra 5 tries to process an intent sent from acra 4. This is very unlikely to occur. Can you reproduce it?

**Comment by iammini5** [comment]
It happened all the times when i try to upgrade it on Samsung Android 9 devices, and after it happen it seems it can't go back to normal and repeat it over and over again.

**Comment by F43nd1r** [comment]
I think this should be fixed somewhere on the way to 5.3.
