### ISSUE TITLE
Error restarting app after crash

### ISSUE THREAD

**Issue by LauraAnt** [ACRA/acra#742]
Hello,

First of all, thank you for all your work! ACRA is an amazing library :)

I have a problem with the scheduler, in Android 9. This is the code I'm using:

```java
@AcraScheduler(requiresNetworkType = JobInfo.NETWORK_TYPE_UNMETERED,
        requiresBatteryNotLow = true,
        restartAfterCrash = true)
```

After the crash, the app should restart, but it doesn't, and an error is shown in the logs:

Logcat:
```
W/System.err: java.lang.IllegalArgumentException: You're trying to build a job with no constraints, this is not allowed.
W/System.err:     at android.app.job.JobInfo$Builder.build(JobInfo.java:1532)
        at org.acra.scheduler.RestartingAdministrator.lambda$shouldFinishActivity$0(RestartingAdministrator.java:54)
        at org.acra.scheduler.-$$Lambda$RestartingAdministrator$CVz1ZvvFh5_kx7lb0l5ujUOH9EE.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
```

I think it may be fixed with a small correction, so I will make a pull request.

**Comment by Vorlif** [comment]
Is there a chance for a new release where this issue is fixed? :blush:

**Comment by F43nd1r** [comment]
5.4.0 released today

**Comment by Vorlif** [comment]
Wow, that was pretty fast. Thank you very much.

**Comment by KoenduBuf** [comment]
I just ran into this problem using acra 5.5.1, downgrading to 5.4.0 fixed the issue, but I thought I would share since it might be interesting if more people have the same issue @F43nd1r
