### ISSUE TITLE
minSdk 22 on ch.acra:acra-advanced-scheduler:5.3.0

### ISSUE THREAD

**Issue by scysys** [ACRA/acra#745]
Upgrade from 5.2.1 to 5.3.0 ends up in this

```
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 22 declared in library [ch.acra:acra-advanced-scheduler:5.3.0] /PATH/AndroidManifest.xml as the library might be using APIs not available in 15
	Suggestion: use a compatible library with a minSdk of at most 15,
		or increase this project's minSdk version to at least 22,
		or use tools:overrideLibrary="org.acra.scheduler" to force usage (may lead to runtime failures)
```

**Comment by F43nd1r** [comment]
The documentation for the advanced scheduler is still missing.
In short: 5.2 used workmanager, but this led to complaints about blown up dependency size.
So I made the decision to drop workmanager, as it was only used in the advanced scheduler to provide its features on older versions.

You can use `tools:overrideLibrary="org.acra.scheduler"`, but then you'll have to disable the scheduler on older versions.
