### ISSUE TITLE
empty httpsender report

### ISSUE THREAD

**Issue by benibela** [ACRA/acra#748]
I am receiving empty http reports from acra 5.2.1. The url is called, including parameters, but there is no post data in the request body. Why?

The annotations [are straightforward](https://github.com/benibela/videlibri/blob/master/android/android/src/de/benibela/videlibri/VideLibriApp.kt#L29-L41):

> ```
> @AcraCore(buildConfigClass = BuildConfig::class,
>         reportFormat = StringFormat.KEY_VALUE_LIST,
>         resReportSendSuccessToast = R.string.crash_dialog_ok_toast,
>         resReportSendFailureToast = R.string.crash_dialog_fail_toast
>         )
> @AcraHttpSender(uri = "http://www.benibela.de/autoFeedback.php?app=VideLibriACRA",
>         httpMethod = HttpSender.Method.POST,
>         socketTimeout = 5*60*1000,
>         connectionTimeout = 2*60*1000
>         )
> @AcraDialog(resText = R.string.crash_dialog_text,
>         resCommentPrompt = R.string.crash_dialog_comment_prompt
> )
> class VideLibriApp : Application() {
> ```

**Comment by F43nd1r** [comment]
I've tried to reproduce this, but was unable to do so. Do you have the same problem with the latest version?

**Comment by benibela** [comment]
I tried to update, but that did not work out, because I am still using SdkVersion 27.

My app has a background service, with AlarmManager or JobSheduler. Perhaps it only happens from a sender there

Now it is also becomes very weird when I try to put the Android version in the query string. 

  ```
    val builder = org.acra.config.CoreConfigurationBuilder(this)
    builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder::class.java).setUri("http://www.benibela.de/autoFeedback.php?app=VideLibriA"+android.os.Build.VERSION.SDK_INT)
    ACRA.init(this, builder)
```
I just received an empty report without any number in the url. But it still had the app name prefix from the builder rather than the one from the annotation

From my own device everything works.

**Comment by F43nd1r** [comment]
There are broken phones/os out there. Especially chinese oems like to "improve" android, which breaks lots of things. It is also possible that something else (e.g. a web scrapper) is calling your endpoint.
In the end your backend should expect to receive invalid reports and handle them gracefully.

**Comment by benibela** [comment]
>It is also possible that something else (e.g. a web scrapper) is calling your endpoint.

That is probably the most reasonable explanation. It might get the url from github.
