### ISSUE TITLE
Kotlin "An Annotation argument must be a compile time constant"

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#754]
I get "An Annotation argument must be a compile time constant" when I try to use compile time config with in Kotlin.

I understand this is because I use String resources. Is there any workaround?

Sample config

@AcraNotification(
        resTitle = R.string.crash_notif_title,
        resText = R.string.crash_dialog_text,
        resChannelName = R.string.app_name,
        resSendButtonText = R.string.send,
        resDiscardButtonText = R.string.cancel,
        sendOnClick = true
)

**Comment by F43nd1r** [comment]
String resource ids should be compile time constants.
I've made a quick test to confirm this and it worked for me.

You might need to update your android gradle plugin, maybe old versions didn't emit R as final.
