### ISSUE TITLE
getReportFields() in 4.11 is deleted

### ISSUE THREAD

**Issue by MohammadNsr** [ACRA/acra#756]
i was using version 4.9.1  as you see in gradle 
"implementation 'ch.acra:acra:4.9.1'"
after update to 4.11
"implementation 'ch.acra:acra:4.11'"
i found that the function "getReportFields()"does not exist any more
 in my case, i use it like this:
Set < ReportField > fields = ACRA.getConfig().getReportFields();
and i searched the wiki, but i did not find any thing about it.

**Comment by F43nd1r** [comment]
`getReportFields` was equivalent to `reportContent`. Use that one instead.
