### ISSUE TITLE
Acra5Activity cannot be cast to org.matomo.sdk.extra.MatomoApplication

### ISSUE THREAD

**Issue by scysys** [ACRA/acra#757]
Tried several ways and actually I have no solution to use Acra and Matomo inside one App.

**On AndroidManifest.xml**
**ACRA**
```
    <application
        android:name=".Acra5Activity">
```

or

**Matomo**
```
    <application
        android:name=".matomo.tracking">
```

Everything is working but if I want to use booth of them. What can I do?

**Comment by F43nd1r** [comment]
create an application class implementing both.

**Comment by scysys** [comment]
Sorry for this. Should sleep now. Its working. thanks!
