### ISSUE TITLE
Custom dialog message on a handleException

### ISSUE THREAD

**Issue by sherlock1982** [ACRA/acra#760]
Hi! Thanks for your work - we really enjoy working with ACRA.

Currently I have an option in my app "Send log report to a dev".

If I use `handleException(null)` it shows a standard dialog where user can enter a comment. But the dialog tells a user the application crashed. While it's not - and it's bad UX 

On the other hand I can make a dialog on my own and call `handleSilentException(null)` but than I can't add `USER_COMMENT` field. As a workaround I put it in CUSTOM_DATA which is not properly handled by tracepot.

So what's the proper way? 
I need to:
1. Show a dialog to the user with a different message (not the one about crash)
2. Collect his input and send it in a report as `USER_COMMENT` field

**Comment by F43nd1r** [comment]
Easiest solution would probably be `handleSilentException` + a custom collector, something like this:
```java
@AutoService(Collector.class)
class CustomCollector extends Collector {

    void collect(@NonNull Context context, @NonNull CoreConfiguration config, @NonNull ReportBuilder reportBuilder, @NonNull CrashReportData crashReportData) throws CollectorException {
        if(reportBuilder.getException() instanceof UserLogException) crashReportData.put(ReportField.USER_COMMENT, ((UserLogException) reportBuilder.getException()).getComment());
    }
}
```

an alternative approach is to extend CrashReportDialog for custom handling.

**Comment by sherlock1982** [comment]
Thanks, I implemented it. Though I needed to fill in proper stacktrace as well.

```
@Suppress("unused")
@AutoService(Collector::class)
class UserCommentCollector : Collector {
    override fun collect(context: Context, config: CoreConfiguration, reportBuilder: ReportBuilder, crashReportData: CrashReportData) {
        val exception = reportBuilder.exception
        if (exception is UserLogException) {
            with(crashReportData) {
                val reportString = "Report requested by developer"

                put(ReportField.USER_COMMENT, exception.userComment)
                put(ReportField.STACK_TRACE, reportString)
                put(ReportField.STACK_TRACE_HASH, reportString.hashCode().toHexString())
            }
        }
    }
}
```
