### ISSUE TITLE
How to use @ReportsCrashes on Version 5.2 +

### ISSUE THREAD

**Issue by Balaji-wi** [ACRA/acra#763]
Previously i was using @ReportsCrashes annotation for connecting with server and push report field datas on Version ACRA 4.9.2 with dependency 'ch.acra:acra:4.9.2'. 

On latest versions, dependencies are mentioned specifically for each function, i have added  "ch.acra:acra-http:5.2.0" and "ch.acra:acra-core:5.2.0" , but im not able to use @ReportsCrashes annotation. Kindly suggest me on fixing it .

Thanks 
K Balaji

**Comment by F43nd1r** [comment]
https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---compile-time

**Comment by Balaji-wi** [comment]
Thanks, but stuck up another issue.

@AcraDialog(resText = R.string.crash_toast_text)

@AcraHttpSender(
        uri = "***",
        httpMethod = HttpSender.Method.POST,
        socketTimeout = 20000)
@AcraCore(buildConfigClass = BuildConfig.class)
public class AppTracker extends Application {
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class).setReportFormat(StringFormat.JSON);
        builder.setBuildConfigClass(BuildConfig.class).setReportContent(ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BRAND,
                ReportField.PHONE_MODEL,
                ReportField.BUILD,
                ReportField.STACK_TRACE,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_CRASH_DATE);

        try {
            builder.build();
        } catch (ACRAConfigurationException e) {
            e.printStackTrace();
        }
        // The following line triggers the initialization of ACRA
        ACRA.init(this, builder);
    }
}


Am i missing anything ? im recieving empty data on php server . Previosuly i used to send particular data through ReportField and get it through variable on server .

**Comment by F43nd1r** [comment]
You're mixing and duplicating configuration types. Thats unnessary, it can be written as 

```java
@AcraDialog(resText = R.string.crash_toast_text)
@AcraHttpSender(
        uri = "***",
        httpMethod = HttpSender.Method.POST,
        socketTimeout = 20000)
@AcraCore(buildConfigClass = BuildConfig.class,
reportFormat = StringFormat.JSON,
reportContent = {ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BRAND,
                ReportField.PHONE_MODEL,
                ReportField.BUILD,
                ReportField.STACK_TRACE,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_CRASH_DATE})
public class AppTracker extends Application {
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        // The following line triggers the initialization of ACRA
        ACRA.init(this);
    }
}
```

But if you're using php I wouldn't expect you to want `reportFormat = StringFormat.JSON`. Try changing that to the other value.

**Comment by Balaji-wi** [comment]
its almost working. Thank you. Recieving all data on proper format except STACK_TRACE data is received with special characters which i tried to convert to readable format with many conversions and decoding but it didnt work.

is it possible to share a  sample data format while choosing StringFormat.JSON ?

**Comment by Balaji-wi** [comment]
I tried receiving data with StringFormat.JSON , but unable to get proper data . Will the output be in jsonobject format or something else ? i just wish to know the data format, so that I will try to parse it accordingly.

**Comment by F43nd1r** [comment]
JSON example:
```json
{
    "STACK_TRACE":"java.lang.IllegalStateException: Could not execute method for android:onClick\n\tat android.view.View$DeclaredOnClickListener.onClick(View.java:5336)\n\tat android.view.View.performClick(View.java:6256)\n\tat android.view.View$PerformClick.run(View.java:24701)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6541)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat android.view.View$DeclaredOnClickListener.onClick(View.java:5331)\n\t... 9 more\nCaused by: java.lang.RuntimeException: 1\n\tat com.faendir.acratest.context.MainActivity.onClick(MainActivity.java:36)\n\t... 11 more\n",
    "REPORT_ID":"1ed71618-772b-4aab-90d8-dcc3311c6554",
    "ANDROID_VERSION":"8.0.0",
    "APP_VERSION_CODE":1,
    "USER_CRASH_DATE":"2019-10-17T10:54:44.373+02:00",
    "IS_SILENT":false
}
```
KEY_VALUE example:
```
STACK_TRACE=java.lang.IllegalStateException%3A+Could+not+execute+method+for+android%3AonClick%0A%09at+android.view.View%24DeclaredOnClickListener.onClick%28View.java%3A5336%29%0A%09at+android.view.View.performClick%28View.java%3A6256%29%0A%09at+android.view.View%24PerformClick.run%28View.java%3A24701%29%0A%09at+android.os.Handler.handleCallback%28Handler.java%3A789%29%0A%09at+android.os.Handler.dispatchMessage%28Handler.java%3A98%29%0A%09at+android.os.Looper.loop%28Looper.java%3A164%29%0A%09at+android.app.ActivityThread.main%28ActivityThread.java%3A6541%29%0A%09at+java.lang.reflect.Method.invoke%28Native+Method%29%0A%09at+com.android.internal.os.Zygote%24MethodAndArgsCaller.run%28Zygote.java%3A240%29%0A%09at+com.android.internal.os.ZygoteInit.main%28ZygoteInit.java%3A767%29%0ACaused+by%3A+java.lang.reflect.InvocationTargetException%0A%09at+java.lang.reflect.Method.invoke%28Native+Method%29%0A%09at+android.view.View%24DeclaredOnClickListener.onClick%28View.java%3A5331%29%0A%09...+9+more%0ACaused+by%3A+java.lang.RuntimeException%3A+1%0A%09at+com.faendir.acratest.context.MainActivity.onClick%28MainActivity.java%3A36%29%0A%09...+11+more%0A
&REPORT_ID=65a8a608-c674-4d1c-80b3-5af59608bf12
&ANDROID_VERSION=8.0.0
&APP_VERSION_CODE=1
&USER_CRASH_DATE=2019-10-17T10%3A47%3A51.530%2B02%3A00
&IS_SILENT=false
```

**Comment by Balaji-wi** [comment]
Thanks a lot. I use to receive JSON format properly on old version of ACRA ,  here im getting empty data , tried different recieving types on PHP . I am getting data for KEY_VALUE but stack trace data is not readable ( tried to convert that too but couldnt get proper output ) . I dont know where im making mistake. Thanks for guiding!

**Comment by F43nd1r** [comment]
Values in key_value are urlencoded. I
'm not used to php, so I can't tell what the problem is. Json works fine and as before in my own backend.
