### ISSUE TITLE
False line number in Bug report

### ISSUE THREAD

**Issue by MohammadNsr** [ACRA/acra#764]
i am using progurard in my android application and acra too.
the line numbers are false, when the code is obfuscated with proguard.
can acra cause this problem, or it is only because of proguard?
in a debug version, where the code is not  obfuscated with proguard, the lines are correct.
do you have any idea?

**Comment by F43nd1r** [comment]
This sounds like it is caused by proguard. 
Usually, including acra should also load its [proguard config](https://github.com/ACRA/acra/blob/master/acra-core/proguard.cfg), which helps prevent things like that.
If that's not the case, you'll have to include those lines in your own proguard configuration.

**Comment by mikehardy** [comment]
I'm not sure why but in our builds (same app store upload apk, release build with proguard) some of our stacks have line numbers and some have bogus ones. We're not doing anything that would not include the acra proguard config so it's puzzling to me. I don't have a clean reproduction or a lead on a cause but I thought you might be interested to hear at least a report that something odd is indeed happening. Current versions of everything, so maybe it's an D8/R8 thing, or...I dunno. If I figure it out I'll circle back here.

**Comment by F43nd1r** [comment]
Alright, maybe keep this open then...
Although I haven't seen this issue myself and won't be able to do anything about it without a more conrete lead.

**Comment by mikehardy** [comment]
Yeah, I'm pretty good at troubleshooting and I can't do anything with my report either ;-). If it goes stale and that's it, then that's it. We'll see. Thanks @F43nd1r

**Comment by MohammadNsr** [comment]
i am still having this problem.

**Comment by MohammadNsr** [comment]
there was already settings of acra in proguard.cfg, and it was not working will...
but i changed now to what you gave me: https://github.com/ACRA/acra/blob/lts-4/acra/src/main/proguard/proguard.cfg
and i am still having the problem, as you can see here:

java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at com.ortim.android.a6.activity.StudienverwaltungActivity.onItemClick(SourceFile:2)
	at com.ortim.android.a6.activity.C.onItemClick(SourceFile:1)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
	at android.widget.AbsListView$3.run(AbsListView.java:4151)
	at android.os.Handler.handleCallback(Handler.java:808)

my custom classes alone have this problem, as you can see. so what can i do?

**Comment by mikehardy** [comment]
I am also still having this myself, but also can't explain it, I'm always able to figure out what it is going on from the method names alone so haven't pursued it much, but I still speculate it is part of the shift to D8/R8, that's when I noticed it.

**Comment by MohammadNsr** [comment]
i shift to D8/R8 also. and upadte to androidx libs.
maybe it is the cause...

**Comment by mikehardy** [comment]
it is worth noting that the mapping.txt file used by google play console to decode stack traces (uploaded automatically by my app release process via the 'Triple T' publishing library in gradle - https://github.com/Triple-T/gradle-play-publisher) allows the play console to decode things

But pre-D8/R8 things worked fine for ACRA as well. And they are supposed to be backwards compatible with all the proguard config stuff so honestly it should not be happening, and is likely not ACRA's fault per se, just some unfortunate interaction with the new tool

Perhaps a quick demo app that has side-by-side builds capable, one with the old toolchain (gradle 3.3 I suppose?) and one with the new would show it easily

**Comment by MohammadNsr** [comment]
i am still having this problem, and i noticed that line numbers are false only in release version.
in debug version the stack trace have the right line numbers.
i noticed that in both stack traces, the method names are not obfuscated.

**Comment by F43nd1r** [comment]
Still can't reproduce.

**Comment by MohammadNsr** [comment]
i updated today from 4.11 to the latest version. but still having the same problem.
is asking for this permisson a possible cause? 
<uses-permission android:name="android.permission.READ_LOGS" />
i get the warning that this permission only granted to system apps.

**Comment by F43nd1r** [comment]
Very unlikely. Afaik modern android versions just ignore this permission request.

**Comment by MohammadNsr** [comment]
here are my acra specifics in my proguard.cfg file, may be it can help:
# # # # # # # ACRA specifics

# we need line numbers in our stack traces otherwise they are pretty useless
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable

# keep this class so that logging will show 'ACRA' and not a obfuscated name like 'a'.
# Note: if you are removing log messages elsewhere in this file then this isn't necessary
-keep class org.acra.ACRA {
        *;
}

-keepclassmembers class org.acra.ReportField { 
   public static <fields>; 
} 

# keep this around for some enums that ACRA needs
-keep class org.acra.ReportingInteractionMode {
   *;
}

-keep public class org.acra.ErrorReporter {
   public void addCustomData(java.lang.String,java.lang.String);
}

-keep public class org.acra.ErrorReporter {
   public org.acra.ErrorReporter$ReportsSenderWorker handleSilentException(java.lang.Throwable);
}
# # # # # # # # End ACRA specifics

-keep public class com.ortim.android.acra.CrashReportActivity {
	 *;
}

i am now using gradle version 6.1.1
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
and plugin version 4.0.1
classpath 'com.android.tools.build:gradle:4.0.1'#
still working with acra 4.11
implementation 'ch.acra:acra:4.11'  (i updated the acra version in one try, but i've got the same problem)
