### ISSUE TITLE
How to send mail report silently?

### ISSUE THREAD

**Issue by jboxx** [ACRA/acra#765]
Which configuration I should set when I want to sending the crash report silently via email?
I didn't find any wiki that related silent mode once I use mail Plugin.

Thanks

**Comment by F43nd1r** [comment]
Sending a mail requires user interaction. There is currently no way around that. 

As seen in #604, direct(silent) mail sending requires a password to be compiled into the apk, which is not acceptable, because the mail account could be compromised to easily.
