### ISSUE TITLE
Provide a callback to perform cleaning tasks before proposing to send a report

### ISSUE THREAD

**Issue by christophehenry** [ACRA/acra#771]
As ACRA monopolizes `Thread.setDefaultUncaughtExceptionHandler()`, it is not possible to reference a callback to perform cleaning tasks when the application meets an uncaught exception. This is inconveniant, in particular if the application displays an unswipable notification that could not be canceled during the handling of the crash.

**Comment by F43nd1r** [comment]
Use a `ReportingAdministrator` with cleanup in either `shouldStartCollecting` (before report collection) or `shouldSendReport` (after report is built, but before anything is killed). Always return true if you don't want to block certain reports.

**Comment by christophehenry** [comment]
@F43nd1r Works well, thanks.
