### ISSUE TITLE
Acra send mail with empty content

### ISSUE THREAD

**Issue by zungx** [ACRA/acra#772]
I'm using for tracking crash, but received mail with empty msg. 
`implementation 'ch.acra:acra-mail:5.1.3'`
`minSdkVersion 21`
`targetSdkVersion 28`
Please help to check, thank you

**Comment by F43nd1r** [comment]
Test if issue persists with current version, which is 5.5.0

**Comment by zungx** [comment]
> Test if issue persists with current version, which is 5.5.0

I'm try with version 5.5.0 still empty msg log

My config
`override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        if (BuildConfig.DEBUG) {
            val builder = CoreConfigurationBuilder(this)
            builder.setBuildConfigClass(BuildConfig::class.java)
                .setReportFormat(StringFormat.KEY_VALUE_LIST)
            ACRA.init(this, builder)
        }
    }`

**Comment by F43nd1r** [comment]
Where is your mailsender config?

**Comment by zungx** [comment]
> Where is your mailsender config?

this is my mail sender config

```
@AcraCore(reportContent = [REPORT_ID, PACKAGE_NAME, APP_VERSION_CODE, APP_VERSION_NAME, ANDROID_VERSION, PHONE_MODEL, STACK_TRACE])
@AcraMailSender(
    mailTo = "myemail@mail.com",
    reportAsFile = false
)
class AppApplication : BaseApplication() {}
```

**Comment by F43nd1r** [comment]
Does it work without `reportAsFile = false`?
dev or production environment?

**Comment by zungx** [comment]
> Does it work without `reportAsFile = false`?
> dev or production environment?

worked without `reportAsFile = false`. Thank you so much
I'm used for dev env

**Comment by zungx** [comment]
@F43nd1r have you know problem with `reportAsFile =false`?
