### ISSUE TITLE
OS major version parsing failed for: acra 5 For input string: "acra 5"

### ISSUE THREAD

**Issue by Saeed-Ataee** [ACRA/acra#774]
I choose [Acrarium](https://github.com/F43nd1r/Acrarium) for server-side and I'm using `docker-compose` to set up the server using this [link](https://github.com/F43nd1r/Acrarium/wiki/Standalone-docker-setup). When the android application send data to server, I get this message and no data store in DB:

```
acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
acrarium    | Hibernate: select 1 as col_0_0_ from `user` user0_ where ? in (select roles1_.`roles` from `user_roles` roles1_ where user0_.`username`=roles1_.`user_username`) limit ?
```

What's the problem?

**Comment by F43nd1r** [comment]
1. You should've opened this issue in the acrarium repository, as it is very unlikely to have anything to do with acra itself.
2. The two lines you posted are just a warning (which can be safely ignored. we don't care about [user agent detection](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L381) here, although I've never seen this message) and a debug message detailing one database access.
3. Wild guess: Your `basicAuthLogin` and/or `basicAuthPassword` might be wrong

**Comment by Saeed-Ataee** [comment]
Dear @F43nd1r, You are right. I'm sorry about it. I just thought opening issue in this repository would help me faster. I checked the client-side and the problem was invalid `uri`! thanks.

**Comment by F43nd1r** [comment]
I am currently the only dev on both projects, I'll help with the same speed regardless of location :)
Glad you found your issue!
