### ISSUE TITLE
Global application Silent Exception

### ISSUE THREAD

**Issue by alphater** [ACRA/acra#776]
I want to apply ACRA.getErrorReporter (). HandleSilentException (caughtException); function in the whole project. When Exception occurs in my application, the App does not exit, only toast prompt is given, now the toast prompt is displayed, but my app Still quit.
My English is not very good, I don't know if I have clearly expressed my needs.

Below is my configuration, what should I do?

`        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class).setReportFormat(StringFormat.JSON);
        builder.setBuildConfigClass(BuildConfig.class).setReportContent(
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BRAND,
                ReportField.PHONE_MODEL,
                ReportField.BUILD,
                ReportField.STACK_TRACE,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_CRASH_DATE);
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class)
                .setText(getString(R.string.acra_toast_text))
                .setEnabled(true);
        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
                .setUri("https://api.xxx.com/crash")
                .setHttpMethod(HttpSender.Method.POST)
                .setHttpHeaders(header)
                .setSocketTimeout(20000)
                .setEnabled(true);
        try {
            builder.build();
        } catch (ACRAConfigurationException e) {
            e.printStackTrace();
        }
        // The following line triggers the initialization of ACRA
        ACRA.init(this, builder);`

thank!

**Comment by F43nd1r** [comment]
It is impossible for an app to keep running after an uncaught exception, as such an exception will leave it in a broken state.
Which means to do what you want you need to catch all exceptions.
To do that you have to wrap all your code in `try` blocks and then send the exception using `handleSilentException`.
