### ISSUE TITLE
ACRA not working with Android 11 (API 30)

### ISSUE THREAD

**Issue by tmoseneder** [ACRA/acra#785]
I am aware of the fact that the official target version still is 29, I am just creating this issue to make sure you guys know and that others can follow the progress of this issue.

The problem is a NoClassDefFoundException regarding the com.android.internal.util.Predicate class which is deprecated since API 26 but was still included in the SDK of API 29 (I checked that in the sources locally) 

When i switch to TargedSdkVersion = 30, the class is not found anymore which I assume is because they finally decided to remove it from the SDK. 

> 2020-06-17 14:28:28.212 23119-23119/at.placeholder.login E/AndroidRuntime: FATAL EXCEPTION: main
    Process: at.placeholder.login, PID: 23119
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/util/Predicate;
        at org.acra.util.IOUtils.streamToString(IOUtils.java:84)
        at org.acra.ACRA.getCurrentProcessName(ACRA.java:303)
        at org.acra.ACRA.isACRASenderServiceProcess(ACRA.java:294)
        at org.acra.ACRA.init(ACRA.java:210)
        at org.acra.ACRA.init(ACRA.java:193)

**Comment by F43nd1r** [comment]
Which ACRA version are you using? That method doesn't exist in the current version.

**Comment by tmoseneder** [comment]
Oh, that's in fact a bit embarassing. I only saw that the usage of that class was moved into the StreamReader class of ACRA but i somehow overlooked that this class was already modified to not use that class anymore!
Sorry for bothering!

**Comment by F43nd1r** [comment]
This issue exists in the last ACRA 4 version (4.11), which I wanted to support for a while longer. Thanks for noting this, I'll backport StreamReader.
