### ISSUE TITLE
MailSender Does not work on Android 11

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#787]
I have configured MailSender module so user can tap on the notification and send crash report by using their email app.

While this config work fine on Android 7,8,9 and 10, it does not work on 11. ACRA says " Caused by: org.acra.sender.j: No email client found" in the logs.

See EmailIntentSender at https://github.com/ACRA/acra/blob/4e2357a9390b7de6d8fd1ae41e167f62270e1606/acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java

It calls `resolveIntent.resolveActivity` which is not permitted anymore because of https://developer.android.com/preview/privacy/package-visibility

I would not want QUERY_ALL_PACKAGES ( https://developer.android.com/reference/kotlin/android/Manifest.permission#query_all_packages ) merged but perhaps use try catch instead of `resolveIntent.resolveActivity` or you can add intent filter for email mime type.

Here is my config:

       initAcra {

                setBuildConfigClass(BuildConfig::class.java)
                setReportFormat(StringFormat.KEY_VALUE_LIST)
                setReportContent(ReportField.USER_COMMENT,
                        ReportField.PACKAGE_NAME,
                        ReportField.APP_VERSION_NAME,
                        ReportField.ANDROID_VERSION,
                        ReportField.BRAND,
                        ReportField.PHONE_MODEL,
                        ReportField.PRODUCT,
                        ReportField.USER_APP_START_DATE,
                        ReportField.USER_CRASH_DATE,
                        ReportField.STACK_TRACE,
                        ReportField.LOGCAT)`

              plugin<MailSenderConfigurationBuilder> {
                    setEnabled(true)
                    setMailTo(Constants.contactEmail)
                    setReportAsFile(false)
                }

                plugin<NotificationConfigurationBuilder> {
                    setEnabled(true)
                    setTitle(getString(R.string.crash_notif_title))
                    setText(getString(R.string.crash_dialog_text))
                    setChannelName(getString(R.string.app_crash_notification_channel))
                    setSendButtonText(getString(R.string.send))
                    setDiscardButtonText(getString(R.string.cancel))
                    setSendOnClick(true)

                    setResDiscardButtonIcon(R.drawable.crash_log_discard)
                    setResSendButtonIcon(R.drawable.crash_log_send)
                }
            }

Here is the error

**Comment by NLLAPPS** [comment]
I Use the following in my Manifest to workaround this issue

`    <queries>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="message/rfc822" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND_MULTIPLE" />
            <data android:mimeType="message/rfc822" />
        </intent>
    </queries>`

**Comment by F43nd1r** [comment]
> I Use the following in my Manifest to workaround this issue
> 
> ` <queries> <intent> <action android:name="android.intent.action.SEND" /> <data android:mimeType="message/rfc822" /> </intent> <intent> <action android:name="android.intent.action.SEND_MULTIPLE" /> <data android:mimeType="message/rfc822" /> </intent> </queries>`

That looks more like the intended solution than a workaround for me.

Try/catch isn't possible because we resolve one intent and send another (when attachments are present).
