### ISSUE TITLE
Whitelist feature for excludeMatchingSettingsKeys

### ISSUE THREAD

**Issue by binarynoise** [ACRA/acra#790]
Would it be possible to add an includeOnlyMatchingSettingsKeys to _only_ include some keys I am really interested in (two in my case) and leave out the whole rest to enhance privacy?
I think it would be easy to implement in org.acra.collector.SettingsCollector#isAuthorized.
What about this?
```java
private boolean isAuthorized(@NonNull CoreConfiguration config, @Nullable Field key) {
	if (key == null || key.getName().startsWith("WIFI_AP")) {
		return false;
	}
	for (String regex : config.excludeMatchingSettingsKeys()) {
		if (key.getName().matches(regex)) {
			return false;
		}
	}
	if(config.includeOnlyMatchingSettingsKeys().isEmpty()) {
		return true;
	}
	for (String regex : config.includeOnlyMatchingSettingsKeys()) {
		if (key.getName().matches(regex)) {
			return true;
		}
	}
	return false;
}
```

**Comment by F43nd1r** [comment]
Regex should be powerful enough to allow excluding everything except two keys, which is equivalent to including just two keys. I would recommend using negative lookahead, so we don't need to introduce a new option. E.g.:

` "^(?!VIBRATE_ON|USER_ROTATION)$"`

**Comment by binarynoise** [comment]
Thanks for the response and the example
I ended up with using
`"^((?!foo|bar).)*$"`
as I wanted also to include settings that contain foo.
Please add the two examples to the documentation so other devs can find it quicker

**Comment by mikehardy** [comment]
@binarynoise should be restated as "here's a pull request for the documentation with examples to help future people with requests like mine...", it's open source, "we" are the implementors, all of us :-)

**Comment by F43nd1r** [comment]
No need to PR, the wiki is open to edits from anyone. But yeah, improving the documentation yourself is appreciated.

**Comment by binarynoise** [comment]
@mikehardy 
I would update the javadoc, but where is that `CoreConfigurationBuilder` file?
I can't find it:
It should be [here](https://github.com/ACRA/acra/tree/acra-5.6.1/acra-core/src/main/java/org/acra/config) but it isn't, 
Github fails to resolve it 
and even IntelliJ idea can only give me the decompiled code, 
but it defenititly has to be somewhere, because the app runs well and there even are some [tests](https://github.com/ACRA/acra/blob/acra-5.6.1/acra-core/src/test/java/org/acra/config/CoreConfigurationBuilderTest.java)

**Comment by F43nd1r** [comment]
> I just found the AcraCore, is that the right place?

Yes. Builders are generated from annotations.

**Comment by binarynoise** [comment]
I created the PR.
It needs a better commit message though.
