### ISSUE TITLE
Empty report when using a custom sender with SimplePluginLoader (5.5.1)

### ISSUE THREAD

**Issue by gitdefllo** [ACRA/acra#791]
Trying to using a custom sender but the `CrashReportData` seems empty. Instead of the deprecated `setReportSenderFactoryClasses()`, I'm using a `SimpleLoader` to load my custom factory, which is not mentionned in the documentation (but in the [javadoc](https://www.acra.ch/javadoc/5.5.1/): "_register with plugin loading instead_"). Here's what I did:  

**MyApplication.kt** :
```java
@AcraCore(buildConfigClass = BuildConfig::class.java,
        reportFormat = StringFormat.JSON,
        reportContent = [
            ReportField.BUILD_CONFIG,
            ReportField.PACKAGE_NAME,
            ReportField.ANDROID_VERSION,
            ReportField.APP_VERSION_CODE,
            ReportField.APP_VERSION_NAME,
            ...
        ])
```
```java
val builder = CoreConfigurationBuilder(this)
                .setBuildConfigClass(BuildConfig::class.java)
                .setReportFormat(StringFormat.JSON)
                .setPluginLoader(SimplePluginLoader(CustomSenderFactory::class.java)) // using my custom factory
ACRA.init(this, builder)
```

**CustomSenderFactory.java** :
```java
@AutoService(ReportSenderFactory.class)
public class CustomSenderFactory implements ReportSenderFactory {

    public CustomSenderFactory() {
        // requires empty constructor
    }

    @NonNull
    @Override
    public ReportSender create(@NonNull Context context, @NonNull CoreConfiguration config) {
        return new CustomSender();
    }

    @Override
    public boolean enabled(@NonNull CoreConfiguration config) { return true; }
}
```

**CustomSender.java**:
```java
public class CustomSender implements ReportSender {
    @Override
    public void send(@NotNull Context context, @NotNull CrashReportData report) {
        Log.d(this.getClass().getName(), ">>>>> Report = " + report.toJSON()); // nothing, it's empty
        ...
    }
}
```

The logcat at restart shows an empty report:
```
07-01 14:27:49.624 7477-7477/? I/ACRA: ACRA is enabled for com.package.dev, initializing...
07-01 14:27:50.162 7463-7519/? D/ACRA: About to start sending reports from SenderService
07-01 14:27:50.162 7463-7519/? D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
07-01 14:27:50.162 7463-7519/? D/ACRA: Using PluginLoader to find ReportSender factories
07-01 14:27:50.162 7463-7519/? D/ACRA: SimplePluginLoader loading services from plugin classes : [Ljava.lang.Class;@d1fcac2
07-01 14:27:50.162 7463-7519/? D/ACRA: Loaded plugin from class : class com.package.acra.CustomSenderFactory
07-01 14:27:50.162 7463-7519/? D/ACRA: reportSenderFactories : [com.package.acra.CustomSenderFactory@a5ca0d3]
07-01 14:27:50.162 7463-7519/? D/com.package.acra.CustomSenderFactory: >>>>> CustomSenderFactory create()
07-01 14:27:50.163 7463-7519/? D/ACRA: Adding reportSender : com.package.acra.CustomSender@8a2f410
07-01 14:27:50.165 7463-7519/? I/ACRA: Sending report /data/user/0/com.package.dev/app_ACRA-approved/.stacktrace
07-01 14:27:50.167 7463-7519/? D/ACRA: Sending report using com.package.acra.CustomSender
07-01 14:27:50.167 7463-7519/? D/com.package.acra.CustomSender: >>>>> CustomSender = send()
07-01 14:27:50.242 7477-7477/? D/ACRA: onActivityCreated class com.package.activities.MainActivity
07-01 14:27:50.246 7463-7519/? D/com.package.acra.CustomSender: >>>>> Report = {}                       <----------
07-01 14:27:50.303 7463-7519/? D/ACRA: Sent report using com.package.acra.CustomSender
07-01 14:27:50.303 7463-7519/? D/ACRA: Report was sent by all senders
07-01 14:27:50.303 7463-7519/? D/ACRA: Finished sending reports from SenderService
```
However, when I use the deprecated `setReportSenderFactoryClasses()`, it works perfectly and the `CrashReportData` contains everything.

Any idea ? What did I miss ?  
Thanks

**Comment by F43nd1r** [comment]
`SimplePluginLoader` overrides all Plugin discoveries, so you'd have to declare all used plugins, which includes `Collector`s.
This is probably not what you want. Instead, refer to [this wiki page](https://github.com/ACRA/acra/wiki/Custom-Extensions#registering-an-extension) on how to make your `ReportSenderFactory` discoverable.

**Comment by gitdefllo** [comment]
Thanks for your quick reply, I really appreciate. Indeed, now that I removed `setPluginLoader`, I can see these kind of logs: 
```
D/ACRA: Building report
D/ACRA: Calling collector org.acra.collector.DropBoxCollector
D/ACRA: Collector org.acra.collector.DropBoxCollector completed
D/ACRA: Calling collector org.acra.collector.ConfigurationCollector
D/ACRA: Collector org.acra.collector.ConfigurationCollector completed
...
```
Which means the default collector works and the data is collected into the report. But when I use `@AutoService(ReportSenderFactory.class)` alternative - which was already the case -, `send()` in `CustomSender.java` is never called. What could be the error?

**Comment by F43nd1r** [comment]
Please show your ReportSenderFactory source and build.gradle dependencies block

**Comment by gitdefllo** [comment]
The `ReportSenderFactory` is the same as in the first topic above. And in my `build.gradle`, I use as follows: 
```
    def acra_version = '5.5.1'
    ...
    implementation "ch.acra:acra-core:$acra_version"
    implementation "ch.acra:acra-http:$acra_version"
    compileOnly "com.google.auto.service:auto-service-annotations:1.0-rc6"
    annotationProcessor "com.google.auto.service:auto-service:1.0-rc6"
```

**Comment by F43nd1r** [comment]
Looks like something in your build pipeline prevents your ReportSenderFactory from being included in META-INF/services.
Maybe you're using an old version of the android gradle plugin?
You could also try to create the file manually instead of using `@AutoService`.

It is working on my end, so we need to find what you're doing different.

**Comment by gitdefllo** [comment]
I'm using `'com.android.tools.build:gradle:3.5.3'` version, but I can't upgrade due to Lombok incompatibility ([#2412](https://github.com/rzwitserloot/lombok/issues/2412)). Anyway, as you said, it couldn't be included in services, because I can't see the acra process in debug mode (`com.package.dev:acra`). Something on my side is preventing it. I'll come back to you later after more investigations. Anyway, thank you very much for your help.

**Comment by gitdefllo** [comment]
I didn't find the root problem but I resolved it by manually load my custom service :
![custom_sender_factory](https://user-images.githubusercontent.com/5924363/86452886-40f94280-bd1d-11ea-80e5-1f714ddca774.png)
Thank you very much @F43nd1r for your time!
