### ISSUE TITLE
ACRA 5.6.2 for core is not loading in gradle

### ISSUE THREAD

**Issue by VijayDePrabu** [ACRA/acra#795]
ACRA 5.6.2 for core is not loading in gradle although 5.6.1 does @F43nd1r

**Comment by VijayDePrabu** [comment]
Realized some versions in 5.* core is not required to @ acracore annotation ...

**Comment by F43nd1r** [comment]
I just went back and fixed the missing uploads. jcenter should be up to date by now, maven central will follow in a few hours top.
