### ISSUE TITLE
Problem with ACRA MAIL Manifest File

### ISSUE THREAD

**Issue by GlobooX** [ACRA/acra#798]
Version of ACRA: 5.6.2
I got error when try to start my android application on emulator.

https://i.imgur.com/4Mj3bAK.png - Manifest File
https://i.imgur.com/BSOkxzS.png - Error
https://i.imgur.com/q0HhSLE.png - My build.gradle (app)

**Comment by F43nd1r** [comment]
Ah, I didn't realize this would be a breaking change. Apparently those tags require `android build plugin` version 4 or later.

**Comment by GlobooX** [comment]
What i supposed to do? I have minSDKVersion 26

**Comment by F43nd1r** [comment]
Use `com.android.tools.build:gradle:4.0.0`

**Comment by GlobooX** [comment]
> Use `com.android.tools.build:gradle:4.0.0`

That's work! Thx
