### ISSUE TITLE
HttpSender not working in Xiaomi Redmi Note 8T Android 10

### ISSUE THREAD

**Issue by cmayorga** [ACRA/acra#800]
I am getting crazy to get this to work:

D/ACRA: Building report
D/ACRA: Calling collector org.acra.collector.DropBoxCollector
    Collector org.acra.collector.DropBoxCollector completed
D/ACRA: Calling collector org.acra.collector.CustomDataCollector
    Collector org.acra.collector.CustomDataCollector completed
D/ACRA: Calling collector org.acra.collector.DisplayManagerCollector
D/ACRA: Calling collector org.acra.collector.ConfigurationCollector
D/ACRA: Calling collector org.acra.collector.StacktraceCollector
D/ACRA: Calling collector org.acra.collector.DeviceFeaturesCollector
D/ACRA: Calling collector org.acra.collector.TimeCollector
D/ACRA: Calling collector org.acra.collector.ThreadCollector
    Collector org.acra.collector.ThreadCollector completed
D/ACRA: Calling collector org.acra.collector.SimpleValuesCollector
D/ACRA: Calling collector org.acra.collector.ReflectionCollector
D/ACRA: Calling collector org.acra.collector.MediaCodecListCollector
    Collector org.acra.collector.MediaCodecListCollector completed
D/ACRA: Calling collector org.acra.collector.DeviceIdCollector
D/ACRA: Calling collector org.acra.collector.SharedPreferencesCollector
D/ACRA: Calling collector org.acra.collector.LogCatCollector
D/ACRA: Calling collector org.acra.collector.PackageManagerCollector
D/ACRA: Calling collector org.acra.collector.MemoryInfoCollector
D/ACRA: Calling collector org.acra.collector.LogFileCollector
D/ACRA: Collector org.acra.collector.LogFileCollector completed
D/ACRA: Calling collector org.acra.collector.SettingsCollector
D/ACRA: Collector org.acra.collector.SettingsCollector completed
D/ACRA: Collector org.acra.collector.DeviceIdCollector completed
D/ACRA: Collector org.acra.collector.SharedPreferencesCollector completed
D/ACRA: Collector org.acra.collector.StacktraceCollector completed
D/ACRA: Collector org.acra.collector.PackageManagerCollector completed
D/ACRA: Collector org.acra.collector.TimeCollector completed
D/ACRA: Collector org.acra.collector.SimpleValuesCollector completed
D/ACRA: Collector org.acra.collector.ConfigurationCollector completed
D/ACRA: Retrieving logcat output (buffer:default)...
D/ACRA: Collector org.acra.collector.DeviceFeaturesCollector completed
D/ACRA: Collector org.acra.collector.DisplayManagerCollector completed
D/ACRA: Collector org.acra.collector.ReflectionCollector completed
D/ACRA: Collector org.acra.collector.MemoryInfoCollector completed
D/ACRA: Collector org.acra.collector.LogCatCollector completed
D/ACRA: Finishing activities prior to killing the Process
D/ACRA: Finished class us.cash.MainActivity
D/ACRA: Finished class us.cash.position
D/ACRA: Writing crash report file /data/user/0/XXXXXXXXX/app_ACRA-unapproved/2020-07-23T18:27:16.580+02:00.stacktrace
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
D/ACRA: Mark 2020-07-23T18:27:16.580+02:00.stacktrace as approved.
D/ACRA: Schedule report sending
D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
    Using PluginLoader to find ReportSender factories
D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@2650141]} for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2650141 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
D/ACRA: reportSenderFactories : [org.acra.sender.HttpSenderFactory@99b2720]
D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@2650141]} for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2650141 against plugin class : class org.acra.config.HttpSenderConfiguration
    Adding reportSender : org.acra.sender.HttpSender@fbb98d9
D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
    Using PluginLoader to find ReportSender factories
    ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@2650141]} for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2650141 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
D/ACRA: reportSenderFactories : [org.acra.sender.HttpSenderFactory@cdb954c]
D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@2650141]} for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@2650141 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Adding reportSender : org.acra.sender.HttpSender@5c3e995
    Wait for Interactions + worker ended. Kill Application ? true
W/ACRA: Warning: Acra may behave differently with a debugger attached

It appears all is right, but it is sending nothing, getting no input in the Acrarium output ....

**Comment by mikehardy** [comment]
Xiaomi are infamous for not following Android API contracts - https://dontkillmyapp.com - you should check the unfiltered logcat to see if it refused to start a service or similar, and try configuring the app to avoid battery optimization to see if that fixes it

**Comment by cmayorga** [comment]
Yep, just filtered logcat and found this :( :

2020-07-23 18:44:00.689 1383-2057/? I/AutoStartManagerService: MIUILOG- Reject service :Intent { cmp=XXXXXX/org.acra.sender.JobSenderService } userId : 0 uid : 10217
2020-07-23 18:44:00.689 1383-2057/? D/JobScheduler: Error executing JobStatus{777ab58 #u0a217/0 XXXXXX/org.acra.sender.JobSenderService u=0 s=10217 TIME=none:0 READY}

**Comment by mikehardy** [comment]
As a developer I detest Xiaomi and I communicate why (they do not implement Android APIs correctly) to everyone I see using them, with the recommendation they complain to Xiaomi and purchase a different brand next time.

**Comment by F43nd1r** [comment]
> I can't fix this issue without access to a device with the issue, sorry. I can accept a PR if you manage to fix it yourself.

Just quoting myself here from the other Xiaomi issue.
At this point I'm tempted to close those issues on sight, can't do anything anyway.

**Comment by ElavanResu** [comment]
@cmayorga I have Xiaomi POCO F1 with android 10. If you can tell me what configurations you used maybe I can replicate and test.
HTTP sender and the mailer sender works fine in my mobile, only when I am using Dialog, instead of toast.

**Comment by F43nd1r** [comment]
Superseded by #804
