### ISSUE TITLE
[Question] Effect of ACRA on google play console crash reporting

### ISSUE THREAD

**Issue by ElavanResu** [ACRA/acra#802]
Just got one question, does implementing ACRA affects google play console crash reporting?

I am using ACRA 5.1.3 ( I am updating it to latest version as per the suggestion I got in my previous issue. It's in progress). When I am not using ACRA at all, whenever my app crashes it sends the crash report to google play console ANR and crash section. But when I configure ACRA it doesn't send any reports to google. Does ACRA blocks google crash reporting?

**Comment by F43nd1r** [comment]
ACRA replaces native crash reporting by default. You can enable it with [AcraCore.alsoReportToAndroidFramework](https://www.acra.ch/javadoc/latest/org/acra/annotation/AcraCore.html#alsoReportToAndroidFramework--), but note that this will also display the native crash dialog to the user.

**Comment by ElavanResu** [comment]
Okay, it works with that flag. Thank you.

**Comment by mikehardy** [comment]
If I understand things correctly, I think the precise statement is that it replaces *platform* crash reporting by default *except for native crashes* - which is a little more subtle.

Even with ACRA set as the only reporter, the play store will be where crashes in native libraries go (for instance if you use a WebView in your app, it crashes a *lot* - sometimes for reasons under the applications control - and those all go to play store)

It sounds like you are going to report all crashes to the play store anyway so this may not matter to you, but for anyone else reading, it might be useful to know.

**Comment by F43nd1r** [comment]
Ah, yes. Native is an overloaded word in this case. Platform is better.
