### ISSUE TITLE
Can I Upload App to PlayStore with ACRA Integrated?

### ISSUE THREAD

**Issue by muzeasd** [ACRA/acra#803]
Hello. 

Can I upload my app to PlayStore if I have integrated ACRA with `<uses-permission android:name="android.permission.READ_LOGS"/>` permission? I ask this because as per my understand, this permission is not granted to user applications starting with Android 4.1, although it is granted to system applications and Android Debugging Bridge (ADB).

So how do I handle this? Thanks

**Comment by mikehardy** [comment]
Yes. My project does so all the time (https://play.google.com/store/apps/details?id=com.ichi2.anki) and our target SDK version is at 29 right now I think? Or 28? Way past Android 4 anyway.

If I understand correctly that permission is now "given" freely but only for logs from your own app, which coincidentally is exactly what you need for crash reporting.

It works wonderfully

**Comment by muzeasd** [comment]
Thanks @mikehardy
