### ISSUE TITLE
How Can I use ACRA and Firebase Crashlytics both?

### ISSUE THREAD

**Issue by tushar09** [ACRA/acra#805]
When I am using ACRA my firebase crashlytics is unable to collect the log. I know this is expected. But 
I need to use both of it. 

I want to show the error dialog of acra instead of "Unfortunately App has stopped" and beside this I also want to send the error log to firebase crashlytics. Is there any possibilities to achieve that?

And if I implement my own custom sender then the `AcraMailSender` `AcraDialog` does not work.

**Comment by mikehardy** [comment]
ACRA does not chain default exception handlers, it replaces, yes.
So you set up ACRA first, then chain to Crashlytics.

I don't use Crashlytics in my ACRA-enabled app, but I do want to send things to google analytics at the same time ACRA is configured, so I initialize ACRA first, then I chain the default exception handles myself like this

https://github.com/ankidroid/Anki-Android/blob/2f0af8ff7c5cc18d850aa1fc8c1bdd2c39a6bb1c/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L232-L261

https://github.com/ankidroid/Anki-Android/blob/2f0af8ff7c5cc18d850aa1fc8c1bdd2c39a6bb1c/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java#L123-L132

Looks like crashlytics does the same as my UsageAnalytics class - it chains to the existing handler: 

https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java#L63

So it's an order-of-initialization thing unless ACRA implements chaining to an existing handler. Initialize ACRA first, then initialize Crashlytics at runtime by disabling automatic collection then enabling it after your ACRA init like so https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#enable-reporting

**Comment by F43nd1r** [comment]
ACRA does implement chaining - just initialize ACRA last and enable [`alsoReportToAndroidFramework`](https://www.acra.ch/javadoc/latest/org/acra/annotation/AcraCore.html#alsoReportToAndroidFramework--).

**Comment by tushar09** [comment]
@F43nd1r enabling alsoReportToAndroidFramework shows the "Unfortunately app has stopped"

**Comment by F43nd1r** [comment]
Ah yes - too fast. As @mikehardy noted crashlytics always chains to the next handler. In this case, initialize ACRA first.

**Comment by tushar09** [comment]
@mikehardy I Could not understand your solution. How can I maintain the chain? I have initialized ACRA like below:

```

@AcraCore(buildConfigClass = BuildConfig.class)
@AcraMailSender(mailTo = "wtushar09@gmail.com")
@AcraDialog(reportDialogClass = ErrorReportActivity.class)

public class MainApplication extends MultiDexApplication {
   
    @Override
    public void onCreate() {
        super.onCreate();
        ACRA.init(this);
    }
}
```

**Comment by mikehardy** [comment]
1. read the crashlytics docs on using Android via the opt-in style
1. add the automatic data collection false thing in AndroidManifest per crashlytics opt-in docs
1. initialize ACRA in your startup
1. initialize crashlytics in your startup after ACRA per the crashlytics opt-in docs

**Comment by tushar09** [comment]
I could not solve it. I have tried a lot. After following your steps ACRA does not work. I found that either ACRA or Firebase Crashlytics runs as default crash handler. But not both. I am adding
```
<meta-data
    android:name="firebase_crashlytics_collection_enabled"
    android:value="false" />
```
in manifiest and Initialized them like this way:

```
FirebaseApp.initializeApp(this);
        FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(false);
        ACRA.init(this);
        FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true);
```
But there is not crash reports in firebase.

**Comment by mikehardy** [comment]
@tushar09 that's a shame, I thought that would work based on my read of the code.
@F43nd1r I often wondered why ACRA did not implement default exception handler chaining, as most other crash libraries appear to do it by default, and it makes it tricky to stack multiple app end-of-life handlers

Is this a feature that could be added to ACRA? Respecting installed base and existing behavior it might default to off, but it seems like a sensible change?

**Comment by F43nd1r** [comment]
> ACRA does implement chaining - just initialize ACRA last and enable [`alsoReportToAndroidFramework`](https://www.acra.ch/javadoc/latest/org/acra/annotation/AcraCore.html#alsoReportToAndroidFramework--).

@mikehardy see above.

**Comment by tushar09** [comment]
@F43nd1r I don't want to show the default error dialog. I just need to show the ACRA's custom error dialog and send the error log to the Firebase. So that I can get the log no matter if the user send an email from the ACRA's error dialog or not. 

Beside this I also dont have any personal server so that I can host ACRA Arcalyzer to get the report. So firebase is only one option for me.

**Comment by F43nd1r** [comment]
Alright, I can't quite make sense of Crashlytics initialization process. It seems to be hidden behind 50 abstraction layers.

But I tested an app with ACRA configured as recommended and Crashlytics configured as recommended and it just worked.

Wild guess: Are you initializing ACRA in `onCreate`? It should be in `Application.attachBaseContext`.

**Comment by tushar09** [comment]
@F43nd1r your wild guess was right. Thank you so much. Now I am initializing ACRA in `Application.attachBaseContext` and it worked like a charme.
