### ISSUE TITLE
Crash Report mail not able to attach the crashdata after disabling certain fields in Acracore annotation (5.7.0)

### ISSUE THREAD

**Issue by brajeshnp** [ACRA/acra#807]
1. Initially, with the below mentioned AcraCore parameters, im able to receive the crashdata in the form of mail attachement. 

@AcraCore(
        buildConfigClass = org.acra.BuildConfig.class,
        logcatArguments = {"-t", "200", "-v", "time"},
        reportFormat= StringFormat.JSON,
        reportContent = {
                ReportField.REPORT_ID,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_CRASH_DATE,
                ReportField.DEVICE_ID,
                ReportField.BRAND,
                ReportField.BUILD,
                ReportField.PACKAGE_NAME,
                ReportField.APP_VERSION_NAME,
                ReportField.APP_VERSION_CODE,
                ReportField.ANDROID_VERSION,
                ReportField.PHONE_MODEL,
                ReportField.DEVICE_FEATURES,
                ReportField.CUSTOM_DATA,
                ReportField.STACK_TRACE,
                ReportField.LOGCAT,
                ReportField.APPLICATION_LOG,
                ReportField.USER_EMAIL
        }
)

2. Now, i commented out ReportField.LOGCAT, ReportField.APPLICATION_LOG, ReportField.DEVICE_FEATURES, ReportField.CUSTOM_DATA, fields from the AcraCore config. Still the mail came with attachement. 

3. In the next step i commented out this field **logcatArguments = {"-t", "200", "-v", "time"},**  along with other fields that are commented in step 2

4. On detecting a crash, it opens the mail client, but there is no attachment, it shows a toast "Unable to attach file" 

5. I uncommented all the fields that are commented in steps 2 and 3 , still it is not able to attach the crash logs eventhough ACRA detects crash and opens the mail client ( it still shows toast "Unable to attach file" 

6. After keeping the device idle for sometime, say 5-10 mins or so( the time taken to compose this issue), without any change in code, on next attempt, ACRA detected the crash, the mail client opened and the attachment was there.

**Is this a known bug or am i doing something wrong here ?** 
[mydevicelogs_1.txt](https://github.com/ACRA/acra/files/5182151/mydevicelogs_1.txt)  - **logs when it failed to attach the crashdata**

[mydevicelogs_2.txt](https://github.com/ACRA/acra/files/5182234/mydevicelogs_2.txt) **- Logs when it again started working**

**Comment by brajeshnpmoolya** [comment]
This looks like an issue with the mail client(Gmail) version on the device... even it works sometimes on the same device  ... checked in on another device, it works there also with gmail client...

Hence closing this issue as it is not related to ACRA

**Comment by timbze** [comment]
I am wondering if Gmail does not accept mail text once it's over a certain length. Other mail apps still work.

**Comment by F43nd1r** [comment]
I've never seen this before:
```09-07 13:43:29.253  1747  2373 W ActivityManager: Permission Denial: opening provider org.acra.attachment.AcraContentProvider from ProcessRecord{5c0840 8694:com.google.android.gm/u0a175} (pid=8694, uid=10175) that is not exported from UID 10192
09-07 13:43:29.254  8694  8694 W Gmail   : Gmail:Failed to read either size or name column from metadata cursor
09-07 13:43:29.255  1747  2640 W ActivityManager: Permission Denial: opening provider org.acra.attachment.AcraContentProvider from ProcessRecord{5c0840 8694:com.google.android.gm/u0a175} (pid=8694, uid=10175) that is not exported from UID 10192
09-07 13:43:29.258  8694  8694 W Gmail   : Gmail:Could not read size column from metadata cursor
09-07 13:43:29.263  8694  8694 E Gmail   : ComposeActivity:Error adding attachment
09-07 13:43:29.263  8694  8694 E Gmail   : gny: SecurityException when openAssetFileDescriptor.
09-07 13:43:29.263  8694  8694 E Gmail   : 	at gnz.a(PG:5)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at gnz.a(PG:45)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dvf.a(PG:141)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dum.run(PG:2)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dvf.a(PG:180)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dvf.a(PG:148)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dvf.a(PG:447)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at dre.a(Unknown Source:24)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at bbyz.a(Unknown Source:19)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at bejv.a(Unknown Source:2)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at bejx.run(PG:9)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at bbxa.run(PG:2)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at arbu.run(Unknown Source:18)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at android.os.Handler.handleCallback(Handler.java:883)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at android.os.Looper.loop(Looper.java:214)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at android.app.ActivityThread.main(ActivityThread.java:7397)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at java.lang.reflect.Method.invoke(Native Method)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-07 13:43:29.263  8694  8694 E Gmail   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
09-07 13:43:29.268  7404  7577 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=7579 bindings:W S state:3 counts:0,0,0,1,
09-07 13:43:29.269  2354  2354 I Zygote  : Process 7579 exited due to signal 9 (Killed)
09-07 13:43:29.258  1747  2640 I chatty  : uid=1000(system) Binder:1747_8 identical 2 lines
09-07 13:43:29.259  1747  2640 W ActivityManager: Permission Denial: opening provider org.acra.attachment.AcraContentProvider from ProcessRecord{5c0840 8694:com.google.android.gm/u0a175} (pid=8694, uid=10175) that is not exported from UID 10192
```
Can you deobfuscate that crash?

**Comment by NLLAPPS** [comment]
I have the same problem but cannot see such exception in the logs.

I see something like 

2020-10-10 14:58:30.437 1604-4298/? I/ActivityTaskManager: START u0 {act=android.intent.action.SENDTO dat=mailto:xx@xxxxxxx.xxx flg=0x10000000 cmp=com.google.android.gm/.ComposeActivityGmailExternal (has extras)} from uid 10301
2020-10-10 14:58:30.686 6190-6190/? W/Gmail: ComposeActivity:b/119949571:In finishSetup.
2020-10-10 14:58:30.686 6190-6190/? W/Gmail: Gmail:b/119949571:loading bodyWebView with template emit size of 2091.
2020-10-10 14:58:30.714 6190-10642/? E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/wa_discover.js
2020-10-10 14:58:30.732 6190-6190/? E/Gmail: Gmail:EditWebView JS Console: b/119949571:draft.editor.onLoad; source: file:///android_asset/draft_editor_gmail_compiled.js at 99
2020-10-10 14:58:30.745 6190-6190/? E/Gmail: Gmail:EditWebView JS Console: b/119949571:draft.editor.onLoad is finished; source: file:///android_asset/draft_editor_gmail_compiled.js at 100



My config is


initAcra {
                setBuildConfigClass(BuildConfig::class.java)
                setReportFormat(StringFormat.KEY_VALUE_LIST)
                setReportContent(ReportField.USER_COMMENT,
                        ReportField.PACKAGE_NAME,
                        ReportField.APP_VERSION_NAME,
                        ReportField.ANDROID_VERSION,
                        ReportField.BRAND,
                        ReportField.PHONE_MODEL,
                        ReportField.PRODUCT,
                        ReportField.USER_APP_START_DATE,
                        ReportField.USER_CRASH_DATE,
                        ReportField.STACK_TRACE,
                        ReportField.LOGCAT)

                plugin<MailSenderConfigurationBuilder> {
                    setEnabled(true)
                    setMailTo(Constants.contactEmail)
                    setReportAsFile(false)
                }

                plugin<NotificationConfigurationBuilder> {
                    setEnabled(true)
                    setTitle(getString(R.string.crash_notif_title))
                    setText(getString(R.string.crash_dialog_text))
                    setChannelName(getString(R.string.app_crash_notification_channel))
                    setSendButtonText(getString(R.string.send))
                    setDiscardButtonText(getString(R.string.cancel))
                    setSendOnClick(true)

                    setResDiscardButtonIcon(R.drawable.crash_log_discard)
                    setResSendButtonIcon(R.drawable.crash_log_send)
                }

**Comment by F43nd1r** [comment]
@NLLAPPS I don't think yours is the same problem. It is known that big reports don't work with `setReportAsFile(false)`, which is why we have `setReportAsFile(true)` - that is the fix in your case.

@brajeshnp `buildConfigClass = org.acra.BuildConfig.class` this should be your own BuildConfig, not ACRAs.
I was only able to reproduce this issue if the app was started through android studio. It did not show up when started using the normal app launcher. Can you confirm this behaviour?

**Comment by brajeshnpmoolya** [comment]
> @NLLAPPS I don't think yours is the same problem. It is known that big reports don't work with `setReportAsFile(false)`, which is why we have `setReportAsFile(true)` - that is the fix in your case.
> 
> @brajeshnp `buildConfigClass = org.acra.BuildConfig.class` this should be your own BuildConfig, not ACRAs.
> I was only able to reproduce this issue if the app was started through android studio. It did not show up when started using the normal app launcher. Can you confirm this behaviour?

I have only tested this by launching it through Android studio. Haven't done this through normal app launcher. Currently, the setup where i reproduced this issue is not available, hence cannot confirm the behaviour while launching it through app launcher.
