### ISSUE TITLE
losing org.acra.config.CoreConfiguration & org.acra.config.SchedulerConfiguration

### ISSUE THREAD

**Issue by SoaringAnecdotalBear** [ACRA/acra#808]
why threre is not class CoreConfiguration nor class SchedulerConfiguration in acra\acra-core\src\main\java\org\acra\config  ?but some other classes import them.

**Comment by F43nd1r** [comment]
Duplicate of #758

**Comment by F43nd1r** [comment]
Explanation is here: https://github.com/ACRA/acra/issues/677#issuecomment-401548693.
