### ISSUE TITLE
How to configure ACRA Dialog in Android Gradle Plugin v5 compatible way?

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#810]
**Required reading**
https://github.com/ACRA/acra/wiki/How-to-debug-ACRA

**Describe the bug**
[The annotation style of configuring ACRA recommends using annotations set to 'R' values](https://github.com/ACRA/acra/wiki/Interactions#notification), but Android Gradle Plugin v5 will apparently have non-constant 'R' values, meaning a different style is needed

For instance, this will throw a new deprecation warning:

```

@AcraDialog(
        reportDialogClass = AnkiDroidCrashReportDialog.class,
        resCommentPrompt =  R.string.empty_string,
        resTitle =  R.string.feedback_title,
        resText =  R.string.feedback_default_text,
        resPositiveButtonText = R.string.feedback_report,
        resIcon = R.drawable.logo_star_144dp
)
@AcraHttpSender(
        httpMethod = HttpSender.Method.PUT,
        uri = BuildConfig.ACRA_URL
)
@AcraToast(
        resText = R.string.feedback_auto_toast_text
)
```

It is a new deprecation in Android Gradle Plugin 4.1

```
Avoid the usage of resource IDs where constant expressions are required.

A future version of the Android Gradle Plugin will generate R classes with
non-constant IDs in order to improve the performance of incremental compilation.
```

It may be suppressed temporarily like so:

```
@SuppressLint("NonConstantResourceId")
```

In a similar context in Java, the recommendation is to alter code from switch with cases using the 'R' values (which I suppose must be constant to work in case statements?) to chained if: https://issuetracker.google.com/issues/159878591#comment13

But I'm not sure what transformation to use for annotations. In the connected issue where Butterknife (which also takes config as annotations that use R values) they simply say "don't use Butterknife", so that's not helpful. 

Perhaps a switch to specifying the name of the resource, then ACRA does the id lookup and uses it? https://developer.android.com/reference/android/content/res/Resources.html#getIdentifier(java.lang.String,%20java.lang.String,%20java.lang.String)

**Expected behavior**
No deprecation warnings with recommended initialization style

**Version**
 - Android Gradle Plugin 4.1.0
 - ACRA 5.7.0

**Comment by F43nd1r** [comment]
ugh.

I'll probably just opt for deprecating the annotation configuration in favor of an improved kotlin dsl/java builder.

**Comment by mikehardy** [comment]
As a library consumer the configuration by annotation is interesting but I don't mind having to configure an object with a builder

On the plus side, it's deprecation for a future version and the deprecation warning was added just days ago. I'm just suppressing lint right now (we normally abort on deprecation so we're forced to proactively suppress and then track them honestly in our issue tracker)

**Comment by benardelia** [comment]
This is much impacted as i have large old kotlin project which half of its classes uses butterknife, its in a point where i couldn't change the style of stop using R value where the constant values required
