### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/util/Predicate;

### ISSUE THREAD

**Issue by dolarbhanderi-meka** [ACRA/acra#811]
Class not found exception occurs in version (R)30

ACRA.init(this);

ACRA  give error Failed resolution of: Lcom/android/internal/util/Predicate  when i changed target version 30.

**Comment by F43nd1r** [comment]
You're using an old version, update.

**Comment by F43nd1r** [comment]
Duplicate of #785
