### ISSUE TITLE
JobSenderService cannot be executed on my device

### ISSUE THREAD

**Issue by chenyan-github** [ACRA/acra#812]
Customer define YourOwnSender and send method not called and I debug find JobSenderService cannot be start. 

**Version**
 - Android: 10
 - ACRA:  implementation "ch.acra:acra-core:5.7.0"
 - Code: 

```
@AcraCore(
    buildConfigClass = BuildConfig::class,
    reportFormat = StringFormat.JSON,
    applicationLogFile = "applog.log",
    applicationLogFileDir = Directory.FILES,
    reportContent = [ReportField.APP_VERSION_NAME, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL, ReportField.CUSTOM_DATA, ReportField.STACK_TRACE, ReportField.LOGCAT],
    reportSenderFactoryClasses = [YourOwnSenderfactory::class])
open class MyApplication : Application() {
...
  override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(base)
        ACRA.DEV_LOGGING = true
        ACRA.init(this)
    }
}
```
``` 
public class YourOwnSenderfactory implements ReportSenderFactory {

    @Override
    public ReportSender create(Context context, CoreConfiguration config) {
        return new YourOwnSender();
    }

    @Override
    public boolean enabled(@NonNull CoreConfiguration coreConfig) {
        return true;
    }
}

public class YourOwnSender implements ReportSender {

    @Override
    public void send(Context context, CrashReportData report) throws ReportSenderException {
        try {
            Log.e("YourOwnSender", report.toJSON());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by F43nd1r** [comment]
You got a Xiaomi device?

**Comment by chenyan-github** [comment]
Yes, I override requiresForeground method return true to solved.
 this is my send CrashReportData.
{
    "IS_SILENT":false,
    "ANDROID_VERSION":"9",
    "APP_VERSION_NAME":"1.0",
    "USER_CRASH_DATE":"2020-10-16T20:27:15.649+08:00",
    "STACK_TRACE":"java.lang.RuntimeException: click test
	at com.cy.imagepreview.MainActivity$onCreate$1.onClick(MainActivity.kt:32)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
",
    "PHONE_MODEL":"Mi Note 3",
    "REPORT_ID":"c3c7446e-df24-47b6-9265-c5a54e3d6c4f"
}

```
public class YourOwnSender implements ReportSender {

    @Override
    public void send(Context context, CrashReportData report) throws ReportSenderException {
        try {
            Log.e("YourOwnSender", report.toJSON());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public boolean requiresForeground() {
        return true;
    }
}
```

**Comment by chenyan-github** [comment]
<img width="980" alt="图片" src="https://user-images.githubusercontent.com/26321493/96260080-180d6c80-0ff1-11eb-864a-57b58444ff9c.png">

**Comment by chenyan-github** [comment]
en, because jobservice cannnot be executed is a issue

**Comment by F43nd1r** [comment]
Yeah, a known issue, specifically #804 

This isn't ACRAs fault, Xiaomi messed up their android implementation. We are working on a potential workaround, follow that issue for progress.
