### ISSUE TITLE
Empty email draft using GMail 

### ISSUE THREAD

**Issue by ilingleb117** [ACRA/acra#815]
I made GMail work without attachments

https://github.com/ACRA/acra/blob/3b90348c64c07e7dfad10c2750abfb9b94fcd41a/acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java#L167

    protected Intent buildResolveIntent(@NonNull String subject, @NonNull String body) {
        final Intent intent = new Intent(Intent.ACTION_SEND);
        intent.putExtra(Intent.EXTRA_EMAIL, new String[] { mailConfig.mailTo() });
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.putExtra(Intent.EXTRA_SUBJECT, subject);
        intent.putExtra(Intent.EXTRA_TEXT, body);
        intent.setType("message/rfc822");
        return intent;
    }

**Comment by F43nd1r** [comment]
`ACTION_SENDTO` needs to be used instead of `ACTION_SEND` because otherwise a lot of useless non-email apps will pick up on the intent, e.g. bluetooth share.

**Comment by ilingleb117** [comment]
And if so?
```
    protected Intent buildResolveIntent(@NonNull String subject, @NonNull String body) {
        final Intent intent = new Intent(Intent.ACTION_SENDTO);
        String uriStr = "mailto:" + mailConfig.mailTo() + "?subject=" + subject + "&body=" + body;
        uriStr = uriStr.replace(" ", "%20");
        Uri uri = Uri.parse(uriStr);
        intent.setData(uri);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        return intent;
    }
```

**Comment by F43nd1r** [comment]
What exactly are you trying to fix?

**Comment by ilingleb117** [comment]
If message body (with uri and subject) is in data of intent, draft in GMail will not be empty. If you use setData only with a list of email addresses, then putExtra (Intent.EXTRA_SUBJECT, subject) and Intent.EXTRA_TEXT, body), you get this https://github.com/commons-app/apps-android-commons/issues/3466#issue-576270860
