### ISSUE TITLE
How to send custom logs event to server 

### ISSUE THREAD

**Issue by mohammadrezaberenji** [ACRA/acra#820]
I need to send custom data to the server whenever I need not just after crashing. I implement the arca backend and deploy it to the server. i used the approach to send custom data for logs not just when the app crashed.

```java
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate: ");
        ACRA.getErrorReporter().setEnabled(true);
        ACRA.getErrorReporter().putCustomData("Event at " + System.currentTimeMillis(), "MainActivity");
}
```

also, I set this config for arca in-app class : 
```java
@AcraCore(
        buildConfigClass = BuildConfig.class,
        reportFormat= StringFormat.JSON,
        logcatArguments = {"-t", "100", "-v", "acra", "acra", "*:S"},
        reportContent = {ReportField.ANDROID_VERSION, ReportField.ANDROID_VERSION, ReportField.PHONE_MODEL})
@AcraHttpSender(
        uri = "server_address",
        basicAuthLogin = "user",
        basicAuthPassword = "pass",
        httpMethod = HttpSender.Method.POST)
@AcraToast(resText = R.string.acra_hint, length = Toast.LENGTH_LONG)
```
but when I checked the dashboard there are no logs in it. I think the connection is not established over HTTP. how can solve this problem?  and also how I can notice that acra sends log to server? i also enable ACRA.DEV_LOGGING but I couldn't found any logs for sending data to the server

**Comment by F43nd1r** [comment]
You need to call ACRA.init before you can use it.
Then you can call ACRA.getErrorReporter().handleSilentException(null)

**Comment by mohammadrezaberenji** [comment]
@F43nd1r i call ACRA.init once in application class. does it need to be call in each class that i want to send logs ?

**Comment by F43nd1r** [comment]
Once is enough. You didn't show it in your snippets, so I mentioned it. Also this line is redundant `ACRA.getErrorReporter().setEnabled(true);`

**Comment by F43nd1r** [comment]
Include CUSTOM_DATA in your report content.

**Comment by mohammadrezaberenji** [comment]
thanks for your tips. I have another question. acra is enabled now and it sending data and crashes. but when acra catch crashes and sends logs, fire base crashlytics does not send any logs for crash. how could I enable to use both?

**Comment by F43nd1r** [comment]
See #805
