### ISSUE TITLE
Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

### ISSUE THREAD

**Issue by asajadi84** [ACRA/acra#821]
Hello there.
The title probably explains itself. When I try to use `ArcaDialog` annotation the Android Studio linter gives me this message:

`Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes`

Isn't there a way to pass `resText` and `resCommentPrompt` in another way rather than resource ids?

**Comment by F43nd1r** [comment]
Duplicate of #810
