### ISSUE TITLE
Hide send button icon in notification

### ISSUE THREAD

**Issue by mueller-ma** [ACRA/acra#822]
I'm using the notification module in ACRA 5.7.0. How can I hide the icons of the send and discard button?

**Comment by F43nd1r** [comment]
Sorry it took me a while to test this. You can just pass `0` as the icon resource to disable it.

**Comment by mueller-ma** [comment]
I passed `0`, but now the notification isn't shown at all. After a crash ACRA wants to send the mail:
````kotlin
            getPluginConfigurationBuilder(NotificationConfigurationBuilder::class.java).apply {
                setEnabled(true)

                setResIcon(R.drawable.ic_openhab_appicon_white_24dp)
                setResTitle(R.string.crash_report_notification_title)
                setResText(R.string.crash_report_notification_text)
                setResSendButtonText(R.string.crash_report_notification_send_mail)
                setResSendButtonIcon(R.drawable.ic_openhab_appicon_white_24dp)
                setResDiscardButtonIcon(R.drawable.ic_openhab_appicon_white_24dp)

                setResChannelName(R.string.notification_channel_crash_reports)
                setResChannelDescription(R.string.notification_channel_crash_reports_description)

                setSendOnClick(false)
            }
````

**Comment by F43nd1r** [comment]
What's your device, acra and android version?

**Comment by mueller-ma** [comment]
Amazon Fire Tablet with FireOS (ROM Based on Android 5.1.1) and Acra 5.7.0

**Comment by F43nd1r** [comment]
I've tested on an API 22 emulator and it works fine for me. Here's my config (using ACRA 5.8.0 config form, but that shouldn't change the logic)
```kotlin
initAcra {
    httpSender {
            ...
    }
    notification {
        title = getString(R.string.notification_title)
        text = getString(R.string.notification_text)
        channelName = "acra-test"
        resSendButtonIcon = 0
        enabled = true
    }
}
```

You can check if you find anything in the logs to help us here, or try if 5.8.0 makes a difference. Other than that I'm lost on this.

**Comment by mueller-ma** [comment]
I'm going to check this again after 5.8 has been released.

**Comment by mueller-ma** [comment]
With 5.8.1 the notification now shows up on my device.
