### ISSUE TITLE
how to generate CrashID for a specific crash issue on multiple devices?

### ISSUE THREAD

**Issue by praveenb** [ACRA/acra#823]
Hi,

Is it possible to generate a Crash ID for specific crash issue on a device. So if same crash issue happen on another device, it should also give same Crash ID.

This way we can know the Crash issues on multiple devices are same or different.

Thank you.

**Comment by F43nd1r** [comment]
It is impossible to identify if two crashes on different devices are the same.
You can always compare the stacktraces, but there will be subtle differences based on android and device version.
