### ISSUE TITLE
How to attach custom files

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#826]
So i was checking throuh Wiki on how to attach custom files to Email Reporting but was not able to find something usefull except #577 PR which looks like it added support for attachments. Are there any GIST or something how to attach new files ?

**Comment by F43nd1r** [comment]
I've written a short block on attachments [here](https://github.com/ACRA/acra/wiki/AdvancedUsage#adding-file-attachments-to-reports). 
The feature was introduced in #560.

**Comment by arcanewater** [comment]
Thanks!
