### ISSUE TITLE
Is it possible to redact the crash stacktrace before sending?

### ISSUE THREAD

**Issue by martynamaron** [ACRA/acra#827]
We have found that some [`SocketTimeoutExceptions` may contain **source IP addresses** in their messages](https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/io/IoBridge.java#190). Due to the company policy, we need to ensure that no Personal Identifiable Information (PII) is being collected by any of our services or that we block any access to it from our end.

We've taken care of redacting error logs and exception stacktraces that would end up in an ACRA report when logging silent exceptions, but I'm wondering if it's possible to redact the stacktrace of a crash log at all? I'm aware that:
- it's unlikely we'd let the app crash with a `SocketTimeoutException`
- unlikely that many other exceptions print out IP addresses in their messages
- the same crash log would end up in Play console, unredacted

But we'd like to take some proactive steps to prove we're doing anything we can to avoid collecting PII where possible.

Would redacting the crash stacktrace be a case of implementing a `Collector` extension containing code similar to the [`StacktraceCollector`](https://github.com/ACRA/acra/blob/master/acra-core/src/main/java/org/acra/collector/StacktraceCollector.kt) but just making sure the stacktrace is redacted?

**Comment by F43nd1r** [comment]
Yes, a custom collector would work. An alternative would be to do the processing in a custom sender, e.g. by overriding `HttpSender.convertToString`.

**Comment by martynamaron** [comment]
Thanks @F43nd1r! 🙏🏻 
One more question - if I were to implement a custom collector or a sender, I'm just a bit confused as to where those extensions would go - directly into my Android project, using the annotations for example? Or do I need to fork this repo, add the new implementation there and make use of that fork in my project instead?

**Comment by F43nd1r** [comment]
No need to fork, see https://github.com/ACRA/acra/wiki/Custom-Extensions

**Comment by martynamaron** [comment]
So that's hasn't worked for me so far... I've implemented a `RedactedStacktraceCollector` class which is virtually this:

```
@AutoService(Collector::class)
class RedactedStacktraceCollector : Collector {

    override fun getOrder(): Collector.Order {
        return Collector.Order.FIRST
    }

    override fun collect(context: Context, config: CoreConfiguration, reportBuilder: ReportBuilder, crashReportData: CrashReportData) {
        try {
            crashReportData.put("REDACTED_STACK_TRACE", getRedactedStackTrace(reportBuilder.message, reportBuilder.exception))
        } catch (t: Exception) {
            crashReportData.put("REDACTED_STACK_TRACE", null as String?)
            throw CollectorException("Error while retrieving " + ReportField.STACK_TRACE.name + " data:" + t.message, t)
        }

    }

    private fun getRedactedStackTrace(message: String?, throwable: Throwable?): String { ...}
}
```

And I've disabled the `STACK_TRACE` report field when building the ACRA configuration. Still, I get the `STACK_TRACE` section in the ACRA report when I crash the app and no `REDACTED_STACK_TRACE` field. What have I missed? 🤔 

I also realised that the automatic stack trace deobfuscation probably won't work anymore once I only send the redacted stack traces, right? Perhaps a better option would be using a custom sender like you suggested before?

**Comment by F43nd1r** [comment]
> Still, I get the STACK_TRACE section in the ACRA report when I crash the app

Yeah, I forgot about this. STACK_TRACE jhas special handling and can't be disabled. Better do do post processing in this case.

> no REDACTED_STACK_TRACE field

That probably means your annotation processing isn't set up correctly. Remember you need to use kapt instead of apt when using kotlin.

> I also realised that the automatic stack trace deobfuscation probably won't work anymore once I only send the redacted stack traces, right? Perhaps a better option would be using a custom sender like you suggested before?

Yeah post processing is better here. You can use a custom sender or a [`ReportingAdministrator`](https://www.acra.ch/javadoc/latest/org/acra/config/ReportingAdministrator.html#shouldSendReport-android.content.Context-org.acra.config.CoreConfiguration-org.acra.data.CrashReportData-).

**Comment by martynamaron** [comment]
> Remember you need to use kapt instead of apt when using kotlin.

Right, that was indeed the problem, I'm getting the `REDACTED_STACK_TRACE` field as expected now, thanks!

I'll try with post processing though, to redact the actual stack trace as you suggested 🙌🏻
