### ISSUE TITLE
Attach zip files to MailSender after crash happened

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#829]
Is it possible to ZIP files before we open MailSenderConfiguration? I know there is out of the box support for setAttachmentUris on CoreConfiguration but in this case file must exists? What i want to do is that after crash happens and before i open Email client i want to zip files and attach them to mail. Is this something where i am supposed to use **ReportSenderFactory** or should i just somehow extend CoreConfiguration attachmentUris?

**Comment by F43nd1r** [comment]
Use a `AttachmentUriProvider` to generate your zip file and return it's uri to acra.

**Comment by arcanewater** [comment]
But in this case you probably have to use FileProvider as ACRA is in different process?

**Comment by F43nd1r** [comment]
You `AttachmentUriProvider` will be called by ACRA in the sender service process. You can use ACRAs integrated content provider.
