### ISSUE TITLE
Huawei mail intent (gmail )is empty when choosing intent is prompted

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#831]
It seems that on Huawei devices if device does not have default mail client set such as Gmail and is prompted to choose email client i get empty mail without body and attachments, in logs i can only see 

`19417 19417 W ACRA    : No email client supporting attachments found. Attachments will be ignored`

but Gmail was choose to send. I came across following thing: https://stackoverflow.com/questions/59314608/android-studio-mailto-intent-doesnt-show-subject-and-mail-body/59365539#59365539

but i am unable to override to set this selector as then i receive error `Can't set package name when selector is already set`

Any idea how to solve this issue?

**Comment by arcanewater** [comment]
Awesome thanks! When can we expect new release ?

**Comment by F43nd1r** [comment]
Working on it today. Due to bintray/cjenter shutting down I need to rework the release process, so it may take some time.

**Comment by F43nd1r** [comment]
https://github.com/ACRA/acra/releases/tag/acra-5.8.0-beta5 done.
