### ISSUE TITLE
Accessing Acra Dialog directly

### ISSUE THREAD

**Issue by ritvij14** [ACRA/acra#833]
Hello,
I wanted to ask, is there a way to access the Acra Dialog directly? For example, pressing a specific button could trigger it?

**Comment by F43nd1r** [comment]
Does this help you? https://github.com/ACRA/acra/wiki/AdvancedUsage#sending-reports-for-caught-exceptions-or-for-unexpected-application-state-without-any-exception

**Comment by ritvij14** [comment]
@F43nd1r thanks for the help! :D
