### ISSUE TITLE
Open class for EmailIntentSender

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#836]
Is it possible to leave EmailIntentSender as open class? 

This commit closed it: https://github.com/ACRA/acra/commit/b2ebba203bc99e1aea3148e074cb9865110ce5bb#diff-4d22a6c00d9fa51ce55d30d98f444e547ad6d33a9885cec3b157c15cc51019f5R50

I am using buildAttachmentIntent to provide some additional data to body as its not available at the startup.

**Comment by F43nd1r** [comment]
The class is open due to the @OpenAPI annotation on the implemented interface. The keyword wasn't necessary anymore.

**Comment by F43nd1r** [comment]
Sorry for closing this issue so quickly. While it should've been working, it wasn't. Now really fixed in beta8
