### ISSUE TITLE
Handle exception not accepting null

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#841]
With recent change handleException is not accepting null to force send logs as mentioned in API

```
 /**
     * Send a normal report for the given exception
     *
     * @param e              The [Throwable] to be reported. If null the report will contain a new Exception("Report requested by developer").
     * @param endApplication if you want the application to be ended after sending the report.
     */
    fun handleException(e: Throwable, endApplication: Boolean)
```

i guess it should be e: Throwable?

**Comment by arcanewater** [comment]
Thanks for quick fix, possible release with this fix ?

**Comment by F43nd1r** [comment]
I'd rather wait for a more important bug to come up, to reduce the release spam a bit. You can just use `new RuntimeException("Report requested by developer")` instead of `null`. Should give almost the same behaviour.
