### ISSUE TITLE
LimiterData access enhancement request

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#843]
**Describe the bug**

I would like to be able to see the LimiterData that my app has generated, so that I can reason about how recently a report has happened, and can then present slightly different user experiences if a user is attempting to (for example) manually submit a "definitely send it / ignore limiter data" bug report too frequently

**Expected behavior**

Basically, I want to do this - this is actual code I'm using but you can see we are toggling access protection off:

```java

        private long getTimestampOfLastReport(AnkiActivity activity) {
            // If the user canceled the report and tried again, it appears they have clicked
            // Inspect approved / sent reports in order to tell if they have actually sent something.
            long mostRecentTimestamp = -1;
            try {
                LimiterData limiterData = LimiterData.load(activity);
                Field limiterDataListField = limiterData.getClass().getDeclaredField("list");
                limiterDataListField.setAccessible(true);
                List<LimiterData.ReportMetadata> limiterDataList = (List<LimiterData.ReportMetadata>)limiterDataListField.get(limiterData);
                for (LimiterData.ReportMetadata report : limiterDataList) {
                    if (report.getExceptionClass().equals(UserSubmittedException.class.getName())) {
                        Method timestampMethod = report.getClass().getDeclaredMethod("getTimestamp");
                        timestampMethod.setAccessible(true);
                        Calendar timestamp = (Calendar)timestampMethod.invoke(report);
                        if (timestamp.getTimeInMillis() > mostRecentTimestamp) {
                            mostRecentTimestamp = timestamp.getTimeInMillis();
                        }
                    }
                }
            } catch (Exception e) {
                Timber.w(e, "Unexpected exception checking for recent reports");
            }

            return mostRecentTimestamp;
        }
```

With apologies, I'd actually propose a PR but I haven't coded Kotlin before and I'm not sure exactly what change to make in order to allow access to the ReportMetadata list and it's getTimestamp method, and the code has moved from Java to Kotlin between the version I'm toggling above (5.7.0) and the upcoming 5.8.0 so I'm quite uncertain how to manage it.

Seems reasonable though, especially if the list returned was a copy or immutable in some way - I'm not trying to monkey around with internal data structures, I just want to know when the last entry in the limiter data for a given exception was

**Version**
 - ACRA 5.7.0

**Comment by F43nd1r** [comment]
This is already possible in ACRA 5.8. You can read (or even write) the limiterdata:
```java
long mostRecentTimestamp = LimiterData.load(this).getReportMetadata().stream()
    .filter(report -> report.getExceptionClass().equals(UserSubmittedException.class.getName()))
    .mapToLong(report -> report.getTimestamp().getTimeInMillis())
    .max().orElse(-1);
```

**Comment by mikehardy** [comment]
Fantastic! Thanks - hadn't tried 5.8.0 yet since it requires me to alter my config style - if I understand correctly - since I'm using annotations and I treat deprecation as error on build. But I will file that snippet away and I look forward to getting my forward porting done. Thanks @F43nd1r

**Comment by mikehardy** [comment]
Only took me 1.5 years but finally had a chance to finish up the AnkiDroid update to ACRA-current, and just wanted to say I really appreciate the code block above, works great with the new versions :trophy: :beer: :smile:
