### ISSUE TITLE
AutoService doesn't work for registering custom sender in a pure java project

### ISSUE THREAD

**Issue by draekko** [ACRA/acra#852]
AutoService doesn't work for registering custom sender in a pure java project on 5.8.1 and there is no sample code for it in the codebase for the new changes since reportSenderFactoryClasses was removed.

**Comment by draekko** [comment]
Also I did take a look at #847 before posting both of my issues and tried to convert that to a pure java project but that didn't work either.

**Comment by draekko** [comment]
Originally i was also trying to extend hasplugin as per 847 but that was failing bad then removed it and tried as this and it was still failing.

`
@AutoService(ReportSenderFactory.class)
public class VideoEmailReportSenderFactory implements ReportSenderFactory {

    @Override
    public ReportSender create(Context context, CoreConfiguration coreConfiguration) {
        return new VideoEmailReportSender(context, coreConfiguration);
    }

    @Override
    public boolean enabled(CoreConfiguration coreConfiguration) {
        return true;
    }
}
`

but it works with this

`
@AutoService(ReportSenderFactory.class)
public class VideoEmailReportSenderFactory implements ReportSenderFactory {
    @Override
    public ReportSender create(Context context, CoreConfiguration coreConfiguration) {
        return new VideoEmailReportSender(context, coreConfiguration);
    }
}
`

Whats the real use for the enabled method?

**Comment by F43nd1r** [comment]
> it works with this

Nice to see you figured it out. The top should be no different though.

> Whats the real use for the enabled method?

It is used internally to allow you to disable plugins that are on the classpath but not used. For example if you override one of the default senders you need to disable the original one.

**Comment by draekko** [comment]
I spent a little over two days trying to figure it out and why it was failing. The Kotlin version per #847 had extended another class as well as implementing ReportSenderFactory and it was what threw me in the wrong direction, looking at the actual code in acra was somewhat confusing since it didn't seem apply and i figured i was missing something obvious by last night. This morning i started stripping everything one by one until i arrived at number two up there.

The top one was auto generated by android studio when it asked to implement methods when i tried to create a new ReportSenderFactory for testing.  Maybe adding a note somewhere that its not needed would help :)

Well hopefully someone stuck with a java only project will stumble onto this issue in the tracker and not waste so much time.

Have a good one.

**Comment by F43nd1r** [comment]
https://www.acra.ch/docs/Senders/#registering-your-sender updated with senders in example projects.
