### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by chanben2005** [ACRA/acra#854]
1. How to make dialog comment text equal mail body?
![Screenshot_20210603_162948](https://user-images.githubusercontent.com/34121011/120614193-8d975180-c489-11eb-9664-751d60b4fa24.png)

2.  I click the KEYCODE_BACK button, it will hold the app title.
     I need to double click KEYCODE_BACK button for quit.
![adf](https://user-images.githubusercontent.com/34121011/120614907-4fe6f880-c48a-11eb-9077-05d93d42a22d.png)

3. Can auto newline for report File ?

Thank you!

**Comment by chanben2005** [comment]
3. Can auto newline for report File ?
Thank you!

**Comment by F43nd1r** [comment]
1. Using either a custom Dialog class or a custom Mail Sender.
2. Seems like a bug, I'll investigate.
3. Use `StringFormat.KEY_VALUE_LIST` for readability.

**Comment by chanben2005** [comment]
1. Have some example? Is it this one?
[]( https://github.com/ACRA/acra/wiki/Examples)
[](https://github.com/ACRA/acra/wiki/Custom-Extensions)

**Comment by F43nd1r** [comment]
https://www.acra.ch/docs/Senders#implementing-your-own-sender extend from MailSender
https://www.acra.ch/docs/Interactions#dialog extend from CrashReportDialog

**Comment by chanben2005** [comment]
Thank you for your guidance. I will try it.
