### ISSUE TITLE
Default NotificationConfigurationBuilder and MailSenderConfigurationBuilder - do not opens e-mail application

### ISSUE THREAD

**Issue by henrichg** [ACRA/acra#855]
ACRA version 5.8.2 (and 5.8.1) using Java (not Kotlin).

Configuration is in Application.attachBaseContext():

```
        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this)
                .withBuildConfigClass(BuildConfig.class)
                .withReportFormat(StringFormat.KEY_VALUE_LIST);
        //builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class)
        //        .setResText(R.string.acra_toast_text)
        //        .setEnabled(true);
        builder.getPluginConfigurationBuilder(NotificationConfigurationBuilder.class)
                .withResChannelName(R.string.notification_channel_crash_report)
                .withResChannelImportance(NotificationManager.IMPORTANCE_DEFAULT)
                .withResIcon(R.drawable.ic_exclamation_notify)
                .withResTitle(R.string.acra_notification_title)
                .withResText(R.string.acra_notification_text)
                .withResSendButtonIcon(0)
                .withResDiscardButtonIcon(0)
                .withSendOnClick(true)
                .withEnabled(true);
        builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                .withMailTo("henrich.gron@gmail.com")
                .withResSubject(R.string.acra_email_subject_text)
                .withResBody(R.string.acra_email_body_text)
                .withReportAsFile(true)
                .withReportFileName("crash_report.txt")
                .withEnabled(true);

        ACRA.DEV_LOGGING = true;

        ACRA.init(this, builder);

```
1. In notification are two buttons: OK and CANCEL, Click on it do nothing.

2. Click on notification body (is enabled by .withSendOnClick(true)) do not opens E-mail application or Share bottom sheet, but generated is:

2021-06-04 16:55:17.779 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Found ConfigurationBuilders : [org.acra.config.MailSenderConfigurationBuilder@2c2a7e2, org.acra.config.NotificationConfigurationBuilder@6d48773]
2021-06-04 16:55:17.780 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Using default Report Fields
2021-06-04 16:55:17.801 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: ACRA processName='sk.henrichg.phoneprofilesplus:acra'
2021-06-04 16:55:17.810 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Not initialising ACRA to listen for uncaught Exceptions as this is the SendWorker process and we only send reports, we don't capture them to avoid infinite loops
2021-06-04 16:55:17.821 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Registered content provider for authority sk.henrichg.phoneprofilesplus.acra

ACRA 5.7.0 working good.

**Comment by F43nd1r** [comment]
Which email clients are installed on the device?

**Comment by henrichg** [comment]
GMail. I'm using GMail in all my devices. In 5.7.0 send crash as attachment working good. In all my devices. Also not any user report me problem with sending crash report.

**Comment by F43nd1r** [comment]
I've tested acra 5.8 with recent gmail versions on multiple android versions.

Which Gmail and Android versions are you using?

**Comment by henrichg** [comment]
Samsung Galaxy S10 with Android 11, stock One Ui, rooted, GMail version 2021.05.02.373487627.Release
Currently tested also in:
Samsung Galaxy S21 with Android 11, stock One Ui, not rooted, GMail version 2021.05.02.373487627.Release
Nexus 5x, Android 9, stock rom, rooted, GMail version 2021.04.03.370471299.Release
Xiaomi Redmo ote 9 pro, Android 10, not rooted, GMail version 2021.04.03.370471299.Release

**Comment by henrichg** [comment]
Problem is also in Pixel 3a, with Android 12 beta 1..
Testid with crash generayted by:
`throw new RuntimeException("Test Crash");`

**Comment by F43nd1r** [comment]
Excluding Xiaomi, those are all devices without any known issues. I'll need to dive deeper. Please follow https://www.acra.ch/docs/How-to-debug and post all the logs.

**Comment by henrichg** [comment]
I'm using ACRA.DEV_LOGGING = true;
You want all logs from start of application to generated crash and click to notification?
Notification was generated for crash but not working send e-mail from it.

**Comment by henrichg** [comment]
Logcat from start of application:
[acra_5.8.2_logcat.txt](https://github.com/ACRA/acra/files/6602826/acra_5.8.2_logcat.txt)

**Comment by henrichg** [comment]
Maybe problem is also with this: After force stop application from App info and again start, crash report notification is immediatelly again generated. 
Application has foreground service with notification, this service is started at start of application.

**Comment by F43nd1r** [comment]
Your logs don't show anything that would indicate the notification was clicked at all. There were changes in the email sender in 5.8, but even if that was failing you should still see `About to start sending reports from SenderService`. If possible link me your source code, or provide a minimal viable example. I'll continue to try and reproduce your issue in the coming days.

**Comment by henrichg** [comment]
After click into notification was generatet this log:
```
2021-06-04 16:55:17.779 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Found ConfigurationBuilders : [org.acra.config.MailSenderConfigurationBuilder@2c2a7e2, org.acra.config.NotificationConfigurationBuilder@6d48773]
2021-06-04 16:55:17.780 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Using default Report Fields
2021-06-04 16:55:17.801 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: ACRA processName='sk.henrichg.phoneprofilesplus:acra'
2021-06-04 16:55:17.810 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Not initialising ACRA to listen for uncaught Exceptions as this is the SendWorker process and we only send reports, we don't capture them to avoid infinite loops
2021-06-04 16:55:17.821 17970-17970/sk.henrichg.phoneprofilesplus D/ACRA: Registered content provider for authority sk.henrichg.phoneprofilesplus.acra
```
Only this.

Sorce code is in my GitHub, but is huge: https://github.com/henrichg/PhoneProfilesPlus/tree/devel
Crash is generated from GUI (Editor menu), for testing it.

**Comment by henrichg** [comment]
I have in Editor menu also nonfatal test:
```
            try {
                throw new RuntimeException("Test non-fatal exception");
            } catch (Exception e) {
                PPApplication.recordException(e);
            }

  static void recordException(Throwable ex) {
        try {
            ACRA.getErrorReporter().handleException(ex);
        } catch (Exception ignored) {}
    }

```
Result is the same. Click to notification do nothing.
[acra_5.8.2__nonfatal_logcat.txt](https://github.com/ACRA/acra/files/6602918/acra_5.8.2__nonfatal_logcat.txt)

**Comment by henrichg** [comment]
Click to notification do not remove it. It stays displayed. Also click to action OK button.

**Comment by F43nd1r** [comment]
It seems like I'd need a modified android sdk to compile your app, as you're using hidden classes. Can you provide me with a compiled debug build instead?

**Comment by henrichg** [comment]
Debug apk: https://drive.google.com/file/d/1V1CwYC_X-PBdm1sTLAE32_OHdrCwQLhC/view?usp=drivesdk

**Comment by F43nd1r** [comment]
Problem identified
```
2021-06-06 18:41:50.479 567-613/? W/BroadcastQueue: Unable to launch app sk.henrichg.phoneprofilesplus/10156 for broadcast Intent { act=org.acra.intent.send flg=0x10000010 cmp=sk.henrichg.phoneprofilesplus/org.acra.receiver.NotificationBroadcastReceiver bnds=[22,1300][148,1426] (has extras) }: process is bad
```

**Comment by henrichg** [comment]
And how to solve it?

**Comment by F43nd1r** [comment]
No idea yet

**Comment by F43nd1r** [comment]
Okay, so that message above just means the process crashed too much and won't be started anymore. But after a device restart I got 
```
2021-06-06 18:50:33.495 5389-5389/sk.henrichg.phoneprofilesplus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sk.henrichg.phoneprofilesplus:acra, PID: 5389
    java.lang.RuntimeException: Unable to create application sk.henrichg.phoneprofilesplus.PPApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:156)
        at androidx.work.WorkManager.getInstance(WorkManager.java:184)
        at sk.henrichg.phoneprofilesplus.PPApplication.onCreate(PPApplication.java:946)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
```
Something regarding workmanager configuration. I'm guessing all this is caused by you commenting `if(ACRA.isACRASenderServiceProcess()) return;`. I've just published 5.8.3 which makes that method directly available again for java classes (in 5.8.2 you can call it with ACRA.INSTANCE)

**Comment by henrichg** [comment]
`java.lang.RuntimeException: Unable to create application sk.henrichg.phoneprofilesplus.PPApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
     `

Hm, this exception is generated sometime, but I do not know why. PhoneProfilesPlus uses defualt WorkManager configuration.
`        workManagerInstance = WorkManager.getInstance(getApplicationContext());`

This is not needed in manifest file, because it is default initialization:
```
<!--        <provider-->
<!--            android:name="androidx.work.impl.WorkManagerInitializer"-->
<!--            android:authorities="${applicationId}.workmanager-init"-->
<!--            android:exported="false"-->
<!--            tools:node="remove" />-->

```

Maybe is needed initilize it before ACRA? Then must be intilaized in attachBaseContext() for 5.8.
ACRA uses WorkManager?

I will testing 5.8.3. Thank you.

**Comment by F43nd1r** [comment]
Acra does not use workmanager, but can conflict with it if your application doesn't treat acras senderservice process correctly.

**Comment by henrichg** [comment]
Hm sorry, but not working. Fatal and also non-fatal exception. The same bug, notification do nothing.

**Comment by F43nd1r** [comment]
Did you uncomment `if(ACRA.isACRASenderServiceProcess()) return;`?

**Comment by henrichg** [comment]
Commented is in onCreate(), not attachBaseContext(). All configuration in onCreate() is commented and moved into attachBaseContext() for 5.8.
Better is move configuration to onCreate() for me?

**Comment by henrichg** [comment]
If I move configuration into onCreate(), notification is not generated at all.

**Comment by F43nd1r** [comment]
You need this `if(ACRA.isACRASenderServiceProcess()) return;` before any non-acra configuration in *both* attachBaseContext and onCreate. acra configuration should be in attachBaseContext.

**Comment by henrichg** [comment]
Workiiing :-) Both fatal and non-fatal exception.

I'm added:
`if(ACRA.isACRASenderServiceProcess()) return;`

1. in `onCreate()` immediatelly after `super.onCreate();`
2. in `attatchBaseContext()` immediatelly after `super.attatchBaseContext();`
3. Acra configuration at `attachBaseContext()` but after `if(ACRA.isACRASenderServiceProcess()) return;`

Thank you very much.

**Comment by mikehardy** [comment]
@F43nd1r pardon me for hopping on here, but you say:

> Acra does not use workmanager, but can conflict with it if your application doesn't treat acras senderservice process correctly.

...and the solution is (if I understand it correctly) to bail out of general app initialization if it's the ACRA sender process, which (if I understand it correctly) solves the WorkManager conflict / crash by (I think?) making sure work manager is not initialized 2+ times via the app init code running again?

Do I have the right? Because I had a WorkManager issue on another project with this stack trace and we were never able to fully diagnose. The stack itself if you go in the WorkManager code could be one of 3+ different causes IIRC and we did not consider the multi-process case, that might have been our root cause.

Thanks for any thoughts, apologies again for intruding

https://github.com/notifee/react-native-notifee/issues/237#issuecomment-802088434

@helenaford WorkManager IllegalStateException maybe due to multi-process WorkManager init? :eyes: :point_up:

**Comment by F43nd1r** [comment]
> and the solution is to bail out of general app initialization if it's the ACRA sender process

Yes.
