### ISSUE TITLE
Inherit AttachmentUriProvider

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#860]
So with latest release i get an error when i am extending AttachmentUriProvider

`Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option`

I had no problems with beta 11 but with upgrade to 5.8.3 i get this error now, any solution for this?

**Comment by F43nd1r** [comment]
This is a false positive in IntelliJ, tracked in https://youtrack.jetbrains.com/issue/KTIJ-12711. You can safely ignore it, compilation will work anyway.

**Comment by F43nd1r** [comment]
If you're on kotlin, add "-Xjvm-default=all" to your jvmArgs

**Comment by woitaylor** [comment]
kotlinOptions {
    freeCompilerArgs = ['-Xjvm-default=compatibility']
}
