### ISSUE TITLE
Warning: provider#org.acra.attachment.AcraContentProvider@android:authorities was tagged at AndroidManifest.xml to replace other declarations but no other declaration present

### ISSUE THREAD

**Issue by christophehenry** [ACRA/acra#861]
**Describe the bug**
I get this warning during the compilation but found nothing in ACRA's documentation as to how to make it disappear. I suppose this happens because `android:authorities` is not filled in `AndroidManifest.xml` and ACRA tries to replace a field that is already empty. But I have not idea what this field should contain.

**Expected behavior**
No warning should pop in the compilation logs.

**Version**
 - Android: 5.0 to 11
 - ACRA 5.8.3

**Comment by F43nd1r** [comment]
Unfortunately the offending declaration is necessary in some cases. The warning can be safely ignored. For more info see https://github.com/ACRA/acra/pull/710/files#r225096150

**Comment by christophehenry** [comment]
Ok, I understand now. Thank you.
