### ISSUE TITLE
Broken links in documentation pages not accessed through sidebar

### ISSUE THREAD

**Issue by michpohl** [ACRA/acra#868]
**Required reading**
https://github.com/ACRA/acra/wiki/How-to-debug-ACRA

**Describe the bug**
This is a bug in the documentation, not in ACRA itself:
when opened directly, the links from one documentation page to another are broken.
Example:
1. In the repo's readme file click on the link to the `Setup` page.
2. Scroll all the way down, click on the link to the `Senders`page
3. Observe that the page was not found, because the url provided was `https://www.acra.ch/docs/Setup/Senders` instead of `https://www.acra.ch/docs/Senders`
4. Now click on the `Setup`menu item in the sidebar, then repeat step 2.
5. This time, the link works as intended

This behaviour can be reproduced by opening any of the documentation urls directly, then clicking on a link. 

**Expected behavior**
One would expect the links to always work the same and serve the correct url.

**Version**
no version, it's the docs

**Additional comment**
I initially just wanted to help out and submit a PR for this, but I have never used mdx nor docusaurus, so it turned out to be not as e asy as I thought. If someone can point me to proper resources on this concrete issue, I am happy to do some reading and provide a fix.

**Comment by F43nd1r** [comment]
Opened upstream https://github.com/facebook/docusaurus/issues/5026. This is caused by github pages redirecting `folder` urls to `folder/` urls, which isn't handled correctly by docusaurus.

**Comment by F43nd1r** [comment]
Alright, apparently there is a new option to toggle for this. Fixed now.
