### ISSUE TITLE
Compiler argument "-Xjvm-default=all" conflicts with ROOM database

### ISSUE THREAD

**Issue by Doomsdayrs** [ACRA/acra#882]
**Describe the bug**
To implement a customer sender, one must add the "-Xjvm-default=all" to their project.

When such argument is added, ROOM compilation has a variety of issues.

**Expected behavior**
The library does not require extra arguments to function properly. Allowing developers to overload in Kotlin easily.

**Version**
 - ACRA: 5.8.3

**Comment by F43nd1r** [comment]
I really don't understand why the old `@JvmDefault` was deprecated, if the new system is still completely broken (also had multiple issues with it in other places). Switched back to the old system with 5.8.4

**Comment by Doomsdayrs** [comment]
This is strange. `v5.8.4` Lets me inherit `ReportSenderFactory` but inheriting `ReportSender` causes the "use the -xjvm.." requirement

**Comment by F43nd1r** [comment]
You'll still need `-Xjvm-default=enable` to extend those interfaces, but it shouldn't affect anything else.
