### ISSUE TITLE
Permission is changed for API getDeviceId(), but no version check

### ISSUE THREAD

**Issue by wowhhh** [ACRA/acra#887]
**Describe the bug**
The API `TelephonyManager.getDeviceId()` needs `READ_PHONE_STATE` in API-level 28 and below, but is changed to `READ_PRIVILEGED_PHONE_STATE` since 29.
According to the [docs](https://developer.android.com/reference/android/telephony/TelephonyManager#getDeviceId()), if an app targets 29 but no such permission, it will throw a `SecurityException` (and thus crash).
Currently, only the first permission is mentioned [here](https://github.com/ACRA/acra/blob/master/acra-core/src/main/java/org/acra/collector/DeviceIdCollector.kt#L46). The second permission cannot be used.

**Expected behavior**
My suggestions:
put null directly for above 28 (and we can remove the `@Throws`)
```java
override fun collect() {
    if(SDK_INT <= 28)
        target.put(ReportField.DEVICE_ID, getTelephonyManager(context).deviceId)
    else
        target.put(ReportField.DEVICE_ID, null)    
}
```
This may prevent potential crashes during collecting device-id.

**Version**
 - ACRA latest

@F43nd1r Could you help me review this? Very thanks!

**Comment by F43nd1r** [comment]
@wowhhh you can open a PR for this.
