### ISSUE TITLE
Email not opening on OS < 9

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#888]
I detected a  lot of issues on Devices with OS<9 i guess this is probably related with Gmail change if i am not mistaken? Is there any way to fix this that it will work for all of them ? All it does it displays message like opening email and nothing actually happens.

**Comment by F43nd1r** [comment]
Which Acra version?
Try switching between 5.8.0-beta4, 5.8.1-beta10 and 5.8.4, which are old mail sending, new mail sending on Q+ and new mail sending on M+ respectively.

**Comment by arcanewater** [comment]
With 5.8.4 it seems it better but still having problem with Xiaomi Redmi 4X (7.1.2 android)

**Comment by F43nd1r** [comment]
See https://github.com/ACRA/acra/issues/804, at this point xiaomi cannot be fully supported by me. Their android is broken and I don't have access to one to try and work around it.

**Comment by arcanewater** [comment]
Thanks for the info!
