### ISSUE TITLE
Insert Data to Acrarium's Custom Columns from ACRA

### ISSUE THREAD

**Issue by Kasina09** [ACRA/acra#899]
I found this custom column(s) feature in Acrarium helpful.
![Custom Columns](https://user-images.githubusercontent.com/80304849/129866999-a4d1326b-a5b7-431d-bd35-cd86cda6ecf6.PNG)

![Capture](https://user-images.githubusercontent.com/80304849/129868316-d8fd05e7-1e61-4d13-b297-4a0931b7395f.PNG)

But how to add/insert data into this column?
Can it be handled with ACRA (either automate or by adding codes)?

**Comment by F43nd1r** [comment]
Acrarium just extracts a json path. For example you could use ACRA custom data (`ACRA.errorReporter.putCustomData("Extra_Information", "myValue")`) and then extract it in Acrarium with `CUSTOM_DATA.Extra_Information`

**Comment by Kasina09** [comment]
Could you please elaborate how to extract it in Acrarium?
Is it from the android application before sending the reports or do I need to tweak the Acrarium?

**Comment by F43nd1r** [comment]
> Could you please elaborate how to extract it in Acrarium?
> Is it from the android application before sending the reports or do I need to tweak the Acrarium?

Just put that string `CUSTOM_DATA.Extra_Information` in your custom column definition  in Acrarium.

**Comment by Kasina09** [comment]
I am sorry, but where can I find this 'custom column definition'?

I tried changing the 'path' from database. It can read the data, but also changed the column name (and it's kinda risky if I need to change from database manually).
![custom column](https://user-images.githubusercontent.com/80304849/130061193-5e4fbafe-4bb0-4876-9ca7-df052cdaccf2.PNG)

**Comment by F43nd1r** [comment]
There is no name right now, the path is displayed everywhere.

**Comment by Kasina09** [comment]
Ohhh. I thought it was me who got it wrong.
Alright, thank you :)
