### ISSUE TITLE
Multiple entries added to Acralyzer from one custom data string 

### ISSUE THREAD

**Issue by chris6647** [ACRA/acra#90]
Wasnt quite sure if this belonged with acra or acralyzer, but i hope this is the right place.

Seems similar to https://github.com/ACRA/acralyzer/issues/23 and https://github.com/ACRA/acra/issues/66

When trying to send a forced error report with a full html page parsed with Jsoup as a single string, I still get multiple entries when seeing the report in acralyzer. If i run StringEscapeUtils.escapeJava() on the string before giving it to acra, i correctly get a single custom data entry, but with many unneccesary backslashes etc. Not quite sure if this is because some of the escaping is done twice, once with the apache utils, and once within acra.

It seems to me that perhaps the fixes applied with issue 23 and 66 dont cover all cases?

**Comment by william-ferguson-au** [comment]
Can't replicate
