### ISSUE TITLE
403: Client error - request will be discarded

### ISSUE THREAD

**Issue by vaishak109** [ACRA/acra#901]
Crash reports are not getting posted in acrarium. Few days ago, only few of the crashes were posted.. rest was discarded. Now, all the crashes are getting discarded. Tried changing basicAuthLogin and basicAuthPassword. But no use

Here is the log:

https://dpaste.org/Te3p

**Comment by F43nd1r** [comment]
Anything in the server log? You need to investigate which part of your request pipeline returns the 403. Could be a proxy server or something

**Comment by vaishak109** [comment]
Okay, will be checking that. Thanks!

**Comment by divyanshdxn** [comment]
@vaishak109 any updates? How did you solved the error?

**Comment by yogeshmehare** [comment]
> Okay, will be checking that. Thanks!

How did you fixed this issue. Where was the issue.
