### ISSUE TITLE
No way to check if ACRA is initialized

### ISSUE THREAD

**Issue by lgawron** [ACRA/acra#94]
ACRA.getErrorReporter().handleException(caughtException) would throw if ACRA is not actually initialized (debug mode for example).

It would be nice to have ACRA.isInitialized() or probably even better:

ACRA.handle( exception ) that does not throw.

**Comment by InvoiceFox** [comment]
But you don't want to initialize it in some cases (like when in emulator) and then you get runtime errors for things like ACRA.getErrorReporter().handleException(e); and putCustomData.
