### ISSUE TITLE
follow http redirects

### ISSUE THREAD

**Issue by benibela** [ACRA/acra#948]
**Describe the bug**

My webhoster has changed my website, and now I do not receive crash reports anymore. In the log on the device, I find

      ACRA    : Could not send ACRA Post - request will be discarded. responseCode=301 message=Moved Permanently

**Expected behavior**

When the http server responds with 30x, acra should send the report to the new location

**Version**
 - Android: 11
 - ACRA 5.7.0

**Comment by F43nd1r** [comment]
ACRA uses HttpUrlConnection, which already follows redirects by default, unless it is across protocols. Did your url change from http to https or vice versa? In this case following the redirect is a security issue and won't be supported.

**Comment by benibela** [comment]
> Did your url change from http to https 


indeed


Switching to https is not a security issue. Https is more secure than http

**Comment by F43nd1r** [comment]
You can read more on the topic here https://stackoverflow.com/questions/1884230/httpurlconnection-doesnt-follow-redirect-from-http-to-https

I won't be implementing anything for this, but you can always extend the HttpSender to your needs.
