### ISSUE TITLE
acra not send report ! 

### ISSUE THREAD

**Issue by amirhosenebrahimi** [ACRA/acra#951]
ACRA does not report crashes to my server. 
This has worked for me before. 

I create an empty app and passed my ACRA code. not worked! 
my Application class is ->
![image](https://user-images.githubusercontent.com/37499590/142691257-c9527648-09d1-446d-8aa8-a78e688d2b9c.png)

and I use this line for send crash ->
`            ACRA.errorReporter.handleException(Throwable("aaaa"))
`
but I do not get any response on my log in server.

 - Android: [Android 9]
 - ACRA [5.8.4]

**Comment by F43nd1r** [comment]
If it is a MIUI device, see #804. Otherwise post relevant device logs.

**Comment by F43nd1r** [comment]
Unclear issue and no response - closing
