### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by weikaiyun** [ACRA/acra#965]
![image](https://user-images.githubusercontent.com/20124328/146775742-26ff2ad1-f0a8-4a53-a220-9029bd676255.png)

when I clone the repo, there is a sync error. I can't build from the source code. 

Help wanted

**Comment by F43nd1r** [comment]
Make sure you're using the latest version of your IDE

**Comment by weikaiyun** [comment]
yeah, updating the IDE to the latest version can solve the problem.
