### ISSUE TITLE
Empty logcat

### ISSUE THREAD

**Issue by pontusberglund** [ACRA/acra#99]
I'm using the 4.4.0 version of Acra and crash reports are sent to (and handled by) HockeyApp. Acra is configured to send 100 lines from logcat in every crash report:

logcatArguments = {  "-t","100","-v","time","AppName:D","*:S" }

Most of the time this works great but in some (about 30-40%) reports the logcat looks like this:

--------- beginning of /dev/log/main
--------- beginning of /dev/log/system

This happens randomly and I can't see a pattern for when it happens and when it not. It seems like the log is totalyy empty but I'm 100% sure it's not.

Another strange thing I've noticed is that sometimes, our logging appears under /dev/log/system which I thought were impossible from API level 16 and up?

**Comment by william-ferguson-au** [comment]
Closing due to lack of interest
